### ISSUE TITLE
Resolve Known Issue: Gift Codes Limit

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1008]
The was a previous feature on the Settings page which should allow a merchant to "Specify, how many times a gift code can be redeemed for the associated time pass."

However, this functionality was deprecated in v0.10.0
We hid this from the settings page in a previous version but have had several requests to re-implement.

## Acceptance Criteria
For Time Passes only, restore the ability to limit the number of times a voucher code can be redeemed
**Details**
   - The box should be un-checked by default
     - When unchecked; the text box should be disabled
   - The box should only accept integer values
   - Please match existing styles for the text box & checkbox

> Limit the number of times a voucher can be redeemed.
> Voucher can be redeemed a maximum of ___ times per user.

> Legen Sie fest, wie oft ein Gutschein eingelöst werden kann.
> Der Gutschein kann maximal ___ Mal pro Benutzer eingelöst werden.

![image](https://user-images.githubusercontent.com/41650164/55027684-d9a9fa00-4fd3-11e9-9eda-aab8a7228ee8.png)

**Comment by thrijith** [comment]
@ksmoore125 

The gift code feature was deprecated for a long time and was hidden it was removed in `v0.10.0`.

As per the statistics [here](https://wordpress.org/plugins/laterpay/advanced/) as of now, around 70% of users are above `v2.0.0`.

This setting was not removed as it had interdependency with other code. So this will take some time. I am guessing a day. Might change when we start on this.

Please let me know whether to proceed with this.

Thanks.

**Comment by ksmoore125** [comment]
As long as it will not take significantly more effort let's fix the issue. 
Even if merchants are not currently using it, it is a valuable feature to provide.

**Comment by thrijith** [comment]
@ksmoore125 

- Is the disclaimer to be added below all the existing subscription vouchers? The desired image is same as the Current image.
- Is the voucher limit only to be provided for Time Pass only?
- Should the number of limit be allowed to edit once saved?

**Comment by ksmoore125** [comment]
> Is the disclaimer to be added below all the existing subscription vouchers?
It would just go next to the '+ Generate voucher code' link which is static at the bottom of the page so one warning message beneath all the vouchers. Let me know if you would like a more detailed mockup

> The desired image is same as the Current image.
They are very similar but _slightly_ different. In the current image, the newly created and still editable voucher) is the top one. In the desired image, it is the bottom one. Let me know if a prototype would be helpful.

> Is the voucher limit only to be provided for Time Pass only?
Yes, since subscriptions auto-renew a user shouldn't need to use a voucher more than once for a subscription.

> Should the number of limit be allowed to edit once saved?
For simplicity: No - similar to how the price is not editable today

**Comment by ksmoore125** [comment]
This is currently blocked until a change is made within LaterPay due to the fact that the WordPress plugin cannot count the # of times a voucher is used for a purchase since the purchase data is stored within the LaterPay system. We will revisit this once the necessary changes are made within LaterPay.

**Comment by ksmoore125** [comment]
Won't Do
