### ISSUE TITLE
Resolve Known Issue: LaterPay Pro Merchant Account

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1010]
There is an existing feature on the Settings page which allows a merchant to identify that "I have a LaterPay Pro merchant account."

Since we are no longer supporting that offering, we should remove the checkbox and potentially any related code.

**Comment by thrijith** [comment]
@ksmoore125, This should take an hour or less for the fix.

**Comment by thrijith** [comment]
Support for Pro removed and released in [2.3.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.3.0)
