### ISSUE TITLE
Adjust content preview options so that they are combined into one interface

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1012]
## User Story
As a LaterPay Merchant, I would like to be able to customize the payment overlay to include pieces from all of the options currently available.

## Helpful Documentation
https://docs.laterpay.net/connector/configuration/inpage_configuration/appearance/

## Acceptance Criteria
(!) Note: Where the text varies between the ticket and the mockup, please **use the wording in the ticket**
- Grey sidebar content should not change; that is why it is left empty in the mockups
- Changes to the **Configure Appearance** section should dynamically change the **Preview** in real time
- Changes should not be applied to the WordPress site until the user clicks **Save**

Configuration Setting English | German | Logic | Checked Mockup | Un-checked Mockup
------------ | ------------- | ------------ | ------------- | -------------
Show purchase button above article |Zeige Kauf-Button über dem Artikel | See #1193 | [Here](https://sketch.cloud/s/45evm/WkoWog/play)|[ Here](https://sketch.cloud/s/45evm/m1J07qL/play)
Customize position of purchase button | Anpassen der Position des Kauf-Buttons | Visible & editable if the above is checked; if the above is unchecked then is hidden & false | [Here](https://sketch.cloud/s/45evm/oY4QmmY/play) | [Here](https://sketch.cloud/s/45evm/kazn44g/play)
Show Purchase Overlay |Kauf-Overlay anzeigen| See #1193 |[Here](https://sketch.cloud/s/45evm/WkoWog/play) | [Here](https://sketch.cloud/s/45evm/DPl9pqe/play)
Header |Überschrift | Visible & editable if “Show Purchase Overlay” is checked; otherwise it is hidden & false | See details below | -- |
Show LaterPay Introduction |LaterPay Einführung anzeigen | Visible & editable if “Show Purchase Overlay” is checked; otherwise it is hidden & false | [Here](https://sketch.cloud/s/45evm/WkoWog/play)| [Here](https://sketch.cloud/s/45evm/agRzlvA/play)
Show Time Passes & Subscriptions below modal |Zeigen Sie Zeitabläufe und Abonnements unter modal an | See #1193 | [Here](https://sketch.cloud/s/45evm/Axa9obx/play)|[Here](https://sketch.cloud/s/45evm/WkoWog/play)
Customize position of Time Passes & Subscriptions | Anpassen der Position von Zeitabläufen und Abonnements | Visible & editable if the above is checked; if the above is unchecked then is hidden & false | [Here](https://sketch.cloud/s/45evm/KvYz22n/play) | [Here](https://sketch.cloud/s/45evm/paenDDQ/play)
Add custom HTML section below payment button | Hinzufügen eines benutzerdefinierten HTML-Abschnitts unter dem Zahlungsbutton | Visible & editable if “Show Purchase Overlay” is checked; otherwise it is hidden & false | [Here](https://sketch.cloud/s/45evm/l1Z8L9K/play) | [Here](https://sketch.cloud/s/45evm/WkoWog/play)
Show valid payment options | Gültige Zahlungsoptionen anzeigen | Visible & editable if “Show Purchase Overlay” is checked; otherwise it is hidden & false | [Here](https://sketch.cloud/s/45evm/WkoWog/play) | [Here](https://sketch.cloud/s/45evm/8yZO8lw/play)

**Header Functionality:** This should adjust the Header content as is done today under Appearance > Teaser + Purchase Overlay > Header > Header Title

## Default Options / Backward Compatibility
`Code formatted items below` denote that this can be configured by the user today and we should use what they currently have selected.

Setting | New User | Teaser + Purchase Link | Teaser + Explanatory Overlay | Teaser + Purchase Overlay
------------ | ------------- | ------------ | ------------- | -------------
Show purchase button above article | | ✅ | ✅ |  
Customize position of purchase button | | `Custom position` | `Custom position` |  
Show Purchase Overlay | ✅ | ✅ | ✅ | ✅
Header |Read Now, Pay Later | -- |Read Now, Pay Later| `Header Title`
Show LaterPay Introduction | ✅ | ✅ | | 
Show Time Passes & Subscriptions below modal | | ✅ | ✅ | 
Customize position of Time Passes & Subscriptions | | `Custom position` | `Custom position` |  
Add custom HTML section below payment button | | | | 
Show valid payment options | ✅ | | | `Show footer`

## Prototype & Mockup
https://sketch.cloud/s/45evm/WkoWog/play
![image](https://user-images.githubusercontent.com/41650164/55260955-b2ebfd80-5237-11e9-883d-eb18d054e3e3.png)

**Comment by thrijith** [comment]
This will also cover https://github.com/laterpay/laterpay-wordpress-plugin/issues/1013

This is a major change we need to add the markup for new things update js for the dynamic selection of preview. Code has to be refactored in the process for optimisation.

Some of the defaults options can be added. But we need to decide what should be the selected options for a merchant when they upgrade the plugin based on their current selection off appearance.

This might take up to 6-7 days.

**Comment by ksmoore125** [comment]
Testing notes can be found [here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1559593394009600).

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
