### ISSUE TITLE
Allow merchants to adjust color scheme

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1014]
## User Story
As a LaterPay Merchant, I would like to be able to easily configure the colors of my payment modal no matter the appearance option.

## Mock-up
![image](https://user-images.githubusercontent.com/41650164/55263697-e03ca980-523f-11e9-8bf7-09fff7b3ab5c.png)

## Acceptance Criteria
(!) Note: Where the text varies between the ticket and the mockup, please use the wording in the ticket
- Make the color options currently available under the "Teaser + Purchase Overlay" option available to all appearance configurations
  - Remove the `Header` and `Show footer` options since these will be moved into the new `Configure Appearance` section
- Under Settings > LaterPay > Appearance; remove `Button & Link Color` and `Button & Link Hover Color` (See Notes column in the table below)
- When saved this should update the WordPress site as well as the Modal Preview in the top half of the page (if updating the modal preview is a significant effort; this can be disregarded for the MVP)

English | German | Notes
------------ | ------------- | -------------
CUSTOMIZE COLORS |FARBEN ANPASSEN| 
Header background color |Hintergrundfarbe Header| 
Purchase option background color |Hintergrundfarbe Kaufoptionen | 
Main text color |Schriftfarbe Text | 
Description text color |Schriftfarbe Beschreibungen| 
Purchase button background color |Hintergrundfarbe Kaufbutton | This should replace Settings page `Button Color`
Purchase button hover color | Kaufen-Taste schweben Farbe | NEW! (not shown in mockup) This should replace Settings page `Button Hover Color`
Purchase button text color |Schriftfarbe Kaufbutton| 
Link main color |Schriftfarbe Links | This should replace Settings page `Link Color`
Link hover color |Hover-Schriftfarbe Links | This should replace Settings page `Link Hover Color`
Footer background color |Hintergrundfarbe Footer | 

# Default Options / Backward Compatibility
`Code formatted items` below denote that this can be configured by the user today and we should use what they currently have selected. `**Code formatted & bold items**` were set on the Settings > LaterPay page.

**GOAL:** The appearance should stay the same without merchants needing to make any changes.

New Color Setting | Teaser + Purchase Link | Teaser + Explanatory Overlay | Teaser + Purchase Overlay
-- | -- | -- | --
Header background color | Default | Default | `Header background color`
Purchase option background color | Default | Default | `Purchase option background color`
Main text color | Default | Default | `Main text color`
Description text color | Default | Default | `Description text color`
Purchase button background color | `**Button & Link Color**` | `**Button & Link Color**` | `Purchase button background color`
Purchase button hover color | `**Button & Link Hover Color**` | `**Button & Link Hover Color**` | `Purchase button background color`
Purchase button text color | Default | Default | `Purchase button text color`
Link main color | `**Button & Link Color**` | `**Button & Link Color**` | `Link main color`
Link hover color | `**Button & Link Hover Color**` | `**Button & Link Hover Color**` | `Link hover color `
Footer background color | Default | Default | `Footer background color`

**Comment by thrijith** [comment]
@ksmoore125 
>Under Settings > LaterPay there is a LaterPay Colors section. This can be removed since it is no longer needed. (The functionality should be covered under the existing Purchase Options > Purchase button background color)

This option is not just for the purchase button. It's applied to timepass/subscription buttons and also in backend. This applies to  all **clickable LaterPay elements**

_Purchase Options > Purchase button background color_ is currently applied to **Teaser + Purchase Overlay** button.

Let me know what should be done about this.

Backend Buttons.
![screenshot 2018-11-14 at 9 05 57 pm](https://user-images.githubusercontent.com/13589980/48493093-342a9100-e851-11e8-8876-705203bafd44.png)

Frontend Buttons.
![screenshot 2018-11-14 at 9 06 29 pm](https://user-images.githubusercontent.com/13589980/48493094-34c32780-e851-11e8-847f-40f91c80d79e.png)

**Comment by ksmoore125** [comment]
**Backend Buttons:**
We could either: `make this color static` OR use the `Purchase button background color`

**Frontend Buttons (timepass and subscription):**
We use the `Purchase button background color`

![image](https://user-images.githubusercontent.com/41650164/48494952-8be6df00-e7f4-11e8-813d-273d3ed264e0.png)

**Comment by ksmoore125** [comment]
Testing notes can be found [here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1559593394009600).

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
