### ISSUE TITLE
Move relevant items from the Settings Page to the Appearance tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1015]
### User Story
As a LaterPay Merchant, I would like all of the applicable items located in one place so that it is easy to find.

### Acceptance Criteria
- Move the "Automatically Generated Teaser Content" configuration options from the Settings page to the bottom of the Appearance Tab
- Move the "Content Preview under Overlay" configuration options from the Settings page to the bottom of the Appearance Tab
- Update the "Content Preview under Overlay" functionality so that it will apply as long as the merchant has selected to "Show payment options in purchase overlay" (currently it is only displayed if the Appearance is set to "Teaser + Purchase Overlay"

### Mock-up
![image](https://user-images.githubusercontent.com/41650164/47438885-ee5a3b80-d770-11e8-8a52-f448881b0e6c.png)

**Comment by thrijith** [comment]
@ksmoore125 

All these setting are implemented in a different way, need to check how to move them to into Plugin settings page. We can use some part of existing markup, this will be added after the layout for new Appearance is in place.

>Update the "Content Preview under Overlay" functionality so that it will apply as long as the merchant has selected to "Show payment options in modal" (currently it is only displayed if the Appearance is set to "Teaser + Purchase Overlay"

Just to confirm, the functionality will only work if `Show payment options in modal` is selected.

This should take about 2-3 days.

**Comment by ksmoore125** [comment]
> Just to confirm, the functionality will only work if `Show payment options in modal` is selected.
Sorry, I renamed the options without updating the text of the ticket. This should be `Show payment options in purchase overlay` I will update the description accordingly. Let me know if you have any doubts!

**Comment by ksmoore125** [comment]
To save time, instead we can just link to the appropriate sections on the existing Settings > LaterPay page.

**Comment by ksmoore125** [comment]
Won't do
