### ISSUE TITLE
Update Time Passes Description

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1018]
### User Story
As a LaterPay merchant, the descriptions for time passes versus subscriptions is a bit confusing. I would like additional guidance on when to use each item so that I am not confused during my initial site set up.

### Acceptance Criteria
Update the Time Pass Description here:
![image](https://user-images.githubusercontent.com/41650164/47225677-49142180-d384-11e8-88d2-2617247ca9c3.png)

**From**
> **Sell bundles of content**
> With Time Passes you can sell time-limited access to a category or your entire site. Time Passes do not renew automatically.
> 
> Click the "Create" button to add a Time Pass.

**To** 
> **Sell time-limited access to content**
> With Time Passes you can sell time-limited access to a category or your entire site. Time Passes do not renew automatically and are a great option for readers who are not quite ready to commit to a subscription.
>
> Click the “Create” button to add a Time Pass.

**Comment by thrijith** [comment]
@ksmoore125 

This won't take much time, it's fix can be added along with any other ticket's fix in the milestone.
Let me know if that's fine.

Thanks

**Comment by thrijith** [comment]
Description updated and released in [2.3.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.3.0)
