### ISSUE TITLE
Allow for multiple categories to be included or excluded

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1019]
https://laterpay.atlassian.net/browse/PRODUCT-236

### User Story
Our merchant buchreport.de is unable to create time passes that exclude some of their content. They can only create a time pass for just one category, all categories or all but one category. Part of the problem seems to derive the fact that currently they have to set up a new category whenever they want to offer a different pricing. Therefore the have so many categories that can't flexibly managed with the current time pass configuration.

### Acceptance Criteria
Make the Category options multi-select for:
- Category Default Pricing
- Time Passes
- Subscriptions

This should be for both includes categories and excludes categories

**Comment by ksmoore125** [comment]
> Thrijith [18 days ago]
> @Kimberly Moore The `Allow for multiple categories to be included or excluded` ticket has major changes in the selection behaviour, i need to check how it is implemented in order to change it first. Once that is done need to update how the data is parsed and saved for all three types (TimePass, Subscription, Category Price). I am assuming this might take `1-2` days this is not fixed might decrease or increase once I start working on it.

**Comment by ksmoore125** [comment]
Let's hold off on this until we get the content access issues 100% resolved.
We will aim to get this completed by the end of the year but will resolve all known issues first since this is a risky change.

**Comment by ksmoore125** [comment]
### Initial Testing

- Functionality on Pricing tab looks good & works well
- Category Pricing works well
- Time Passes & Subscriptions appear to have issues

**Steps to Reproduce**
![image](https://user-images.githubusercontent.com/41650164/50523059-b1bdff80-0a93-11e9-9722-32e605e0390f.png)

![image](https://user-images.githubusercontent.com/41650164/50523065-bc789480-0a93-11e9-8dc6-d3664498ebad.png)

![image](https://user-images.githubusercontent.com/41650164/50523094-dfa34400-0a93-11e9-8d09-972488ef8ec9.png)





_Meanwhile, The Greatest Showman appears to be working properly_
![image](https://user-images.githubusercontent.com/41650164/50523088-d914cc80-0a93-11e9-8e3a-5ff00a3ea9e9.png)

**Comment by thrijith** [comment]
@ksmoore125 I have added some changes to display and store selected categories for `Category Default Prices` in an order they are selected. Let me know if we need that or it's ok to display them as it was ( sorted by category name ).
