### ISSUE TITLE
User Management: Allow Merchants to Assign Users to Roles Based on Contribution Level

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1022]
https://laterpay.atlassian.net/browse/PRODUCT-234

### User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.

### Acceptance Criteria
For each time pass & subscription:
- Allow the merchant to select one or more existing user roles to which they would like the user assigned #1054
- If a user has one of the selected time passes or subscriptions then their role should be updated accordingly #1055 
- If a user's subscription or time pass is no longer active we should remove the user from this role #1056 

### Mockup & Prototype
https://sketch.cloud/s/45evm/OmoePVw/play
![image](https://user-images.githubusercontent.com/41650164/49179392-ccc41500-f317-11e8-899a-29f8b2725ad0.png)

**Comment by thrijith** [comment]
@ksmoore125 

Just confirming the flow for this.

1) If Merchant has provided a registration link then we will show the `Require WordPress Sing in`.
2) Once the required sign in checked then we will display the role selection.

WordPress allows to enable registration.

Check `Settings >> General Settings` and enable `Anyone can register`

Which will provide option for anyone to register on to site.

Let me know whether to use that if enabled or only use the provided link in `WordPress User Registration Page`

**Comment by ksmoore125** [comment]
See the prototype at https://sketch.cloud/s/45evm/OmoePVw/play for a walk through 
(click anywhere on the screen and it will highlight clickable areas)

Flow outline:
- Show dropdown
- After the merchant makes a selection
  - If they **have** provided a registration link: Display the `Require WordPress Sing in` checkbox
  - If they **have not** provided a registration link: Display the `Require WordPress Sing in` check box with an error message (see #1057 for details)

> Let me know whether to use that [`Settings >> General Settings` and enable `Anyone can register`] if enabled or only use the provided link in `WordPress User Registration Page`

I would assume that only using the provided link in `WordPress User Registration Page` would be simpler. In this case the merchant can fill this with the WordPress standard page location or their own custom page location which would also make it more flexible with less effort from us.

**Comment by ksmoore125** [comment]
Given our new plan this is no longer required. Won't Do.
