### ISSUE TITLE
Secure Download Widget Requires Users to Select "I already purchased this"

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1026]
See https://github.com/laterpay/laterpay-wordpress-plugin/issues/979

A video with steps to reproduce can be found at:
https://rtcamp.slack.com/archives/GA2P84GBZ/p1539878184000100

**Comment by ksmoore125** [comment]
I was able to reproduce this issue today at https://www.der-bank-blog.de/herausforderungen-2018/ebook/31925/

**Comment by thrijith** [comment]
@ksmoore125 Unable to replicate this on staging or local.

This was fixed and released in `v2.2.2` and tracked in https://github.com/laterpay/laterpay-wordpress-plugin/issues/1036

I checked the code used to render the shortcode and it seems outdated.

Can you please check what version is being used on the reported site?

Thanks
