### ISSUE TITLE
WordPress Gutenberg Compatibility - Content Blocking with Embedded HTML - WP Issue

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1027]
See the final two comments in https://github.com/laterpay/laterpay-wordpress-plugin/issues/967

WordPress has an existing issue that will not allow content blocking with images. This should be resolved with WP 5.0

This ticket is to verify that it is working as expected under WP 5.0

**Comment by thrijith** [comment]
Working as expected, tested on WP 5.0, and 5.1.1 and on staging env.

**Comment by thrijith** [comment]
> Working as expected, tested on WP 5.0, and 5.1.1 and on staging env.

Tested on above environments.
