### ISSUE TITLE
Readers can Easily Read Blurred Content

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1037]
### User Story
As a LaterPay Merchant, I would like it to be extremely difficult for my readers to read blocked or blurred content but I would like the blurred content to accurately convey what the reader will gain access to.

### Steps to Reproduce
1. Open a blog post that has blurred content behind the paywall (in order for this to happen the Appearance tab must be set to Teaser + Purchase Overlay)
2. Right click & view source
3. Scroll down and observe that you can easily read the blurred content since this is simply a css style

![image](https://user-images.githubusercontent.com/41650164/48362835-2b2b9b00-e66a-11e8-835e-e83b4b986c78.png)

### Acceptance Criteria
- The content should remain similar to the original in layout (headers, titles, etc) and in length

### Potential Solutions
- Keep the existing content but scramble the letters in each word
- Leave the headings the same but replace the words with gibberish (lorum ipsum, etc) keeping the word count
- We are very open to other solutions. Whatever is easiest to implement and maintain that will prevent the readers from reading the blurred content but still give them a good idea of the format of what is being hidden.

**Comment by ksmoore125** [comment]
> The length of blurred content shown is set using `Content Preview under Overlay` in `Settings -> LaterPay`
> 
> It is supposed to give a preview of part of the paid content so I am not sure if we should scramble that part. We can scramble the text but it won’t convey very clearly what the post has in it. Right now what I can see is if value of all setting is set to` 0` it shows all the content.

I think that the importance of preventing the reader from circumventing LaterPay and reading the "blocked" content is higher than conveying what the post contains. We want to give them a general idea as far has headings, images, and length of the article but we don't want them to be able to read it without paying. I believe that just scrambling the letters within the words (if that is possible) should make it difficult to read but will still show the length & layout of the article. We can discuss on our call tomorrow if you have additional doubts or suggestions.

**Comment by ksmoore125** [comment]
Overall this looks good, could we make two changes:

1) Would it be possible & without too much effort to leave headings with the original text just blurred?

2) If we look at the same article free & burred side by side. It appears that the free version has a white space under the paragraph (like <p></p> or <br><br>) whereas the burred content just starts a new line (<br>). Could we add the line breaks to the burred content?

![image](https://user-images.githubusercontent.com/41650164/49024745-d1de6400-f15f-11e8-99d5-930a05a241c6.png)

**Comment by thrijith** [comment]
>1. Would it be possible & without too much effort to leave headings with the original text just blurred?

`Heading 1` is part of the content right? 
Right now we are replacing the content inside tags with scrambled text.

I've updated code to not scramble text if it is inside heading tags like **h1,h2,h3,h4,h5,h6**

Let me know if this is ok. So we can merge and test on staging.

>2 Could we add the line breaks to the burred content?
This is also done.

**Comment by ksmoore125** [comment]
This is perfect. Thanks!

**Comment by thrijith** [comment]
Fixed and released in [2.3.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.3.0)
