### ISSUE TITLE
User Management: Select User Role

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1054]
https://laterpay.atlassian.net/browse/PRODUCT-234

### User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.
**Using another plugin:** Merchants can set up roles to adjust the user experience to create premium offerings. These roles could do things such as remove ads, remove pop-ups, or provide access to commenting, etc.
**LaterPay plugin:** Needs to assign the user to this role when they purchase a specific pricing option (time pass or subscription).

### Goal
For each time pass & subscription allow the merchant to select one or more existing user roles to which they would like the user assigned
- If it is significantly more effort, the scope can be limited to only allowing the merchant to select one user role

### Acceptance Criteria
When the merchant creates or edits a time pass or subscription they should be provided with:
- A list of existing user roles
  - We should not allow/display backend roles or any role that has these capabilities
- The merchant should be able to select one or more (optional) user role(s)
- Dropdown description:
> Grant purchasers access to: *(optional)*
- Put an info (i) icon to the right of the dropdown box which displays the following tooltip on hover:
> Give readers who purchase this option a premium experience by assigning them to a user role with access to special features or disabled disruptive features (like ads).

### Mockup & Prototype
https://sketch.cloud/s/45evm/OmoePVw/play
![image](https://user-images.githubusercontent.com/41650164/49179392-ccc41500-f317-11e8-899a-29f8b2725ad0.png)

**Comment by thrijith** [comment]
@ksmoore125 

>A list of existing user roles
>We should not allow/display backend roles or any role that has these capabilities

We will only list roles that have reading capability, if role has more capability than that it won't be secure.

Let me know if that's fine.

**Comment by ksmoore125** [comment]
If possible, I would like to include Subscriber but will trust your judgement if it is best to leave that one off as well.

**Comment by ksmoore125** [comment]
Given our new plan this is no longer required. Won't Do.
