### ISSUE TITLE
User Management: Assign User Role

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1055]
https://laterpay.atlassian.net/browse/PRODUCT-234

### User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.
**Using another plugin:** Merchants can set up roles to adjust the user experience to create premium offerings. These roles could do things such as remove ads, remove pop-ups, or provide access to commenting, etc.
**LaterPay plugin:** Needs to assign the user to this role when they purchase a specific pricing option (time pass or subscription).

### Goal
When an end-user successfully accesses content:
- We check to see if this content was purchased using a time pass or subscription which has a role associated to it
  - If so, the user should be assigned to that role
  - If not, we do nothing

### Acceptance Criteria
- **If a user has access to the content and is logged in to WordPress**
  - The role(s) should be added to any existing roles associated with their user account
- **If a user has access to the content and is NOT logged in to WordPress**
  - We create a new WordPress user account using their LaterPay email address (returned by the API) and a GUID for the password
  - The role should be added to that account
- **General:**
  - If a user has multiple roles, the WordPress UI will only display one. This is acceptable. We will simply add this role(s) to any existing role(s) the user has. We will not worry about whether or not this is displayed in the WordPress UI.

### Creating a new User Account
**WordPress Requirements**
- Username (email) & Password

**LaterPay Requirements**
- Ability to identify the user based on what is returned by the API (so that we do not create a new user every time they read an article or access the site)

**Comment by thrijith** [comment]
>When an end-user successfully accesses content:
>We check to see if this content was purchased using a time pass or subscription which has a role associated to it

When the user visits a page it checks if the user has access. If user has access we will check whether the post has a timepass/subscription which adds role and user bought it. If true then add logged in user to the role.

>If a user has access to the content and is NOT logged in to WordPress
>We create a new dummy user account

Not sure how this should be done. What deatils would be used to create account?

>We should track each time a new user account is created (along with the merchant id) so that we can monitor and ensure that this is not getting out of control

Is the tracking part meant for analytics? I am not sure what is `ensuring` meant here. Is it account creation?

**Comment by ksmoore125** [comment]
> When the user visits a page it checks if the user has access. If user has access we will check whether the post has a timepass/subscription which adds role and user bought it. If true then add logged in user to the role.
Yes

> Not sure how this should be done. What deatils would be used to create account?
This is the tricky part and I am open to suggestions. I will update in the details of the ticket above so that it is easier to keep track as we move forward.

> Is the tracking part meant for analytics? I am not sure what is ensuring meant here. Is it account creation?
Yes, make this an event in Google analytics so that we can track each time a new dummy user is created & which merchant they were created under.

**Comment by ksmoore125** [comment]
Given our new plan this is no longer required. Won't Do.
