### ISSUE TITLE
User Management: UNassign User Role

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1056]
https://laterpay.atlassian.net/browse/PRODUCT-234

### User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.
**Using another plugin:** Merchants can set up roles to adjust the user experience to create premium offerings. These roles could do things such as remove ads, remove pop-ups, or provide access to commenting, etc.
**LaterPay plugin:** Needs to assign the user to this role when they purchase a specific pricing option (time pass or subscription).

### Goal
When an end-user FAILS to accesses content:
- We check to see if this content was purchased using a time pass or subscription which has a role associated to it
  - If so, the user should be REMOVED from that role
  - If not, we do nothing

### Acceptance Criteria
- **If a user does not have access to the content and is logged in to WordPress**
  - The LaterPay role(s) associated to that content should be removed from their account
  - Any other existing roles associated with their user account should not be modified
- **If a user does not have access to the content and is NOT logged in to WordPress**
  - No action is required since they will not have any roles assigned to them if they are not logged in

**Comment by thrijith** [comment]
>When an end-user FAILS to accesses content:
>We check to see if this content was purchased using a time pass or subscription which has a role associated to it

When the user visits a page it checks if the user has access. If user doesn't have access we will check whether the post has a timepass/subscription which adds role and remove if the role exists in user.

**Comment by ksmoore125** [comment]
Correct.

**Comment by ksmoore125** [comment]
Given our new plan this is no longer required. Won't Do.
