### ISSUE TITLE
User Management: Require WordPress Sign in

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1057]
https://laterpay.atlassian.net/browse/PRODUCT-234

### User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.
**Using another plugin:** Merchants can set up roles to adjust the user experience to create premium offerings. These roles could do things such as remove ads, remove pop-ups, or provide access to commenting, etc.
**LaterPay plugin:** Needs to assign the user to this role when they purchase a specific pricing option (time pass or subscription).

### Goal
We should allow the merchant to require the user to log in to WordPress instead of us creating "dummy accounts."
Der Bank Blog requirement:
> collect user emails via the native WP registration form

### Acceptance Criteria
**Merchant Experience:**
- Add a text box on the Settings page where the merchant can enter the location of their registration page (URL / page id / whatever you recommend)
  - This should go directly above the existing "Require login" section
    - Title: WordPress User Registration Page
    - Description: If you would like to provide a premium experience by requiring your readers to sign-in to WordPress, please provide us with your User Registration Page.
    - Textbox description: WordPress User Registration Page URL
  - If this is not filled in the "Require users to log in" should be disabled with a disclaimer that they must provide the location of the registration form before they can require this. Disclaimer:
> Please go to Settings > LaterPay and complete the "WordPress User Registration Page" section.
- After a merchant has selected a user role, they should be provided with the ability to require users to log in to WordPress
  - Check box description:
> Require WordPress sign-in:
  - Put an info (i) icon to the right of the checkbox which displays the following tooltip on hover:
> If checked, your readers will be redirected to your registration page after they purchase this option. If un-checked, we will create a fake account on their behalf to ensure a frictionless experience. 

**End-User Experience:**
When a user successfully purchases a time pass or subscription which requires the user to log in to WordPress, after the purchase
- The user should be redirected to the registration page
  - *Assumption:* If the user is already logged in, it will automatically sign them in
- Once they have registered (or been automatically signed in), they should be redirected to the content they just purchased with their new user role assigned (#1055)

### Mockup & Prototype
https://sketch.cloud/s/45evm/OmoePVw/play
![image](https://user-images.githubusercontent.com/41650164/49179216-6ccd6e80-f317-11e8-928e-aa8ba6dbd9be.png)

**Comment by thrijith** [comment]
>When a user successfully purchases a time pass or subscription which requires the user to log in to WordPress, after the purchase

Should we keep login before purchase? What should be done if user doesn't signup after purchase?

>we will create a fake account on their behalf to ensure a frictionless experience.

We will need details here too for account creation.

**Comment by ksmoore125** [comment]
CLOSING TICKET - This is no longer required if we retrieve their LaterPay email address via the API; this is instead replaced with #1065
