### ISSUE TITLE
Custom Table Migration Part 2

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1058]
Custom Table Migration Part 1: #984 

### Acceptance Criteria
- Check if the user has completely migrated or not
  - If they have migrated
    - Nothing is required
  - If they have not migrated
    - Disable upgrade to v2.4.0
    - Display the following message on the plugin page (to explain why they cannot upgrade)

> LaterPay has updated their plugin to remove dependencies on custom tables. You must `migrate your data` before you can update to future versions of LaterPay. This will not result in any visible changes to your site or your plugin set up.
> 
> Click `here` to migrate.

*Text with a grey background `denotes hyperlink to kick off migration`

**Comment by thrijith** [comment]
>If they have not migrated
>* Disable upgrade to v2.4.0
>* Display the following message on the plugin page (to explain why they cannot upgrade)


@ksmoore125 We can't deactivate the plugin and provide an option to migrate.

I've added an option to display a notice and deactivate the plugin if data has not been migrated. 

If we wan't to provide an option to migrate in `2.4.0`, will have to disable plugin functionalities accordingly.

You can check the notice in https://github.com/laterpay/laterpay-wordpress-plugin/pull/1064 description. Let me know if the current implementation is fine or needs change.

Thanks

**Comment by ksmoore125** [comment]
So if they have not migrated, the plugin will be deactivated. Then how will they migrate if they cannot do so while the plugin is disabled? Can we provide an easy downgrade button so that they can revert to v2.3.0 and then migrate?

**Comment by ksmoore125** [comment]
Thank you for the clarification, so to update the ticket:

### Acceptance Criteria
- Check if the user has completely migrated or not
  - If they have migrated nothing is required
  - If they have not migrated:
    - Deactivate LaterPay Plugin
    - Display the following message as many places as possible

> WARNING! Your LaterPay plugin has been disabled.
> LaterPay has updated their plugin to remove dependencies on custom tables. You must migrate your data before you can re-activate your plugin. 
> 
> To complete this process, please Rollback your plugin to v.2.3.0 and click the header to migrate your data. Once this is complete you will be free to successfully update and re-activate your plugin.
>
> If you do not have a preferred Rollback method, we recommend WP Rollback.
> Please contact support@laterpay.net if you have any questions or concerns.

* WP Rollback is what I am currently using on my test site however we can recommend another plugin or link to other instructions if you would prefer. If you approve of using WP Rollback then please link that to https://wordpress.org/plugins/wp-rollback/

**Comment by thrijith** [comment]
@ksmoore125 Update the notice with rollback instructions.

>Display the following message as many places as possible

This will be displayed after de-activation and unfortunately, it will disappear on refresh. We can't keep the notice anywhere other than that as the plugin isn't active anymore.

![notice_example](https://user-images.githubusercontent.com/13589980/50336779-fe09bc80-0534-11e9-8241-398a04a60b71.png)

**Comment by ksmoore125** [comment]
Ok, thanks!

**Comment by thrijith** [comment]
Fixed and released in [2.4.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.0)
