### ISSUE TITLE
Remove "Buy a ... to read the full content." at the Bottom of Articles

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1062]
### Requirements
One of our merchants has asked that we remove the following sentence which appears if they have an active time pass or subscription available for purchase on that post.
- Remove "Buy a ... to read the full content." sentence from the bottom of articles
- Known variants of this sentence are:
  - Buy a time pass to read the full content.
  - Buy a subscription to read the full content.
  - Buy a time pass or subscription to read the full content.

### Screenshot
![49306344-92818180-f497-11e8-9816-dd4f7b3450eb](https://user-images.githubusercontent.com/41650164/49308410-d4adc180-f49d-11e8-97e8-f39ac2dd159b.png)

**Comment by thrijith** [comment]
Fixed and released in [2.4.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.0)
