### ISSUE TITLE
User Management: Require LaterPay Sign-in

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1065]
https://laterpay.atlassian.net/browse/PRODUCT-234

### User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.
**Using another plugin:** Merchants can set up roles to adjust the user experience to create premium offerings. These roles could do things such as remove ads, remove pop-ups, or provide access to commenting, etc.
**LaterPay plugin:** Needs to assign the user to this role when they purchase a specific pricing option (time pass or subscription).

### Goal
Given that this feature requires the end-user's email address, we must ensure that the email address is available in all scenarios.

### Acceptance Criteria
```
Pending the answers to the following questions:
1) Settings > LaterPay has the option to 
"Require the user to log in to LaterPay before a "Pay Later" purchase." 
Is it possible to enable this functionality only for specific Time Passes 
(ie: If a merchant sets up a PayLater Time Pass and selects a User Role to be applied on purchase)
or must it be applied to all Pay Later purchases?
```
- If it is a PayNow purchase: The user must register with LaterPay with their purchase therefore we will have their email address; no additional work required
- If it is a PayLater purchase (Time Passes): The user is not required to register and therefore we will not have their email address if they are a new customer
  - If a merchant sets up a PayLater Time Pass and selects a User Role to be applied on purchase, display the following message: _to be determined after additional discovery questions (above) are answered_

### Mockup & Prototype
https://sketch.cloud/s/45evm/OmoePVw/play
![image](https://user-images.githubusercontent.com/41650164/49179392-ccc41500-f317-11e8-899a-29f8b2725ad0.png)

**Comment by thrijith** [comment]
>Is it possible to enable this functionality only for specific Time Passes
(ie: If a merchant sets up a PayLater Time Pass and selects a User Role to be applied on purchase)
or must it be applied to all Pay Later purchases?
> If a merchant sets up a PayLater Time Pass and selects a User Role to be applied on purchase.

This can be done. That is if Time Pass has some data related to role to be applied on purchase we can override behaviour of backend setting for that particular time pass.

If 'none' is selected and backend setting is also disabled user should be able to purchase without login also.

**Comment by ksmoore125** [comment]
Given our new plan this is no longer required. Won't Do.
