### ISSUE TITLE
Capture Merchant Usage Data & Send to Google Analytics

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1066]
### User Story
As the WordPress Plugin Product Manager, I would like to know which feature are and are not being used by our merchants so that we can more accurately prioritize future projects and also understand where our merchants are struggling to use the product.

### Acceptance Criteria
- Pass the information provided in the spreadsheet below into the LaterPay Google Analytics account

https://docs.google.com/spreadsheets/d/1lELa7pzgTyOXPJA3kJhTwoBzbj2HP9AmREzRLeh3bx0/edit?usp=sharing

**Comment by ksmoore125** [comment]
Testing Note in regards to LP WP Pricing > Pricing Summary

> Thrijith Thankachan 
> This should be automatically triggered on page load of pricing.
> 
> Last triggered date is stored in browser storage. To clear that 
> 
> Visit the backend pricing tab.
> 
> On chrome click on 3 dots 
> Select 'More Tools > Developer Tools'
> 
> Open Application tab.
> On left hand you can should see a menu. Click and expand 'Local Storage'. Click on the site you are testing.
> 
> Select 'lpSummarySentDate' and click on the cross button. Reload the page again to trigger events.
> 
> Below is a screenshot of the place where you will find the summary date stored
> 
> https://drive.google.com/open?id=1ufYtkjD10PSaq1Nl3CuqhOGlB0WPS3aP

**Comment by ksmoore125** [comment]
> For encryption we will have to encrypt the Merchant Id with a secret key. That would have to pre set in the source code. Since our code is open source it can used to reverse engineer and get merchant Id.

After discussing this with the LaterPay team, there are other instances where the Merchant Id could be derived from the code so we can remove this requirement.

**Comment by thrijith** [comment]
Fixed and released in [2.4.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.0)
