### ISSUE TITLE
Post should not display as "FREE" if "Global Default Price" is not selected

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1067]
### User Story
One of our merchants has let us know that they are confused when the post displays as FREE on the post page even after they have set a price.
![image](https://user-images.githubusercontent.com/41650164/49598755-ecc18d00-f944-11e8-88ce-1a91093baab5.png)

### Acceptance Criteria
When the Global Default Price is set to "FREE unless price is set on post page or by category" on the Post Page if...
 
- Global Default Price is selected, no change in behavior
![image](https://user-images.githubusercontent.com/41650164/49598791-04007a80-f945-11e8-96cb-1cc5c4b93440.png)

- Category Default Price is selected, hide the Global Default value
![image](https://user-images.githubusercontent.com/41650164/49599202-01eaeb80-f946-11e8-8286-af38314bc94e.png)

- Individual Article Price is selected, hide the Global Default value
![image](https://user-images.githubusercontent.com/41650164/49598974-6ce7f280-f945-11e8-8c8c-f7e89a37eb77.png)

**Comment by thrijith** [comment]
Fixed and released in [2.4.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.0)
