### ISSUE TITLE
If Post is Assigned to a Category with Category Default Pricing, Global Default Cannot be Selected

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1068]
### User Story
I was testing another ticket and set up a Category Default Price then noticed that the Global Default Price was grey-ed out. This was quite confusing.
![image](https://user-images.githubusercontent.com/41650164/49599716-49be4280-f947-11e8-9a89-9b7241484a50.png)

### Acceptance Criteria
- If it is simple, we should allow the merchant to select the Global Default Price (thereby over-ridding the Category Default Price like we would do if they selected the Single Article Price)
- If the above suggestion is a large effort, then we can leave the functionality as is but with the following tooltip: "Global Default Pricing is not available to Posts which have a Category Default Price."

**Comment by thrijith** [comment]
>If it is simple, we should allow the merchant to select the Global Default Price (thereby over-ridding the Category Default Price like we would do if they selected the Single Article Price)

@ksmoore125 How will it affect based on `Global Default Price` selection?

For example. 
If `Every post is FREE unless they match a Category Default Price...`
Should `Global Default Pricing` allowed for selection?

>thereby over-ridding the Category Default Price like we would do if they selected the Single Article Price

Not sure if that should be done if the selection is `Every post is FREE unless they match a Category Default Price...`

Please correct if wrong.

Thanks.

**Comment by ksmoore125** [comment]
Let's just do the following:

> ... we can leave the functionality as is but with the following tooltip: "Global Default Pricing is not available to Posts which have a Category Default Price."

The tooltip should display on hover of the disabled Global Default Price option.

Please let me know if you have any additional questions!

**Comment by thrijith** [comment]
Fixed and released in [2.4.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.0)
