### ISSUE TITLE
LaterPay Queries run on Content where LaterPay is Disabled

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1079]
# User Story
As a LaterPay merchant, I would like to be able to use the LaterPay plugin without needing to install any additional plugins (for caching etc) and without noticeably slowing my site.

_See https://docs.google.com/document/d/1hFfDnFlY-DXcySoYYyDAqc5DTYzjhrE4UjpSvt6sAYI/edit?usp=sharing for log of customer communications_

# Acceptance Criteria
WordPress content with LaterPay disabled should run as few queries / checks as possible and should not have a noticeable performance hit when the LaterPay plugin is enabled.

### Steps to Reproduce

1. Navigate to http://kimberlystestsite.cloudaccess.host/wp-admin/admin.php?page=laterpay-pricing-tab and observe that `Pages` are disabled
2. Navigate to http://kimberlystestsite.cloudaccess.host/ (a page therefore LaterPay is disabled)
3. Note that the page takes 0.48s to load
4. Deactivate the LaterPay plugin and refresh http://kimberlystestsite.cloudaccess.host/

**Observed Result**
The page takes 0.08s to load. That is 0.4s less than when the LaterPay plugin was activated.

**Desired Result**
The page performance should not noticeably change.

In the example in the Google doc above (see page 6), there are a high number of queries being run on a `page` even though I do not have LaterPay enabled for `pages`. Ideally, we would only run queries / check for access when an end user is on a post or page etc with blocked content. We would not want to run queries for every post / page whose title is listed in the sidebar, for example.

**Comment by thrijith** [comment]
Fixed and released in [v2.5.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.3)
