### ISSUE TITLE
Self-service merchant may be confused by the Voucher layout in WordPress

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1080]
### User Story
As a new merchant, I would like to be able to use all features of the LaterPay WordPress plugin without any confusion or hesitation. Currently, the fact that the "+ Generate Voucher Code" is below where you input the price for the voucher is a bit confusing.

### Acceptance Criteria
Adjust the layout per the mockup below
![image](https://user-images.githubusercontent.com/41650164/50841947-63c6b880-132b-11e9-9243-992e1626138c.png)

**User Flow**
User sets up Timepass / Subscription & user wishes to set up a voucher:
1) User clicks "+ Generate voucher code"
2) Voucher code, "reduces the price to" with text box for price input & description input appears

> Note: With step 2, "+ Generate voucher code" should now be below the voucher information so that the merchant can easily add additional voucher codes by repeating steps 1 & 2

3) Clicking save will save the newly created voucher code

https://laterpay.atlassian.net/browse/PRODUCT-233

**Comment by thrijith** [comment]
@ksmoore125 Once the time pass or subscription is saved after voucher generation. Should the price of existing vouchers ( generated vouchers ) be editable?

**Comment by ksmoore125** [comment]
You are correct that the functionality should work as it does today so that the existing vouchers should not be editable
![image](https://user-images.githubusercontent.com/41650164/51253704-b07e4500-1964-11e9-9b5c-eec7aa54ac9b.png)

**Comment by thrijith** [comment]
Released in [v2.4.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.2)
