### ISSUE TITLE
Warn Merchants that Uninstall will Remove Data

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1081]
### User Story
As a LaterPay WordPress merchant experiencing issues with the plugin, often my first instinct is to do a rollback (without a backup, but rather by trying to install a former version of the plugin through the wp backend gui) and I destroy all of my setup in the process.

### Potential Solutions
A) Would it be possible to do something like this:
![image](https://user-images.githubusercontent.com/41650164/50849955-20c21080-133e-11e9-99e5-34411ee432fa.png)

B) Adjust how we Delete the plugin now so that data is preserved unless they choose to remove via a second full uninstall routine similar to:
![image](https://user-images.githubusercontent.com/41650164/50850064-73033180-133e-11e9-8619-bad6462c117e.png)

C) Modify the uninstall warning from:
> Are you sure you want to delete LaterPay and its data?

to:

> Are you sure you want to delete LaterPay and ALL its data? You will loose all pricing configurations. This cannot be undone.

**Comment by ksmoore125** [comment]
Per our discussion, options A) & C) above are not possible so we will proceed with option B)

I would like to put this on the Account tab. Is this an acceptable option? 
Another suggestion was the LaterPay Settings page, are there any benefits to putting it there?

Let me know which if one preferred over the other from a technical perspective and I can put together a quick mockup. Thanks!

**Comment by thrijith** [comment]
>I would like to put this on the Account tab. Is this an acceptable option?

Seems Ok to me. The current behavior is, when the plugin is deleted from the site all data is removed.
If we proceed with above option. It will be triggered when it is called from Account Tab ( Data will be erased and the plugin will be deactivated )

>Another suggestion was the LaterPay Settings page, are there any benefits to putting it there?

We can also add an option in settings which merchant can select i.e to delete data on plugin delete. We can provide a checkbox where the user could select if the data should be cleaned when the plugin is uninstalled in the normal way.

**Comment by ksmoore125** [comment]
### Acceptance Criteria
Please add the following section to the bottom of the account tab
- Title: Delete Plugin & Data
- Message: 
**Warning!** This operation removes the LaterPay plugin and deletes ALL its data. 
You will lose all appearance settings and pricing configurations. This cannot be undone.
_
[Click here](https://www.laterpay.net/contact-support) or email support@laterpay.net to provide feedback or to reach our customer service team.
- Button Text: Delete Plugin
- Warning Message: Are you sure you want to delete LaterPay and ALL its data? You will loose all pricing configurations. This cannot be undone.
- Warning Message Options: `Delete LaterPay` `Cancel`

### German Translation
_Pending_

### Mockup:
![image](https://user-images.githubusercontent.com/41650164/51269499-46779700-1988-11e9-9805-d2509937f1c9.png)

**Comment by ksmoore125** [comment]
I am sorry I misunderstood the first time. Let's adjust the functionality to:
1) On account tab the merchant can erase data and deactivate plugin
2) After deactivation the user us redirected to plugins page to delete plugin

Data should not be erased from the Plugins page. This should only be deleted if the merchant performs step 1 above.

Updated text for the Account Page
### English Version
- Title: Deactivate Plugin & Delete Data
- Message: 
**Warning!** This operation deactivates the LaterPay plugin and deletes ALL its data. 
You will lose all appearance settings and pricing configurations. This cannot be undone.
_
[Click here](https://www.laterpay.net/contact-support) or email support@laterpay.net to provide feedback or to reach our customer service team.
- Button Text: Deactivate Plugin & Delete Data
- Warning Message: Are you sure you want to delete LaterPay and ALL its data? You will loose all pricing configurations. This cannot be undone.
- Warning Message Options: `Delete LaterPay Plugin` `Cancel`

### German Translation
- Title: Plugin & Daten deaktivieren
- Message: 
**Achtung!** Diese Operation deaktivieren das LaterPay Plugin und löscht alle Daten unwiderruflich.
Sie verlieren hierbei alle Layout- und Preiskonfigurationen. Diese Aktion kann nicht rückgängig gemacht werden.
_
[Klicken Sie hier](https://www.laterpay.net/contact-support) oder schreiben Sie eine Email an support@laterpay.net, um Feedback zu geben oder mit unserem Kundensupport Kontakt aufzunehmen.
- Button Text: Plugin & Daten deaktivieren
- Warning Message: Sind Sie sicher, dass Sie LaterPay und alle Daten löschen möchten? Sie verlieren alle Preiskonfigurationen. Diese Aktion kann nicht rückgängig gemacht werden.
- Warning Message Options: `LaterPay Plugin löschen` `Abbrechen`

**Comment by thrijith** [comment]
@ksmoore125 Here are the is the behaviour in various environments and deactivation from plugins page after the change.

Unable to upload GIF so attaching drive link.
 
Non-VIP env: https://drive.google.com/open?id=1kYZExEh3I-xqXnF5TLvU7gdjCopAqqlW
VIP env: https://drive.google.com/open?id=1nssIbnZDYIRhP8xHjg1BWymKevSWj4TK
Deletion from plugins page: https://drive.google.com/open?id=1TdFZtsvG1UWAcAF4qKEskbH3pVHvRtTb

Please note I've added/updated some string for VIP env and other. Could you please add translations for the same?

NON-VIP

1. Button Text : Delete Plugin Data
2. Action Completed Text: LaterPay data has been erased successfully.
3. Message (Part of it which has change): Warning! This operation deletes ALL LaterPay plugin data.
4. Warning Message: Are you sure you want to delete ALL LaterPay Plugin data? You will loose all pricing configurations. This cannot be undone.
5. Warning Message Options: Delete LaterPay Plugin Data

VIP

1. Action Completed Text: LaterPay has been successfully uninstalled. It can be re-activated from the plugins page.
2. Warning Message: Are you sure you want to deactivate LaterPay plugin and delete ALL its data? You will loose all pricing configurations. This cannot be undone.
3. Warning Message Options: Deactivate LaterPay Plugin

Thanks

**Comment by ksmoore125** [comment]
This looks great! Please proceed. I am awaiting translations from our native German speakers.

**Comment by ksmoore125** [comment]
VIP German Translations

Button Text : Plugin Daten löschen
Action Completed Text: Alle LaterPay Daten wurden erfolgreich gelöscht.
Message: Achtung! Diese Operation löscht alle LaterPay Plugin Daten unwiderruflich.
Warning Message: Sind Sie sicher, dass Sie alle LaterPay Daten löschen möchten? Sie verlieren alle Preiskonfigurationen. Diese Aktion kann nicht rückgängig gemacht werden.
Warning Message Options: Plugin Daten löschen

**Comment by thrijith** [comment]
Released in [v2.4.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.4.2)
