### ISSUE TITLE
Update WordPress Plugin Home Page to be more Sales / Marketing Driven

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1107]
https://wordpress.org/plugins/laterpay/

The `Description` tab, can be updated by editing the following section of this file.

https://github.com/laterpay/laterpay-wordpress-plugin/blob/5838219d10adb4b06490ff87a9b5f01aa6df42a7/laterpay/README.txt#L16

**Comment by ksmoore125** [comment]
https://docs.google.com/document/d/1IMHrw66xS_OSonpM7NIgVtTp2pcD2qCA_GWxTMeYBgM/edit?ts=5c882466#heading=h.ldakccppzqdm

**Comment by thrijith** [comment]
Released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
