### ISSUE TITLE
Create "Advanced" Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1109]
### User Story
As a self service user, I just want to get up and running as quickly as possible.
As a power-user, I want all of the features possible at my finger-tips.
We need to be able to support both as simply as possible.

### Acceptance Criteria
Create a new "Advanced" tab which will contain information on all of our "advanced" features, specifically:
- Information on under-used or hidden features
  - Merchant Analytics Dashboard (in LaterPay)
  - Secure Download Widget
  - Payment Button shortcode
  - Dynamic Pricing
  - Custom Positioning (at a later date)
- Settings Available on the Settings > LaterPay page with links
- Information removed from the existing Account tab
  - Deactivate Plugin & Delete Data
  - ~~Sandbox Environment~~
- All external links should open in new tabs

### Mockup
_If additional design specifications is needed, let us know and our designer would be happy to help._

![image](https://user-images.githubusercontent.com/41650164/53256705-178ec800-368e-11e9-833f-6637160a97c8.png)

### Main Content
**Advanced Features | Erweiterte Funktionen**

English | German | Notes
-----|-----|-----
ANALYTICS | ANALYTICS | (section not shown in mockup)
LaterPay's Analytics Dashboard helps track your sales over time so that you can easily see how your content is performing and which posts are driving the highest revenues.  | Das Analytics Dashboard von LaterPay hilft Ihnen, Ihre Verkäufe im Laufe der Zeit zu verfolgen, so dass Sie sehen können, wie Ihre Inhalte funktionieren und welche Beiträge die höchsten Einnahmen bringen. | [screenshot here](https://drive.google.com/file/d/198pPxGw7JIdLlAO52O8HWLJLFVo01vVD/view?usp=sharing)
[Click here to view your dashboard.](https://web.uselaterpay.com/dialog/entry/?redirect_to=/merchant/#/login) | [Klicken Sie hier, um Ihr Dashboard zu sehen.](https://web.laterpay.net/dialog/entry/?redirect_to=/merchant/#/login) | (url is different depending on region)
ASK FOR CONTRIBUTIONS | SPENDEN UND BEITRÄGE FÖRDERN | (section not shown in mockup)
Using the LaterPay Button Generator, in just a couple of minutes you can create a custom contributions button that can be used on your website, in email, or social media posts.|Mit dem LaterPay Button Generator können Sie in nur wenigen Minuten einen benutzerdefinierten Beitragsbutton erstellen, der auf Ihrer Website, in E-Mails oder Social Media-Posts verwendet werden kann.| [screenshot here](https://drive.google.com/file/d/1kSMl1eke_RXG1dFUvVq34EiNBiLrRcDr/view?usp=sharing)
[Click here to go to our Button Generator.]() | [Klicken Sie hier, um zu unserem Button Generator zu gelangen.]() | URL is a bit complex: If Live Merchant ID is blank: https://www.laterpay.net/signup/merchant If Live Merchant ID is not blank: **EU:** https://web.laterpay.net/merchant/admin/laterpaycontributions/button-generator/ **US:** https://web.uselaterpay.com/merchant/admin/`MerchantID`/button-generator/ (where `MerchantID` is their merchant ID)
CHARGE FOR DOWNLOADABLE CONTENT | GEBÜHR FÜR HERUNTERLADBARE INHALTE | [screenshot here](https://drive.google.com/file/d/1dJkEE2M7NH3qai09vbcZzAYD-cyogaYj/view?usp=sharing)
Using a custom [shortcode](https://en.support.wordpress.com/shortcodes/), you can easily charge for downloadable content (such as PDFs). This short code allows you to customize the content, heading, description, and background image. | Mithilfe von einem benutzerdefinierten [Shortcode](https://en.support.wordpress.com/shortcodes/) können Sie für herunterladbare Inhalte (z.B. PDFs) Gebühren erheben. Der Shortcode erlaubt Ihnen, den Inhalt, die Überschrift, die Beschreibung und das Hintergrundbild anzupassen. |
[Click here for detailed instructions.](https://www.laterpay.net/academy/how-to-charge-for-downloadable-content-in-the-laterpay-wordpress-plugin) | [Klicken Sie hier für eine detaillierte Anleitung.](https://www.laterpay.net/academy/how-to-charge-for-downloadable-content-in-the-laterpay-wordpress-plugin)|
CREATE SUBSCRIPTION BUTTON | ABONNEMENT ERSTELLEN | [screenshot here](https://drive.google.com/file/d/1FSmOhIcZmxS_Pa1L4uDR-yX6qJIOuzv-/view?usp=sharing)
With this [shortcode](https://en.support.wordpress.com/shortcodes/), you can create a button to promote a subscription or time pass anywhere on your site. The button background color, font color, and text can be easily customized or you can upload an image to use for the button.| Mit diesem [Shortcode](https://en.support.wordpress.com/shortcodes/) können Sie einen Button erstellen, um Abonnements oder Zeitpässe auf Ihrer Website zu fördern. Die Hintergrundfarbe, Schriftfarbe und der Text des Buttons können leicht angepasst werden. Alternativ können Sie ein Bild hochladen, das für den Button verwendet werden soll. | 
[Click here for detailed instructions.](https://www.laterpay.net/academy/how-to-create-a-subscription-button-in-the-laterpay-wordpress-plugin)  | [Klicken Sie hier für eine detaillierte Anleitung.](https://www.laterpay.net/academy/how-to-create-a-subscription-button-in-the-laterpay-wordpress-plugin) |
DYNAMIC PRICING | DYNAMISCHE PREISSETZUNG | [screenshot here](https://drive.google.com/file/d/1Os62HCwgUXg9tkX5a4zX7OGe9y0qBMSE/view?usp=sharing)
Dynamic pricing is a feature available on the Edit Post page. Once there, simply choose “Individual Price” in the Pricing for this Post section then click “+ Add dynamic pricing” at the bottom. Once you’ve completed this, you can drag and drop the points on the graph to adjust pricing based on the days since the article was originally published. | Dynamische Preisgestaltung ist eine Funktion, die auf der Seite "Beitrag Bearbeiten" verfügbar ist. Wählen Sie "Individueller Preis" im Abschnitt "Preise" für den Beitrag und klicken Sie dann unten auf "+ Dynamische Preisgestaltung hinzufügen". Nun können Sie die Punkte in der Grafik verschieben, um die Preise anzupassen. | 
~~Click here for pricing tips from our experts.~~  | ~~Klicken Sie hier, um Preisinformationen von unseren Experten zu erhalten.~~ | _Article not ready yet, we can add this later._ 

**Advanced Settings | Erweiterte Einstellungen**
`The arrows & hyperlinks should link to the corresponding anchor on the Settings > LaterPay page.`

English | German | Notes
-----|-----|---
ACCESS| ZUGRIFF | 
[Click here to adjust your LaterPay user access settings.]() Within these setting you can: | [Klicken Sie hier, um Ihre LaterPay-Benutzereinstellungen anzupassen.]() Innerhalb dieser Einstellung können Sie: | 
• Require end-users to login prior to purchase | • Endbenutzer auffordern, sich vor dem Kauf einzuloggen | 
• Give unrestricted access to specific user roles | • Bestimmten Nutzerrollen uneingeschränkten Zugriff geben |
APPEARANCE| DARSTELLUNG | 
[Click here to access additional appearance configurations](), including: | [Klicken Sie hier für weitere Design Einstellungen](), zum Beispiel: | 
• Button & link colors | • Button & Link Farben | 
• Length of default teaser content | • Standard Teaser-Länge | 
• Length of blurred content displayed behind paywall| • Wie viel des Inhalts verschwommen hinter der Bezahlschranke erscheinen soll | 
~~CONFIGURE SANDBOX ACCOUNT~~| | _After discussing with our integrations team, this was not being used so we will simply remove it from the interface. If merchants complain we can add it in this location._
DELETE ACCOUNT| PLUGIN & DATEN DEAKTIVIEREN | 
**Warning!** This operation deactivates the LaterPay plugin and deletes ALL its data. You will lose all appearance settings and pricing configurations. This cannot be undone.| **Achtung!** Diese Operation deaktivieren das LaterPay Plugin und löscht alle Daten unwiderruflich. Sie verlieren hierbei alle Layout- und Preiskonfigurationen. Diese Aktion kann nicht rückgängig gemacht werden. |This is where we will move the existing `Deactivate Plugins & Delete Data` button
TECHNICAL| TECHNISCHE EINSTELLUNGEN | 
[Click here for more technical configuration options](), including:| [Klicken Sie hier für weitere technische Einstellungen](), zum Beispiel: | 
• Enable caching compatibility mode| • Aktivieren Sie den Caching-Kompatibilitätsmodus | 
• Define fallback behavior in case LaterPay API is not responding | • Wählen Sie ein Fallback-Verhalten für den Fall, dass die LaterPay-API nicht antwortet | 

### Sidebar Content

English | German | Notes
-----|-----|-----
TIPS & TRICKS | TIPPS & TRICKS | 
HELP! The new version of the plugin is not compatible with my site. How can I rollback? [Click here for step by step instructions.](https://support.laterpay.net/rollback-wordpress-plugin) | HILFE! Die neue Version des Plugins ist mit meiner Web Seite nicht kompatibel. Wie kann ich einen Rollback durchführen? [Klicken Sie hier für eine Schritt-für-Schritt-Anleitung.](https://support.laterpay.net/rollback-wordpress-plugin) | 
Have you found all of our Advanced Settings? [Click here to see even more LaterPay configurations.]() | Haben Sie alle unsere erweiterten Einstellungen gefunden? [Klicken Sie hier, um noch mehr LaterPay-Konfigurationen zu sehen.]() | Link should go to the Settings > LaterPay page
Pay Later can be counter-intuitive at first. [Click here]() to learn more and see our recommendations on [when to use Pay Now versus Pay Later.]() | Pay Later kann zunächst kontraintuitiv sein. [Klicken Sie hier](), um mehr zu erfahren und unsere Empfehlungen zum Verwenden von Pay Now versus Pay Later zu lesen. | `need article`
FAQs | FAQs | 
 | | See #1141 for requirements
SUPPORT | KUNDENSUPPORT | 
[Click here](https://www.laterpay.net/contact-support) or email [support@laterpay.net]() to provide feedback or to reach our customer service team. | [Klicken Sie hier](https://www.laterpay.net/contact-support) oder schreiben Sie eine Email an [support@laterpay.net](), um Feedback zu geben oder mit unserem Kundensupport Kontakt aufzunehmen. |

**Comment by ksmoore125** [comment]
See also https://github.com/laterpay/laterpay-wordpress-plugin/issues/1110

**Comment by ksmoore125** [comment]
- Under the advanced features section, please also have the image link (in a new tab) to the corresponding location
- Please move the contribution button image & subscription button image to the right column; it is ok if they need to be skinnier just keep the same ratio so that the test doesn't look stretched
- Move the arrows to the right column as well
- Make the arrow links open in new tabs
- Kimberly to provide the correct URL for "Click here to learn more and see our recommendations on when to use Pay Now versus Pay Later." later this week

**Comment by thrijith** [comment]
>Please move the contribution button image & subscription button image to the right column; it is ok if they need to be skinnier just keep the same ratio so that the test doesn't look stretched

>Move the arrows to the right column as well

@ksmoore125 Are you suggesting to move the images to the sidebar? I don't think we would be able to align the images correctly for all info.

**Comment by ksmoore125** [comment]
Sorry about that! When I mention the "right column" for the button images and the arrows, I mean:
![image](https://user-images.githubusercontent.com/41650164/54920629-ad0db980-4ed1-11e9-99b9-f1fc965d8eae.png)

**Comment by ksmoore125** [comment]
Under Tips & Tricks, please update the link for "Click here to learn more and see our recommendations on when to use Pay Now versus Pay Later." to use the following:
https://www.laterpay.net/academy/getting-started-with-laterpay-the-difference-between-pay-now-pay-later

**Comment by thrijith** [comment]
> update the link for Click here to learn more and see our recommendations on when to use Pay Now versus Pay Later.

Updated

**Comment by thrijith** [comment]
Added and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
