### ISSUE TITLE
Create ShortCode for Payment Button

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1113]
https://laterpay.atlassian.net/browse/PRODUCT-275
### Problem Statement
**Description**
Both Buchreport & Pueblo Pulp would like to have landing pages advertising their Time Passes &/or Subscriptions.
Right now in WordPress, the only way to link to these payment options is in the payment overlay.

Buchreport: recently introduced a time pass offering (1 month access to all premium content) which they'd like to advertise on a landing page. However, they don't know how to set up a page that shows the overlay with the time pass option, but without the single purchase option for the page itself. As a workaround, they currently link from a banner, which advertises the time pass, to one specific premium article instead of linking to a landing page.

Pueblo Pulp: is there anyway to have an "ad hoc" subscription page without a story. I may have missed understanding how to do this. Or maybe it's not possible. 
...
Basically I'm trying to offer a way from a membership page to offer memberships. I didn't see a way how to do that unless you click on a story with a membership. I may have missed on an option.

Here is a screenshot provided by Buchreport:
![image](https://user-images.githubusercontent.com/41650164/51691671-d63cc700-1fc0-11e9-8a4b-a8a42ae2c4b6.png)

### Acceptance Criteria
ShortCode should allow for the following components:

Parameter | Optional or Required  | Default Value  | Description
------------ | ------------- | ------------- | -------------
Pricing Category ID | Required | | _Here, could we use `Pass-15` or `Sub-17` as displayed on the Pricing tab? (see screenshot below)_
Button Text | Optional | (LP cart) Buy Now, Pay Later | If they display our default button, this will be the button text
Button Background Color | Optional | The `Main Color` on the Settings page | f they display our button, this will be the button background color 
Button Text Color | Optional | The LaterPay default color which is white (I do not believe they can override this...) | If they display our button, this will be the text color
Custom Image | Optional | If empty we display a button (outlined above) | Path to an image that should be used instead of a button

![image](https://user-images.githubusercontent.com/41650164/51696844-0dfd3c00-1fcc-11e9-8e86-bd4a330ff12c.png)

**Comment by thrijith** [comment]
Should `Button Text` just contain `Buy Now, Pay Later` in default value or the price too? If so how should we display all data?

Custom Image will override other attributes, right? ( basically, only the image will be shown and will be linked to the payment page )

@ksmoore125

**Comment by ksmoore125** [comment]
Correct, the image would just display the image and we would hyperlink it. 
Otherwise we display a button where they can modify the style if they choose to.

**Comment by thrijith** [comment]
@ksmoore125 Please check the description of https://github.com/laterpay/laterpay-wordpress-plugin/pull/1116 and let me know if something needs change.

**Comment by thrijith** [comment]
@ksmoore125 for https://github.com/laterpay/laterpay-wordpress-plugin/pull/1116#issuecomment-458249219

I can update error to be displayed just for admin users, let me know if I should do that. 
However, an admin user can use the preview option while adding a shortcode to see how it will be displayed in frontend.

![preview](https://user-images.githubusercontent.com/13589980/51890202-7e87cc80-23c1-11e9-88f9-76fe1a062fc3.png)

Please note `laterpay_premium_download` shortcode will also display error on the frontent if invalid data is provided.

For preview inside the editor, we might need to add a custom block just for the block editor, let me know whether to look into it.

**Comment by ksmoore125** [comment]
For [#1116 (comment)](https://github.com/laterpay/laterpay-wordpress-plugin/pull/1116#issuecomment-458249219). Let's proceed with the error message as described, the German translations are:
Subscription:
> Wir konnten kein Abo mit id="2" auf dieser Seite finden.

TimePass:
> Wir konnten keinen Zeitpass mit id="2" auf dieser Seite finden.

In regards to your comment above, I have started a ticket [here](https://github.com/laterpay/laterpay-wordpress-plugin/issues/1109).

**Comment by ksmoore125** [comment]
On the [staging site](https://lpwptestprod.wpengine.com/wp-admin/post.php?post=15&action=edit) everything looks good except:

1. Subscription Purchase Button – Custom
button_text is not displayed

2. Invalid Detail Result
Errors are not displayed

**Comment by thrijith** [comment]
@ksmoore125 

> button_text is not displayed

I've added a fix for this.

> Errors are not displayed

Errors will only be displayed in preview mode. You can access preview mode here.

![errorsshortcode](https://user-images.githubusercontent.com/13589980/52998083-57646e00-3448-11e9-8826-c12ac2903d2a.png)

![screenshot 2019-02-19 at 1 15 15 pm](https://user-images.githubusercontent.com/13589980/52998120-6f3bf200-3448-11e9-9610-ec6600ce97df.png)

Please check and let me know if you have any concerns.

**Comment by ksmoore125** [comment]
> 1. Subscription Purchase Button – Custom > button_text is not displayed

Resolved

> 2. Invalid Detail Result >  Errors are not displayed

I can see this on the preview screen but now that I am seeing this functionality, I believe you were right and it would be best if this were displayed on the published post as well. Would you mind making that change?

**Comment by thrijith** [comment]
> @thrijith - Is there a character limit on the `button_text` ?

Nope

**Comment by thrijith** [comment]
Released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
