### ISSUE TITLE
Subscription Vouchers: Enable voucher to only be applied for the first month

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1117]
### User Story
As a LaterPay merchant, I would like to be able to offer subscriptions at a reduced rate, or even free, for the first month of the subscription. After the first month, the rate should increase to the normal subscription rate.

### Acceptance Criteria
- Allow subscription vouchers to be 0.00 (free)
  - Existing validation should remain in place for all other amounts (ie: 0.05 is not acceptable)
- Add option for 
> Voucher applies to first `1 Month` period only.
**German**
> _Pending translation_

  - - _where `1 Month` will dynamically update to the time period selected for the subscription_
    - Box should be un-checked by default

### Mockups
![image](https://user-images.githubusercontent.com/41650164/51999035-8443e780-247f-11e9-9d89-ed2686397b87.png)

**Comment by thrijith** [comment]
@ksmoore125 

>I would like to be able to offer subscriptions at a reduced rate, or even free, for the first month of the subscription.

I tried creating a subscription with the price set to `1.49` but that isn't working as expected. Even if we remove validations for min price of `1.99`. I am not sure if the LaterPay API supports subscriptions at a lower price than `1.99` please correct me if wrong.

Current behaviour when the price is below `1.99`

![sub_min](https://user-images.githubusercontent.com/13589980/52001220-e2ef7c80-24e4-11e9-84e6-25a800e59437.gif)

>After the first month, the rate should increase to the normal subscription rate.

I am not sure what changes should be done in WP plugin for this as right now Subscription and renewal are not handled in WP Plugin.

>Existing validation should remain in place for all other amounts (ie: 0.05 is not acceptable)

Existing validation allows the price of Time Pass or Voucher of Time Pass to be `0.00` or `0.05` to be the least price from `0.01` to `0.04` are not valid.

**Comment by ksmoore125** [comment]
We will put this on hold until the functionality is made available in LaterPay as a whole

**Comment by ksmoore125** [comment]
Won't Do
