### ISSUE TITLE
Notify Merchants of New Features within the Plugin

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1119]
# User Story
As a LaterPay merchant, I would like to know what new features have been added to each new version of the plugin so that I can take advantage of them.

# Acceptance Criteria
### 1) Create a message bar to notify of new features within the plugin
This should be across the top of the plugin and displayed:
- Until it is dismissed (or a new version is installed)
- No matter which tab the merchant is on
- Ideally this should **NOT** be displayed when the plugin is first installed

### 2) Display a custom message for each release highlighting the one most important feature
For this release the message should read:
> **Version 2.6.0 Highlights**
> You can now fully customize the appearance of your payment overlay. Visit the Appearance tab to check it out!

> **Highlights der Version 2.6.0**
> Sie können nun das Erscheinungsbild Ihres Zahlungs-Overlays vollständig anpassen. Besuchen Sie die Registerkarte Aussehen, um es auszuprobieren!

### 3) Add the ability to dismiss the modal
This should hide it until the next version update
- Have an "X" in the top right corner

### 4) Add a [button to link](https://wordpress.org/plugins/laterpay/#developers) to additional features released
> Learn More

> Erfahren Sie mehr

### Additional Notes
- This modal may not be needed for minor version releases 
- Light color: #2f6f6b
- Dark (button) color: #2f6f6b
- In the mockup below, this appears above the in-page help. Let me know if this is not possible or if it will increase the difficulty level.

# Mockup
![image](https://user-images.githubusercontent.com/41650164/57727029-1a2e0780-7656-11e9-859b-429cef9be483.png)

### Inspiration
![image](https://user-images.githubusercontent.com/41650164/57725520-f1f0d980-7652-11e9-8a0b-7c1e395bd2f4.png)

**Comment by ksmoore125** [comment]
Testing Notes:

- In German, the version number and button are in German but the rest of the message is in English
- Bar missing on the Advanced tab

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
