### ISSUE TITLE
Expand Visibility Toggle Functionality

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1120]
### User Story
As a LaterPay WordPress Plugin merchant, I would like to be able to view changes while in TEST mode without those changes being visible to my site visitors.

### Acceptance Criteria
- Remove the "It is invisible / visible to visitors" toggle
- When in test mode, LaterPay should be invisible to visitors
- If the WordPress user would have access to the existing "Post Preview Mode" toggle, it should be available while in test mode

![image](https://user-images.githubusercontent.com/41650164/52970365-2cf7af80-3379-11e9-9a71-bad196bb84af.png)

**Comment by thrijith** [comment]
@ksmoore125 Please confirm on the following

> Remove the "It is invisible / visible to visitors" toggle
> When in test mode, LaterPay should be invisible to visitors

When in TEST mode plugin features will only be visible to admin users?

> If the WordPress user would have access to the existing "Post Preview Mode" toggle, it should be available while in test mode

Should the Preview Mode widget be only available in TEST mode only?

> Why would we want “Plugin is in TEST mode. It is visible to visitors.” ?

I am not sure about the exact use case here. The invisible/visible part doesn't behave differently for visitors or admins. If it's invisible then it applies to all users, same goes for visible.

**Comment by ksmoore125** [comment]
> When in TEST mode plugin features will only be visible to admin users?
Correct, LaterPay will no longer be visible to end-users / visitors

> Should the Preview Mode widget be only available in TEST mode only?
I believe that is how it functions today, correct? If it is simpler to make it available in both TEST and LIVE that is acceptable to me as well.

**Comment by thrijith** [comment]
Updated feature and released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
