### ISSUE TITLE
Improve Existing Settings > LaterPay Page

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1121]
### User Story
As a self service user, I just want to get up and running as quickly as possible.
As a power-user, I want all of the features possible at my finger-tips.
We need to be able to support both as simply as possible.

### Acceptance Criteria
On the existing Settings > LaterPay page:
* Make each heading an anchor so that we can link to that specific section of the page from other places within the plugin
* We should also re-order / re-organize the page as follows
* For each info icon, we should display a tooltip with the additional description that is available today. Some of them are quite long so if a pop-up modal would work better, that is acceptable as well.

### Content Details
_In progress_
Only items with changes are noted below all others are simply rearranged but should keep the same text in both English and German.

English | German | Notes
------------ | ------------- | -------------
Access | Zugriff | Should be an anchor
While most content access is controlled by LaterPay, in this section you can adjust the number of times a Voucher can be redeemed, require users to log in prior to purchase, or allow unlimited access to specific user roles | Die meisten Inhaltseinschränkungen sind durch Laterpay kontrolliert, Sie können jedoch in diesem Bereich einstellen wie oft ein Gutschein eingelöst werden kann, ob Benutzer sich vor dem Bezahlen einloggen müssen oder bestimmten Nutzerrollen uneingeschränkten Zugriff geben. | 
~~Number of times a Voucher can be Redeemed~~ | ~~Anzahl wie oft ein Gutschein eingelöst werden kann~~ | Remove this item
Require User Login before Purchase | Benutzer müssen sich einloggen um bezahlen zu können |
Analytics | Analytics | Should be an anchor
LaterPay is not in the business of selling data. This tracking information is for your benefit so that you can determine the effectiveness of your pricing strategy. To view your analytics, log in to your LaterPay account at laterpay.net to view your Merchant Analytics dashboard. | LaterPay verkauft keine Daten an Dritte. Diese Tracking-Daten werden für Ihren Vorteil erhoben und Dienen der Optimierung Ihrer Preisstrategie.  |
Appearance | Darstellung | Should be an anchor
Our most common configuration options are found under the LaterPay plugin’s Appearance tab. Here you can adjust the default colors, the number of characters automatically generated as your teaser content, and also the length of the  content preview blurred behind our paywall. | Die grundlegende Darstellungs-Konfiguration finden Sie im LaterPay Plugin Darstellungs-Tab. Hier können Sie die Standard-Farben, Anzahl an Zeichen für den Teaser-Inhalt des Inhalts sowie die Länge des verschwommen dargestellten Vorschau Inhalts hinter der Bezahlschranke konfigurieren. | 
Button & Link Color | Button & Link Farbe | 
Button & Link Hover Color | Button & Link Mouseover Farbe  | 
Default Teaser Content Word Count | Teaser-Länge | Tooltip should be existing paragraph "The LaterPay WordPress plugin automatically generates teaser content..."
Percentage of Post Blurred behind Overlay | Prozent, wie viel des Inhalts verschwommen hinter der Bezahlschranke erscheinen soll | Tooltip should be existing paragraph "In the appearance tab, you can choose to preview..."
Minimum Number of Words Blurred behind Overlay | Minimale Wortanzahl, die verschwommen hinter der Bezahlschranke erscheinen soll | Tooltip should be existing paragraph "In the appearance tab, you can choose to preview..."
Maximum Number of Words Blurred behind Overlay | Maximale Wortanzahl, die verschwommen hinter der Bezahlschranke erscheinen soll | Tooltip should be existing paragraph "In the appearance tab, you can choose to preview..."
Technical | Technische Einstellungen | Should be an anchor
I am using a caching plugin (e.g. WP Super Cache or Cachify)| Ich verwende ein Caching-Plugin (z. B. WP Super Cache oder Cachify) | Tooltip should be existing paragraph "You MUST enable caching compatiblity mode, if you are using a caching solution..."
In the case that the LaterPay API becomes unresponsive: | Im Falle, dass die LaterPay API nicht erreichbar ist: |Dropdown options and explanation text should remain the same
~~Enable requests to LaterPay API on home page~~ | | This item should be removed
Contact LaterPay Support| Kontaktieren Sie den LaterPay Support | Should be an anchor
Have questions or feature requests? [Click here to contact LaterPay support](https://www.laterpay.net/contact-support) | Haben Sie Fragen oder vermissen eine Funktion? [Klicken Sie hier um den LaterPay Support zu kontatkieren](https://www.laterpay.net/contact-support) |

### Mockup
![image](https://user-images.githubusercontent.com/41650164/52976368-e319c400-338e-11e9-95f1-97f72c7d6aaa.png)

**Comment by thrijith** [comment]
@ksmoore125, here is a query regarding the `Access` section.

>Number of times a Voucher can be Redeemed

I don't think we have something for voucher redeem count right now. The `Gift Codes Limit` section you see in settings is of a deprecated featured that was removed.

**Comment by thrijith** [comment]
@ksmoore125 We can display modal on click of the info icon, however the UI won't be as expected for `Unlimited Access to Paid Content` section. Each role is a different setting and cannot be added as shown in the mockup. Let me know if it's ok to just move it under the access section. 

Please check [this](https://d.pr/free/v/xArdGx) screencast and let me know if ok.

**Comment by ksmoore125** [comment]
The screencast looks great, I may have a few minor style requests once I can see the full page but the modal and `Unlimited Access to Paid Content` sections look good. Thanks!

**Comment by thrijith** [comment]
@ksmoore125 here is a preview of the settings page, I have kept somethings for now ( eg. caching information in Technical section ), we can remove if not needed.

Changes are under review right now, let me know if something needs change regarding styling before it is available on staging for testing.

![lpsettings](https://user-images.githubusercontent.com/13589980/53037191-8e19a300-349f-11e9-8c47-d9864109fc4b.png)

**Comment by ksmoore125** [comment]
Style Changes:

1) Make "Unlimited Access to Paid Content" the same size / style as "Require User Login ..."

2) Un-bold "User Role" and the list of user roles

3) For all anchors, please make the font bigger (so it is more apparent that it is a heading) and style it so that it isn't blue even though it is technically a link (I do not have a strong preference as far as if it should be underlined or not so either way is fine)

**Comment by ksmoore125** [comment]
**I found two minor typos under the Technical section:**
You MUST enable caching **compatib`i`lity** mode, if you are using a caching solution that caches entire HTML pages.
In caching compatibility mode`,` the plugin works like this: 

**Other**
![image](https://user-images.githubusercontent.com/41650164/53251052-5ff3b900-3681-11e9-8ac2-c422724ec12a.png)

1) I forgot to update this text after we removed the voucher section and would also like to combine it with the require user log in text. Please update the Access paragraph to:

English | German
------------ | -------------
While most content access is controlled by LaterPay, in this section you can require users to log in prior to purchase or allow unlimited access to specific WordPress user roles (this feature can be useful for giving free access to existing subscribers or other stakeholders). We recommend the plugin 'User Role Editor' for adding custom roles to WordPress. | _pending_

2) Remove the header & paragraph for `Unlimited Access to Paid Content`

3) Assuming this isn't too difficult, update the table so that the options are bold
![image](https://user-images.githubusercontent.com/41650164/53251214-c547aa00-3681-11e9-906c-83721d28c5c6.png)

4) Update `User Role` to `WordPress User Role` and un-bold this cell

5) Update `Unlimited Access to Categories` to `Receives unlimited access to:` 

6) Update `Your Personal Google Analytics:` to `Your Google Analytics` (so that it will fit on one line)

**Comment by thrijith** [comment]
@ksmoore125 I have done the changes as mentioned above.

Please check below screenshot. I have made changes to the links as mentioned in https://github.com/laterpay/laterpay-wordpress-plugin/issues/1121#issuecomment-465335934

![lpsettings](https://user-images.githubusercontent.com/13589980/53338187-175e2900-3929-11e9-9879-00c620e12ea9.png)

Also note, as shown in mockup there will be space between, the input and option text LMK if that's fine, confirming as there is less space in the option text and input in above comment.

**Comment by ksmoore125** [comment]
This looks great; I have followed up on the German translation.

**Comment by ksmoore125** [comment]
I have updated the comment above with the German translation. It is also here:

> Während der größte Teil des Inhaltezugriffs von LaterPay kontrolliert wird, können Sie Ihre User in diesem Abschnitt auffordern, sich vor dem Kauf anzumelden oder können Ihnen unbegrenzten Zugriff auf bestimmte WordPress-Benutzerrollen gewähren (diese Funktion eignet sich besonders für den kostenlosen Zugriff für bestehende Abonnenten oder andere Nutzer, die besondere Rechte haben sollen). Wir empfehlen das Plugin 'User Role Editor', um Ihrem WordPress eigene Rollen hinzuzufügen.

**Comment by ksmoore125** [comment]
This looks great, just one more change after experiencing this functionality:

- Please adjust so that all (i) info icons go back to tooltips (sorry!)
- Please change the tooltip for `Default Teaser Content Word Count` to the following so that it will fit in a tooltip

English | German
----- | -----
The LaterPay WordPress plugin automatically generates teaser content for every paid post without teaser content. | Das LaterPay Plugin erzeugt automatisch einen “Teaser” für Ihre Beiträge, falls dieser nicht von Ihnen spezifiziert wird.

**Comment by thrijith** [comment]
Updated and released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
