### ISSUE TITLE
LaterPay Content Default Values

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1122]
Make Posts & Media the only two LaterPay Content items that are selected by default.

NOTE: For existing merchants, we should maintain their current selection.

![image](https://user-images.githubusercontent.com/41650164/53034225-5f1c1680-3438-11e9-9f78-4571174c1a41.png)

**Comment by thrijith** [comment]
Changes released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
