### ISSUE TITLE
Update Subscription Default Price

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1123]
Based on recommendations from our sales team, we should update the default price for a subscription from `1.99` to `3.99`

**Steps:**
1. Open the Pricing Tab
2. Click "+ Create" Subscription
Price should display `3.99`
No other changes are needed.

![image](https://user-images.githubusercontent.com/41650164/53034419-b7531880-3438-11e9-9e57-fb38495ea540.png)

**Comment by thrijith** [comment]
I thing **EUR** was missed, I have updated default price for **EUR** from `1.49` to `3.49`. Please let me know if that needs change.

@ksmoore125

**Comment by ksmoore125** [comment]
Can we make them both `3.99` so that it is the same for both $ and € ?

**Comment by thrijith** [comment]
Changes released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
