### ISSUE TITLE
Update Default Global & Category Default Price

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1124]
Based on recommendations from our sales team we should:

1. Update the default Global Default Price from `0.20` to `0.30`
![image](https://user-images.githubusercontent.com/41650164/53034581-1e70cd00-3439-11e9-998e-4aaf44f33bd2.png)

2. Update the default Category Default Price from `0.05` to `0.40`
![image](https://user-images.githubusercontent.com/41650164/53034793-94753400-3439-11e9-9703-062d2f492bba.png)

No other changes are needed.

**Comment by thrijith** [comment]
@ksmoore125 Please check 👇 

> Update the default Global Default Price from `0.20` to `0.30`

Global Default Price is `0.29` by default, I have updated it to `0.30`.

> Update the default Category Default Price from `0.05` to `0.40`

Category Default Price doesn't have a default price, it uses the current value of Global Default Price.

**Comment by ksmoore125** [comment]
> Category Default Price doesn't have a default price, it uses the current value of Global Default Price.

Thanks for the clarification, we can leave that as-is.

I spoke with our biz dev team. Could we actually update the Global Default Price to `0.39` (same for $ and €)

**Comment by thrijith** [comment]
Changes released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
