### ISSUE TITLE
Update Account Tab to Assist with Getting Started

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1126]
### User Story
As a new self-service merchant I want the getting started flow to be as frictionless as possible. Therefore we should provide clear steps for getting started and remove any items that could cause confusion.

### Related Tickets
- https://github.com/laterpay/laterpay-wordpress-plugin/issues/1109 Move `Deactivate Plugin & Delete Data` to Advanced tab
- https://github.com/laterpay/laterpay-wordpress-plugin/issues/1120 Remove the "Visibility Toggle" so that it is only a toggle between TEST & LIVE
- https://github.com/laterpay/laterpay-wordpress-plugin/issues/1109 Move the `Sandbox Environment` section to the Advanced tab

### Acceptance Criteria
- Update the styles & layout to more closely match the styling on LaterPay.net as shown in the mockup below
- Update the page content so that the sections are as follows:
  - TEST vs LIVE toggle (https://github.com/laterpay/laterpay-wordpress-plugin/issues/1120)
  - STEP 1: Select your Region
  - STEP 2: Create LaterPay Account
  - STEP 3: Getting Started
  - STEP 4: Accept Payments
- There should be a new sidebar which contains
  - Who is LaterPay?
  - FAQs
  - Support contact information

### Mockup
_If additional design specifications is needed, let us know and our designer would be happy to help._

![image](https://user-images.githubusercontent.com/41650164/53256642-f6c67280-368d-11e9-8853-9f0b7c17bf1e.png)

### Content

English | German 
-----|-----
(TEST / LIVE Toggle info) In Test mode, only WordPress administrators will be able to see the LaterPay paywall. You must complete step 4 below to enable Live mode. This will display the paywall to your followers and allow you to begin accepting payments. | Im Testmodus können nur WordPress-Administratoren die LaterPay Paywall sehen. Sie müssen Schritt 4 unten ausführen, um den Live-Modus zu aktivieren. Dadurch wird die Paywall Ihren Anhängern angezeigt und Sie können mit der Annahme von Zahlungen beginnen.
STEP 1: SELECT YOUR REGION | SCHRITT 1: WÄHLEN SIE IHR REGION  
If you select 'Europe', all prices will be displayed and charged in Euro (EUR), and the plugin will connect to the LaterPay Europe platform. If you select 'United States', all prices will be displayed and charged in U.S. Dollar (USD), and the plugin will connect to the LaterPay U.S. platform. | Wählen Sie 'Europa' werden alle Preise in Euro (EUR) dargestellt und berechnet. Während Sie 'Vereinigte Staaten' wählen, werden alle Preise in U.S. Dollar (USD) dargestellt und berechnet. Das Plugin verbindet sich mit dem der Region entsprechenden Plattform.
Use existing region dropdown | Use existing region dropdown 
STEP 2: CREATE LATERPAY ACCOUNT | SCHRITT 2: LATERPAY KONTO ERSTELLEN
A LaterPay Account is required in order to process financial transactions. You may skip this step if you have already created a LaterPay account. | Für die Abwicklung von Finanztransaktionen ist ein LaterPay-Konto erforderlich. Sie können diesen Schritt überspringen, wenn Sie bereits ein LaterPay-Konto angelegt haben.
[SIGN UP](https://www.laterpay.net/signup/merchant) | [SIGN UP](https://www.laterpay.net/signup/merchant)
STEP 3: GETTING STARTED | SCHRITT 3: ANFANG
It may take up to 5 business days for our banking partners to verify your information. You may go ahead and get started setting up your plugin while it is in "Test mode" then, once we've emailed you to let you know your account is live, come back and complete step 4 below in order to begin accepting payments. | Es kann bis zu 5 Werktage dauern, bis unsere Bankpartner Ihre Daten überprüft haben. Sie können mit der Einrichtung Ihres Plugins beginnen, während es sich im "Testmodus" befindet. Sobald wir Ihnen eine E-Mail geschickt haben, um Ihnen mitzuteilen, dass Ihr Konto aktiv ist, führen Sie Schritt 4 aus, um mit der Annahme von Zahlungen zu beginnen.
[Click here to read our Getting Started Guide](https://www.laterpay.net/academy/getting-started-with-the-laterpay-wordpress-plugin) or simply click through the remaining tabs and check out the LaterPay features available on your Edit Post pages to see all of the options available. To help you get started, all of the default values are automatically set to our experts' recommendations. | [Klicken Sie hier, um unseren Getting Started Guide zu öffnen](https://www.laterpay.net/academy/getting-started-with-the-laterpay-wordpress-plugin) oder klicken Sie einfach durch die restlichen Registerkarten und schauen Sie sich die LaterPay-Funktionen auf Ihren Edit Post-Seiten an, um alle verfügbaren Optionen zu sehen. Um Ihnen den Einstieg zu erleichtern, werden alle Standardwerte automatisch auf die von unseren Experten empfohlene Werte eingestellt. 
STEP 4: ACCEPT PAYMENTS | SCHRITT 4: ZAHLUNGEN AKZEPTIEREN 
It may take up to 5 business days for our banking partners to verify your information. Once we've emailed you to let you know your account is live, follow the steps below to begin accepting payments. | Es kann bis zu 5 Werktage dauern, bis unsere Bankpartner Ihre Daten überprüft haben. Sobald wir Ihnen eine E-Mail geschickt haben, um Ihnen mitzuteilen, dass Ihr Konto aktiv ist, folgen Sie die unten beschriebenen Schritte, um mit der Annahme von Zahlungen zu beginnen.
1 [Click here](https://web.uselaterpay.com/dialog/entry/?redirect_to=/merchant/#/login) to log in to your LaterPay account | 1 [Hier klicken](https://web.laterpay.net/dialog/entry/?redirect_to=/merchant/#/login), um sich bei Ihrem LaterPay-Konto anzumelden. 
2 Navigate to the developer tab & copy and paste your Merchant ID & API Key into the corresponding boxes below | 2 Navigieren Sie zur Registerkarte für Entwickler und kopieren Sie Ihre Händler-ID und Ihren API-Schlüssel in die entsprechenden Felder unten.
Don't see a developer tab? [Click here](https://www.laterpay.net/contact-support) to contact our support team | Sie sehen keine Registerkarte für Entwickler? [Klicken Sie hier](https://www.laterpay.net/contact-support), um unser Support-Team zu kontaktieren.
3 Ensure that the toggle at the top of the page is switched to LIVE mode  | 3 Stellen Sie sicher, dass der Schalter oben auf der Seite in den LIVE-Modus geschaltet ist.
Use existing Live Environment Merchant ID & API Key text boxes | Use existing Live Environment Merchant ID & API Key text boxes 

**Sidebar Content**
- Existing `Who is LaterPay` section
- Existing `FAQs` section
- New `Customer Support` section

English | German
-----|-----
SUPPORT | KUNDENSUPPORT	
[Click here](https://www.laterpay.net/contact-support) or email support@laterpay.net to provide feedback or to reach our customer service team.	| [Klicken Sie hier](https://www.laterpay.net/contact-support) oder schreiben Sie eine Email an support@laterpay.net, um Feedback zu geben oder mit unserem Kundensupport Kontakt aufzunehmen.

**Comment by ksmoore125** [comment]
Minor style changes:
**Header**
1. Can we add a shadow like laterpay.net?
![image](https://user-images.githubusercontent.com/41650164/53354016-887eeb80-38eb-11e9-99ab-0aae06d08448.png)
![image](https://user-images.githubusercontent.com/41650164/53354107-bbc17a80-38eb-11e9-9f2e-c19df2b43995.png)

**Sidebar**
2. Please remove the font-weight: 500; style so that the text does not appear bold.
3. Please adjust the colors to: Header color `#737373` Font color `#B0B0B0`
4. If the sidebar can extend all the way to the right side of the screen, please:
  -  Extend it all the way to the right edge of the screen:
  - Ensure it extends up to the shadow (item 1)
  - Remove the rounded corners

If it cannot extend to the right side of the screen:
  - Adjust so that the rounded corners match the radius of the rounded corners of the visibility toggle

**Other**
6. If possible, please make the SIGN UP button the same width as the region dropdown
7. German translation & links - Kimberly needs to provide this information

**Comment by ksmoore125** [comment]
@thrijith - The German translations and hyperlinks have been updated. Please let me know if you have any questions. (Note that the URLs may be different between the US & Germany)

**Comment by thrijith** [comment]
@ksmoore125 Changes have been deployed on staging env, Please check and let me know if ok.

**Comment by thrijith** [comment]
Updated and released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
