### ISSUE TITLE
Broken Link in Global Default Pricing

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1129]
**Steps to Reproduce:**
- Navigate to the pricing tab
- Edit the Global default price
- Select "Set individual article default price"

Note the following paragraph:
> TIP: "Pay Later" is LaterPay's patented revenue model which allows your customers to purchase content with a single click, dramatically reducing their barriers to entry. Once they have purchased $5 or 5€ worth of content, they will be asked to settle their invoice. [Click here](https://support.laterpay.net/hc/en-us/articles/201251457-What-is-LaterPay-) to learn more.

**Observed Result**
The link no longer works

**Fix**
Update the link to the following:
https://www.laterpay.net/academy/getting-started-with-laterpay-the-difference-between-pay-now-pay-later

**Comment by thrijith** [comment]
Updated and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
