### ISSUE TITLE
Secure Download Widget: content_type default updates

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1132]
For each content type available to the Secure Download Widget, there is a default image and button.

### content_type="music" 
The defaults are as follows:
![image](https://user-images.githubusercontent.com/41650164/53341401-15687b80-38d1-11e9-9618-a0a652405909.png)

**Acceptance criteria**
- The image should be related to music
~~- The button should say `Listen Now`~~
If we do not have an existing image let me know and I can provide one.

~~### content_type="gallery"~~
~~- The button should say `View now`~~

### Product Requirements
- Once the above is complete, we need to update the corresponding getting started article

**Comment by thrijith** [comment]
@ksmoore125 I have updated code to work with `music` type, you can also use `audio` instead of `music`.

Here's a preview.

![screenshot 2019-02-25 at 10 43 30 pm](https://user-images.githubusercontent.com/13589980/53355594-57380700-394f-11e9-88ab-87668607d17a.png)

**Comment by ksmoore125** [comment]
We should have this button display "Download now" so that it is consistent with the other content types. Other than that, what you have looks great.

**Comment by thrijith** [comment]
> We should have this button display "Download now" so that it is consistent with the other content types. Other than that, what you have looks great.

@ksmoore125 We already had a `audio` type available for the `content_type` in shortcode with button text `Listen Now`, and the above image. I am not sure if that should be changed for `music` to `Download Now`.

Please let me know if you have any concerns.

**Comment by ksmoore125** [comment]
Ok, that is fine to leave as-is.

**Comment by ksmoore125** [comment]
See http://lpwptestprod.wpengine.com/2017/11/16/hello-world/
The content_type="music" does not display the updated image.

**Comment by thrijith** [comment]
>The content_type="music" does not display the updated image.

@ksmoore125 Unable to replicate, could you please check in a private window or clear cache and try again?

https://d.pr/TPQGgA

**Comment by thrijith** [comment]
Fixed and released in [v2.5.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.0)
