### ISSUE TITLE
Minor Account Tab Enhancements

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1137]
### Details
After the style updates made in the previous plugin update, there are a few minor enhancements to complete the improved user experience.

### Acceptance Criteria
1) Remove style for visibility toggle to be 55% so that it will appear correctly in small browser windows
![image](https://user-images.githubusercontent.com/41650164/53589758-d6972780-3b55-11e9-875d-b8855eedc174.png)

2) Make all hyperlinks open in new tabs. The following open in the current tab:
   - SIGN UP
   - Click here to read out Getting Started Guide
   - Click here (under STEP 4 > 2)

3) _Optional_ If possible, please make the shadow for the header extend all the way to the end of the screen and also in front of the grey sidebar background. At a minimum, remove the right shadow.

4) Update the spacing for WHO IS LATERPAY? The final paragraph (starting with "Requiring upfront...") should not have any line breaks.

5) Update the hyperlinks under the SUPPORT section so that they are the same color as the other hyperlinks

6) Update the FAQ section to match the original mockup and include additional items now that we have articles to link to (FAQs and Support sections of the sidebar should appear in all cases so if it could be a shared element that only needs to be updated once, that would be ideal)
See #1141 for requirements

**Comment by thrijith** [comment]
![account-en](https://user-images.githubusercontent.com/13589980/54751416-e78d0300-4c00-11e9-80d7-6c3422789d37.png)

![account-de](https://user-images.githubusercontent.com/13589980/54751415-e78d0300-4c00-11e9-8905-b0c205cdece1.png)
@ksmoore125

**Comment by ksmoore125** [comment]
1. Remove style for visibility toggle to be 55% so that it will appear correctly in small browser
❌ - For the most part this looks good but see [this video](https://drive.google.com/file/d/13ACaKkOM3SlA4jnizo2NhSYsBVfZnx9Y/view?usp=sharing) for some strange behavior. Let me know if you need additional details.

2. Make all hyperlinks open in new tabs. 
✅ 

3. If possible, please make the shadow for the header extend all the way to the end of the screen and also in front of the grey sidebar background. At a minimum, remove the right shadow.
❌ - See [this doc](https://docs.google.com/document/d/1Bk_m46mniPjNR_nSo9WT5xh-xnGvWjLJUZ1H5zLCmJ8/edit?usp=sharing) for a few different acceptable options; please implement whichever is simplest

4. Update the spacing for WHO IS LATERPAY? 
✅ 

5. Update the hyperlinks under the SUPPORT section so that they are the same color as the other hyperlinks 
✅ 

6. Update the FAQ section - See #1141 for requirements
❌ - See #1141 for changes

**Comment by thrijith** [comment]
Fixed and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
