### ISSUE TITLE
Minor Appearance Tab Enhancements

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1140]
Since we are updating the style of the Account & Advanced tabs, we should make the following changes to the Appearance tab to take advantage of the new style:

### Acceptance Criteria
* Add grey sidebar this should include:
  * Advanced Settings section (see details below)
  * FAQ & Support sections (same sections as on Account & Advanced tabs; these should have the same content in all cases so if it could be a shared element that only needs to be updated once, that would be ideal - see #1141 for requirements)

Advanced Settings | Erweiterte Einstellungen
----- | -----
[Click here]() to adjust the default colors, the number of characters automatically generated as your teaser content, and also the length of the content preview blurred behind our paywall. | [Hier]() können Sie die Standard-Farben, Anzahl an Zeichen für den Teaser-Inhalt des Inhalts sowie die Länge des verschwommen dargestellten Vorschau Inhalts hinter der Bezahlschranke konfigurieren.

* The hyperlinks should link to the Settings > LaterPay > Appearance section

### Mockup
![image](https://user-images.githubusercontent.com/41650164/54309989-5a620280-459f-11e9-8114-3f5c5331994f.png)

**Comment by thrijith** [comment]
Updated and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
