### ISSUE TITLE
Update Sidebar FAQ Section

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1141]
Update the FAQ section to match the original mockup and include additional items now that we have articles to link to (FAQs and Support sections of the sidebar should appear in all cases so if it could be a shared element that only needs to be updated once, that would be ideal)

English | German
----- | -----
Having Trouble with Page Cache? [Click here.](https://support.laterpay.net/wordpress-cache) | Probleme mit dem Page Cache? [Klicken Sie hier.](https://support.laterpay.net/wordpress-cache)
Having Trouble on WPEngine? [Click here.](https://support.laterpay.net/i-am-having-trouble-with-wordpress-engine) |  Probleme mit dem Seiten-Cache? [Klicken Sie hier.](https://support.laterpay.net/i-am-having-trouble-with-wordpress-engine)
The new version of the plugin is not compatible with my site. How can I rollback? [Click here.](https://support.laterpay.net/rollback-wordpress-plugin)  | Die neue Version des Plugins ist nicht kompatibel mit meiner Website. Wie kann ich einen Rollback durchführen? [Klicken Sie hier.](https://support.laterpay.net/rollback-wordpress-plugin) 

### Mockup
![image](https://user-images.githubusercontent.com/41650164/54773711-1cd12b00-4bd8-11e9-8153-b0a863a5f37e.png)

**Comment by thrijith** [comment]
>Update the FAQ section to match the original mockup **and include additional items now** that we have articles to link

Can you please add link to the original mockup?

Current FAQ includes all data, since all data is available in the new links, now, the FAQ section should contain just text + link  like given above in the table?

![faq](https://user-images.githubusercontent.com/13589980/54703081-261db180-4b5e-11e9-94a3-1382a8554ae5.png)


@ksmoore125

**Comment by thrijith** [comment]
@ksmoore125 Here are the latest changes.

![faq-new-en](https://user-images.githubusercontent.com/13589980/54747712-a0e5db80-4bf5-11e9-89db-5371fcd1fe10.png)

![faq-new-de](https://user-images.githubusercontent.com/13589980/54747711-a0e5db80-4bf5-11e9-95a7-542fa12dd0fa.png)

**Comment by ksmoore125** [comment]
Mockup uploaded; per the mockup please simply remove the non-bolded text in your screenshot

**Comment by thrijith** [comment]
![account](https://user-images.githubusercontent.com/13589980/54775753-9eef3d00-4c34-11e9-9765-2cbf3d218ed7.png)

@ksmoore125 Changes as of now, can you check visibility toggle in standard resolutions and let me know if something needs changes?

Thanks

**Comment by ksmoore125** [comment]
This looks good. Thank you for your help today!

**Comment by thrijith** [comment]
Updated and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
