### ISSUE TITLE
Custom Positioning 'Already bought this link' Enhancement

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1142]
The 'Already bought this link' should align with the remainder of the LaterPay content. (Requested by Der Bank Blog)

![image](https://user-images.githubusercontent.com/41650164/53744376-8d4f1c80-3e62-11e9-8726-d0d19981a7ec.png)

**Comment by ksmoore125** [comment]
Related to #1131

**Comment by ksmoore125** [comment]
Der Bank Blog added the following custom CSS to their site. This workaround has resolved their issue.

` .lp_identity_container {
     padding:0 40% !important;
}`

**Comment by thrijith** [comment]
Current Result on Default theme without the css.
![Screenshot 2019-03-29 at 11 04 23 PM](https://user-images.githubusercontent.com/13589980/55251653-1ba69a80-5277-11e9-94d9-d236d935d74e.png)

After applying the given css.

![Screenshot 2019-03-29 at 11 04 40 PM](https://user-images.githubusercontent.com/13589980/55251674-26612f80-5277-11e9-8176-8bb208341934.png)

@ksmoore125 I think client might have some custom css which is resulting in mis-alignment.

**Comment by ksmoore125** [comment]
Since this works properly with the default theme and the work around has satisfied DBB; we will Close - Won't Do.
