### ISSUE TITLE
Bug: Pay Now option not Enabled

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1143]
### Steps to Reproduce
1. Navigate to a place where you can edit a Pay Later price (like following places):
  - Edit Post Page > Individual Price
  - Pricing Tab > Global Default Price > Set individual article default price
  - Pricing Tab > Category Default Price
  - Pricing Tab > Time Pass
2. Adjust the price so that it should be eligible for Pay Now (eg: $3.50)

**Observed Result**
Pay Now cannot be selected

**Desired Result**
I should be able to select Pay Now as long as the price is above $1.99 or 1.49€

![image](https://user-images.githubusercontent.com/41650164/54230329-2bcb2580-44d4-11e9-91c7-b45647032fad.png)

**Comment by thrijith** [comment]
Fixed and released in [v2.5.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.1)
