### ISSUE TITLE
JetPack plugin allows access to Paid Content

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1144]
### Issue 1: Free Access to Paid Content in App
**Steps to Reproduce**
1. Ensure that the WordPress site has JetPack installed
2. Download the WordPress iOS app
3. Add the site to your "followed sites" (Reader > Followed Sites > Manage)
4. From the screen above, click the site and select a paid article

**Observed Result**
The article content is displayed in full for free.

**Desired Result**
Paid content should not be displayed for free. 
A few implementation options include: 
- Display paywall as shown in other places (from step 4 above, click the icon in the top right corner of the app & Open in Safari; here it is displayed correctly)
- Display only the teaser content
- Do not allow the article to appear in the app

### Issue 2: Free Access to Paid Content via Email
**Steps to Reproduce**
1. In the WordPress app, navigate to Me > Notification Settings > select the site you are using for testing
2. Enable "Email me new posts"
3. Create a new, paid post

**Observed Result**
You receive an email displaying the full content for free.

**Desired Result**
Paid articles should not be emailed.

### Technical Notes
It appears that the following hooks can be used to disable the features above.
- https://developer.jetpack.com/hooks/publicize_should_publicize_published_post/
- https://developer.jetpack.com/hooks/jetpack_sync_prevent_sending_post_data/
- https://developer.jetpack.com/hooks/jetpack_is_post_mailable/

**Comment by ksmoore125** [comment]
Additional context for LaterPay team [here](https://laterpay.slack.com/files/UB0CZAR4M/FGTAA0QP5/WordPress_App_Provides_Free_Access_to_Paid_Content)

**Comment by thrijith** [comment]
Fixed and released in [v2.5.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.1)
