### ISSUE TITLE
Additional Updates to Visibility Toggle

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1153]
## Description
With `v2.5.0` #1120 we updated the functionality of the visibility toggle. As we have used this new functionality we have a few additional changes.

### 1) Remove Post Page Warning Message
Today the following message is displayed; please leave the Test mode widget but remove the warning message
![image](https://user-images.githubusercontent.com/41650164/54778973-092bc180-4be4-11e9-9681-0c3cd33f0da0.png)

### 2) Adjust Test Mode Functionality
**Functionality User Flows**
![image](https://user-images.githubusercontent.com/41650164/55024090-28ec2c80-4fcc-11e9-9673-a120a44213f4.png)

---------------------------------------------------
_Issue 2 Functionality Details:_
**v2.5.0 behavior**
* Have toggle set to test mode
* Visit in incognito mode; paywall is not displayed ✅ 
* Visit as admin with `post preview mode` set to admin; paywall is not displayed ✅ 
* Visit as admin with `post preview mode` set to visitor; paywall is displayed but when you try to purchase, you see a warning message and cannot effectively test the user flow
![image](https://user-images.githubusercontent.com/41650164/54779396-0f6e6d80-4be5-11e9-8ca2-caf6417f5745.png)

**Pre-v2.5.0 behavior**
* Revert plugin to pre-v2.5.0
* Set visibility toggle to Test mode & visible to visitors
* Visit page in incognito mode (as if you are a visitor)
* Attempt to make a purchase and note that although no payment is collected, the merchant can effectively test the user purchase flow
![image](https://user-images.githubusercontent.com/41650164/54779611-93c0f080-4be5-11e9-8d02-c34835ff0cfb.png)

**Desired Behavior Summary**
When Account tab visibility toggle is in test mode and `post preview mode` is set to visitor, use the pre-v2.5.0 behavior for visibility toggle `test mode & visible to visitors` and as if you are viewing the site as a visitor:
![image](https://user-images.githubusercontent.com/41650164/54779611-93c0f080-4be5-11e9-8d02-c34835ff0cfb.png)

**Comment by ksmoore125** [comment]
**1) Remove Post Page Warning Message**
✅ - Looks good

**2) Adjust Test Mode Functionality**
I am sorry for making this so confusing; I will update the description shortly to show the potential flows for our future reference. In the meantime, this is _very_ close just a few changes

2.1) When the site is in live mode and a open a paid article in an incognito window (in order to simulate the behavior of a true visitor), I do not see the payment dialog

2.2) When the site is in live mode and I am an admin with the Post Preview Mode = visitor, please update the error message to the following
> Your site is in LIVE mode, your visitors would now see the LaterPay purchase dialog. To experience this behavior, open this page in an 'incognito window' or log out of WordPress. 
> Note: You will be charged for purchases made while in LIVE mode.

**Flow highlighting the two issues outlined above:**
![image](https://user-images.githubusercontent.com/41650164/55023599-2b01bb80-4fcb-11e9-8748-c5aa6e547a32.png)

**Comment by ksmoore125** [comment]
**Testing scenarios:**

- User is Admin
  - Site in Test Mode
    - Post Preview Mode is Admin  ✅ 
    - Post Preview Mode is Visitor  ✅ 
  - Site in Live Mode
    - Post Preview Mode is Admin ✅ 
    - Post Preview Mode is Visitor ✅ 

- User is Visitor
  - Site in Test Mode  ✅ 
  - Site in Live Mode  ❌ 

**Steps to Reproduce**
- Set the site in Live Mode
- Open a paid article in an incognito window (or logged out of WordPress)
Observed Result: There is no paywall
Desired Result: There should be a paywall & the user should be charged to view the article
Notes: Tested using https://laterpay.dev.rt.gw/2019/03/20/testing-issue-1144/

**Comment by thrijith** [comment]
>Site in Live Mode
Can you please verify if you are getting same issue on other articles? It might be due to cache.

@ksmoore125

**Comment by ksmoore125** [comment]
@thrijith - This is working properly now.

**Comment by thrijith** [comment]
Fixed and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
