### ISSUE TITLE
Voucher Improvements Part 1

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1159]
### User Story
As a LaterPay Merchant, I may not understand that a voucher applied to a subscription will be applied not only to the first month, but to the entire life of the subscription. We should make this obvious.

### Acceptance Criteria
For Subscription Vouchers, add the following disclaimer:
**English:** This will reduce the price for the entirety of the subscription.
**German:** Der Gutschein bezieht sich auf die gesamte Laufzeit des Abos.
![image](https://user-images.githubusercontent.com/41650164/55092690-ff410d00-5080-11e9-99fe-68ec7f2e9850.png)

**Comment by ksmoore125** [comment]
See https://github.com/laterpay/laterpay-wordpress-plugin/issues/1008#issuecomment-477728603

**Comment by thrijith** [comment]
Updated and released in [v2.5.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.2)
