### ISSUE TITLE
Voucher Improvements Part 2

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1160]
### Acceptance Criteria
When a voucher code is added; add it **under** any existing vouchers (this applies to both time passes and subscriptions).

**Current:**
![image](https://user-images.githubusercontent.com/41650164/54777253-ef887b00-4bdf-11e9-9e24-9ad374a15bae.png)
**Desired:**
![image](https://user-images.githubusercontent.com/41650164/54777304-0af38600-4be0-11e9-8a44-773a9c45ace0.png)

**Comment by ksmoore125** [comment]
See also https://github.com/laterpay/laterpay-wordpress-plugin/issues/1008#issuecomment-477728603

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
