### ISSUE TITLE
Add Warning to Clear Cache when site goes to Live Mode

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1164]
### Description
While testing, it was discovered that if the plugin is in TEST mode and someone visits a page, if the site is using page cache, the markup is stored for that particular page.

Once the plugin mode is updated to LIVE, the payment box is not shown as it is showing the cached version. This is due to the page cache. We cannot provide an option to clear cache as there isn’t a generic solution.

Therefore we need to let the merchant know to clear cache once the plugin mode is updated to get expected results.

### Acceptance Criteria
When the site is changed from test to live mode the following error message should be displayed:
**Important:** In both messages below the text _in italics_ should not actually display in italics, this is simply used here to denote the text that can be clicked to hide the warning message. When this is clicked, it should hide all of the below text (until the site is switched to test & the live mode again in which case it should reappear).

**English:**
> Congratulations, you are now accepting payments through LaterPay! 
> We recommend [clearing your cache](https://www.wpbeginner.com/beginners-guide/how-to-clear-your-cache-in-wordpress/) in order to ensure that the paywall is visible everyone. _Hide message._

**German**
> Herzlichen Glückwunsch, Sie akzeptieren jetzt Zahlungen über LaterPay!
> Wir empfehlen [Ihren Cache zu leeren](https://www.wpbeginner.com/beginners-guide/how-to-clear-your-cache-in-wordpress/), um sicherzustellen, dass die Paywall für alle sichtbar ist. _Nachricht verstecken._

### Mockup
![image](https://user-images.githubusercontent.com/41650164/57087157-11881980-6cc5-11e9-9f47-80aa40da6f3b.png)

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
