### ISSUE TITLE
Remove Hyperlinks from Obfuscated Text

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1167]
# Scenario
Merchant as a hyperlink to a PDF that they would like to charge for. The hyperlink is behind the paywall as obfuscated text; however, a user can still click the link and access the content.

Example: http://kimberlystestsite.cloudaccess.host/?p=355
![image](https://user-images.githubusercontent.com/41650164/56980428-f5a83a80-6b41-11e9-94d7-b957413f2c83.png)

# Acceptance Criteria
Ensure that hyperlinks in the obfuscated text cannot be accessed

**Implementation Options**
Listed in order of preference (most preferred at the top):
- remove the url from the hyperlink so that the text is still styled as a link but the link does not go anywhere
- remove the hyperlink all together
_Let me know if you have another suggestion!_

**Comment by thrijith** [comment]
Fixed and released in [v2.5.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.3)
