### ISSUE TITLE
Lower Subscription Minimum Value

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1168]
### User Story
As a LaterPay merchant, I would like to be able to have a low prices as possible so that my readers are more likely to purchase.

### Acceptance Criteria
- Lower the subscription minimum price to to PayNow minimum price of $1.99 / 1.49€
- In the case that the merchant has the region set to the EU and then switches to the US they could potentially have a subscription priced lower than $1.99 which would cause an error when the end-user tries to purchase that subscription therefore:
  - If the region = US
  - And there is at least one subscription less than $1.99
  - Then display the following message:
> (!) Important: The minimum value for "Pay Now" prices in the US is $1.99. Please be sure to update your subscriptions so that your users to not receive an error when they try to purchase.

### Mockup
![image](https://user-images.githubusercontent.com/41650164/57146652-773ed900-6d8b-11e9-85e2-b266e4239505.png)

**Comment by thrijith** [comment]
Updated and released in [v2.5.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.5.3)
