### ISSUE TITLE
Voucher Code Explanatory Text Looks Like Error Message

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1174]
# Details
The existing warning message looks like an error
![image](https://user-images.githubusercontent.com/41650164/57778265-4b0b4c80-76e9-11e9-9cbb-c667f49c6804.png)

# Acceptance Criteria
- Change the text color from red to yellow (something like #ffb74d)

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
