### ISSUE TITLE
Changing Region to EU Displays a Message about US Pricing

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1175]
# Details
We received feedback that the following message is confusing. If they change the region to the EU, why is there a message talking about the US?
![image](https://user-images.githubusercontent.com/41650164/57778586-fddbaa80-76e9-11e9-8b0d-a455c404e101.png)

Additionally, users did not like that they had to select region during the signup process and again inside the plugin.

# Acceptance Criteria
- Change Step 1 text to:
> STEP 1: SELECT CURRENCY

> SCHRITT 1: WÄHRUNG AUSWÄHLEN

- Remove the intro paragraph

- Change the drop down options to:
  - USD ($)
  - EURO (€)

- The error message described in the details should:
  1) Not be displayed the first time the account page is loaded
  2) Be displayed when the "currency" changes from EURO to USD
  3) Change the message to: (where (!) is the warning icon)

> (!)  Important: The minimum value for "Pay Now" prices in the U.S. region is $1.99. If you previously set "Pay Now" prices lower than 1.99, these will need to be adjusted accordingly.

> (!) Wichtig: Der Mindestwert für "Pay Now"-Preise in der Region USA beträgt 1,99 $. 
Wenn Sie zuvor "Pay Now" Preise unter 1,99 festgelegt haben, müssen diese entsprechend angepasst werden.

# Mockup
![image](https://user-images.githubusercontent.com/41650164/57785275-0ab2cb00-76f7-11e9-9e9d-52836101dec4.png)

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
