### ISSUE TITLE
Steps on Account Tab are Confusing

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1176]
# Feedback
- Language About Waiting Period on Account Tab is Confusing
- Account Tab "Step 4" says Paywall; what does that mean?
- Account Tab Step 4 mentions Toggle To Live; How Can you Test First?
- Step 5: We don't know when we're actually done.
- At what point do we go "live" with the plugin?
- There was something along the lines "go and explore the plugin" which has 4 (5?) tabs. That's not what I want;I want the shortest path to have an MVP integration. And then I'd like to know that I've completed each step since that wasn't clear in the plugin's tabs. For example - once I entered the API Key / Merchant ID then I didn't know if they are valid and if that's all I had to do in that tab and which tab is the next one...

# Acceptance Criteria
We will update the steps on the Account Tab to the following:

English | German | Notes 
------------ | ------------- | -------------
`just change "4" to "3"` | `just change "4" to "3"` | Test / Live Tooltip
STEP 1: SELECT CURRENCY | SCHRITT 1: WÄHRUNG AUSWÄHLEN | See #1175
STEP 2: GET STARTED | SCHRITT 2: ERSTE SCHRITTE  | 
Click through the remaining tabs from left to right. We will provide tips and instructions at the top of each page or click here to read our [Getting Started Guide](https://www.laterpay.net/academy/getting-started-with-the-laterpay-wordpress-plugin) for step by step instructions. | Klicken Sie von links nach rechts durch die verbleibenden Registerkarten. Wir werden Ihnen oben auf jeder Seite Tipps und Anleitungen geben oder klicken Sie hier, um unseren ["Getting Started Guide"](https://www.laterpay.net/academy/getting-started-with-the-laterpay-wordpress-plugin) für eine Schritt-für-Schritt-Anleitung zu lesen.  | 
STEP 3: LINK TO LATERPAY | SCHRITT 3: MIT LATERPAY VERKNÜPFEN | 
A LaterPay Account is required to process financial transaction (so that we can pay you).| Ein LaterPay Konto ist erforderlich um Auszahlungen zu erhalten. |
LOGIN or SIGN UP | Anmelden oder Registrieren | [LOGIN US](https://web.uselaterpay.com/dialog/entry/?redirect_to=/merchant/#/login) / [LOGIN EU](https://web.laterpay.net/dialog/entry/?redirect_to=/merchant/#/login) / [SIGN UP](https://www.laterpay.net/signup/merchant) 
Once you have created your account, you will be instructed to copy and paste your Merchant ID & API Key into the boxes below. This ensures that your plugin is linked to your account. | Sobald Sie Ihr Konto erstellt haben, werden Sie angewiesen, Ihren Merchant ID & API Key zu kopieren und in die untenstehenden Felder einzufügen. Dadurch wird sichergestellt, dass Ihr Plugin mit Ihrem Konto verknüpft ist. | 
This is required in order to ensure that you receive payments. Log in to your LaterPay account, navigate to the Developer tab & copy and paste the information into the corresponding boxes. | Dies ist erforderlich, um sicherzustellen, dass Sie Zahlungen erhalten. Melden Sie sich bei Ihrem LaterPay-Konto an, navigieren Sie zur Registerkarte Entwickler, kopieren Sie die Informationen und fügen Sie diese in die entsprechenden Felder ein. | Tooltip for both Merchant ID & API Key
STEP 4: GO LIVE | SCHRITT 4: GO-LIVE | 
How can I be sure that I am ready to go live? | Wie kann ich sicher sein, dass ich bereit bin, live zu gehen? | 
Set up your Pricing | Legen Sie Ihre Preise fest. | 
Preview your site while logged into WordPress to ensure everything is displayed as expected | Überprüfen Sie ihre Webseite, während Sie bei WordPress angemeldet sind, um sicherzustellen, dass alles korrekt angezeigt wird. | 
Create and link to your LaterPay account so that all revenue can be sent to your bank account | Erstellen und verlinken Sie Ihr LaterPay-Konto, so dass alle Einnahmen auf Ihr Bankkonto überwiesen werden können. | 
Optional Configurations: | Optionale Konfigurationen: | 
Adjust the Appearance to match your brand colors | Passen Sie das Erscheinungsbild an Ihre Unternehmensfarben an. | 
Explore the Advanced tab to learn about additional features available | Erkunden Sie die Registerkarte "Erweitert", um mehr über weitere verfügbare Funktionen zu erfahren. | 
**Click the toggle at the top of the page to switch to "LIVE" mode and start generating revenue!** | **Klicken Sie auf den Kippschalter oben auf der Seite, um in den "LIVE"-Modus zu wechseln. Beginnen Sie Umsätze zu generieren!** | 
 
# Mockup
![image](https://user-images.githubusercontent.com/41650164/58126653-072cb180-7bd9-11e9-9554-413b17f618c7.png)

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
