### ISSUE TITLE
Add Step by Step Instructions on Each Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1178]
# Details
- "One page = one step then "next" or "done" button"
- "Registration steps are not clear: where are we on the process, what steps are left, step-by-step instructions missing"
- "WP pages have a lot of text / ink at each step which is disturbing and creates problems for people not familiar with WordPress"
- There was something along the lines "go and explore the plugin" which has 4 (5?) tabs. That's not what I want; I want the shortest path to have an MVP integration. And then I'd like to know that I've completed each step since that wasn't clear in the plugin's tabs. For example - once I entered the API Key / Merchant ID then I didn't know if they are valid and if that's all I had to do in that tab and which tab is the next one...

# Acceptance Criteria
- Add a bar similar to that in #1119 to the top of each tab
- Add the ability for the bar to be dismissed; once dismissed, it should never appear again

Tab | English | German | Learn More URL
---- | ---- | ---- | ----
Appearance | **_Optional_** Use the appearance tab to configure your payment button colors and how your pricing options are displayed.  | **_Optional_** Verwenden Sie die Registerkarte Aussehen, um die Farben Ihrer Zahlungstasten zu konfigurieren und wie Ihre Preisoptionen angezeigt werden.  | N/A
Pricing | **REQUIRED** Use this tab to configure your default prices. Prices can also be set for an individual post on the edit post page.  | **ERFORDERLICH** Auf dieser Registerkarte können Sie Ihre Standardpreise konfigurieren. Die Preise können auch für einen einzelnen Beitrag auf der Seite Beitrag bearbeiten festgelegt werden.  | [Learn More](https://www.laterpay.net/academy/wordpress-pricing) or [Erfahren Sie mehr](https://www.laterpay.net/academy/wordpress-pricing) 
Advanced | **_Optional_** Here we highlight advanced features & settings like contributions, selling downloadable content, and promoting your subscriptions. Scroll through to learn more! | **_Optional_** Hier heben wir erweiterte Funktionen und Einstellungen wie Beiträge, den Verkauf von herunterladbaren Inhalten und die Werbung für Ihre Abonnements hervor. | N/A

# Mockup

![image](https://user-images.githubusercontent.com/41650164/58346941-18b4ca00-7e22-11e9-84b2-3e1ce4efe4bd.png)

**Comment by ksmoore125** [comment]
Pending article for pricing tab; should be posted online in the next couple of days. This should not hold up the release but hopefully we can get it up ASAP as release both at the same time.

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
