### ISSUE TITLE
Clarify Visibility Toggle

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1179]
# Feedback
"When logged in as admin, the preview popup allows to choose between admin / visitor view. It's unclear if this is what visitors will see on the website of it it's just a test mode."

# Acceptance Criteria

- Add the beaker image & message about Test & Live mode to the visibility toggle
- Additionally, add the following message to ensure that this is clear:

English | German
-- | --
Complete the steps on the [account tab](url) to make this visible to visitors | Führen Sie die Schritte auf der [Registerkarte Konto]() aus, um dies für Besucher sichtbar zu machen

# Mockup
(the background of the beaker should be transparent, not white)
![image](https://user-images.githubusercontent.com/41650164/58345074-169c3c80-7e1d-11e9-94e6-ae5422c4caf3.png)

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
