### ISSUE TITLE
Verify that the Region, Merchant ID, & API Key are a Valid Combination

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1180]
# User Story
As a LaterPay merchant, I would like the plugin to automatically validate my information so that my end users can easily make purchases without experiencing any issues.

# Acceptance Criteria
- When any of the following items are changed we should validate to ensure that the combination is still valid
  - Region aka Currency
  - Merchant ID
  - API Key
- This validation may be done using [this API call](https://docs.laterpay.net/platform/intro/validatesignature/)
- If the above items are not valid, run the API again with the other region
  - If the API still returns false:
    - Perform the same behavior as if the Merchant Id or API Key is missing
      - Switch the plugin to TEST mode and disable LIVE mode
      - Display the existing error message: The LaterPay plugin needs valid API credentials to work.
  - If the API response is true when the region is changed:
      - Switch the plugin to TEST mode and disable LIVE mode    
      - Display the following error message

NOTE: `USD` & `EURO` in the error message below should dynamically update to say the correct currency.

English | German
 -- | --
Your LaterPay account is restricted to sell content in `USD ($)`. Please update your currency or contact sales@laterpay.net. | Ihr LaterPay-Konto ist darauf beschränkt, Inhalte in `EURO (€)` zu verkaufen. Bitte aktualisieren Sie Ihre Währung oder kontaktieren Sie sales@laterpay.net.

**Comment by ksmoore125** [comment]
This is a duplicate of #1178

**Comment by ksmoore125** [comment]
API responses: https://gist.github.com/thrijith/8669457fd667b994413158e36addcbc3

**Comment by ksmoore125** [comment]
This does not appear to be working as expected.
**Steps to Reproduce:**
- Currency = $
- Use valid for US info found [here](https://laterpay.slack.com/archives/C02JCERA4/p1559670652014500?thread_ts=1559249126.004700&cid=C02JCERA4)
- Change toggle to Live mode
- Change currency to €

**Observed Result**
Account is updated and account remains in Live mode

**Desired Result**
That combination should be invalid and therefore:
- Switch the plugin to TEST mode and disable LIVE mode
- Display the appropriate error message

**Comment by thrijith** [comment]
My bad, I've done a change in client library too, which needs to be merged.

@ksmoore125 Can you please get this PR https://github.com/laterpay/laterpay-client-php/pull/23 merged? 

Thanks.

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
