### ISSUE TITLE
Minor Updates to WordPress plugin page

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1182]
**Acceptance Criteria**
- Remove ", Mihail Turalenka and Aliaksandr Vahura" from the author's list
- Add the following tags:
  - conversion
  - paygate
  - paywall
  - monetization

**Comment by thrijith** [comment]
Updated in [v2.5.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.4)
