### ISSUE TITLE
Update Appearance Tab Google Analytics Events

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1185]
# Details
With the updates to the Appearance tab, we will also need to update the Google Analytics Events since the existing ones are no longer relevant.

# Summary of Existing Events
Where "/" is "|" due to the fact that Git cannot display |'s inside a table

GA Event Action | GA Event Label
-- | --
Overall Appearance | merchantID / Purchase Link, Explanatory Overlay, or Purchase Overlay
Custom Position | merchantID / Purchase Button
Custom Position | merchantID / Subscriptions & Time Passes
Standard Position | merchantID / Purchase Button
Standard Position | merchantID / Subscriptions & Time Passes

# Acceptance Criteria
Where "/" is "|" due to the fact that Git cannot display |'s inside a table
And bit* values are 1 if checked, 0 if unchecked

GA Event Category | GA Event Action | GA Event Label | GA Event Value | When triggered
-- | -- | -- | -- | --
LP WP Appearance | Update Colors | merchantID |  | On Color Settings Save
LP WP Appearance | Update Appearance | merchantID / Purchase Button | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / Purchase Button Custom Position | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / Purchase Overlay | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / LP Intro | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / TP & Sub Outside Overlay | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / TP & Sub Custom Position | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / Custom HTML | bit* | On Appearance Settings Save
LP WP Appearance | Update Appearance | merchantID / Footer | bit* | On Appearance Settings Save

**Comment by ksmoore125** [comment]
`Update Colors` does not appear to be firing.

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
