### ISSUE TITLE
Update Category Link

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1187]
**Steps to Reproduce**
- Navigate to the Pricing tab
- If there are Category Default Prices, remove them

**Observed Result**
There is a link to "Click here to learn more" which links to a WordPress page which has been removed

**Acceptance Criteria**
Update the URL to https://wordpress.org/support/article/posts-categories-screen/

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
