### ISSUE TITLE
Update Advanced tab to reflect changes to Appearance Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1188]
# Details
Because of the other changes we are making, there are a few minor edits that need to be made to ensure that our language throughout the plugin is clear and correct.

# Acceptance Criteria
- Navigate to LaterPay > Advanced > Appearance & remove the first bullet point "Button & link colors"
- Navigate to LaterPay > Appearance and adjust the "Advanced Settings" sidebar content to:

English | German
-- | --
[Click here]() to adjust the number of characters automatically generated as your teaser content or the length of the content preview blurred behind our paywall. | [Klicken Sie hier](), um die Anzahl der Zeichen anzupassen, die automatisch als Teaserinhalt generiert werden, oder die Länge der Inhaltsvorschau, die hinter unserer Paywall verschwimmt.

- Additionally, we have updated our Merchant Analytics Dashboard so please update the image to [this one](https://drive.google.com/file/d/1UKBWEzL4I0b-mDB4XJKn2m_CJfuJ3mma/view?usp=sharing)

**Comment by ksmoore125** [comment]
These changes do not appear to be reflected on staging.

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
