### ISSUE TITLE
Allow Merchant to Specify Voucher Codes

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1192]
# User Story
As a LaterPay merchant, I would like to be able to specify my voucher codes so that I can make them sound promotional and also so that I can reuse them as needed.

# Details
> I’ve got a partner that has had voucher codes associated with a monthly pass, and the time pass has since been deleted. The voucher codes associated with the pass have, however, been distributed in print, so the partner is wondering if they can create the same voucher codes for a different time pass -- In essence, if they can specify the voucher code instead of having it generated.

# Acceptance Criteria
- Allow Voucher Code to be edited at the time of creation
- Ensure there are not duplicate **active** vouchers within time passes
- Ensure there are not duplicate **active** vouchers within subscription
- If there is a duplicate (as outlined above) display the following error & do not allow the voucher to be saved

English | German
-- | --
This voucher code is already in use, please choose a different name. | Dieser Gutscheincode wird bereits verwendet, bitte wählen Sie einen anderen Namen.

# Mockup
This should follow the same format as the existing voucher errors:
![image](https://user-images.githubusercontent.com/41650164/58898814-06a81680-86c1-11e9-893f-9ae878f0d9d4.png)

**Comment by thrijith** [comment]
>Ensure there are not duplicate active vouchers within time passes
>Ensure there are not duplicate active vouchers within subscription

Even though the voucher data for time passes and subscriptions are stored differently, which would allow duplicate voucher codes to be saved, the current implementation on `Redeem voucher` will be an issue, if the voucher is available in time pass then it will use it. 

As of now, I have added a check, which won't allow duplicate code in Time Pass or Subscription combined.

**Comment by thrijith** [comment]
Reopening as not verified by Kimberly.

**Comment by ksmoore125** [comment]
What you have suggested is an acceptable solution. Thanks!

**Comment by thrijith** [comment]
Released in [v2.5.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.5.4)
