### ISSUE TITLE
Add Error Message in Case of Invalid Appearance Configuration

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1193]
# User Story
As a LaterPay merchant, I would like to be able to click around and play with the different Appearance options without accidentally getting stuck with items disabled and also without accidentally preventing my end users from purchasing my content.

# Details
The following three settings are the most complex piece of the Appearance tab logic. To help ensure that we cover all scenarios, below is a table will all available permutations:

Permutation No. | Show purchase button above article | Show Purchase Overlay | Show Time Passes & Subscriptions below modal | Preview 
-- | -- | -- | -- | --
⚠ 1 |   |   |   | (none checked) ![image](https://user-images.githubusercontent.com/41650164/58905402-45dd6400-86cf-11e9-970f-d227d6c8125e.png) |  
⚠ 2 | ✅ |   |   | ![image](https://user-images.githubusercontent.com/41650164/58905641-d61ba900-86cf-11e9-89ba-13554735b9b7.png)
3 |   | ✅ |   | ![image](https://user-images.githubusercontent.com/41650164/58905520-91900d80-86cf-11e9-8eb9-0408b79f8d78.png)
4 |   |   | ✅ | ![image](https://user-images.githubusercontent.com/41650164/58905535-981e8500-86cf-11e9-9532-a2962a2ca010.png)
5 | ✅ | ✅ |   | ![image](https://user-images.githubusercontent.com/41650164/58905541-9e146600-86cf-11e9-89e1-b99315cf508b.png)
6 |   | ✅ | ✅ | ![image](https://user-images.githubusercontent.com/41650164/58905547-a371b080-86cf-11e9-9dc4-097d485bf871.png)
7 | ✅ |   | ✅ | ![image](https://user-images.githubusercontent.com/41650164/58905566-a9679180-86cf-11e9-990e-02a4b54eceed.png)
8 | ✅ | ✅ | ✅ | ![image](https://user-images.githubusercontent.com/41650164/58905582-aec4dc00-86cf-11e9-94fd-ae139ecf80e8.png)

# Acceptance Criteria
In the table above, we see that all of the permutations except those marked with an ⚠ are valid configurations since the end-user is able to purchase a single article, time pass, or subscription. Whereas the two marked with ⚠ are missing at least one payment option. Therefore for these two configurations we should:

- Disable the Save button
- Display the following warning message both in the standard temporary header, and near the Save button as show in the mockup below (Where ⚠ = the warning symbol we use throughout the plugin)

English | German
-- | --
⚠ Please select one of the recommended options above to ensure that your users can purchase all content types. | ⚠ Bitte wählen Sie eine der oben empfohlenen Optionen aus, um sicherzustellen, dass Ihre Benutzer alle Arten von Inhalten erwerben können.

# Mockup
![image](https://user-images.githubusercontent.com/41650164/58907116-0e70b680-86d3-11e9-8dfe-c4e947d8d01f.png)

**Comment by ksmoore125** [comment]
@thrijith - Would it be possible (without too much effort) to highlight recommended checkboxes as shown in the mockup above?

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
