### ISSUE TITLE
Update Maximum Price Amount for Pay Now Items

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1195]
# User Story
As a LaterPay merchant, if there is sufficient demand for my product, I would like to be able to sell it at a higher price point.

# Acceptance Criteria
- Update the maximum price for Pay Now items to $1,000 / 1,000€

# Resources
https://laterpay.atlassian.net/browse/NEW-132

**Comment by thrijith** [comment]
Released in [v2.6.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.0)
