### ISSUE TITLE
Fix Technical Arrow on Advanced Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1208]
**Steps to Reproduce**
- On a laptop, navigate to the LaterPay > Advanced Tab
- Scroll to the bottom of the page

**Observed Result**
- The arrow for the Technical section is displayed at the bottom of the page

**Desired Result**
- It should be displayed to the right, like the other arrows

![image](https://user-images.githubusercontent.com/41650164/59714076-6250c480-91d6-11e9-91ee-32a2292c8894.png)

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
