### ISSUE TITLE
Update FAQ's Font

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1209]
# Acceptance Criteria
- The FAQ section in the sidebar's font appears to be bold. Instead it should be normal weight and match the "Support" Section
  - It appears that now, this appears bold because the text is `<h3>`
  - NOTE: This change should apply to all tabs (the example below is from the Advanced tab)

**Current:**
![image](https://user-images.githubusercontent.com/41650164/59714148-962bea00-91d6-11e9-9d19-5ba5cb4cdd1b.png)

**Desired:**
![image](https://user-images.githubusercontent.com/41650164/59714877-42ba9b80-91d8-11e9-89bc-cd45524b5b1d.png)

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
