### ISSUE TITLE
DISCOVERY: Contributions

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1213]
Need to talk to merchants to understand what they would want here...
https://docs.laterpay.net/platform/dialogs/contributions/

**Comment by ksmoore125** [comment]
From Sales & Integrations - Merchants are not asking for the button generator in WP, they would like something like this:
![image](https://user-images.githubusercontent.com/41650164/60446723-928d5f80-9be7-11e9-8060-f0cc2d5afc4f.png)

[Example 1](https://www.gutjahr.biz/2019/06/luegen-sex-und-youtube/) | [Example 2](https://jsfiddle.net/4wezut02/2/)

**Comment by ksmoore125** [comment]
Eric suggests using the https://github.com/laterpay/laterpay-client-php library and following the example at https://docs.laterpay.net/platform/dialogs/contributions/quick_start/ (adjusting for PHP)

**Comment by ksmoore125** [comment]
@thrijith - This will be our next big project. I would prefer not to get started with the development until we release the current items but please let me know if you have any questions or concerns with the project in general.

**Comment by thrijith** [comment]
@ksmoore125  
> The Contributions Dialog API is only available in the US, and is available for merchants not using the Sales API. Please contact sales@laterpay.net if you are interested in using this feature.

Will this be an issue for us?
Ref: https://docs.laterpay.net/platform/dialogs/contributions/main_endpoints/, 

Where should the contribution identifier creation be done? It should include an option to define predefined prices as seen in above example.

How will merchant add it to the site, should we provide a Shortcode or attach to post content?

**Comment by ksmoore125** [comment]
1) In regards to the quote above, that is outdated. It is now available to all merchants
2) I am leaning towards adding a new "Contributions tab"
3) I was thinking they could configure it in a wizard-type interface (similar to the Appearance tab...check things and fill in prices and then see a preview) and then we provide them with the shortcode when they are done
There has also been talk of using a Widget but my fear is that with a widget our merchants may not realize we have it since everything else is within the plugin tabs.

**Comment by ksmoore125** [comment]
Eric also shared the idea that we could put this directly into the WordPress WYSIWYG.
However, we still risk the issue of merchants not discovering the feature or the feature being hidden if they use a page builder.

Example of how this could look:
![image](https://user-images.githubusercontent.com/41650164/61892291-124dd780-aed1-11e9-93b6-7f447778f3d0.png)
