### ISSUE TITLE
Contextual Help Updates

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1216]
We have made several updates to the plugin but have not updated the contextual help. Below are a few changes that need to be made in order to ensure that the contextual help remains accurate:

_Note that the contextual help is currently only available in English._

# Account Tab 
### API Credentials
In order to receive payments, you first need a LaterPay account. Once this is set up, you need LaterPay API credentials, consisting of the following to link your WordPress plugin to your LaterPay account.

- Merchant ID (a 22-character string) and
- API Key (a 32-character string).

[Visit our website to read more about how to become a content provider or to sign up with LaterPay.](https://www.laterpay.net/solutions/influencers)

### Test Mode
You can run the LaterPay plugin in two modes:

- **Test Mode** – This allows you to test your plugin configuration.
While providing the full plugin functionality, payments are only simulated and not actually processed.
The plugin will only be visible to admin users, not to visitors.
This is the default setting after activating the plugin for the first time.

- **Live Mode** – In live mode, the plugin is publicly visible and manages access to paid content.
All payments are actually processed.

Using the LaterPay plugin usually requires some adjustments of your theme.
Therefore, we recommend installing, configuring, and testing the LaterPay plugin on a test system before activating it on your production system.

### General
Need additional help? Check out the [LaterPay WordPress Plugin Knowledge Base here](https://www.laterpay.net/academy/tag/wordpress).

# Appearance Tab
Remove the existing categories of `Preview Mode`, `Purchase Button Position`, and `Time Pass Position` and replace with the following:

[Resource](https://docs.laterpay.net/connector/configuration/inpage_configuration/appearance/)

### Configure Appearance
The top portion of this page allows you to customize how your pricing options are displayed. Below are the different options available. By checking & un-checking the corresponding checkboxes, you can easily see how the overlay will be displayed using the preview section to the right.

Once you have your display options configured, **be sure to click save** at the bottom of the Configure Appearance section to apply these changes to your site. 

- **Show purchase button above article** - By enabling this option, a button displaying the article purchase price will be displayed at the top right of the post.
  - **Customize position of purchase button** - Use the provided WordPress code to customize the position of the button described above.
- **Show Purchase Overlay** - Display an overlay with the available purchase options over your paid content.
- **Header** - Adjust the header text that is displayed at the top of the Purchase Overlay.
- **Show LaterPay Introduction** - In the Purchase Overlay, provide information describing LaterPay to your customers.
- **Show Time Passes & Subscriptions below modal** - Display Time Pass &/or Subscription options as tickets at the bottom of your content.
  - **Customize position of Time Passes & Subscriptions** - Use the provided WordPress code to customize the position of the items described above.
- **Add custom HTML section below payment button** - In this section you can choose to add custom HTML or text content at the bottom of the Purchase Overlay.
- **Show valid payment options** - Display a footer section at the bottom of the Purchase Overlay with images of the various payment options available.

### Customize Colors
Use the lower half of this page to customize the colors of the LaterPay elements. This section can be used to ensure that the color scheme matches your theme and brand. The following customizations are available:

- **Header background color** - The header background color defines a custom color used as the background of the Purchase Overlay header.
- **Purchase option background color** - This option defines a custom color for the background of the Purchase Overlay.
- **Main text color** - The main text color defines the text color for the sub-headers (purchase options) within the Purchase Overlay.
- **Description text color** - This option sets the text color for all standard, non-bolded text within the Purchase Overlay.
- **Purchase button background color** - The purchase button color allows you to define a custom background color for the purchase button.
- **Purchase button hover color** - This is the color displayed when a user hovers their mouse over the purchase button.
- **Purchase button text color** -  Here you may define the color of the text displayed in the purchase button.
- **Link main color** -  The link main color defines the text color for all links added by the LaterPay plugin.
- **Link hover color** - This is the color displayed when a user hovers their mouse over links.
- **Footer background color** - The footer background color defines the background color of the footer, payment options section.
- **Restore default values** - By clicking "Restore default values," all colors will be restored to the original LaterPay default values.

# Pricing Tab
### LaterPay Content
Use the LaterPay Content section to select what types of WordPress content you would like to sell using LaterPay. The most common types are Pages, Posts, and Media but additional options may be available depending on the other plugins that you have installed.

**TIP:** If you are not sure what kind of content you would like to sell, we recommend starting with Posts & Media. This should ensure that your Pages (typically your Home Page, About Us Page, etc) remain free while you can monetize the majority of your other content (typically Posts).

For more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

### Global Default Price
Setting the Global Default Price will determine the standard behavior of your monetized content. There are three options to choose from and we will go through each one in detail and provide a few examples to help determine which is the best option based on your strategy:

**1. FREE unless price is set on post page or by category**
**Description:** All articles will be free by default. Time Passes & Subscriptions will only be displayed if the article matches a Category Default Price or has an Individual Article Price set on the Post Page.
**What does that mean?** We are getting a bit ahead of ourselves here but to simplify, this means that your content will be completely free (no single purchases, no time passes, no subscriptions) unless you intentionally override this setting.
**Example:** Assuming you are a news site and you want most of your articles to be free except for your content flagged as “Premium,” then this option is perfect for you. Make articles free by default and then we will walk you through how to override that for your premium content later on in this tutorial.

**2. Posts cannot be purchased individually**
**Description:** Only Time Passes & Subscriptions will be displayed in the purchase dialog.
**What does that mean?** This means that you do not want to allow your users to purchase just one piece of content, instead you only want to allow them to access content using a time pass or subscription.
**Example:** If you are a music streaming service and you don’t want users to be able to purchase one song at a time, but instead you want to sell subscriptions, then this option is best suited for you. By selecting this, you will ensure that only time passes or subscriptions are displayed on your site.

**3. Set individual article default price**
**Description:** All single pieces of content will be for sale at this price unless overridden.
**What does that mean?** This is the most standard of the three options; it is what you would typically think of when you are setting a “default.” By setting a price on this option, you are setting that as the default price for purchasing any single piece of content.
**Example:** I am a blogger, all of my content is along the same topic and ideally of equal interest (and value) to my readers. Therefore, I would like to set one default price for all of my blog posts. By selecting this option, I will do exactly that; set one price for all blog posts. Later I can override this for different categories or for specific posts but by default all of my blog posts will have the same price.

For more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

### Category Default Prices
A category default price is applied to all posts in a given category that don't have an individual price assigned to them on the edit post page.
A category default price overwrites the global default price.
If a post belongs to multiple categories, you can choose on the add / edit post page, which category default price should be effective.
For example, if you have set a global default price of 0.15, but a post belongs to a category with a category default price of 0.30, that post will sell for 0.30.

For more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

### Time Passes
With time passes, you can offer your users time-limited access to your content. You can define which content a time pass should cover and for which period of time it should be valid. A time pass can be valid for all LaterPay content
- on your entire website,
- in specific category/ies, or
- on your entire website except from a specific category/ies.

The validity period of a time pass starts with the purchase and is defined for a continuous use – i.e. it doesn't matter, if a user is on your website during the entire validity period. After a time pass has expired, the access to the covered content is automatically refused. Please note: Access to pages which are still open when a pass expires will be refused only after reloading the respective page. Any files (images, documents, presentations...), that were downloaded during the validity period, can still be used after the access has expired – but the user will not be able to download them without purchasing again.

**Deleting Time Passes**
If you delete a time pass, users who have bought this time pass will still have access to the covered content. Deleted time passes can't be restored.

**Time Passes and Individual Sales**
When a user purchases a time pass, they have access to all the content covered by this pass during the validity period. Of course, you can still sell your content individually.
Example: A user has already purchased the post "New York – a Travel Report" for 0.29. Now he purchases a Week Pass for the category "Travel Reports" for 0.99. The category also contains the "New York" post. For one week, he can now read all posts in the category "Travel Reports" for a fixed price of 0.99. After this week, the access expires automatically. During the validity period, the user will not see any LaterPay purchase buttons for posts in the category "Travel Reports". After the pass has expired, the user will still have access to the post he had previously purchased individually.

For more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

### Subscriptions
Subscriptions work exactly like time passes, with a simple difference: They renew automatically.

When a user purchases a subscription, they have access to all the content covered by this subscription during the validity period. Of course, you can still sell your content individually.

**Deleting a Subscription**
If you delete a subscription it, it will continue to renew for users who have an active subscription until the user cancels it. Existing subscribers will still have access to the content in their subscription. New users won't be able to buy the subscription anymore.

For more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

### Vouchers
Voucher codes can be generated for time passes and subscriptions. Vouchers are most commonly used to give discounted access to readers who already have a print subscription. To create a voucher code, simply click “+ Generate Voucher Code” at the bottom of the time pass or subscription box. A random 6 character code will be generated but this can be overridden with a custom 6 characters if you choose. Then simply set the reduced price, add a description and save!

You can create any number of voucher codes. A voucher code allows one (or multiple) user(s) to purchase a time pass or subscription for a reduced price. A user can enter a voucher code right below the time passes by clicking "I have a voucher". If the entered code is a valid voucher code, the price of the respective offer will be reduced.
A voucher code can be used any number of times and is not linked to a specific user. If you want to invalidate a time pass voucher code, you can simply delete it.
Deleting a voucher code will not affect the validity of time passes which have already been purchased using this voucher code.

A few key things to note when using voucher codes:
- Each active voucher can be redeemed an unlimited number of times
- If a new user signs up for a subscription using a voucher code, the voucher code will reduce the price for the entirety of the subscription
For example, if you have a monthly subscription regularly priced at 10 per month and generate a voucher code which makes that subscription available for 5 per month, anyone who signs up for that subscription using the voucher code will pay 5 every month.

For more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

### Additional Ways to Monetize Content
**Individual Article Price**
If you ever need to override a price for a specific article, you may do so on the WordPress Edit Post page. To do this simply:
1. Navigate to the post you would like to override
2. Choose to Edit that post using the WordPress Admin
3. In the right sidebar you should see a LaterPay section where you can select to use the Global Default Price, a Category Default Price (when applicable), or to set an Individual Price.
By selecting the Individual Price, you will be able to override any other defaults for this specific post.

Check out other advanced pricing options on the [Advanced Tab]() or, for more instruction on setting up [Pricing, click here](https://www.laterpay.net/academy/wordpress-pricing).

**Comment by ksmoore125** [comment]
**Minor changes**

- Account Tab
  - Plugin Mode
    - Please update `The plugin will only be visible to admin users, not to visitors.` so that it is on a new line
- Appearance Tab ✅ 
- Pricing Tab
  - Side panel
    -Please move `Check out other advanced pricing options on the Advanced Tab` so that it is only displayed at the bottom of the **Additional Ways to Monetize Content** section and not in the sidebar
  - Global Default (the current content is too long!)
    - Please remove **all** of the `What does that mean?` and `Example` paragraphs
  - Time Passes (the current content is too long!)
    - Please remove this section `Please note: Access to pages which are still open when a pass expires will be refused only after reloading the respective page. Any files (images, documents, presentations...), that were downloaded during the validity period, can still be used after the access has expired – but the user will not be able to download them without purchasing again.`
    - Please also remove the entire `Time Passes and Individual Sales` section
  - Vouchers (the current content is too long!)
    - Please remove:
`Vouchers are most commonly used to give discounted access to readers who already have a print subscription.`
&
` Then simply set the reduced price, add a description and save!`
&
`A voucher code can be used any number of times and is not linked to a specific user. If you want to invalidate a time pass voucher code, you can simply delete it.

Deleting a voucher code will not affect the validity of time passes which have already been purchased using this voucher code.`

**Comment by thrijith** [comment]
@ksmoore125 Updated as suggested above.

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
