### ISSUE TITLE
Contextual Help Release Notice

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1217]
When this release goes live, display the following message in the release notification banner:

**English:**
> Have you seen our Contextual Help? Click the "Help" box in the upper right corner of any page to get relevant information.

**German:**
> Haben Sie unsere kontextuelle Hilfe schon kennengelernt? Klicken Sie auf das Feld “Hilfe” in der oberen rechten Ecke der jeweiligen Seite, um weitere nützliche Informationen zu erhalten.

**Comment by ksmoore125** [comment]
Update: We will promote this in a future release. Since we will be rolling out the "Wisdom" tracking which has a bar across the top of the page, I do not want a release notification with v2.6.1 which may distract from the Wisdom consent message.

**Comment by thrijith** [comment]
Added in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
