### ISSUE TITLE
Track Pricing Overlay Customizations in GA

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1219]
# Details
This will help us track the user adoption of this new feature and also eventually join to the merchant purchase data so that we can determine if this increases their revenue or not.

# Acceptance Criteria
Event Category | Event Action | Event Label | Event Value
-- | -- | -- | -- 
LP WP Pricing | Customize Display | `merchantID` `sort order` `default selection` | 

- Where the above items are pike delimited
- `sort order` should consist of the following possible values
  - `Default`
  - `Ascending`
  - `Descending`
- `default selection` should consist of the following possible values
  - `First`
  - `Single Purchase`
  - `Time Pass`
  - `Subscription`
- This data should be updated when the merchant clicks save

**Comment by ksmoore125** [comment]
Related to #1136

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
