### ISSUE TITLE
Allow merchants to Opt in or Out of Wisdom data capture on Settings Page

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1220]
# User Story
As a merchant, I would like to be able to change my mind later in case that I develop security concerns or learn to trust LaterPay after more experience with their product.

As a LaterPay support person, I would like to be able to request that a merchant turn on tracking so that I can provide better support.

# Acceptance Criteria
- Allow merchants to Opt in or Out after Activation on the LaterPay Settings Page ([here](https://wisdomplugin.com/support/#advanced))
- Update the existing Analytics section, as follows

### Intro Paragraph
**English**
> In order to make informed decisions about improvements to our plugin, we would like to track its usage on your site. We do not record any sensitive information and are not in the business of selling data. The only metrics that we track are in regards to your WordPress environment and plugin settings. If you would like to add LaterPay events to your own Google Analytics environment, simply link to your Google Analytics account in the box below. Additional analytics on your site's purchase history are available in your LaterPay Merchant Analytics Dashboard. To view this information, simply log in to your LaterPay account on [laterpay.net](https://www.laterpay.net/).

**German**
> Um fundierte Entscheidungen über Verbesserungen an unserem Plugin zu treffen, möchten wir dessen Verwendung auf Ihrer Website verfolgen. Wir erfassen keine sensiblen Informationen und sind nicht im Geschäft mit dem Verkauf von Daten. Die einzigen Kennzahlen, die wir verfolgen, beziehen sich auf Ihre WordPress-Umgebung und die Plugin-Einstellungen. Wenn Sie LaterPay-Ereignisse zu Ihrer eigenen Google Analytics-Umgebung hinzufügen möchten, verlinken Sie einfach auf Ihr Google Analytics-Konto in der untenstehenden Box. Zusätzliche Analysen zur Kaufhistorie Ihrer Website sind in Ihrem LaterPay Merchant Analytics Dashboard verfügbar. Um diese Informationen einzusehen, loggen Sie sich einfach in Ihr LaterPay-Konto auf [laterpay.net](https://www.laterpay.net/) ein.

### New Checkbox
**English**
> Track Plugin Usage & WordPress Settings: 

**German**
> Verfolgen Sie die Verwendung von Plugins und WordPress-Einstellungen:

# Mockup
![image](https://user-images.githubusercontent.com/41650164/60190166-ccc9bc00-97f7-11e9-8312-af43d4859509.png)

**Comment by ksmoore125** [comment]
Update: Due to the discussion [here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1561726478001300?thread_ts=1561392256.008800&cid=GA2P84GBZ), we will instead be putting this on the Advanced tab as defined below:

# Acceptance Criteria
- Allow merchants to Opt in or Out after Activation on the LaterPay Settings Page ([here](https://wisdomplugin.com/support/#advanced))
- Update the existing Advanced tab, as follows:
  - Add a new `Analytics & Usage Data` or `Analytik & Nutzungsdaten` section between **Access** and **Appearance**

# Copy

English | German
-- | -- 
Analytics & Usage Data | Analytik & Nutzungsdaten 
In order to make informed decisions about improvements to our plugin, we would like to gather information on a few of your WordPress settings. We do not record any sensitive information; only data points in regards to your WordPress environment and plugin settings. | Um fundierte Entscheidungen über Verbesserungen an unserem Plugin zu treffen, möchten wir Informationen über einige Ihrer WordPress-Einstellungen sammeln. Wir erfassen keine sensiblen Informationen, sondern nur Datenpunkte in Bezug auf Ihre WordPress-Umgebung und Plugin-Einstellungen.
LaterPay CAN / CANNOT view my settings | _pending_
If you are also interested in making data informed decisions, additional analytics available through LaterPay include: | Wenn Sie auch daran interessiert sind, datenbasierte Entscheidungen zu treffen, sind zusätzliche Analysen über LaterPay verfügbar:
[Google Analytics Events]() | [Google Analytics Veranstaltungen]()
[LaterPay's Analytics Dashboard]() | [LaterPay's Analytics Dashboard für Analysen]()

# Mockup
![image](https://user-images.githubusercontent.com/41650164/60362966-e0b42000-99a7-11e9-88bd-7b3966689d4b.png)

**Comment by ksmoore125** [comment]
The English looks good, we just need to add the German translations. Please also update the English toggle text to match what is shown with the updated requirements in the comment above.

**Comment by thrijith** [comment]
Released in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
