### ISSUE TITLE
Ensure Deactivation Survey is Displayed when Plugin is Deactivated from Advanced Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1221]
# User Story
As a LaterPay Product Manager, I want to ensure that we capture feedback from every potential user flow so that we get well rounded feedback from all of our merchants.

# Acceptance Criteria
- Extend Wisdom ([here](https://wisdomplugin.com/support/#advanced)) to also display the deactivation survey when a merchant deactivates our plugin from the Advanced Tab

**Comment by ksmoore125** [comment]
This looks good. Thanks!

**Comment by thrijith** [comment]
Released in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
