### ISSUE TITLE
Allow Merchants to Easily set an Individual Article to FREE

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1222]
# User Story
https://laterpay.atlassian.net/browse/PRODUCT-457
As a LaterPay merchant, I would like to easily be able to set an article as free. Today this is difficult unless my default article price is free.

# Discovery: Current Status
**Ways to make an article completely free:**
- "Happy Path"
  - Set Global Default Price = `FREE unless price is set on post page or by category`
- Alternatives
  - If they **do not** have Time Passes or Subscriptions for that article
    - Set the individual post price to 0.00
    - Set the category default price to 0.00
  - If they **do** have Time Passes or Subscriptions for that article
    - Set the individual post price or category default price to 0.00 & Exclude that category from all TP & Sub 

**Ways to only offer TP or Sub:**
- "Happy Path"
  - Set Global Default Price = `Posts cannot be purchased individually`
- Alternatives
    - Set the individual post price to 0.00
    - Set the category default price to 0.00

# Acceptance Criteria
- Update the Edit Post Page to allow an option to make the Post Free (see mockup below)
- Existing options should contain the same wording & tooltips (in both English & German) as they do today with the following exception:
  - Individual Price should be updated to `Individual Article Price` in English, it can stay the same in German
- The new option should be:
**English**
> FREE
Time Pass & Subscription Offers Hidden

**German**
>  KOSTENLOS
Zeitreisepass & Abonnementangebote Versteckt

# Mockup
[Prototype here](https://sketch.cloud/s/45evm/a/bYO80Z/play)

**Comment by ksmoore125** [comment]
For reference, design change discussion [here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1561708361000300)

**Comment by ksmoore125** [comment]
@thrijith - This looks great! Only a couple minor style comments:

![image](https://user-images.githubusercontent.com/41650164/60539787-2851e900-9cd3-11e9-87fc-3453c7e9073b.png)

1) It looks like `Global Default Price` is not centered; could we center it so that it matches the other options?

When there are categories, the window is a bit to narrow so scrollbars are added:

2) Could we automatically lengthen the box so that the vertical scroll bar does not appear?

3) For the width, it looks like it is less than 10px too wide. Is there anything that we could make more narrow so that it would fix without the scroll bar? If not, let me know and I can try to come up with other ideas.

**Comment by thrijith** [comment]
> could we center it so that it matches the other options?
fixed it.

> Could we automatically lengthen the box so that the vertical scroll bar does not appear?
Increasing the height might not look good since only the right side will increase in height, we could add a border to category list for so that it's more clearer.

> For the width, it looks like it is less than 10px too wide. 
I am not able to get the same result with horizontal scroll, but there is one, could move the revenue model label below price or something like that?

@ksmoore125 Please check and let me know if you have any concerns.

**Comment by ksmoore125** [comment]
> we could add a border to category list for so that it's more clearer
Sounds like a good plan

> I am not able to get the same result with horizontal scroll
Hardly anything is cut off horizontally, could you just add code to ensure that the horizontal scroll bar is never added? In certain cases some of the text may be cut off but since the WP UI has a fixed width that should not happen often.

**Comment by ksmoore125** [comment]
Current Display:
![image](https://user-images.githubusercontent.com/41650164/60830538-0e098680-a17d-11e9-9d50-63d6d7616a8e.png)

Would it be possible to:
1) Hide the vertical scroll bar (I assume that it is no longer needed)
2) Make the aqua highlight extend far enough to the right to contain all of `Pay Later` (even though it may get cut off the screen)

**Comment by ksmoore125** [comment]
+ Please also update the Pricing for Post Google Event `<merchantID> | <post id> | <Global Default, Category Default or Individual Price>` so that it also has an option for `FREE`

**Comment by thrijith** [comment]
> Hide the vertical scroll bar (I assume that it is no longer needed)

We would need that when there are more are categories on post, I am not able to replicate the displayed scroll behaviour above though, [tested](http://bit.ly/2G2zq5l) in multiple browsers and screen sizes.

> Make the aqua highlight extend far enough to the right to contain all of Pay Later (even though it may get cut off the screen)

Unable to replicate this at my end. Can you send me browser version and screen size if possible?

- Updated GA even with FREE as selected pricing type when individual post is set free.

**Comment by ksmoore125** [comment]
> Updated GA even with FREE as selected pricing type when individual post is set free.
✅ 

> Can you send me browser version and screen size if possible?
Chrome 75 on macOS (Mojave)
This happens regardless of the width of the browser; the sidebar has a fixed width of 278px

**Comment by thrijith** [comment]
> This happens regardless of the width of the browser; the sidebar has a fixed width of 278px

Was able to replicate it, updated, it should be fixed now.

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
