### ISSUE TITLE
DISCOVERY (round 2): User Management

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1228]
# User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.

**Primary Use Case:**  Be able to provide an ad free experience to subscribers

# Re-cap / New Items to Explore
Notes from our last exploration of this topic can be found [here](https://docs.google.com/document/d/1jVv_BHIUZ8SbPZJUo_WDEfsU5VurXQP4zMHNIkcteCc/edit#)

It seems as though user roles would be a very nice way to go. Using the User Role Manager plugin, our merchants could create custom user groups to manage all of the different behaviors then simply assign those roles to a purchase level (ie: Subscription 22)

However we cannot / do not want to require that the merchants sign in to WP & we do not want to create fake user accounts.

**Potential Solutions / Open Questions**
1) Could we do something similar to what is shown [here](http://justintadlock.com/archives/2009/05/09/using-shortcodes-to-show-members-only-content) and add functions into our plugin so that all the merchants need to do is add sections of content inside brackets?

2) Similar to what we discussed last time. Would it be possible to have the merchant set up different user roles with the behavior that they want and then instead of creating a merchant account, we use hooks or another method to temporarily assign them to that role based on the results of the LP `/access` check?

**Comment by ksmoore125** [comment]
One additional [use case](https://laterpay.slack.com/archives/CGA4Y3H08/p1562788274000900): We have a merchant who is currently using [this](https://wordpress.org/plugins/custom-content-by-country) to display custom content for users inside vs outside the US and would like to also use that plugin to change the pricing

**Comment by thrijith** [comment]
@ksmoore125 I've gone through the plugin, couldn't find a way to integrate it though, it is using Shortcodes to handle display of content but that can't be used to change post prices.

Allowing user to change pricing manually might not be good as we need revenue model, currency (region) along with it and if there is invalid price and revenue model combination the purchase link would result in a 404.
