### ISSUE TITLE
Audit German Translations within the Plugin

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1230]
# Instructions
**1) Go [here](http://kimberlystestsite.cloudaccess.host/wp-admin/admin.php?path=plugins%2Flaterpay%2Flanguages%2Flaterpay-de_DE.po&bundle=laterpay%2Flaterpay.php&domain=laterpay&page=loco-plugin&action=file-edit)**

**2) Add / Update all German translations**
Note: This one translation is currently being used for all of the following languages 
![image](https://user-images.githubusercontent.com/41650164/60525859-d00bee80-9cb4-11e9-8296-14322ab5c4c3.png)
No need to update them separately just let Kimberly know if you have any concerns with using one translation for all 3 languages.

**3) Kimberly will export the `.po` file and provide to rtCamp**

**4) rtCamp will make any required adjustments and include in the next release**

**Comment by ksmoore125** [comment]
The .po file is saved [here].(https://drive.google.com/drive/u/0/folders/1Iv8Q8ApPrIkauf_xzhUXQaUThTksPbui)

There are a few separated sentences which may need to be rewritten but this is a good first-pass.

**Comment by ksmoore125** [comment]
Our German Marketing Manager will review this next week.

**Comment by ksmoore125** [comment]
@thrijith - Our marketing manager has finished his audit and has requested the following additional changes:

# Account Tab
1) 
![image](https://user-images.githubusercontent.com/41650164/62053381-16ce0500-b1dd-11e9-861d-d942c3722446.png)

# Appearance Tab
1)
![image](https://user-images.githubusercontent.com/41650164/62053611-98259780-b1dd-11e9-8c60-931f0d17863d.png)

2)
![image](https://user-images.githubusercontent.com/41650164/62053630-a378c300-b1dd-11e9-9013-36b123983ca7.png)

3)
![image](https://user-images.githubusercontent.com/41650164/62053681-b7bcc000-b1dd-11e9-96ee-cc8f6f09ad76.png)

4)
![image](https://user-images.githubusercontent.com/41650164/62053719-cacf9000-b1dd-11e9-9ef2-a17e0d6fd42e.png)

5)
![image](https://user-images.githubusercontent.com/41650164/62053750-da4ed900-b1dd-11e9-92d7-8f9ba02f6622.png)

# Pricing Tab
1)
![image](https://user-images.githubusercontent.com/41650164/62053804-f81c3e00-b1dd-11e9-91c1-cb47c74b5b2c.png)

2)
![image](https://user-images.githubusercontent.com/41650164/62053853-1124ef00-b1de-11e9-9e9f-038dce5a39d3.png)

# Advanced Tab
1)
![image](https://user-images.githubusercontent.com/41650164/62053474-454be000-b1dd-11e9-8dd4-3f183dc3f35f.png)

2)
![image](https://user-images.githubusercontent.com/41650164/62053513-5d236400-b1dd-11e9-8662-ced5193fd74a.png)

3)
![image](https://user-images.githubusercontent.com/41650164/62053990-52b59a00-b1de-11e9-9ed1-c9dcc85e9af9.png)

4)
![image](https://user-images.githubusercontent.com/41650164/62054017-606b1f80-b1de-11e9-83d4-27ea50277bbf.png)

5)
![image](https://user-images.githubusercontent.com/41650164/62054041-6d880e80-b1de-11e9-8afa-df2bc1d805af.png)

6)
![image](https://user-images.githubusercontent.com/41650164/62054064-7aa4fd80-b1de-11e9-80b1-735cd12557c9.png)

**Comment by thrijith** [comment]
@ksmoore125 Updated the marked strings, changes deployed to staging.

**Comment by ksmoore125** [comment]
I have two additional questions out to our marketing manager but otherwise it is looking good.

**Comment by ksmoore125** [comment]
@thrijith - Last change; the grey text should translate as follows:
![image](https://user-images.githubusercontent.com/41650164/62216016-9ab6f700-b36d-11e9-973d-7c4313687bf6.png)
> Rufen Sie die Aktion 'laterpay_time_passes' in Ihrem Theme auf oder verwenden Sie den Shortcode '[laterpay_time_passes]', um Ihren Benutzern die verfügbaren Zeitpässe anzuzeigen.
**Shortcode** [laterpay_time_passes]
**Action** <? php do_action( 'laterpay_time_passes' ); ?>

**Comment by thrijith** [comment]
@ksmoore125 Changes deployed to staging.

**Comment by thrijith** [comment]
Reported translations updated and released in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
