### ISSUE TITLE
Add Vouchers for Single Purchases

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1237]
# User Story
https://laterpay.atlassian.net/browse/PRODUCT-476

As a LaterPay merchant who is part of a larger publishing group, I would like to be able to provide free access to my partners **without them signing into WordPress** so that they can easily access my content.

# Acceptance Criteria
As a temporary solution until we can implement User Management or a re-design of the Pricing Tab, they have requested that we add voucher codes for Single Articles.

- Add the `+ Generate voucher code` functionality to the Global Default Price
- Voucher code functionality (pricing limits etc) should function the same as with Time Passes
- Add a disclaimer (see text in table below) to explain the following functionality: In order to keep this MVP simple, we will make the voucher code available on **all** articles with a single article price (the configuration of the voucher is in the Global Default Price section but the voucher should be available even when the Global Default Price is overridden by a Category Default or Single Article Price)
- "Redeem Voucher" link should be available when the voucher code is in use. The location of this link does not need to be moved since this is an MVP
- Because we do not want to over complicate things for our other merchants, this functionality should be hidden unless enabled on the Settings > LaterPay Page
  - Under the Access Category (between "Require User Login..." and "WordPress User Role...") add a checkbox to enable this feature (see text in table below)
- Since this is an MVP we will need to re-visit it if it starts to get significant usage therefore we should track it's usage in GA as follows
  - GA Event Category = LP WP Settings
  - GA Event Action = Modify LaterPay Settings
  - GA Event Label = <merchantID> / Single Purchase Vouchers Enabled _(where / = pike)_
  - GA Event Value = bit (1 = checked, 0 = unchecked)

Content | English | German
-- | -- | --
Disclaimer | This voucher will provide discounted access to all Articles, even those with a Category Default or Single Article Price. | Dieser Gutschein ermöglicht einen vergünstigten Zugang zu allen Artikeln, auch zu denen mit einem Kategorie-Standard oder Einzelartikelpreis.
Checkbox Text | Enable Vouchers for Single Article Purchases | Gutscheine für Einzelartikelkäufe aktivieren
 
# Mockup
![image](https://user-images.githubusercontent.com/41650164/61069541-21615f80-a3d2-11e9-865e-157852954363.png)

**Comment by ksmoore125** [comment]
Note: In other voucher categories we validate that the voucher cannot be higher than the set price. However in this case we are not sure what the set price will be since it varies by article therefore we will not perform this validation and the voucher has the potential to be priced higher than the single article price.

Vouchers currently have the functionality to be so that if the price goes above the Pay Later margin, then revenue model will be Pay Now so we do not need to worry about this validation either.

**Comment by ksmoore125** [comment]
@thrijith - 
1) Please move the voucher code section below the single article price selection:
![image](https://user-images.githubusercontent.com/41650164/61379488-42f89600-a86d-11e9-975d-bd3366c48805.png)

2) The voucher code does not seem to be working appropriately
**Steps to Reproduce**
- Navigate [here](https://lpwptestprod.wpengine.com/wp-admin/admin.php?page=laterpay-pricing-tab) 
- Note that there is a single article voucher code `KRgmPu`
- Navigate to a post ([example](http://lpwptestprod.wpengine.com/2019/05/07/sample-post-with-links/))
- Attempt to redeem the voucher
**Result:** Clicking `Redeem Voucher Code` just clears the box and does not work as expected

**Comment by thrijith** [comment]
@ksmoore125 I've updated the position of global vouchers and fix issue with the redeeming too, can you please test again?

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
