### ISSUE TITLE
Create Membership Shortcode

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1238]
# User Story
As a LaterPay Merchant, I would like to be able to customize the user experience based on the reader's contribution level.

**Details**
Merchants would like to be able to adjust the user experience to create premium offerings. Functionality should include being able to do things such as remove ads, remove pop-ups, or provide access to commenting, etc.

# Acceptance Criteria
- Use shortcodes to achieve the basic user request of customizing the site based on the user purchase level. Short codes can be used in the editor (similar to what is done [here](http://justintadlock.com/archives/2009/05/09/using-shortcodes-to-show-members-only-content)) to hide content based on if a user has been granted access thanks to the purchase of a specific time pass or subscription. As discussed [here](https://rtcamp.slack.com/archives/GA2P84GBZ/p1562772704000600).
- Short codes should allow for code to be hidden based on the user access as follows:
  - Access to content (default; if the user has access no matter if it was single purchase, time pass, or subscription)
  - Access via any time pass
  - Access via any subscription
  - Access via a specific time pass or subscription
  - _Optional_ User does not have any of the above items
    - This could be used to "hide comments if user does not have a subscription" etc.
    - This is optional and can wait until a later phase of the project if it adds significant complexity

**Comment by thrijith** [comment]
@ksmoore125 

> Short codes should allow for code to be displayed / hidden 
Should the shortcode provide both options to hide / show based on access?

> Access to content (default; if the user has access no matter if it was single purchase, time pass, or subscription)

Basically if user is on a page that is purchasable, and the user has access to it, the code should display/hide based on it?

**Comment by ksmoore125** [comment]
> Should the shortcode provide both options to hide / show based on access?
Thanks for asking! On second thought, I will update the requirements to only include "hide" if we get additional requests we can make changes later to allow for "show"

> Basically if user is on a page that is purchasable, and the user has access to it, the code should display/hide based on it?
Yes

**Comment by ksmoore125** [comment]
See [this section of the code](https://github.com/laterpay/laterpay-wordpress-plugin/blob/96d4f1c001790d5511f308dbee04fa1fcaee5955/laterpay/application/Controller/Frontend/Shortcode.php#L571-L590) for details

**Comment by thrijith** [comment]
Released in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
