### ISSUE TITLE
Add Membership Section to Advanced Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1240]
# User Story
As a LaterPay WordPress Plugin user, I would like to be able to see and get more information on all features, including shortcodes and other hidden features, so that I can ensure that I am taking advantage of everything that LaterPay has to offer.

# Acceptance Criteria
Add the following section to the Advanced tab (between `CREATE SUBSCRIPTION BUTTON` and `DYNAMIC PRICING`)

English | German
-- | --
**DYNAMIC ACCESS** | **DYNAMISCHER ZUGRIFF**
Create a customized experience with our newest [shortcode](https://en.support.wordpress.com/shortcodes/) & [function](https://codex.wordpress.org/Function_Reference). Using LaterPay's Dynamic Access feature, you can show or hide content - ads, promotional pop-ups, bonus features, virtually anything you can imagine - based on the level of access a user has purchased.| Erstellen Sie ein benutzerdefiniertes Erlebnis mit unserem neuesten [Shortcode](https://en.support.wordpress.com/shortcodes/) und der neuen [Funktion](https://codex.wordpress.org/Function_Reference). Mit der LaterPay Dynamic Access-Funktion können Sie Inhalte - Anzeigen, Werbe-Popups, Bonus-Features, praktisch alles, was Sie sich vorstellen können - ein- oder ausblenden, abhängig von der Zugriffsebene, die ein Benutzer erworben hat. 
[Click here for detailed instructions.](https://www.laterpay.net/academy/wordpress-dynamic-access) _NOTE: This url will not work now but I will ensure it is functional before our release_ | [Klicken Sie hier für eine detaillierte Anleitung.](https://www.laterpay.net/academy/wordpress-dynamic-access)
Instead of an image we display the following text in a format similar to (I like the check marks for bullet points and giving it a defined border): | ![image](https://user-images.githubusercontent.com/41650164/61963323-f01b8e80-af90-11e9-9014-fa8f4c8f504b.png)
`Ad-Free Experience`  `Hide Promotions after Purchase` `Restrict Bonus Features to Subscribers` `Much More!` |  `Werbefreies Erlebnis` `Promotionen nach dem Kauf ausblenden` `Beschränkung der Bonus-Features auf Abonnenten` `Und noch mehr!`

**Comment by ksmoore125** [comment]
@thrijith - I have added the German translation to the description

**Comment by ksmoore125** [comment]
@thrijith - This looks good. The only change needed is translating the title in the German version.

**Comment by thrijith** [comment]
@ksmoore125 Updated translation and fixed width issue with feature box.

**Comment by thrijith** [comment]
Added in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
