### ISSUE TITLE
Membership Release Notification

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1242]
**English**
**Version 2.6.2 Highlights:** Create an ad-free experience & much more with our newest shortcode. Check out the "Dynamic Access"  section on the Advanced tab or [click here](url) for more details. [`Learn More`](https://wordpress.org/plugins/laterpay/#developers)

**German**
**Version 2.6.2 Highlights:** Erstellen Sie ein werbefreies Erlebnis und vieles mehr mit unserem neuesten Shortcode. Besuchen Sie den Abschnitt “Dynamischer Zugriff” auf der Registerkarte “Erweitert” oder klicken Sie hier für weitere Informationen. [`Erfahren Sie mehr`](https://wordpress.org/plugins/laterpay/#developers)

**Comment by ksmoore125** [comment]
@thrijith - I have added the German translation to the description

**Comment by thrijith** [comment]
Added in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
