### ISSUE TITLE
Edit Post Pricing Bugs / Enhancements

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1246]
Minor updates related to #1222 

# Global Default Price = FREE
- On Pricing tab, change pricing from `Individual Article Default Price` to `FREE`

**Observed Result**
On the Edit Post Page: The old individual article default price is displayed:
![image](https://user-images.githubusercontent.com/41650164/61653916-fd7b0500-ac80-11e9-93a9-572049857e79.png)

**Desired Result**
- Display the "FREE" message to the right of the `Global Default Price` option when it is selected
![image](https://user-images.githubusercontent.com/41650164/61656005-58aef680-ac85-11e9-979a-6adacb944119.png)
- Display "FREE" when the `Global Default Price` is not selected
![image](https://user-images.githubusercontent.com/41650164/61656025-64022200-ac85-11e9-878b-ca0883ad5155.png)
- Only show "Time Pass & Subscription Offers Hidden" message when `Make Article Free` is selected
- When the Global Default Price = FREE, disable `Make Article Free` and display the following tooltip

English | German
-- | --
In order to make this article free, simply select the "Global Default Price" option above. | Um diesen Artikel kostenlos zu machen, wählen Sie einfach die Option “Globaler Standardpreis” oben.

 

# Unable to Assign Singe Article Price
- On Pricing tab, set an `Individual Article Default Price`
- Navigate to the Edit Post Page
- Select `Individual Price`

**Observed Result**
The text box to enter the individual post price is missing (even after refreshing the page)
![image](https://user-images.githubusercontent.com/41650164/61654387-eee11d80-ac81-11e9-9ed7-908b21c678ff.png)

**Desired Result**
The text box to enter the individual post price should be displayed any time `Individual Price` is selected (as shown below)
![image](https://user-images.githubusercontent.com/41650164/61654594-6151fd80-ac82-11e9-8c58-0b5d19c07217.png)

**Comment by thrijith** [comment]
@ksmoore125 I tried adding the message on the side but it didn't work as expected, it would need more changes as the display and hide are set on multiple actions in pricing switch. Let me know if that's needed or just `Display "FREE"`

- What should be done when individual purchases are disabled?
![Screenshot 2019-07-23 at 4 57 18 PM](https://user-images.githubusercontent.com/13589980/61708685-021be800-ad6b-11e9-814d-eb32919f96f9.png)

- Fixed the edit box problem

**Comment by ksmoore125** [comment]
@thrijith - See my responses below:

> I tried adding the message on the side but it didn't work as expected
Could we add that message in a tooltip?

> What should be done when individual purchases are disabled?
Continue to display the existing message at the top & disable all options

**Comment by thrijith** [comment]
@ksmoore125  changes deployed to staging env.

**Comment by thrijith** [comment]
Fixed in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
