### ISSUE TITLE
Remove Contributions from Advanced Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1249]
# User Story
As a LaterPay merchant, I don't want irrelevant information cluttering my plugin.

# Acceptance Criteria
- Remove Contributions section (shown below) from Advanced Tab

![image](https://user-images.githubusercontent.com/41650164/61811351-ee25c400-ae06-11e9-87d0-4414e22e6acb.png)

**Comment by thrijith** [comment]
Fixed in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
