### ISSUE TITLE
GDPR Compliance Enhancement

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1251]
# Description
As part of GDPR, LaterPay needs to allow merchants to delete their accounts. 
**How does this affect the WordPress Plugin?**
We need to ensure that when a merchant deactivates their LaterPay Account, that the plugin functions properly.

See discussion [here](https://laterpay.slack.com/archives/C02JCERA4/p1563809776017800).

# User Story
As a former, now deactivated, LaterPay merchant, I would like for the LaterPay plugin to deactivate as well so that my users do not get errors each time they try to purchase or access previously purchased content.

# Acceptance Criteria
Without noticeably slow the process,

- When purchase links are generated, check the merchant status
- If merchant account is deactivated, switch plugin to Test mode

_**Note:** This will make all content free however, if the merchant is deactivated, users will not be able to purchase content. Therefore free content is the preferred UX._

**Comment by ksmoore125** [comment]
This does not seem to be working as expected, below are the steps that I took while testing:

1. Open a sample post in an incognito window
2. Click the purchase link and observe that it proceeds to the purchase flow 
3. Navigate back to the article (without purchasing)
4. In LaterPay backend, deactivate my merchant account
5. Refresh the page & click with purchase link

**Expected Result:**
The article would be free

**Observed Result:**
The article is not free & when I click the purchase link, I get a 404 error

**Comment by ksmoore125** [comment]
The above behavior was due to caching on our wp-engine site. The behavior works as expected on non-cached sites.

**Comment by thrijith** [comment]
Released in [v2.6.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.3)
