### ISSUE TITLE
Add Contributions Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1252]
# User Story
As a LaterPay WordPress merchant, I want all of the features of LaterPay available within the WordPress plugin so that I do not have to go back and forth between the LaterPay site and WordPress.

# Acceptance Criteria
- Add a `Contributions` / `German pending` tab (between Appearance & Pricing)
- Sidebar content should be as follows:

English | German
-- | --
TIPS & TRICKS | TIPPS & TRICKS
Setting up your site can be overwhelming so here are a few tips from the experts at LaterPay to help you determine where to place your contributions request. | ?
 **Option 1: At the end of your posts**| ?
Users who reach the end of an article, video or interactive experience are much more likely to pay you for your hard work. | ?
**Option 2: In the header or sidebar** | ?
The primary benefit of placing the contributions shortcode in your site header or sidebar is that you can copy and paste it once in your theme and it will be displayed throughout your site. | ?
**Option 3: In a popup** | ?
If you want to provide multiple contribution options without cluttering your site, one common solution is to add a button to your header or sidebar which will trigger a popup containing the LaterPay contributions shortcode. This option is a bit more involved than the others so [click here for detailed instructions](url). | ?
Existing FAQs section | "
Existing Support section | "
Additionally, please update the Appearance tab `Advanced Settings` to TIPS & TRICKS for consistency | TIPPS & TRICKS

![image](https://user-images.githubusercontent.com/41650164/63201788-55bce100-c04c-11e9-9aab-48742aa7d75e.png)

**Comment by thrijith** [comment]
@ksmoore125 points after `Option 3` are supposed to be added in the list or after the list, shouldn't they link to something or have more information? Please check the following image and let me know, if the sidebar content is not as intended.

![Screenshot 2019-08-28 at 7 15 31 PM](https://user-images.githubusercontent.com/13589980/63861286-3e74e080-c9c8-11e9-97a6-c991cb49152f.png)

**Comment by ksmoore125** [comment]
@thrijith - This is no longer needed with the new design; sorry for the extra work!
