### ISSUE TITLE
Add Google Analytics Events to Track Usage of Contributions within Plugin

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1253]
# User Story
As a LaterPay employee, I want to be able to understand what features are being used and how they are being used within the plugin so that I can make informed decisions about future projects and enhancements to existing features.

# Acceptance Criteria
When a merchant clicks to `Copy Shortcode` trigger the following events

GA Event Category | GA Event Action | GA Event Label | GA Event Value
-- | -- | -- | --
LP WP Contributions | Contribution Options | `merchant ID` | `count of amounts`
LP WP Contributions | Custom contribution amount | `merchant ID` | bit

**Comment by thrijith** [comment]
@ksmoore125 for `count of amounts` if custom amount is enabled and has amount should it be `+1`?

**Comment by ksmoore125** [comment]
@thrijith - I assume that would be difficult to make this to where it chooses between Pay Now & Pay Later automatically behind the scenes. Therefore we should make it > $1.99/1.49€ Pay Now.

Let me know if my assumption is incorrect and I will think about it a bit more.

**Comment by thrijith** [comment]
I meant to ask, what should be the value that would go into `count of amounts` in the end? Is it number of different amounts configured in the shortcode?

**Comment by ksmoore125** [comment]
@thrijith sorry I should have looked at the ticket to get the full context. It is the count of the different amount configured but let's not add one for the custom that way

`Contribution Options` + `Custom contribution amount` = total number of options
