### ISSUE TITLE
Allow for Contributions Inside the WordPress Plugin

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1254]
# User Story
As a LaterPay WordPress merchant, I want all of the features of LaterPay available within the WordPress plugin so that I do not have to go back and forth between the LaterPay site and WordPress.

# Acceptance Criteria
- Merchant should have the ability to generate a:
  - Contributions button (#1299) or 
  - Dialog with multiple amounts (#1300)
- Merchant should be able to preview their contributions dialog (see also #1274) 
- Finally, the merchants should be able to easily generate the shortcode & copy it to the clipboard for use in WordPress (see also #1275) 

**Global Configuration Options**

English | German | Notes
-- | -- | --
Campaign name | Name des Rechnungspostens | 
Contributions for... | Spenden für... | Campaign name default value
Enter the name you would like to appear on your customers’ invoice. We recommend including your organization’s name as well as something to remind them of this specific contribution. | `Geben Sie die Beschreibung ein, die auf der Rechnung Ihrer Kunden erscheinen soll. Wir empfehlen Ihnen, den Namen Ihrer Organisation anzugeben und etwas, das sie an diese individuelle Spende erinnert.` | Campaign name tooltip
Thank you page (optional) | Dankeschön-Seite (optional) | 
http://www... | http://www... | Thank you page default value
Optional. After the button is clicked, we can redirect the visitor to a page of your choice (for example, a dedicated "thank you" page on your website). | _Optional._ Nachdem der Button geklickt wurde, können wir den Besucher auf eine Seite Ihrer Wahl (beispielsweise eine dedizierte "Dankeschön-Seite" auf Ihrer Website) weiterleiten. | Thank you page tooltip
Amount | Betrag | Pay Now vs Pay Later selection should follow the standard validation rules
Show multiple contribution amounts | Mehrere Contribution-Beträge anzeigen | If unchecked: #1299 If checked (default): #1300
Use this checkbox to toggle between a contributions button which allows one static contribution amount or a dialog which allows users to choose between several contribution amounts. | Verwenden Sie dieses Kontrollkästchen, um zwischen einem Contribution-Button, der einen fixen Betrag erlaubt, und einem Dialog, der es dem Benutzer ermöglicht, zwischen mehreren Contributions-Beträgen zu wählen, umzuschalten. | Show multiple contribution amounts  tooltip
Allow custom contribution amount | Benutzerdefinierten Contribution-Betrag erlauben | Should be disabled unless `Show multiple contribution amounts` is checked (see #1300); checked by default
Only available if "Show multiple contribution amounts" is checked, this feature will add an input box to your contribution dialog allowing users to contribute custom amounts. | Nur verfügbar, wenn “Mehrere Contributions-Beträge anzeigen” aktiviert ist. Ihrem Contributions-Dialog wird ein Eingabefeld hinzugefügt, in dem Nutzer benutzerdefinierte Beträge eingeben können. | Allow custom contribution amount tooltip

# Mockup
Note, we can use our standard tooltip icon, no need to customize it to match the below mockup
![image](https://user-images.githubusercontent.com/41650164/65279240-64872f80-daf3-11e9-8161-a18834edea26.png)

# Technical Documentation
https://docs.laterpay.net/platform/dialogs/contributions/quick_start/ 
https://jsfiddle.net/4wezut02/2/

**Comment by ksmoore125** [comment]
@thrijith - The translation for amount is currently "Beitragsbetrag" is should be "Betrag"
![image](https://user-images.githubusercontent.com/41650164/67306138-1a131d00-f4bc-11e9-958a-e118dd926032.png)

**Comment by thrijith** [comment]
@ksmoore125 The English text is `Contribution Amount` in mockup and just `Amount` in the issue description, which one should be used?
