### ISSUE TITLE
Minor Fix: Update Dashboard Picture

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1256]
Navigate to the Advanced Tab & note that the image for Analytics appears stretched
![image](https://user-images.githubusercontent.com/41650164/61818186-ea4d6e00-ae15-11e9-8390-e61fd2aae0fc.png)

Please update so that is it no longer out of proportion
![image](https://user-images.githubusercontent.com/41650164/61818236-0a7d2d00-ae16-11e9-85a4-b1a248c971af.png)

This can be achieved by updating the dimensions or removing either the fixed height or width, etc

**Comment by thrijith** [comment]
Fixed in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
