### ISSUE TITLE
German Translation Audit Part 2

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1260]
# Description
In #1230 we performed an audit of the translations within the plugin however, this was not complete. In order to complete the project we need to audit the following places as well

# Acceptance Criteria
Audit & update translations in the following areas:

- [x] Contextual Help
- [x] Settings > LaterPay page
- [x] Grey sidebar area on each tab

**Comment by ksmoore125** [comment]
Translations can be found [here](https://docs.google.com/document/d/17mJYdpy_-fj8TS5uTWVL4Rw101sD8W9rzCiP3ohciEI/edit?usp=sharing)

**Comment by thrijith** [comment]
@ksmoore125 

For pricing tab help, can you verify translations of `Individual Article Price` and keep the text format same as in english version ( e.g Global default price )

Missing translations for following sections

Pricing Tab
- Time Passes
- Subscriptions
- Voucher

Appearance Tab
- Customize Colors

**Comment by thrijith** [comment]
Here is the screenshot for time pass section in Pricing Tab, same goes for subscription and voucher section.

![timepasses](https://user-images.githubusercontent.com/13589980/64876985-0fb86480-d66e-11e9-94c4-e38b0acae9d0.png)

Appearance Tab

![appearance](https://user-images.githubusercontent.com/13589980/64877001-1c3cbd00-d66e-11e9-9a5f-17149a617d7c.png)

**Comment by thrijith** [comment]
Updated in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
