### ISSUE TITLE
Feature Request: Allow for Secure Download Widget Content Type = link

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1262]
# User Story
As a LaterPay WordPress plugin user, I would like to allow for a similar functionality to the secure download widget however, instead of the large box, I would like to be able to display a URL so that it will not take up so much vertical space on my site.

# Notes
This functionality has been requested from a new potential partner. We were able to create a prototype of the behavior they want [here](http://kimberlystestsite.cloudaccess.host/?p=321). However they would like the site to look the same as it does today (where the red text is a link to download):
![image](https://user-images.githubusercontent.com/41650164/62154310-0cd6ff80-b2cc-11e9-9da5-84b2b957aed9.png)

# Acceptance Criteria 
Update the existing secure download link shortcode to:

- Allow for `content_type = "link"`
- In this scenario the `title` & `description` would be the link text as shown in the following example

`[laterpay_premium_download`
`target_post_id="138"`
`heading_text="The Secure Download Widget"`
`description_text="How to Charge for Downloadable Content in the LaterPay WordPress Plugin"`
`content_type="link"]`

[The Secure Download Widget - How to Charge for Downloadable Content in the LaterPay WordPress Plugin](https://www.laterpay.net/academy/how-to-charge-for-downloadable-content-in-the-laterpay-wordpress-plugin)

**Comment by thrijith** [comment]
@ksmoore125 Just to be clear, if content_type is set to link, then just a link would be shown which links to a paid article? 

Where should the targeted post/price be shown? or will user be just redirected to the targeted article?

**Comment by ksmoore125** [comment]
> Just to be clear, if content_type is set to link, then just a link would be shown which links to a paid article?

Correct

> Where should the targeted post/price be shown?

We will not display the price, if the merchant would like the price to be shown, they can include this in the `heading_text` or `description_text`

> Will user be just redirected to the targeted article?

When the user clicks the link, it will be the same flow as the current download widget as described below

1) Click link
2) If the article is not free: Redirected to the payment flow
     If the article is free: Skip this step
3) After payment complete, redirected to article & the content downloads

**Comment by thrijith** [comment]
Added in [v2.6.2](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.2)
