### ISSUE TITLE
Home Page Query Performance Improvements

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1270]
# Background
One of our merchants has reported performance issues on their home page. It has been determined that this due to the fact that they are using `the_posts` and `the_content` to embed snippets of their paid content on their home page. By using these hooks to display portions of paid content, it is triggering LaterPay's queries.

# Acceptance Criteria
In order to prevent this unnecessary queries from being run, 
when LaterPay is disabled for `Pages`, 
we should detect that the main call originated from a page and then for each nested post, immediately exit out of the query and not run it

**Comment by ksmoore125** [comment]
I installed the plugin on my site and it still appears that queries are being run. 
**Steps to Reproduce**
- Deactivate LaterPay plugin
- Ensure Query Monitor is active
- Navigate to Home page
- Note that 39 queries are run and that page load time is 0.0616 sec
- Activate LaterPay plugin
- Navigate to Settings > LaterPay and ensure that is checked
- Navigate to Home page

**Observed Result**
- 56 queries are run and the page takes 0.3092 sec to load
**Desired Result**
- The page load time should resemble that of when the LaterPay plugin is disabled (0.0616 sec)

**Comment by thrijith** [comment]
I am unable to replicate issue mentioned above, could you please give me access to the site where the plugin is active with the new setting? Please refer [this](https://drive.google.com/open?id=1iURQeaI94dnud0t7MV7T9d8o1dH5R7qq) to verify the change.

Also note we have to verify queries fired by plugin using `Queries by Component` tab, page load time is not constant.

**Comment by ksmoore125** [comment]
@thrijith - I tested [here](http://kimberlystestsite.cloudaccess.host) which you already have access to. Let me know if you need anything else!

**Comment by thrijith** [comment]
Released in [v2.6.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.3)
