### ISSUE TITLE
Post Pricing FireFox Display Issue

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1272]
Der Bank Blog reported that they are unable to see the category prices in v2.6.1 using the most recent version of FireFox
![image](https://user-images.githubusercontent.com/41650164/62796682-6ba43200-ba9f-11e9-88e9-66b77fd1186e.png)

I have been unable to replicate their issue but did experience another display issue
![image](https://user-images.githubusercontent.com/41650164/62796733-8676a680-ba9f-11e9-8873-27ad724d4fee.png)

We have asked them to update to v2.6.2 since there were related enhancements and to also enable Wisdom so that we can gather additional details on their WordPress setup

**Comment by ksmoore125** [comment]
@thrijith - In case it helps, Der Bank Blog let us know that the price is displayed after saving, they just cannot see it before saving.

**Comment by thrijith** [comment]
@ksmoore125 Fixed the category display issue. Could you verify the revenue model UI issue in Firefox?

**Comment by thrijith** [comment]
Fixed in [v2.6.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.3)
