### ISSUE TITLE
Lower Pay Now limit so that it is >=$1.99 / 1.49€

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1276]
Currently the validation appears to limit Pay Now to > $1.99 / 1.49€ 
This should be updated to >**=**$1.99 / 1.49€

**Comment by thrijith** [comment]
Added in 3931d17e5006aa57091a6d7ec573fe1de705d0ff

**Comment by thrijith** [comment]
Fixed in [v2.6.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.3)
