### ISSUE TITLE
Dynamic Pricing: Extended "Days"Functionality

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1284]
# User Story
As a LaterPay merchant, I would like to be able to extend the dynamic pricing capability for longer 1 year.
See conversation [here](https://laterpay.slack.com/archives/CGA4Y3H08/p1567183082006300) for context.

# Acceptance Criteria

- ~~Add similar functionality to pricing so that the user can double click on the days item & type the number of days~~
- Allow for days up to 366 days

**Comment by thrijith** [comment]
Added in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
