### ISSUE TITLE
Update Title of Pricing Tab

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1286]
# User Story
As a new LaterPay merchant, I may be confused between "Contributions" and "Pricing;" I would like the difference between these tabs to be made clear so that I can get my site set up and quickly and easily as possible.

# Acceptance Criteria
- Change the `Pricing` tab to `Paywall`
- Kimberly to update all corresponding documentation
  - https://www.laterpay.net/academy/wordpress-pricing
  - https://www.laterpay.net/academy/how-to-create-a-subscription-button-in-the-laterpay-wordpress-plugin
  - https://www.laterpay.net/academy/how-to-charge-for-downloadable-content-in-the-laterpay-wordpress-plugin
  - https://www.laterpay.net/academy/getting-started-with-the-laterpay-wordpress-plugin

**Comment by thrijith** [comment]
@ksmoore125 Do you just want the Tab text to be update? Do you want me to update the url and any other reference as well?

**Comment by ksmoore125** [comment]
- Leave the url in case people have it bookmarked
- The sidebar should be updated
- I went through the plugin and checked for mentions of the "Pricing Tab" and could not find any so I do not believe that there are any other references which need to be updated but please let me know if you come across any

**Comment by thrijith** [comment]
> let me know if you come across any

I don't see any references on frontend either, but we have `pricing` in the code, I think that is fine as we are just updating the tab text for now.

**Comment by thrijith** [comment]
This was reverted in https://github.com/laterpay/laterpay-wordpress-plugin/commit/195137885252a1853c42350732e8d35d9fe123fb, so adding back in `To do`
