### ISSUE TITLE
Update Account Tab to Remove Static Checkmarks

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1287]
# User Story
We received the following feedback from a UX designer as they integrated with the plugin:

> Another point of confusion appeared on the LaterPay WordPress settings. At the bottom of the Settings, the section STEP 4 shows a list of checked off items, giving the user the impression that they have completed these items, however, I did not “Adjust the Appearance…” so this should not be checked off. Because it is checked off, I questioned if this was a static list or not.
[Full notes here](https://docs.google.com/document/d/1pw2IqExQGqnh3DL99DRMPGjWs2drVfOStiRa2BEcadY/edit#)

# Acceptance Criteria
**Option 1 (preferred)**
- [ ] <- Doing something like this

**Option 2**
Change to standard bullet points

**Comment by thrijith** [comment]
Updated in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
