### ISSUE TITLE
Disable Account Tab Autoscroll

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1288]
# Steps to Reproduce
- Ensure that you're Merchant ID & API Key on the Account tab are empty
- Navigate to the Account tab
- Note that it will automatically scroll down to this section of the page

# Feedback

> It makes sense to make sure the user is signed up/logged in before they take any further actions, however, showing the user something then immediately scrolling them away from it is disruptive. 
[Full details here](https://docs.google.com/document/d/1pw2IqExQGqnh3DL99DRMPGjWs2drVfOStiRa2BEcadY/edit#)

# Acceptance Criteria
- Remove this functionality

**Comment by thrijith** [comment]
Fixed in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
