### ISSUE TITLE
Display only Time Pass or Subscription on Article

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1297]
# User Story
As a LaterPay merchant, I would like to have a mix of pages that have Time Passes/Subscriptions only and other pages which have Single Article +Time Passes/Subscriptions on them so that I can earn revenue customized to the content.
[Thread here](https://laterpay.slack.com/archives/CGA4Y3H08/p1568362771001100)

# Acceptance Criteria
If the Single Article Price on the Post page is set to 0 then:
- If there are no applicable time passes or subscriptions, the article should be free
- If there are applicable time passes or subscriptions, they should be displayed without a single article price

**Notes:**
Below are a few scenarios:
- Global Default Price = FREE
If the merchant wants the article to be
  -  Completely free: select the global default price
  - Single Article +Time Passes/Subscriptions: set a single article price on the post page
  - Only Time Passes/Subscriptions: today this is not possible, this is what the ticket hopes to address
- Global Default Price = Set to a single article price
If the merchant wants the article to be
  -  Completely free: select this option on the post page
  - Single Article +Time Passes/Subscriptions: this is the default or they can override the price on the post page
  - Only Time Passes/Subscriptions: today this is not possible, this is what the ticket hopes to address

**Comment by thrijith** [comment]
Fixed in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)

**Comment by ksmoore125** [comment]
`Won't Do` - This ticket would conflict with #977
Therefore this user can change the global default price to `0.00` and use the process outlined by #1302 to achieve the same result
