### ISSUE TITLE
Contribution Dialog Configuration

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1300]
# User Story
As a LaterPay WordPress merchant, I want all of the features of LaterPay available within the WordPress plugin so that I do not have to go back and forth between the LaterPay site and WordPress.

# Acceptance Criteria
If `Show multiple contribution amounts` is checked,
- Display the global configuration options as described on #1254 
- Ensure that `Allow custom contribution amount is enabled`
- Display multiple amounts for the merchant to fill in
  - Each amount can be configured between Pay Now & Pay Later (as usual)
  - Two amounts should be displayed by default, once the second amount is filled in, a third box should appear, once the third amount is filled in, a fourth box should appear, when that box is filled in, a fifth box should appear. That is the maximum.
  - If any of the boxes has their amount removed or is left blank, it should disappear from the preview and not be included in the shortcode. Then if they leave the page and return, that box should be gone.
  - By default, the first box should be highlighted. This indicates that it is the option selected by default. If they click the outside of the textbox it will change the highlighting and also the default selection in the preview. _(this is not set in stone; let me know if it is difficult technologically)_
- Button Text: Contribute now | Jetzt spenden
- If `Show multiple contribution amounts` then the default selection should be the amount preserved in the 1 remaining amount field

# Mockup
[Prototype here](https://www.figma.com/proto/EjpsLuinbMUnkZS3ga4MtD/WordPress?node-id=105%3A1&scaling=scale-down)

**Default**
![image](https://user-images.githubusercontent.com/41650164/65284997-d9149b00-db00-11e9-9847-c99168aae41d.png)

**Comment by ksmoore125** [comment]
@thrijith - 

1) For the dialog (both preview & actual), please update the button text to: Button Text: Contribute now | Jetzt spenden

2) We are also missing the following translations:

English | German
-- | --
Support the author | `pending`
How much would you like to contribute? | `pending`
Custom Amount: | `pending`
To include this on your site, click the button below and paste the code where you would like it to appear. | Um dies auf Ihrer Website einzubinden, klicken Sie auf die Schaltfläche unten und fügen Sie den Code an der Stelle ein, an der er erscheinen soll.

**Comment by thrijith** [comment]
@ksmoore125 didn't get this part, can you add a screenshot if possible?

> For the dialog (both preview & actual), please update the button text to: Button Text: Contribute now | Jetzt spenden

**Comment by ksmoore125** [comment]
> Note: The list item is translated properly for the button but is not translated for the dialog.
It is working properly now, please disregard

> For the dialog (both preview & actual), please update the button text to: Button Text: Contribute now | Jetzt spenden

Screenshot | Current | Desired
-- | -- | --
![image](https://user-images.githubusercontent.com/41650164/67314627-a0cef680-f4ca-11e9-8566-6bf83967b17e.png) | Button dynamically updates based on selected amount | Contribute now
![image](https://user-images.githubusercontent.com/41650164/67314682-c65c0000-f4ca-11e9-9359-4647d081f64e.png) | Button dynamically updates based on selected amount | Contribute now
![image](https://user-images.githubusercontent.com/41650164/67314725-d70c7600-f4ca-11e9-9079-b88ea3a0e03b.png) | Button dynamically updates based on selected amount | Jetzt spenden
![image](https://user-images.githubusercontent.com/41650164/67314781-e25fa180-f4ca-11e9-8ad8-f185f5bed0bc.png) | Button dynamically updates based on selected amount | Jetzt spenden
