### ISSUE TITLE
Create New Hook to be Used for Facebook Campaigns Tracking Pixel

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1301]
# User Story
As a LaterPay integrations specialist, I would like to use a hook to display a certain portion of content (a FB pixel) only when the user has performed the purchase (not every time they have access) so that a partner can to measure conversions via FB.

# Acceptance Criteria
See discussion [here](https://laterpay.slack.com/archives/C02JCERA4/p1568913160076000)

Adding a new hook that can be used by merchants to perform custom operations when a user is redirected back after the purchase.
In this case:
- LaterPay Plugin will add a hook
Active Theme of Merchant’s Site
- Will use the hook to create a temporary cookie after purchase.
-  Add a hook in wp_head which will verify if cookie exists and add pixel JS snippet.

**Comment by thrijith** [comment]
Added in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
