### ISSUE TITLE
Individual Article Price not Overriding Global Default

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1302]
**Steps to Reproduce**

1. Navigate to the pricing tab and set up the following configurations
    - Global Default Price: 0.00
    - At least one time pass &/or subscription

2. Navigate to an article & ensure that the article is set to the Global Default Price
    Observe: the paywall shows the time pass &/or subscription ☑️ 

3. Edit the article to assign a Single Article Price
    **Observed Result:** The single article price is not displayed in the paywall ❌ 
    **Desired Result:** The single article price is should be displayed in the paywall

**Comment by blakecrosby** [comment]
Here are some more details:

- 4 time passes are defined, assigned to four different categories.
- Global default price is set to $0.00
- No category default prices are set
- Individual price is set to $8.99 on a page.

Access to the blog is available if required.. Send a private message to @bcrosby on LaterPay slack for login details.

**Comment by thrijith** [comment]
Fixed in [v2.6.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.4)
