### ISSUE TITLE
Add Subscription Button to the Visual Editor

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1307]
# User Story
As a LaterPay WordPress plugin user, I would like to be able to easily add a subscription/time pass button shortcode to my site without having to leave the visual editor.

# Acceptance Criteria
The following functionality should work similarly to what is shown [here](https://rtmedia.io/docs/addons/shortcode-generator/rtmedia-gallery-block/)
- Add Insert Subscription Button option to the visual editor
- On insert, insert appropriate shortcode
- Allow merchant to configure:
  - Subscription ID/Time Pass ID (required)
  - Button Color
  - Button Text
  - Text Color

**Comment by ksmoore125** [comment]
**Notes from initial testing:**

- Please update "TimePass" to "Time Pass" in both instances
- Merchants unfamiliar with the existing shortcode likely will not know where to get the Time Pass or Subscription ID. Could we do something like the following? (if option 2 is preferable let me know and I will write the tooltip text)

![image](https://user-images.githubusercontent.com/41650164/68970010-ed48e180-07ab-11ea-91dd-af91f08bd0c3.png)

**Comment by ksmoore125** [comment]
Here are updates based on details provided in [this slack comment](https://rtcamp.slack.com/archives/GA2P84GBZ/p1574070741001100?thread_ts=1574070353.001000&cid=GA2P84GBZ)

Please proceed with "Option 2" - Adding a tooltip. Tooltip text should read as follows:
> To find the Time Pass or Subscription ID, navigate to the Paywall tab. The ID is the number located to the left of the Time Pass or Subscription.

**Comment by thrijith** [comment]
Added in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
