### ISSUE TITLE
Add Dynamic Access to the Visual Editor

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1311]
# User Story
As a LaterPay WordPress plugin user, I would like to be able to easily add dynamic access functionality to my site without having to leave the visual editor.

# Acceptance Criteria
The following functionality should work similarly to what is shown [here](https://rtmedia.io/docs/addons/shortcode-generator/rtmedia-gallery-block/)
- Add Insert Dynamic Access option to the visual editor
- On insert, allow the merchant to insert the content that they want to hide into the Dynamic Access block
- Allow them to configure the time pass(es) &/or subscription(s) which should control the access

**Comment by ksmoore125** [comment]
**Notes from initial testing:**
This block's behavior could be a bit confusing to merchants unfamiliar with the shortcode. In order to help clarify, please make the following changes:

- Add the following intro paragraph:
_Use this block to show or hide the content in the block based on which LaterPay product the user has purchased._
- Adjust the Access behavior options to:
  - Show contents after purchase
  - Hide contents after purchase
- Update `TimePass` to `Time Pass` (also in error message)
- Adjust the options to add one additional dropdown:
_Purchase requirement_
  - _Any purchase_
  - _Specific Time Passes or Subscriptions_
- If "Any purchase" is selected then the existing `Time Passes to select` & `Subscriptions to select` drop downs should be hidden
- If they select to show a specific time pass or subscription see the question on #1307 - We should help guide them so they know how to get the ID

**Mockup**
![image](https://user-images.githubusercontent.com/41650164/68973657-76641680-07b4-11ea-8b75-0824c5af9d01.png)

**Comment by ksmoore125** [comment]
@thrijith here are the final changes:
- Remove "Show/Hide content based on User access" message now that the radio option are more clear
- Update the intro paragraph to the following:
> Use this block to show or hide the content in the block based on which LaterPay product the user has purchased.
**IMPORTANT:** This should not be used to hide the content you would like behind the paywall. That will be done automatically once you have set a price for this article.

**Comment by thrijith** [comment]
Added in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
