### ISSUE TITLE
Add Downloadable Content to the Visual Editor

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1312]
# User Story
As a LaterPay WordPress plugin user, I would like to be able to easily add a downloadable content shortcode to my site without having to leave the visual editor.

# Acceptance Criteria
The following functionality should work similarly to what is shown [here](https://rtmedia.io/docs/addons/shortcode-generator/rtmedia-gallery-block/)
- Add Insert Downloadable Content option to the visual editor
- On insert, insert appropriate shortcode
- Allow merchant to configure:
  - Select the downloadable content (Media)
  - Set the price for the content if it is not already set ⚠️ _Is this possible?_
  - Heading text (optional)
  - Description text (optional)
  - Content type (optional)
  - Tease image (optional)

**Comment by ksmoore125** [comment]
**Notes from initial testing:**

- Need Content Type for `link` (#1262 )
- Where do I set the price?
_Could we do something like the following?_
![image](https://user-images.githubusercontent.com/41650164/68968588-91308e00-07a8-11ea-9697-108e448efe84.png)

**Comment by thrijith** [comment]
> Where do I set the price?

@ksmoore125 Adding price would require change to existing Shortcode setup as well, the current shown price is the price set in **Global Default Price**. Please let me know if I should proceed with changes to include price in Premium Download Shortcode.

**Comment by thrijith** [comment]
Added in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
