### ISSUE TITLE
Add Contribution Button to the Visual Editor

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1313]
# User Story
As a LaterPay WordPress plugin user, I would like to be able to easily add a contributions shortcode to my site without having to leave the visual editor.

# Acceptance Criteria
The following functionality should work similarly to what is shown [here](https://rtmedia.io/docs/addons/shortcode-generator/rtmedia-gallery-block/)
- Add Insert Contribution Button option to the visual editor
- On insert, insert appropriate shortcode
- Allow merchant to configure: _(similar functionality to what is described in #1300 )_
  - Campaign Name
  - Thank you page (optional)
  - Show multiple contribution amounts
     - If checked, Allow custom contribution amount
  - Amount(s)

**Comment by ksmoore125** [comment]
**Notes from initial testing:**

- When the amount is set to 1.99 (for single amount or one of the multiple amounts), it will not let me select "pay now"
- Please change `Revenue` to `Revenue Model`

**Comment by ksmoore125** [comment]
@thrijith here are the final changes:
- Please change `Revenue` to `Revenue Model` (it looks like this change was only done for Amount 5, please make this change for Amounts 1-4 & the single amount)
- For multiple amounts, instead of defaulting all options to 0.00, please set the defaults to:
  - 1 Pay Later
  - 2 Pay Later
  - 5 Pay Now
  - Option 3 selected by default
  - Custom Amount enabled

![image](https://user-images.githubusercontent.com/41650164/69273779-a2114300-0b9e-11ea-9ce9-6dd069fbe100.png)

**Comment by thrijith** [comment]
Added in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
