### ISSUE TITLE
Make All User Roles Available to Unlimited Access Section

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1317]
# User Story
As a LaterPay WordPress Plugin merchant who already has a different subscription platform, I would like to be able to give unlimited access to users in the "Subscriber" role so that they can get free access to content as a subscriber would expect and as a merchant, I do not have to make any changes to my WordPress set up.

# Acceptance Criteria
- Add all WordPress default user roles (except Administrator) to the Settings > LaterPay > Access > Unlimited Access section.

**Comment by thrijith** [comment]
Added in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
