### ISSUE TITLE
Minor Translation Update to Contributions Tooltip

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1325]
Replace `Spende` with `Beitragszahlung` in the following tooltip:
![image](https://user-images.githubusercontent.com/41650164/67845769-566bfc00-fb00-11e9-8eba-ad162434fed5.png)

**Comment by thrijith** [comment]
Updated in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
