### ISSUE TITLE
Update Plugin Tags

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1327]
**Description**
We discovered that our tags were not working properly because we exceeded the 12-tag limit as [defined here](https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/) therefore we need to update our tags.

**Acceptance Criteria**
_Update our tags to the following:_
Contribution
Conversion
Earn Money
Micropayment
Monetization
Monetize Content
Paid Content
Payment
Paywall
Sell Article
Sell Content
Subscription

**Comment by thrijith** [comment]
Updated in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
