### ISSUE TITLE
Dynamic Button Text Not Updating Properly

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1330]
# Example 1
Default value appears to think it is the single article
**Steps to Reproduce**
- Navigate [here](https://www.epochtimes.de/politik/welt/usa-verschaerfen-strafzoelle-gegen-china-trump-kann-ausnutzung-der-usa-nicht-laenger-zulassen-a2979688.html)

**Observed Result**
The button says `Jetzt kaufen, später zahlen` aka "Read Now, Pay Later"

**Desired Result**
Button should read `Jetzt abonnieren` aka "Subscribe now"

**Additional Notes**
- If you click on another radio button and then back to the original option, it does display "Subscribe now" as expected

# Example 2
Default value appears to think it is a subscription
**Steps to Reproduce**
- Navigate [here](https://jamesstrauss.com/first-ten-days-30-days-has-september-audiobook/)

**Observed Result**
The button says `Subscribe Now`

**Desired Result**
Button should read `Buy Now`

**Additional Notes**
- If you click the pricing option, it does display "Buy Now" as expected
- Pricing set up shown below
![image](https://user-images.githubusercontent.com/41650164/69179911-f39fcc00-0ad1-11ea-87ef-f652cc452af6.png)

**Comment by thrijith** [comment]
Fixed in [v2.8.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.8.0)
