### ISSUE TITLE
Allow for links in custom purchase options

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1341]
# Description
Earlier this year we added support for custom purchase options. This allows a merchant to add an option to the paywall which will link to (for example) their own subscription offer outside of LaterPay. We have one merchant who has implemented this inside WordPress. In their purchase option description, they have included a link. However, because the entire purchase option is clickable to select the radio button, this link does not function properly.

![image](https://user-images.githubusercontent.com/41650164/70085915-d4776300-15d6-11ea-8e2f-e3a7709726de.png)

# Acceptance Criteria
Update the paywall so that links in the purchase option description can be clicked.

# Technical Details

> **Eric Larsen**
Somewhere in the code we have e.preventDefault(); being called which stops the anchor tag from firing.

**Comment by thrijith** [comment]
@ksmoore125 Fix has been added to staging site, you may test it on [this](http://lpwptestprod.wpengine.com/2019/05/07/sample-post-with-links/) post.

**Comment by thrijith** [comment]
Fixed in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
