### ISSUE TITLE
Premium Download Support in Classic Editor

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1343]
# Description
In v2.8.0 we added support for the Premium Download shortcode in the visual editor for users using WordPress Blocks. However, we have several merchants who still utilize the classic view and would like to experience the ease of use provided in our new block.

# Acceptance Criteria
Allow users using the WordPress Classic editor to generate a Premium Download shortcode without leaving the editor (to find the media ID etc).

**Comment by ksmoore125** [comment]
@thrijith - Please make the following updates to this feature:

- Instead of asking for the media's Post ID & Title, allow the merchant to select the Media
  - Update `Post ID` to `Premium Content`
  - Update the PostID text box to a button which reads `Select Downloadable Media`
  - Remove the Post Title label & text box
- Update `Heading Title` to `Heading Text`
- Update `Description text` to `Description Text` 
- Update `Teaser Image Path` to `Custom Image`
- Update `Select Media` to `Select Teaser Image (optional)`

**Mockup**
![image](https://user-images.githubusercontent.com/41650164/70445743-9c9e6e80-1a61-11ea-937d-fe108fd2e746.png)

**Comment by ksmoore125** [comment]
@thrijith - This looks good! Can we make the following change to make it a bit less confusing for new users?

**For both the subscription & the time pass modal please:**
- Ensure all labels have the first letter of each word capitalized
- Update the modal as follows to ensure that it is clear that they should select an image **or** customize the button

**Mockup**
![image](https://user-images.githubusercontent.com/41650164/70446919-78439180-1a63-11ea-9392-19b2caff00f4.png)

**Comment by ksmoore125** [comment]
This is looking great! Just a couple items around the Custom Image / Image Preview; would it be possible to:

- If the Content Type is changed (ie: to Audio) could the image preview change appropriately?
  - If not, could the image preview be hidden unless a custom image is selected?
_Either option is acceptable so please proceed with whichever is simpler_

- Once a Downloadable Media is selected, please show the file name (in case there is no preview available) so that the merchant can know that the media was selected properly (one potential solution shown below)

- Please add a way to clear the custom image (one potential solution shown below)

![image](https://user-images.githubusercontent.com/41650164/70547698-f0c75280-1b36-11ea-9b72-58dce3af2744.png)

**Comment by thrijith** [comment]
Added in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
