### ISSUE TITLE
Purchase Button Support in Classic Editor

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1344]
# Description
In v2.8.0 we added support for the LaterPay Purchase Button shortcode in the visual editor for users using WordPress Blocks. However, we have several merchants who still utilize the classic view and would like to experience the ease of use provided in our new block.

# Acceptance Criteria
Allow users using the WordPress Classic editor to generate a LaterPay Purchase Button shortcode without leaving the editor. The primary benefit of this is to make the feature more visible to our merchants; currently it is a hidden feature.

**Comment by ksmoore125** [comment]
_Moving from where I put this on the wrong ticket_

@thrijith - This looks good! Can we make the following change to make it a bit less confusing for new users?

**For both the subscription & the time pass modal please:**
- Ensure all labels have the first letter of each word capitalized
- Update the modal as follows to ensure that it is clear that they should select an image **or** customize the button

**Mockup**
![image](https://user-images.githubusercontent.com/41650164/70446919-78439180-1a63-11ea-9392-19b2caff00f4.png)

**Comment by ksmoore125** [comment]
Similar to the comment [here](https://github.com/laterpay/laterpay-wordpress-plugin/issues/1343#issuecomment-564112902): 
- Please add a way to Clear the custom image if it has been selected
- Please also hide the preview if a custom image has not been selected

**Comment by thrijith** [comment]
Added in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
