### ISSUE TITLE
Update Voucher Shortcode to include Subscriptions

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1348]
# User Story
[Discussion here](https://laterpay.slack.com/archives/C02JCERA4/p1575983603424200)

# Acceptance Criteria
Update existing voucher shortcode to allow for subscriptions. Parameters should include:
- `type` (timepass or subscription; default = timepass)
- `id` (numeric ID of the time pass or subscription)
- Ensure that shortcode functions properly when there is more than one voucher code available to be used on an article

**Comment by thrijith** [comment]
> On my test site (here) the display looks off; is that just my site configuration or is it something which needs to be resolved?

`Preformatted` formatting was used which lead to above issue, I have updated the post, please check again and let me know if you have any concerns. Thanks.

**Comment by thrijith** [comment]
> When configured for a subscription, the voucher still reads "Validity: 1 Month" & "Renewal: No automatic renewal" On standard subscription vouchers this is not the case; does this function differently or should we update the language?

Yes the language should be updated for Subscription.

For example in case of 1 Month Subscription

```
Validity: 1 Month Subscription (Renews in a month, cancellable anytime)
Renewal: Automatically renewed.
```


Please let me know if this is ok.

**Comment by thrijith** [comment]
Added in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
