### ISSUE TITLE
Resolve Minor Errors in Voucher Shortcode

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1350]
## Issue 1
> if an id for time pass is added in the shortcode but a subscription voucher is used for redeeming, the purchase will be for subscription instead of time pass which

**Solution:** Display error message (below)

## Issue 2
> when a user enters an invalid coupon code, it doesn't show error messages and just remove coupon code from text box

**Solution:** Display error message (below)

## Error Message Text
**English**
Please enter a valid voucher code.

**German**
Bitte geben Sie einen gültigen Gutscheincode ein.

**Comment by thrijith** [comment]
@ksmoore125 

On further testing, it seems the error is displayed, but not in certain cases, so we won't need the new message at the moment. 

This is the current message, **VOUCHER_CODE** + `is not a valid voucher code!`, **VOUCHER_CODE** being the code user used for redeeming.
