### ISSUE TITLE
Contributions UX Improvements

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1354]
# User Story
As a LaterPay merchant, I would like to be able to customize my contributions ask so that it request fits in with my site's messaging.

# Acceptance Criteria
The below features should be available on the Contributions tab as well as in the Contributions block:
- Allow merchant to customize the contribution dialog header
- Allow merchant to customize the contribution dialog description
- These options should only be displayed if `Show multiple contribution amounts = checked`

. | English | German
-- | -- | --
**Input Label** | Dialog Header | Dialog-Titel
**Default Value** | Support the author | Unterstützen Sie den Autor
**Input Label** | Dialog Description | Dialog-Beschreibungstext
**Default Value** | How much would you like to contribute? | Wie viel möchten Sie als Contribution (freiwillige Beitragszahlung) beitragen?

**Comment by thrijith** [comment]
Updated in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
