### ISSUE TITLE
Make WP Plugin Function with LaterPay Connector Script

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1355]
[Context here](https://laterpay.slack.com/archives/C02JCERA4/p1576172121009900?thread_ts=1576146095.493100&cid=C02JCERA4)

> - LaterPay WordPress plugin handles any redirect on a site when active, this is done to handle purchase redirects.
> - When user is redirected from LaterPay Connector / Valid Purchase etc it has lptoken in the request
> - WordPress plugin verifies the token for validity, when user is redirected after purchase done via LaterPay Connector, the verification fails and user is not redirected as expected.
> - The request has _lpc_ad in the params, which can be used to identify if the response was set by LaterPay Connector
> - We will check existence of the param and avoid the verification to fix conflict

**Comment by thrijith** [comment]
Fixed in [v2.9.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.0)
