### ISSUE TITLE
Issue making post free if there is a Category Price

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1368]
**Steps to Reproduce**
- On the Paywall tab
  - Set the Global Default Price to Free
  - Ensure there is at least one Category Default Price
- On an Edit Post Page
  - Set Post to a Category with a Category Default Price
**Observed Result**
There is no way to make the post free

**Proposed Solution**
Do not disable the option to "Make Article Free"

**Comment by thrijith** [comment]
Fixed in [v2.9.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.1)
