### ISSUE TITLE
Allow Merchant to Specify Purchase Button Text Hover Color

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1372]
# Description
We allow the merchant to specify the purchase button color, the purchase button text color, and the purchase button hover color.

However, we don't allow them to specify the purchase button hover text color. This can results in a button that is illegible on hover.

# Acceptance Criteria
- Add option for 
**EN:** Purchase button hover text color
**DE:** Hover-Schriftfarbe Kaufbutton
  - Default color should be white
- Adjust the Color Customization Options to be in the following order (as shown in the mockup)
  - ...
  - Purchase button background color
  - Purchase button text color
  - Purchase button hover color
  - Purchase button hover text color
  - ...

# Mockup
![image](https://user-images.githubusercontent.com/41650164/72441607-9726f900-3770-11ea-987f-7e80a3c54d84.png)

**Comment by thrijith** [comment]
Hi @ksmoore125

Should a new option be added to the Appearance Tab's, `CUSTOMIZE COLORS` section right below `Purchase button text color`, is any other change that expected to be resolved with this ticket?

**Comment by ksmoore125** [comment]
Sorry! I had the entire ticket full complete with a mockup and it all disappeared. I will get it added back :(

**Comment by ksmoore125** [comment]
@thrijith - I tested and this is looking good except for the following scenario:

- Change hover color & hover text to different colors
- Open article with paywall
- Check that the change was reflected
  - In the Appearance Preview ✅ 
  - In the Post Preview ✅ 
  - On the Post in an Incognito Window or Other Browser ✅ 
- Navigate to the Appearance Tab & Restore to Default (or Adjust Colors)
- Check that the change was reflected
  - In the Appearance Preview ✅ 
  - In the Post Preview ✅ 
  - On the Post in an Incognito Window or Other Browser ❌

**Comment by thrijith** [comment]
@ksmoore125 this seems like a page cache issue, can you test on a site without page cache enabled?

Page cache is enabled on WPEngine, you can clear it from here after changing appearance color and verify the change.

![cache-clear](https://user-images.githubusercontent.com/13589980/72580287-9a9dba00-3901-11ea-8a7f-fbba2709a4a0.png)

I have updated the code to handle cache invalidation on WPEngine whenever appearance config is changed i.e updating any of these options should invalidate cache and you should be able to view the change, so you can update color and change layout along with it to verify change.

![appearance-config](https://user-images.githubusercontent.com/13589980/72580509-56f78000-3902-11ea-80a6-13b2509ccc39.png)

Clearing cache on appearance color changes won't be a good option, so merchant can clear cache manually once color settings have been finalized.

**Comment by thrijith** [comment]
Released in [v2.9.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.1)
