### ISSUE TITLE
Update Plugin metadata so that all Tags are also Keywords

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1374]
# User Story
As a LaterPay employee, I want merchants to be able to find our plugin using the WordPress Add Plugin Search feature.

# Acceptance Criteria
The WordPress Add Plugin Search feature defaults to metadata instead of tags. To ensure that we show up in the appropriate search results, we should ensure that all of our tags are also "keywords"

List of tags here: #1327

**Comment by thrijith** [comment]
Updated in https://github.com/laterpay/laterpay-wordpress-plugin/commit/36c4f0668b8151beb6ae06131a7093ddd4abe14e

**Comment by thrijith** [comment]
Updated in [v2.9.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.1)
