### ISSUE TITLE
Reduce Pay Now Validation

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1386]
# Acceptance Criteria
- For the EU only
- Reduce Pay Now validation to 1€
- Ideally for subscriptions only but if validation is the same for all pay now, it can be done for all purchase options (whichever is easier)

**Comment by thrijith** [comment]
Released in [v2.9.3](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.3)
