### ISSUE TITLE
Test & Update `Tested UpTo` Version to 5.4

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1391]
# Description
Per [this slack conversation](https://rtcamp.slack.com/archives/GA2P84GBZ/p1586159239001600?thread_ts=1586158965.001500&cid=GA2P84GBZ) we should ensure that the LaterPay plugin is compatible with WordPress v5.4 and update the `Tested UpTo` version number

# Acceptance Criteria
- Ensure that the LaterPay plugin functions properly with WordPress v5.4
  - If not, resolve any issues
- Update the `Tested UpTo` version number to 5.4

**Comment by thrijith** [comment]
Updated, released [v2.9.4](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.9.4)
