### ISSUE TITLE
Custom voucher names not working properly

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1397]
**Steps to Reproduce**
- Navigate to the Paywall tab of the LaterPay plugin
- Create a new time pass or subscription (or choose to edit an existing one)
- Click to `+ Generate voucher code`
- In the orange box, edit the code to a custom value (`COVID19` for example)
- Click `Save`

**Observed Result**
The purchase option is saved but the voucher code is not the one that was typed in

**Desired Result**
The voucher code should be the custom code that you typed in (ie: `COVID19`)

**Comment by milindmore22** [comment]
@ksmoore125 
### Scenario : 
if I did a fresh install and added a purchase option ( subscription or time pass ) and Vouchers with it, it fails to save voucher code.

but if I save ( re-save ) **Global Default Price** ( any option ) then **reload** and tried saving my voucher code it worked.

This is my testing scenario, please let me know if there is any other scenario / steps to reproduce same issue.

**Comment by ksmoore125** [comment]
@milindmore22 - It appears that there is still validation from the user's side (below). If this is difficult to change then we can add the validation back, we just need to ensure that there are error messages etc when the merchant tries to save the voucher (instead of letting them set a custom one and then simply replacing it when they save).

![image](https://user-images.githubusercontent.com/41650164/82688604-c7027380-9c1e-11ea-8193-9bb0fcd03ef2.png)

**Comment by ksmoore125** [comment]
We should re-instate the merchant UI validation as well. It looks as though this was working properly in `v2.9.0`

![image](https://user-images.githubusercontent.com/41650164/82695615-09ca4880-9c2b-11ea-99e4-055bf8c44ea6.png)

**Comment by milindmore22** [comment]
Save button and Generate Voucher link will be disabled until a valid code is entered
![image](https://user-images.githubusercontent.com/1132541/82832055-b4ff2a00-9ed7-11ea-970c-d8479a181766.png)
