### ISSUE TITLE
Contributions not Functioning Properly for EU

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1398]
**Steps to Reproduce**
1. Ensure your Account tab is set to `EURO`
2. Change your WordPress language to "Deutsch" 
3. Navigate to the LaterPay > Contributions tab
4. Add campaign name
5. Type "1" into the first custom amount input field
6. Wait until the input field autocompletes to "1,00"
7. Add a second custom amount
8. Generate code
9. Add code to a post
10. Publish post

**Observed Result:**
The "all_amounts" attribute in the code does not include an amount and therefore the dialog loads with 0,00 for all options.

**Desired Result:** 
Entered amounts should be displayed correctly in the "all_amounts" attribute of the code & in the user facing dialog.

**Note:**
When Kimberly tried to reproduce she was unable to the first time but was able to in future tests.

**Comment by ksmoore125** [comment]
@tomasstark - I attempeted to product check but this still appears to be an issue. I followed the steps above and this is [the contribution shortcode/dialog](https://lpwptestprod.wpengine.com/2020/08/19/145/) that was created.

**Comment by tomasstark** [comment]
@ksmoore125 I see. I found this is the issue with the cached JS asset. Here's how to overcome the issue:

1. While in admin area, visit [this URL](https://lpwptestprod.wpengine.com/wp-content/plugins/laterpay/built_assets/js/laterpay-backend-contributions.js?ver=2.9.5) directly.
2. Refresh Contributions screen.
3. Try generating shortcode again.
