### ISSUE TITLE
Remove Wisdom plugin integration

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#1409]
**Description**
When we were actively working on the plugin, we were looking into ways to collect additional usage data and therefore set up an integration with "Wisdom." Now that this plugin is being moved into maintenance mode, we have cancelled our Wisdom subscription and should therefore remove the related code.

**Acceptance Criteria**
Remove all code related to "Wisdom"

Relates to: https://github.com/laterpay/laterpay-wordpress-plugin/issues/1211, https://github.com/laterpay/laterpay-wordpress-plugin/issues/1220, https://github.com/laterpay/laterpay-wordpress-plugin/issues/1221

**Comment by tomasstark** [comment]
@ksmoore125 With the removal of Wisdom code, can the following paragraph be removed from the 'Analytics & Usage data' section in Advanced tab?

> In order to make informed decisions about improvements to our plugin, we would like to gather information on a few of your WordPress settings. We do not record any sensitive information; only data points in regards to your WordPress environment and plugin settings.

Thanks!

**Comment by ksmoore125** [comment]
@tomasstark - Let's leave it since it is applicable to the Google Analytics data that we will still be capturing. That means that this section of the Advanced Tab will look like:

![image](https://user-images.githubusercontent.com/41650164/90397604-b5820980-e05d-11ea-9c45-0dc8c99ae8d4.png)
