### ISSUE TITLE
Option to hide free-to-read posts from post listings

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#161]
Some users might want to hide posts e.g. from the front page, if they only contain premium files that are linked to by another post.
Put differently: if I create a free-to-read post (that itself is free) - say for a interview - which links to the paid video file of the interview and a paid full transcript, I might not want those two linked posts to show up on my frontpage or related posts listings.

To hide those posts, we could offer a toggle in the Appearance tab that automatically hides all posts that are linked to from free-to-read posts. Premium download links from a free-to-read post are recognizable by the use of the [laterpay_premium_download].

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla @mturalenka Merged, please close if all ok.
