### ISSUE TITLE
Test plugin in legacy versions of WordPress

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#2]
We should verify that the plugin is compatible with all legacy WordPress versions we want to support.
For testing purposes, you can get every version WordPress ever released from http://wordpress.org/download/release-archive/

Our compatibility goal is WP >= 3.3.

**Comment by twoldrich** [comment]
@mturalenka Is the compatibility goal of WP >= 3.3 still valid in your opinion?

**Comment by mturalenka** [comment]
@twoldrich currently its not possible, and one more reason to avoid this is version usage statistic, like https://wordpress.org/about/stats/
