### ISSUE TITLE
Teaser is not generated automatically

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#224]
If no teaser content has been specified, the plugin should automatically use the first x (depending on the settings formely defined in settings.php) words as teaser. At the moment, the plugin doesn't create the teaser automatically.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please check.

**Comment by twoldrich** [comment]
For completeness sake: Works fine!
