### ISSUE TITLE
Category default price is not automatically applied

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#231]
A category default price should be applied automatically to all posts in the respective category that use the global default price.

Example:
1. A post uses the **global default price** and is in "Category A".
2. I create a **new category default price** for "Category A".
=> The **price type** of this post should automatically change to **category default price**.
=> The **price** of this post should automatically change to the **category default price**.
=> The user should **not** be able to choose the option **global default price** in the pricing widget anymore (until **all** the category default prices that apply to this post have been deleted or the post is **unassigned** from all categories with a category default price)  

If we replay the example above with **two or more** new category default prices, the highest of these prices should be applied. (See ticket #144)

**Comment by twoldrich** [comment]
Just tested with **feature/231_category_default_price_auto_apply**

What **works** now: **Apply new category default price to posts with global default price**
The price-type for a post in category A is automatically applied if a category default price is created for category A.

What **doesn't work**: **Use category default price for posts that are newly assigned to a category with category default price**
- There is a post without a category and with an individual price / global default price
- I create a category default price for category A
- I open the post and assign it to category A 
- =>"Category default price" is selected correctly, but no list of category default prices is displayed:
![screenshot 2015-01-19 17 37 58](https://cloud.githubusercontent.com/assets/6638286/5803978/9560d664-a002-11e4-83be-c896b6b6698d.png)
- => After updating the post, price and price type are the same as before but no price-type is selected.
![screenshot 2015-01-19 17 37 47](https://cloud.githubusercontent.com/assets/6638286/5803992/b1404fb8-a002-11e4-81a6-b0e2668c7a26.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fixed issue with category select, please check.
