### ISSUE TITLE
Double /access call

### ISSUE THREAD

**Issue by arenstar** [laterpay/laterpay-wordpress-plugin#328]
Im not exactly sure why this is happening but it seems like every call is duplicated

here are some logs showing this.....

<134>Sep 12 11:40:27 webapi-1.muc.laterpay.internal haproxy[27177]: 107.6.163.194:58879 [12/Sep/2014:11:40:27.251] http-in~ lpapi_external_muc/webapi-1-8000 50/0/1/2/53 200 214 - - ---- 4/4/0/0/0 0/0 {api.laterpay.net||LaterPay Client - PHP - v0.2|deflate;q=1.0, compress;q=0.5||||||} {application/json|||} "GET /access?article_id=21719&cp=w5EsNaAFAujconYjpxMeAN&lptoken=&ts=1410522021&hmac=a61da9cda15478f1e2d7c670275b971ceaa4b0e84bbf5fcb98ed8c78 HTTP/1.0"

<134>Sep 12 11:40:27 webapi-1.muc.laterpay.internal haproxy[27177]: 107.6.163.194:58890 [12/Sep/2014:11:40:27.809] http-in~ lpapi_external_muc/webapi-1-8001 48/0/0/2/50 200 214 - - ---- 4/4/0/0/0 0/0 {api.laterpay.net||LaterPay Client - PHP - v0.2|deflate;q=1.0, compress;q=0.5||||||} {application/json|||} "GET /access?article_id=21719&cp=w5EsNaAFAujconYjpxMeAN&lptoken=&ts=1410522021&hmac=a61da9cda15478f1e2d7c670275b971ceaa4b0e84bbf5fcb98ed8c78 HTTP/1.0"

<134>Sep 12 11:40:28 webapi-1.muc.laterpay.internal haproxy[27177]: 107.6.163.194:58900 [12/Sep/2014:11:40:28.419] http-in~ lpapi_external_muc/webapi-1-8002 46/0/0/3/49 200 214 - - ---- 4/4/0/0/0 0/0 {api.laterpay.net||LaterPay Client - PHP - v0.2|deflate;q=1.0, compress;q=0.5||||||} {application/json|||} "GET /access?article_id=21715&cp=w5EsNaAFAujconYjpxMeAN&lptoken=&ts=1410522022&hmac=3c222b0ae96453113ef143e2da6d26cf9b0c322d1acf3a3047234b0e HTTP/1.0"

<134>Sep 12 11:40:29 webapi-1.muc.laterpay.internal haproxy[27177]: 107.6.163.194:58911 [12/Sep/2014:11:40:29.012] http-in~ lpapi_external_muc/webapi-1-8003 55/0/0/2/57 200 214 - - ---- 4/4/0/0/0 0/0 {api.laterpay.net||LaterPay Client - PHP - v0.2|deflate;q=1.0, compress;q=0.5||||||} {application/json|||} "GET /access?article_id=21715&cp=w5EsNaAFAujconYjpxMeAN&lptoken=&ts=1410522023&hmac=5c50b88dd034b1f878e3acbbe2bc88c4106c99f19e4d599f08a984e4 HTTP/1.0"

**Comment by twoldrich** [comment]
@mturalenka Can you say if this is still relevant/happening?

**Comment by mturalenka** [comment]
we already implemented functionality to pre-fetch post access once per request
https://github.com/laterpay/laterpay-wordpress-plugin/blob/897af6db8240612cb37c14c4f917a5ea8cb0fe5b/laterpay/application/Controller/Frontend/Post.php#L482-L539
