### ISSUE TITLE
Only attach (Selenium) tests to classes with prefix 'test_'

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#331]
In order to avoid breaking tests by modifying classes attached to elements, special class names should be used (e.g. 'lp_test_add-button') that point out that some (Selenium) tests are attached to that class.

(All LaterPay classes (and IDs) have to start with 'lp_'.)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Is this issue still actual?

**Comment by mturalenka** [comment]
yes, this is still actual
