### ISSUE TITLE
Support Link Checker

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#334]
A customer reportet that his link checking plugin "Broken Links Checker" lists all the links on his website as broken with the URL "web.laterpay.net/no_cookies...". Obviously, the link checker is simply a crawler that does not accept our cookie and therefore the checks fail.
We should support the use of link checking plugins, just as we do it with search engine crawlers.

**Comment by drdla** [comment]
Trying to load a paid post with the (W3C link checker)[http://validator.w3.org/checklink] returns a '403 forbidden' error, which makes a link checker report 'broken'.
This status code is inappropriate in my opinion, because you CAN see something there (namely the teaser content).
Should we better return a 200 status code?

**Comment by drdla** [comment]
Seems as if returning a 200 status code would be best, as e.g. Mailchimp would reject to use a page with a 301 or 302 status code.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Usual request to our page from crawler:

Log: === HTTP code : 400 ===

HTTP/1.1 302 Moved Temporarily
Server: nginx
Date: Wed, 04 Mar 2015 13:37:37 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
X-Powered-By: PHP/5.5.9-1ubuntu4.3
X-Pingback: http://local.wordpress.dev/xmlrpc.php
Set-Cookie: token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
Location: https://api.laterpay.net/gettoken?cp=SsG3WvBNpDVNZRo22BxVsC&redir=http%3A%2F%2Flocal.wordpress.dev%2F121&ts=1425476257&hmac=fff44dd4af16443a4761d76fb71c7b4eb5aea58766fac4c9e1b0b65f

HTTP/1.1 302 Found
Date: Wed, 04 Mar 2015 13:37:38 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Location: /identify?cp=SsG3WvBNpDVNZRo22BxVsC&gettoken=True&redir=http%3A%2F%2Flocal.wordpress.dev%2F121&ts=1425476257&hmac=27650fcffe8926e7c767dde5ff54ad52bec59ef0cf2bb76a6121641b
Server: TornadoServer/3.2.2
Connection: close

HTTP/1.1 302 Found
Content-Length: 0
Expires: 0
Server: TornadoServer/3.2.2
Etag: "c|aTXvXfeBKCdVBHRwEmczO5Dtmr01P/50uuv4kmMylF/aJNCKKDl0fSau0TJLPgWuS8gu9VLy0CQNox/zhHPBXQ==|1425476258|f38eba590f83800b244472d8c38c1ff2c2d13acab6c4eeeeca2c2508"
Location: /check?cp=SsG3WvBNpDVNZRo22BxVsC&gettoken=True&redir=http%3A%2F%2Flocal.wordpress.dev%2F121&ts=1425476257&hmac=8a93baa8d0069f31f50bf34dfb9468edda7dc56e02dde3b86ed618be
Cache-Control: no-cache
Date: Wed, 04 Mar 2015 13:37:38 GMT
If-None-Match: "c|aTXvXfeBKCdVBHRwEmczO5Dtmr01P/50uuv4kmMylF/aJNCKKDl0fSau0TJLPgWuS8gu9VLy0CQNox/zhHPBXQ==|1425476258|f38eba590f83800b244472d8c38c1ff2c2d13acab6c4eeeeca2c2508"
P3p: CP=IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT
Content-Type: text/html; charset=UTF-8
Set-Cookie: lp-D="c|aTXvXfeBKCdVBHRwEmczO5Dtmr01P/50uuv4kmMylF/aJNCKKDl0fSau0TJLPgWuS8gu9VLy0CQNox/zhHPBXQ==|1425476258|f38eba590f83800b244472d8c38c1ff2c2d13acab6c4eeeeca2c2508"; Domain=.laterpay.net; expires=Mon, 02 Mar 2020 13:37:38 GMT; httponly; Path=/; secure
Connection: close

HTTP/1.1 302 Found
Date: Wed, 04 Mar 2015 13:37:39 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Location: https://web.laterpay.net/no_cookies
Server: TornadoServer/3.2.2
Connection: close

HTTP/1.1 400 BAD REQUEST
Server: gunicorn/19.1.1-laterpay3
Date: Wed, 04 Mar 2015 13:37:39 GMT
Connection: close
Transfer-Encoding: chunked
Vary: Cookie, Accept-Language
P3P: CP=IDC DSP COR ADM DEVi TAIi PSA PSD IVAi IVDi CONi HIS OUR IND CNT
Content-Type: text/html; charset=utf-8
Content-Language: en
Set-Cookie: csrftoken=I6qdE0WtP370tZDiBJ3OE0m4imdNxAJ6; expires=Wed, 02-Mar-2016 13:37:39 GMT; Max-Age=31449600; Path=/; secure

**Comment by AliaksandrVahura-ScienceSoft** [comment]
HTTP code: 400
Response time: 1.621 seconds
Final URL: https://web.laterpay.net/no_cookies
Redirect count: 4
Instance count: 1

Link is broken.

No chances to fix this. Can be fixed only with Browsecap update.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
"Broken Links Checker" plugin used.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Fixed with link checker update. Please review.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft and I just tested with the current master and both links to posts and to pages worked fine (returned 200).
