### ISSUE TITLE
Youtube videos in paid content are not loaded

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#403]
When pasting a youtube link into the (visual) editor, WordPress usually gets the embed code from youtube and renders a youtube video player.
This is not working anymore in paid posts (making the post free makes it work again).
To be more precise:
- It's not working in the teaser content
- It's not working in the full content after purchase

**Comment by Chrico** [comment]
@twoldrich please contact me in skype, than we will reproduce this together :-)

**Comment by twoldrich** [comment]
@Chrico had another look at this issue and it is very likely that the problem is caused by a plugin (Youlist). As the integration of YouTube videos is now a native function of WordPress and the as the problem doesn't occur for other users, I close this ticket.
