### ISSUE TITLE
Lightbox (jquery fancybox) is not working in paid content

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#404]
Images are not opened in a lightbox, but in a new window, if they are within the paid content of a post.
It IS working in the teaser content though.
I checked the markup and found the problem: the class "fancybox" is removed, if the image is rendered within paid content.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I find out that this isn't problem with "fancybox" class, but with modified image link processing in lightbox plugins.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Basically fix for such issues already implemented from our side (added param "ext" in encrypted file url).  List of most popular WP lightbox plugins that:
a) Work fine with encrypted images without modifications:
1. WP Lightbox 2;
2. FooBox Free Image Lightbox;
b) Can work with encrypted images after modification:
1. Simple Lightbox ( via filter usage );
2. Huge IT lightbox ( extend jquery.colorbox plugin );
3. Wp Jquery Lightbox ( extend jquery.lightbox plugin );
c)  Can't work with encrypted images and not support modifications:
1. Lightbox Plus Colorbox

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich @drdla Please provide list of plugins which we should support.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Is that still relevant or can I close this issue? I'm asking because in the meantime, we had a release, so it might already be resolved.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich I think situation is the same. But as you can see most part of popular lightbox plugins for WP working fine with our plugin (by default or with modifications).

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Could you please close this issue if we had no more reports from customers? We feagured out during investigate that most of these problems can be solved via filters or js extends and not depends from Laterpay plugin realisation.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft No, we didn't receive further complaints, so I'll close this for the moment, thank you!
