### ISSUE TITLE
Form filters: Adjust 'normalization' algorithm.

### ISSUE THREAD

**Issue by AliaksandrVahura-ScienceSoft** [laterpay/laterpay-wordpress-plugin#419]
We need to adjust 'normalization' algorithm besides simple str_replace with something like https://github.com/zendframework/zf1/blob/release-1.12.9/library/Zend/Locale/Format.php to convert all possible input formats to correct one.

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft still valid?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Yes, not so much of work but i'm still busy with more priorite tickets.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please check that numbers saved and formatted correctly.
