### ISSUE TITLE
Encrypt variables to use them with travis.yml

### ISSUE THREAD

**Issue by AlexandrTsumarov-ScienceSoft** [laterpay/laterpay-wordpress-plugin#442]
https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/.travis.yml#L6L7
Needed to encrypt those variables with LaterPay keys to make Travis-Selenium acceptance tests serviceable. It might be done by http://docs.travis-ci.com/user/encryption-keys/
Steps:
1. https://github.com/settings/applications -> Generate new token -> new_token
2. gem install travis
3. copy https://raw.githubusercontent.com/laterpay/laterpay-wordpress-plugin/master/.travis.yml to working dir and remove lines 6-7 from file. (Working dir - is your local directory where you will run local command "travis login")
4. travis login --github-token new_token
5. travis encrypt github_key_pass="$private_one" --debug --add -r laterpay/laterpay-wordpress-plugin
6. travis encrypt key_hash="$private_two" --debug --add -r laterpay/laterpay-wordpress-plugin

The $private_one and $private_two are private and might be sent it by email or skype.

**Comment by drdla** [comment]
@doismellburning is this issue still relevant?

**Comment by doismellburning** [comment]
As @AlexandrTsumarov-ScienceSoft filed it, I'd imagine he would be able to answer this best, but I suspect not...

**Comment by jdelic** [comment]
please note that @laterpay-travisci exists. I created that user for precisely that use-case. @doismellburning: I remember a discussion on Skype about the Selenium tests being outdated? I guess if we could get them to run we could ask them to update the tests? As you looked into the repo and the branch.. is there a chance of them ever running on Travis?

**Comment by doismellburning** [comment]
I have no idea yet; I figured #570 / #566 were better low-hanging fruit to get sorted first

**Comment by doismellburning** [comment]
But, I _will_ close this issue, because it appears to be for the somewhat interesting "during tests, clone the branch of this repo with the tests" code that was removed in #557, which is not something I think we want to be doing.
