### ISSUE TITLE
Purchase button is squeezed together on Android browsers

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#472]
A customer reported a problem with the purchase button on the Android 4.2.2 default browser and the Dolphin browser: It is squeezed together so the LaterPay icon and the price are overlapping.

![screenshot 2014-11-21 10 16 31](https://cloud.githubusercontent.com/assets/6638286/5140162/19653dca-7168-11e4-8523-24529f38d407.png)

**Comment by mturalenka** [comment]
![2015-08-27 15-05-51](https://cloud.githubusercontent.com/assets/6449022/9522855/aafcab26-4cdf-11e5-8026-dc8f5792c63d.png)
