### ISSUE TITLE
Don't render LaterPay teaser instead of excerpts for free posts

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#474]
If **several posts** are listed on **one page** (e.g. a blogs start page) the plugin by default shows only the **teaser** for LaterPay posts with **price >0**. 
If a post is **free**, we currently show the **full text**, which might not be wanted (the user might want to show only the WordPress generated excerpt).
That's why, we should **not influence** how a post is displayed on a page with several posts **if the post is free**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich By default on homepage the_content function used to output content that's why we see full text, the_excerpt by default used on search page. User can change the_content on the_excerpt if he wants. All works ok.

**Comment by twoldrich** [comment]
@AlexandrTsumarov-ScienceSoft Thank you for the explanation – I informed the customer and forwarded your advice to replace the_content by the_excerpt in the respective template.
