### ISSUE TITLE
Improve price setting in dynamic pricing handles

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#477]
Quite often, the price I enter in one of the handles in the dynamic pricing widget, is not applied:

1. I click on one of the handles => A text input occurs.
2. I click again to enter the text input.
3. I enter a new (valid) price and press enter.
=> Quite often (but not always...) the price I entered is ignored and the old price is shown in the handle again.

@drdla Please assign this ticket accordingly.

**Comment by drdla** [comment]
Done when refactoring the dynamic pricing widget.
