### ISSUE TITLE
Currency indicators in dynamic pricing widgets are not displayed correctly

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#478]
In the dynamic pricing widget, the currency indicators are not displayed correctly:
The "EUR" indicator for the start price handle remains always in the upper left corner.
The indicator for the end price handle is blue (almost as the handle's background).
Seen on current master.

![screenshot 2014-11-22 13 19 12](https://cloud.githubusercontent.com/assets/6638286/5154130/38405472-724a-11e4-9c3a-6f5904af5d73.png)
 *Note: The widgets background-color has been changed to grey intentionally for this screenshot*

@drdla Please assign accordingly.

**Comment by drdla** [comment]
Done when refactoring dynamic pricing widget.
