### ISSUE TITLE
Shortcode: Check if the target post/attachment is covered by a time pass

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#485]
The plugin should check for all shortcodes in a post if the shortcode target (post or attachment) is covered by a currently valid **time pass**. If yes, the shortcode should be displayed with a call-to-action button instead of a purchase button (= as if the target post/attachment had been purchased).

Currently, the user can still buy posts from within a shortcode which are covered by a valid time pass.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done, please test.

**Comment by twoldrich** [comment]
Just for completeness sake: Works fine on the current master.

**Comment by twoldrich** [comment]
With current master, even if the current post is covered by a time pass, attachements in shortcodes cannot be downloaded for free (the price is displayed instead of e.g. "download now").

(It should be as described above:
For attachments (= not posts), we should check the referrer: 
Example: You have an attachment in a post in category A. And you have purchased a time pass for category A. So if you try to access the attachment from a post in category A, you should have access to that attachment. If you try to access the attachment from a post in category B (for which you don't have a time pass), you shouldn't have access to the attachment.)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Somehow works fine for me... can't reproduce.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Reproduced with category time pass only. Fixed. Please check.

**Comment by twoldrich** [comment]
Works now also for category time passes.
