### ISSUE TITLE
lptokens received through redirects from LaterPay API are possibly not validated.

### ISSUE THREAD

**Issue by suligap** [laterpay/laterpay-wordpress-plugin#493]
Docs on [/gettoken](https://laterpay.net/developers/docs/backend-api#GET/gettoken):
> The user will be redirected to the URL supplied as redir except that lptoken=<token> will be added to the query string, and the request will be signed using the shared secret. Please make sure you verify the signature before accepting the token.

It looks like laterpay-wordpress-plugin [does not](https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Controller/Post.php#L243-L253) validate that request [and here](https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Controller/Post.php#L337-L339).

**Comment by mturalenka** [comment]
@AliaksandrVahura-ScienceSoft please verify purchase actions as well
