### ISSUE TITLE
Encrypted link is displayed instead of image after purchase

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#495]
A user reported that after purchasing a time pass, he doesn't see any images but only the encrypted links  for the respective image.

![image link](https://cloud.githubusercontent.com/assets/6638286/5249948/e9cff014-7987-11e4-8de5-c543388c8372.png)

I could reproduce this error but reloading the page twice resolved it for me.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Is this issue still actual?

**Comment by twoldrich** [comment]
Tested with current master, cannot reproduce anymore.
