### ISSUE TITLE
Time passes: "Access to category X" time pass gives access to all content

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#498]
With the current master, I created a time pass for a specific category. After purchasing that time pass, I get access to **all content**, not only to the content of the respective category. 

@AliaksandrVahura-ScienceSoft Can you please verify that bug and - if it occurs for you, too, take care of it?

**Comment by twoldrich** [comment]
With the current master, I can reproduce the issue.
@AliaksandrVahura-ScienceSoft Can you please verify the issue?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Works fine for me. The only moment that i wanted to clarify: do we need to show teaser message for the purchased posts on the homepage? Right now even if post is purchased teaser shows on the non-singular pages.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft With the current release and on my test system, I still have this problem – I'll write you more details in our development channel.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed with PR for 574.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fix was merged into master, now you can test access.
