### ISSUE TITLE
Verify API keys by sending test request to LaterPay

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#5]
After entering an API key with the correct length for a LaterPay API key (sandbox or live), we should send a test request to verify the entered key.
At the moment, the only verification is to check for the correct length of the entered key but still show a flash message saying "key verified and saved".
~~This applies to both the account tab and the getStarted tab.~~

**Comment by drdla** [comment]
Actual source code is on https://github.com/laterpay/lpapi_external/blob/develop/lpapi_external/integration/handlers.py

**Comment by twoldrich** [comment]
@jdelic pointed me to https://dev.laterpaytest.net/developers/docs/backend-api#GET/validatesignature
@mturalenka Is that helpful for you?

**Comment by drdla** [comment]
It's even live:
https://www.laterpay.net/developers/docs/backend-api#GET/validatesignature

**Comment by mturalenka** [comment]
@twoldrich looks like its what we need

**Comment by twoldrich** [comment]
@mturalenka Do you know the current state of this issue?

**Comment by mturalenka** [comment]
@twoldrich  we use this API to check API availability(health) on each request. should we add this check while saving account settings?
