### ISSUE TITLE
Render dashboard with fake data in TEST mode

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#509]
It doesn't make sense to collect data and render the dashboard, if the plugin is in test mode, because there is no reasonable data to collect.

On the contrary, it would mess up out statistics, if data collected in TEST mode are mixed with data collected in LIVE mode!

So:
- [ ] Do not collect statistics data in test mode.
- [ ] Add a set of mock data that allows us to showcase the dashboard in TEST mode, i.e. in TEST mode we should render the dashboard with fake data, together with a large hint that it is only showing fake data for illustrative purposes.

**Comment by drdla** [comment]
Kind of collides with #584
This issue should be about providing a helpful empty state for the statistics.
So: show mock data until real data has been collected.

**Comment by twoldrich** [comment]
As we moved the dashboard to the LaterPay merchant dashboard, this can be closed.
