### ISSUE TITLE
Show detailed post statistics in dashboard

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#510]
The user should be able to click a post from the top / bottom list and get more detailed data for this post only.

That detailed data is the same that we are showing in the post statistics pane:
- Total Revenue (ever, as number)
- Total Sales (ever, as number)
- Revenue today (as number)
- Revenue last 30 days (as sparkline)
- Conversion rate ("Buyers") today (as number)
- Conversion rate last 30 days (as sparkline)
- Page views ("Visitors") today (as number)
- Page views last 30 days (as sparkline)

Toggling the details should slideDown / slideUp that section.

(Maybe the post details data should be rendered in the large diagrams as well.)

**Comment by Chrico** [comment]
@drdla i've splitted the frontend post-statistic to 2 partials to reuses the rendering in backend for the post detail data.

basic funcationallity is implemented. Now todo: Styling. ;-)

**Comment by twoldrich** [comment]
As we moved the dashboard to the LaterPay merchant account, this can be closed.
