### ISSUE TITLE
Add quicktag for shortcodes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#515]
It should be possible to insert the basic structure for the shortcode [laterpay_premium_download] via quicktag. By clicking a "LaterPay Premium Content" Button in the editor, the following text should be inserted:

[laterpay_premium_download target_post_id="" heading_text="" description_text=""]

@drdla already started with that in branch **"feature/quicktags_for_shortcodes"**.

**Comment by Chrico** [comment]
@drdla 
The current implementation only inserts the Qtag-button. The Qtag-Buttons are only visible in "text"-mode (not in TinyMCE "visual" mode).

![image](https://cloud.githubusercontent.com/assets/3417446/5851393/d77eae1c-a206-11e4-8150-52342cc7a651.png)


Should the button also visible in "visual" mode? If yes, than we have to build a TinyMCE-Addon.

**Comment by drdla** [comment]
Aha!
A real addon is another issue, this was really just about the quicktag. But the benefit is kind of limited, if the button only appears in text mode. I'm not so convinced that this issue should go into the release.

**Comment by drdla** [comment]
Deleted the branch. Let's not pollute the codebase with pointless features.
