### ISSUE TITLE
Post statistics tab doesn't show correct number of visits (always 0)

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#520]
A customer reported that with the current plugin release 0.9.9, the post statistics tab **doesn't show the correct number visits**, but always 0. Judging from a first test, this problem also occurs for me – I don't see visits although (on different browsers and devices) I had visited a post. I couldn't verify if this also occurs for purchases due to #519.

@Chrico Could you verify that please and take care of the issue if it also occurs for you?

**Comment by Chrico** [comment]
@twoldrich can you pls recheck? If it breaks on your testing envoirment, pls contact me via skype. :-)

**Comment by twoldrich** [comment]
That's fine for the moment. 
Currently, we count each view, i.e. also the post preview and also switching from admin to visitor preview is counted as an individual view. For the moment, this behavior is ok. As discussed with @drdla, I will create a new ticket to collect statistics issues so we can discuss lateron how to correct biased data.
