### ISSUE TITLE
Support "more" tag in teaser

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#521]
A customer requested that the plugin should support the **"more" tag** in the **teaser** for the following reason:
On the front page, usually (for non-LaterPay-posts that use the "more" tag), the text above the more tag is displayed, followed by a **"read more"** / "weiterlesen" link. This link is not shown as soon as we display the LaterPay teaser content as it ignores the more tag.

We should discuss in this ticket, if we want to follow this request.

If we do, we should also decide what the "teaser-only" preview mode should look like. A "read more" link above a "Buy now for 0.05 EUR and pay later" link would be confusing.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
We've added "more" tag support in teaser in version 0.9.13. Please check.

**Comment by twoldrich** [comment]
Thank you @AliaksandrVahura-ScienceSoft, I'll close this issue then.
