### ISSUE TITLE
Allow modifications after the post has been loaded from the database

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#532]
Andreas Berghaus added the 'the_post' action to ajax_load_purchased_content to allow modifications to be made after the post has been loaded from the database. It is called by default in the setup_postdata function, which is invoked for every post during the_loop, to setup the global $post-variable.

see ffc4fe2a7c66bef9e44f406bd08126fc5e5f7066

Do we have to do the same thing for non-Ajax rendering of posts?

**Comment by drdla** [comment]
@derapU Could you please comment on this discussion?

**Comment by derapU** [comment]
i don't see any other way to append custom data to the post_content. maybe a custom laterpay hook to allow modification before the data is send to the client, passing a reference to $post to the callback?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Without global $post variable this hook not worked. Also added check if we use ajax to return full content and not only teaser. Previously it returned content cause post was 0:
https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Controller/Post.php#L826-L832
