### ISSUE TITLE
Add 'maximum redemptions per gift card' to advanced settings page

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#537]
For gift card voucher codes we have discussed a default value of **3** times, a user can redeem that voucher code, before it is disabled.
The merchant should have the option to adjust this value as a setting in the advanced settings page.
Valid values: 1+
Default: ~~3~~ 1

**Comment by twoldrich** [comment]
Works fine for me, redeeming is limited correctly according to the setting on the advanced settings page.
One 
There is some overlap with #535 – @AliaksandrVahura-ScienceSoft Can you please also have a look at this ticket, too?
