### ISSUE TITLE
SEO: LaterPay appends "?" to URL

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#542]
A customer reported, that from an SEO point of view, it's not the best thing that LaterPay appends a "?" to all URLs. I'm not sure if this is a plugin-related issue and I'm not sure if can do anything about this – but wanted to have it documented here in case it is / we can.

**Comment by twoldrich** [comment]
I did not receive an example for such a link yet but a user reported that the "Broken Link Checker" reports links with the appended "?" as broken.

**Comment by mturalenka** [comment]
RE: Symbol "?" is usual prepend before GET params list. I saw no place where "?" added without params.
@AliaksandrVahura-ScienceSoft , its possible after token creation(the first place i remember), we should add checking for params amount, and generaly there was a function to get current url, that remove any special parameters like `hmac` etc. but seems it leaves `?` if there is no any parameter

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed in Laterpay client.
