### ISSUE TITLE
Issue with RSS feeds when LaterPay is active

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#545]
A customer reported that RSS-driven Mailchimp campaigns don't work properly when the plugin is in live mode, as the RSS feeds are modified. (I already asked for more information about what exactly doesn't work properly.)

**With LaterPay**
> Receiving Header: 
> HTTP/1.1302MovedTemporarily(CR)(LF) 
> Date:Tue,23Dec201413:34:29GMT(CR)(LF) 
> Server:Apache(CR)(LF) 
> Vary:Cookie,Accept-Encoding(CR)(LF) 
> X-Pingback:http://www.XXX.de/xmlrpc.php(CR)(LF) 
> ETag:"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"(CR)(LF) 
> Set-Cookie:wfvt_XXXXX=XXXXX;expires=Tue,23-Dec-201414:04:29 
> GMT;Max-Age=1800;path=/;httponly(CR)(LF) 
> Set-Cookie:token=deleted;expires=Thu,01-Jan-197000:00:01GMT;Max-Age=0; 
> path=/(CR)(LF) 
> Last-Modified:Tue,23Dec201411:17:14GMT(CR)(LF) 
> Location:https://api.laterpay.net/gettoken?cp=XXXXXXXXX&redir= 
> http%3A%2F%2Fwww.XXX.de%2Ffeed&ts=XXXXXXXXX&hmac=XXXXXXXXX 
> XXXXXXXXX(CR)(LF) 
> Content-Length:0(CR)(LF) 
> Connection:close(CR)(LF) 
> Content-Type:text/html;charset=UTF-8(CR)(LF) 
> (CR)(LF)

**Without LaterPay**
> Receiving Header: 
> HTTP/1.1200OK(CR)(LF) 
> Date:Tue,23Dec201413:35:52GMT(CR)(LF) 
> Server:Apache(CR)(LF) 
> Vary:Cookie,Accept-Encoding(CR)(LF) 
> X-Pingback:http://www.XXX.de/xmlrpc.php(CR)(LF) 
> ETag:"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"(CR)(LF) 
> X-Robots-Tag:noindex,follow(CR)(LF) 
> Set-Cookie:wfvt_XXXXX=XXXXX;expires=Tue,23-Dec-201414:05:52 
> GMT;Max-Age=1800;path=/;httponly(CR)(LF) 
> Last-Modified:Tue,23Dec201411:17:14GMT(CR)(LF) 
> Connection:close(CR)(LF) 
> Transfer-Encoding:chunked(CR)(LF) 
> Content-Type:text/xml;charset=UTF-8(CR)(LF) 
> (CR)(LF) 

*(I replaced some customer specific information by XXX)*

@AliaksandrVahura-ScienceSoft The title of this ticket is quite unspecific – probably you can adjust it.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich I don't get what should i do here... You said: (I already asked for more information about what exactly doesn't work properly.). Any info?

**Comment by twoldrich** [comment]
No, we didn't receive new infos – I was hoping that the above infos could already be useful to identify a problem. If I don't get more infos today, I'll send a reminder.

**Comment by twoldrich** [comment]
I just talked to our customer:
- He uses MailChimp for newsletters based on his RSS feed.
- MailChimp checks the links in the feed
- If the LaterPay plugin is activated, this check returns 302 (instead of the expected 200)
-> MailChimp refuses to use such links

I also asked him to provide infos from the LaterPay debugger which I will send you ( @AliaksandrVahura-ScienceSoft ) in a private message.

**Comment by drdla** [comment]
Closely related to #334

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Basically same problem with crawler. But here also other moment: should we prevent gettoken request for non-single pages, like it done for single non-purchasable pages.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Seems fixed with Browsecap update )

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed with Browscap update. Please check. I can provide my Mailchimp account for testing.

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft I think we should not try to identify devices (get token), if it's not a paid page. So if it is a page with multiple items, which you can't purchase directly, then we shouldn't check and assign a token.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
What about timepasses and gift passes that can be rendered on non-single pages and free posts and can be purchased?

**Comment by twoldrich** [comment]
I tested with Mailchimp and the current master: I can create and save a RSS driven campaign without any error, so I would say it works.

@drdla As there is an ongoing discussion in this ticket, I leave this ticket open for the moment.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Discussion was moved into the ticket #641. So seems this ticket can be closed.

**Comment by drdla** [comment]
Exactly. This is an unrelated discussion that is led somewhere else already.

**Comment by twoldrich** [comment]
*I suppose the following report is related to this issue, that's why I'm reopening that*

The customer reported, that in the "Google Snippet Tool", all page titles are replaced by "LaterPay" and descriptions are deleted. He assumes because of the new status code 302.

@AliaksandrVahura-ScienceSoft any idea?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Seems that google snippet crawler not supported by browscap. We can do nothing with that. 302 appeared if it was redirected on Laterpay side and stopped on it.

**Comment by twoldrich** [comment]
@drdla @mturalenka Do you know if we can / should manually add crawlers to browscap?
My first thought would be that it would be good to cover Google Services, but I have no idea if that's feasible and useful.

**Comment by drdla** [comment]
I think we SHOULD do that, but I have no idea HOW to do it. I had a quick look at the browscap page, but didn't find a mechanism for adding something to the database.
