### ISSUE TITLE
JetPack gallery plugin doesn't load 

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#547]
A customer reported that the JetPack gallery plugin doesn't load (no gallery is displayed) on his WordPress 4.1 system, if the LaterPay plugin is active and he gets the message "java has to be installed". Without the LaterPay plugin, everything works fine for him.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Checked on our test site, couldn't reproduce problem. JetPack gallery works fine with latest version of WP and Laterpay plugin.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Could you approve this and close issue?
