### ISSUE TITLE
Force language for login / logout iframe

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#551]
*This ticket is related to #538.*

The laterpay_account_links **action** AND **shortcode** should have one attribute **'use_site_language'**, which if present passes the locale of the blog to the forcelang attribute. By default we provide no value for forcelang so that LaterPay guesses the language of the user.

Furthermore, it should be possible to pass a specific CSS file (with full URL of course) to the laterpay_account_links **action**.

**Comment by drdla** [comment]
Let's rather pass the current site language to the forcelang attribute as default so the account links are rendered in the language of the site.
