### ISSUE TITLE
Gift card code is not saved if it's purchased on the homepage

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#552]
Tested with **current master**:

If a gift card voucher is purchased on the homepage,
- the voucher code is not displayed after the purchase
- the voucher is not saved as a valid voucher and can therefore not be redeems

@AliaksandrVahura-ScienceSoft already confirmed that behavior.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fixed. Please check.
