### ISSUE TITLE
Revenue model for new posts is always PPU for prices between 1.49 and 5.00

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#558]
Steps to reproduce:
- Create a **new** post / Open an **existing** post for editing
- Set an **individual** price between **1.49** and **5.00**
- Choose the revenue model **SIS**
- **Publish** the post
- > **PPU** is selected as revenue model
- > **PPU** is displayed as the revenue model for this post in the post overview 

For prices **> 5.00**, the revenue model **SIS is saved correctly**, but still after publishing a post the **indicator** for the revenue model is **not selected** (not green).
![screenshot 2015-01-20 21 09 05](https://cloud.githubusercontent.com/assets/6638286/5825003/9e886676-a0e8-11e4-87bd-9327687278e5.png)

**Comment by twoldrich** [comment]
I tested this issue with the current master.
It occurs **only** on the **add/edit post** page, **not** when setting the **global** or **category default** price.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed.

**Comment by twoldrich** [comment]
Works fine for me.
