### ISSUE TITLE
Update list of caching plugins

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#559]
http://wpdevshed.com/wordpress-caching-plugins/ gives a nice overview of most caching plugins.
Some are not yet included in our list and should be added.

- https://wordpress.org/plugins/hyper-cache/
- https://wordpress.org/plugins/hyper-cache-extended/
- https://wordpress.org/plugins/aio-cache/
- https://wordpress.org/plugins/really-static/

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Merged.
