### ISSUE TITLE
Usability fixes for dashboard interval filter

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#562]
The implementation of the selected interval still has a few things that need to be ironed out:

__TODO__

- [x] The 'next interval' link should not be shown, if there is no data for the next interval (e.g. because it lies in the future)
- [x] The 'previous interval' link should not be shown, if there is no data for the previous interval
- [x] The error message for a non-existent next interval should be removed, because the above changes make it obsolete
- [x] The tooltip text of the prev / next links should match the selected duration, i.e. depending on the selected duration, it should say 'Show next day' / 'Show next 8 days' / 'Show next 2 weeks' / 'Show next month' and 'Show previous day' / 'Show previous 8 days' / 'Show previous 2 weeks' / 'Show previous month'
- [x] The prev / next links should shift the rendered interval by the selected DURATION, not always by one day. E.g. for duration 8 days and current interval '13.1.2015 - 20.1.2015', clicking the prev link should load the data for '4.1.2015 - 12.1.2015'.

-------------

__TODO Step 2__

- [ ] It should be possible to switch to the current day, if the interval is set to '24 hours'
- [x] It should not be possible to switch to an interval in the future, if the interval is set to '2 weeks' or '1 month'

**Comment by Chrico** [comment]
@drdla 

__"previous interval" link should not be shown, if there isno data available__

 We have currently 2 database tables (payment_history and post_view_statistic) for our Dashboard. Both can have a different "earliest entry date". Which should be used?

Secondly, when i'm currently displaying 08.02.2015 - 01.02.2015 and switch to "month"-interval, but the earliest entry ist on 24.01.2015, what should i display?

**Comment by drdla** [comment]
> We have currently 2 database tables (payment_history and post_view_statistic) for our Dashboard. Both can have a different "earliest entry date". Which should be used?

Given that there can be no purchase prior to a view, I would say post_view_statistic.

> Secondly, when i'm currently displaying 08.02.2015 - 01.02.2015 and switch to "month"-interval, but the earliest entry ist on 24.01.2015, what should i display?

Switching the interval always resets the view so that it shows that interval going back from the current date.
This should also answer your other questions.

**Comment by Chrico** [comment]
> Switching the interval always resets the view so that it shows that interval going back from the current date.

Yep, but the switch from "week" + "08.02.2015 - 01.02.2015" to "month" would be "08.02.2015 - 08.01.2015". But we have only entries beginning at 24.01.2015. So the month-statistic is not correct, because the 08.01.2015 - 23.01.2015 are not existing.

**Comment by drdla** [comment]
How is that different from any other incomplete interval?

**Comment by Chrico** [comment]
its not differnt, the question was just about: how should we handle this with "cant step backwards if no data available".

**Comment by Chrico** [comment]
@drdla nearly done. 

Do we also use the [JavaScript Coding Standards](https://make.wordpress.org/core/handbook/coding-standards/javascript/) for JavaScript?

**Comment by drdla** [comment]
If we do, we do it coincidentally :-) LaterPay has clear (internal) coding standards for Javascript which I would like to apply here as well. All the Javascript code in this repo is done in this style.

**Comment by Chrico** [comment]
Ok, because the WordPress Coding Standard uses "Indentation with tabs.". LaterPay uses spaces?

**Comment by drdla** [comment]
yup

**Comment by twoldrich** [comment]
*Just tested with the current feature branch 562*

**Future intervals**
Today (16.02.2015), I should see data until yesterday (15.02.2015), but in the daily view, I see two times the 14th:
![screenshot 2015-02-16 12 02 48](https://cloud.githubusercontent.com/assets/6638286/6210842/f3156ae0-b5d3-11e4-88df-74f3fb96ff14.png)

**Tooltip for next interval**
If there is no data for the next interval, the respective "next" link is not displayed. Still, the tooltip for "show next..." is displayed:
![screenshot 2015-02-16 11 48 20](https://cloud.githubusercontent.com/assets/6638286/6210863/449c6558-b5d4-11e4-8d44-54ce43e266fd.png)

**Comment by Chrico** [comment]
@twoldrich 
thanks a lot! It seems, that something went wrong on my merge. I've readded the correct.

Have to check where the tooltip is generated. Will try to fix this with my next commit.

**Comment by drdla** [comment]
The tooltip is generated from a data attribute using CSS

**Comment by drdla** [comment]
https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/views/backend/dashboard.php#L57

**Comment by Chrico** [comment]
yep, but i have to find the javascript and unbind the event. Don't want to empty that data-Attribute when next/prev is disabled. :/

**Comment by drdla** [comment]
@Chrico I couldn't confirm
> Switching the interval always resets the view so that it shows that interval going back from the current date.
to be working as intended in the new 562 branch. Please have a look at that.

**Comment by drdla** [comment]
Remaining bugs:
- [ ] It should be possible to switch to the current day, if the interval is set to '24 hours'
- [ ] It should not be possible to switch to an interval in the future, if the interval is set to '2 weeks' or '1 month'

**Comment by Chrico** [comment]
i've moved the "TODOS" to the first issue.

@drdla
cant reproduce the second one. But lets talkt in Skype about this 2 new Todos.

**Comment by Chrico** [comment]
@drdla ok, last point is also implemented. The user can now switch to "today" for interval "day".
