### ISSUE TITLE
Time pass analytics page

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#563]
Merchants need a separate dashboard for time passes, so they can e.g. evaluate the performance of different time passes and target ending time passes with marketing campaigns.

~~This page is only displayed, if at least one time pass is active.~~ (see https://github.com/laterpay/laterpay-wordpress-plugin/issues/563#issuecomment-71456339)
The merchant should be able to switch the dashboard page between the normal KPI view and the time passes view (this link is not yet included in the mockup).

![time-pass-analytics-mockup](https://cloud.githubusercontent.com/assets/135148/5898768/061ce6d6-a553-11e4-9ab9-c2061cd096da.png)

This additional dashboard shows
- Data for **all currently active time passes** ('All Time Passes') and each **individual active time pass**
- A time pass is **active**, if it **has been redeemed and is valid for >= 1 day**
- The conditions of the individual time pass (one sentence as displayed on the time pass, including price and revenue model)
- Figures for
  - number of time passes ever sold ('sold')
  - number of currently active time passes ('active')
  - number of gift cards that have not yet been redeemed ('unredeemed'); only displayed if gift cards are defined for this time pass
  - raw revenue ('committed'), i.e. price * number sold; this is raw revenue, because if the time pass was sold as PPU item, the amount might only be paid in the future
  - actual revenue ('paid'), i.e. money actually paid and received by LaterPay 
- A simple column graph showing the **number of time passes expiring by week** (from now), highlighting the number of time passes that are expiring in < 1 month and the number of time passes expiring in > 1 and < 3 months

**Comment by drdla** [comment]
We could simplify the initial implementation by skipping the "active" criterion.
So let's just display all the data we have and then add a filter for "show only active time passes" later.

**Comment by drdla** [comment]
Depends on implementation of #567

**Comment by drdla** [comment]
1. Should we get all time passes statistics for all period of time, or this period is limited?
    -> all time
2. Should i get raw commited price from purchases table?
    -> yes
3. From where i can get paid amount for all time passes?
    -> dammit, you can't...
4. For all time passes statistics graph shows all time passes expiry and what graph shows for invidual time passes?
    -> the exact same thing, only for a specific time pass: when do the sold units of that time pass expire?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Basically feature is implemented. Now need to add styling and improove graphs.

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft please output the time pass conditions on https://github.com/laterpay/laterpay-wordpress-plugin/commit/865d0519cbfc66eeff17b777a3e9e78a1ec04e02#diff-ce79459b7e866f317076ac8a460f978bR222

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft I prepared the navigation submenu, but there are a few TODOs left on that, see the comments in my last commit.
Do YOU want to finish that or should I assign the issue to @yastapenko-ScnSoft ?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla I see, js stuff. Should i do FIXME also, or only TODOs?

**Comment by drdla** [comment]
Both please.
Mind you: the submenu should always only show one option: the currently NOT active dashboard view.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Please check. I don't know how you want the switch back mechanism look like, right now we can switch back by clicking on the dashboard link.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Done. Please check.

**Comment by drdla** [comment]
Some styling is still missing.

**Comment by twoldrich** [comment]
The individual time pass statistics display correct data but the "summary" for all time passes remains empty for me (tested with current master).
![screenshot 2015-02-23 17 46 17](https://cloud.githubusercontent.com/assets/6638286/6332149/f83ec858-bb83-11e4-98f9-12465ebc7c9c.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Seems that ajax broken on summary. Will be fixed.

**Comment by twoldrich** [comment]
@drdla just notices that the last row (Time Pass Software) obviously shows an issue:
It cannot be that a timepass is **sold**, **active** and **unredeemed**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
It can be: if you purchase a gift and not redeemed a code.

**Comment by twoldrich** [comment]
But the definition for an **active** time pass (from the description of this ticket) is 
> "has been redeemed and is valid for >= 1 day"
In my opinion, it wouldn't make sense to count a not-redeemed gift as "active".

**Comment by AliaksandrVahura-ScienceSoft** [comment]
For me active time pass - time pass that currenly gives access to the various content for user.

**Comment by drdla** [comment]
Exactly. And if you purchased a gift code, which has not been redeemed, then the holder of that gift code does NOT have access, thus: NOT active.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Yeah, you are right. Will be fixed also. So we need to display time passes as active if they valid for >= 1 day, right? So time passes for hour will never been displayed as active.

**Comment by drdla** [comment]
Good point. Should we change the criterion to valid >= 1 second?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Better just to leave it as it works right now ) in real time. Need to fix gift passes displaying as active.

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft it would be nice to scale all y-axes of the diagrams identically. For that we need the maximum y-value across all **individual** time pass diagrams so we can assign that as y-axis scale.
Can you take care of that?
The value has to be passed to the diagrams in https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/asset_sources/js/laterpay-backend-dashboard.js#L761

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Sure

**Comment by drdla** [comment]
Assigned to @AliaksandrVahura-ScienceSoft for fixing the scaling thing.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Please review and check if all work ok.
