### ISSUE TITLE
Website not accessible after updating the plugin to 0.9.10

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#564]
We have two reports from customers, that their sites were not accessible after updating the plugin to version 0.9.10.

They reported that there is "some strange token in the URL".

**Comment by Chrico** [comment]
i've tested this with the wp.org-Plugin on a new local machine. Works fine for me. Same goes for updateing the plugin from 0.9.9 to 0.9.10.

It would be helpful to get some more informations (hosting provider, server, php version, ... ) or at least access to the WordPress and FTP/SSH to check the error logs.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Also tested on new installation with versions from wp.org and from git. No errors for me. Need error text and URL example.

**Comment by twoldrich** [comment]
A reported that he cannot access the "posts" section and create / edit posts because the page "remains white" when activating the plugin. @Chrico is informed and has access to the customer's WordPress backend.

**Comment by Chrico** [comment]
There are many plugins installed which can cause this error. So we have to debug this, maybe there is a collision with another plugin. "White screen" always means: _fatal error_ and _debug_display = off_.

When we don't get any FTP-login, than he should debug his installation: https://marketpress.de/2014/wp-debug-log-fehlermeldungen-in-wordpress-ausgeben/  and send us some more informations (debug.log).

**Comment by twoldrich** [comment]
The customer will send us FTP credentials as soon as he's at home again.

**Comment by twoldrich** [comment]
I added some infos to our internal development channel.

**Comment by twoldrich** [comment]
There seem to be two issues:
1. Website not reachable after update: As already discussed in the development channel on Skype, the problem seems to be that after updating the plugin, the API-URLs on the advanced settings page is empty in some rare cases. Activating and deactivating the plugin helped the customer to solve the problem.
2. The empty "posts" section and "create / edit" post page - @Chrico This occurs only for one single customer who has sent us his credentials for FTP and WordPress which I will forward you in our development channel.

**Comment by Chrico** [comment]
This is not directly a LaterPay problem. I've checked his installation and error.log. When the new LaterPay-Plugin 0.9.10 is enabled, the WordPress-Backend will get following error:

```
[29-Jan-2015 06:14:11] PHP Fatal error:  Allowed memory size of 67108864 bytes exhausted 
```

This problem is caused, because the memory_limit is set to 64M:

```php
echo ini_get( 'memory_limit' );
```
![image](https://cloud.githubusercontent.com/assets/3417446/5953306/dcd6085c-a787-11e4-880c-57ec89d8a0d8.png)

Setting the WordPress-constants to a higher value (128M, 258M) will not affect the memory limit. It seems, that the user has no rights to set this value ( `ini_set()` ):

```php
define( 'WP_MEMORY_LIMIT', '256M' );
define( 'WP_MAX_MEMORY_LIMIT', '256M' );
```

Best thing would be, that the user contacts his hoster and asks for setting the memory limit to 128M or better 256M.

**Comment by twoldrich** [comment]
@Chrico Thank you, I already forwarded your answer to the customer – so that's not a plugin issue, that's good.

So basically, the remaining issue is:

> 1. Website not reachable after update: As already discussed in the development channel on Skype, the problem seems to be that after updating the plugin, the API-URLs on the advanced settings page is empty in some rare cases. Activating and deactivating the plugin helped the customer to solve the problem.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
This ticket can be closed.
