### ISSUE TITLE
Add shortcode for time passes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#572]
It should be possible to display the time passes widget within a post by using the shortcode [laterpay_time_passes]. 

- [x] Add shortcode [laterpay_time_passes] ( @AliaksandrVahura-ScienceSoft ) 
- [x] Document shortcode in appearance tab ( @twoldrich )

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done. Need to add proper description of shortcode options to the shortcode function description and document shortcode in appearance tab.

**Comment by drdla** [comment]
Time passes shortcode will work only if custom position is enabled, as we can have only 1 time passes widget rendered on the page at the same time.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Merged. Please check and close if all ok.
