### ISSUE TITLE
Apply category default price also to subcategories

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#573]
Currently, our category default prices don't handle the fact that a category can have a **"parent" category**. So there can be a category **"News"** and the categories **"Sport News"**, **"Tech News"**,  and **"Music News"** could have **"News"** as their **parent**.

In short: We should always use the **more specific** category default price:
- So if there is a category default price for the subcategory, we should use its category default price. 
- If there is no category default price for the subcategory, we should use the parent's category default price.

Please also make sure that this logic is also applied to all the cases described in #231.

**Comment by drdla** [comment]
The pricing helper still needs proper documentation https://github.com/laterpay/laterpay-wordpress-plugin/compare/feature/573_apply_category_default_prices_to_subs#diff-eea486ba59824e373f19f282a12db9c7R890

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done. Seems we don't need in additional changes in bulk price editor. But if your opinion is different please notify me.

**Comment by twoldrich** [comment]
I just tested with the current master: 

**What works**
The mechanism of applying the parent's category default price works for posts, which are assigned or unassigned to or from one or several categories **after** the category default price was created (i.e. the category default price existed before a post was assigned to that category).

**What doesn't work**
The parent's category default price is **not applied** to subcategories which where **already assigned to a subcategory** before creating the parent's category default price.
Example:
- Create a new post and assign it to category A2, which is a subcategory of A1.
- Create another new post and assign it to category A1.
- Create a category default price for category A1
-> This price **should** be applied to the post in category A2 **and** A1 but is **only** applied to the post in **category A1**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich I'll check this.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Seems fixed. Please check.

**Comment by twoldrich** [comment]
*Tested with current master*

The issue described in my **previouse comment** (https://github.com/laterpay/laterpay-wordpress-plugin/issues/573#issuecomment-74041693) is working fine now.

There seem to be some further issues left with the automatical assignment of category default prices to subcategories.

**Steps to reproduce:**

I created three posts: One assigned to category A, one assigned to category AA, one assigned to category AAA.

The hierarchy of the categories is:
A (parent of AA and AAA)
_ AA (parent of AAA)
__ AAA

1. I set a category default price for **A** of **0.50** => All posts now have the **correct** price of 0.50.
2. I set a category default price for **AA** of **0.60** => Posts in **AA and AAA** should now have the price of **60**, but **all posts still have a price of 0.50**.
3. I **deleted** the category default price for **AA** => All posts (still) have the **correct** price of 0.50.
4. I set a price for **AAA** of **0.70** => Posts in **A and AA** should still have a price of **0.50**, posts in **AAA** should have a price of **0.70**, but **all posts still have a price of 0.50**.
5. I deleted the category default price for **A** => Posts in **A and AA** now **correctly** use the **global default** price but posts in **AAA** use an **"empty" category default price**. (See screenshot below)

![screenshot 2015-02-13 10 30 36](https://cloud.githubusercontent.com/assets/6638286/6185158/7a0c4c50-b36b-11e4-80da-770c5fa7c757.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Need to fix styling of category select. It looks too wide, and it should be disabled on edit.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Please check it once again and then reassign issue to the @drdla.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Everything works fine now, thank you!
