### ISSUE TITLE
Handle subcategories in time passes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#574]
Currently, our time passes don't handle the fact that a category can have a **"parent" category**.

If a time pass is valid for a category that has subcategories (i. e. categories are using this category as parent), the time pass should also be valid for the subcategories. So a merchant should be able to sell a time pass for the category "News" which includes all subcategories like "Tech News" and "Sports News" as well as time passes for the individual subcategories.

Please also make sure that this logic is also applied to the handling of shortcodes as described in #485.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed.

**Comment by twoldrich** [comment]
Works for me (with current master)
