### ISSUE TITLE
Revenue model PPU for 5,00 € not clickable

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#577]
In the pricing widget on the **Add / Edit Post** page, the "PPU" button is **displayed but not clickable** for a price of exactly **5.00 EUR**. It should be possible to click the PPU button also for 5.00 EUR purchases.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed.

**Comment by twoldrich** [comment]
Works fine for me, thank you.
