### ISSUE TITLE
Plugin must separate statistics data for live and test mode

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#584]
We should store the information, if data was collected in **live or in test** mode. In **live** mode, we should only display data that was collected in **live** mode. In **test** mode, we should only display data that was collected in **test** mode. **Existing data** should be flagged as "collected in **live** mode".

- [x] Store information, if data was collected in live or test mode
- [x] Flag existing data as "collected in live mode"
- [x] Make sure that only data collected in live mode is displayed in live mode and only data collected in test mode is displayed in test mode.
- [ ] Document this fact in the readme.txt.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Purchase history stored "mode" field which shows which environment was used. So purchase statistic is separated. The only is left - separate voucher statistic.

**Comment by twoldrich** [comment]
After talking to @AliaksandrVahura-ScienceSoft , we already store the "live / test mode" information for **purchases**, so the only information left that needs to be separated by "live / test" are the "**Views**" of a post. Existing views should by default be treated as "collected in live mode".

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Depends from #592. Need to backmerge it.

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft is this ready for a PR now that you backmerged master?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
It's not completed yet.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please test. Need 0.9.11 for table update.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Why we use caching for dashboard on the backend?

**Comment by drdla** [comment]
Back in the days we thought that calculating the dashboard data is really costly. For that reason we intended to only update like twice a day and add a link to manually trigger the calculation.
Turns out it is not that much of a problem with the caching that Christian built.
The ability to refresh the data is a leftover in my opinion that could be removed.

**Comment by twoldrich** [comment]
*Testing in progress*

- Views are not separated by plugin mode: The post statistics shows the same number of views for both live and test mode.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Reason: caching!

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Added cache directory delete on mode change. Please check now.

**Comment by twoldrich** [comment]
I just tested with branch 584:
In the post statistics pane, I currently don't see any views (always 0) both in test and live mode.
Purchases are displayed correctly in the post statistics pane.

**Comment by twoldrich** [comment]
Just tested with feature branch 584: Works fine, thank you!
