### ISSUE TITLE
Review and complete documentation

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#591]
The plugin should be documented in a way that makes it easy to understand what is happening and why that is happening.

All functions need to be documented according to WordPress standards.

Inline comments should be used where appropriate.

**Comment by drdla** [comment]
@yastapenko-ScnSoft I just noticed that we do not consistently use singular or plural in the Model and Helper classes. Some are plural (e.g. "LaterPay_Helper_Vouchers"), while most are singular (e.g. "LaterPay_Helper_String"). With the exception of words that only exist in plural form, I would suggest always using the singular form.
Also applies to the respective file and folder names!

**Comment by drdla** [comment]
Not documented at all:
- LaterPay_Controller_Shortcode::add_free_codes_to_passes
- LaterPay_Controller_Shortcode::get_passes_list_by_id
- LaterPay_Controller_Shortcode::ajax_load_gift_action

Inconsistencies in Model and Helper classes not resolved as requested in https://github.com/laterpay/laterpay-wordpress-plugin/issues/591#issuecomment-74074826

**Comment by drdla** [comment]
@yastapenko-ScnSoft if you are changing the class names anyway, please change "Pass" into "TimePass"

**Comment by yastapenko-ScnSoft** [comment]
Renamed. Maybe any other changes is needed in task?

**Comment by drdla** [comment]
- [ ] rename LaterPay_Model_Pass -> LaterPay_Model_TimePass
- [ ] rename LaterPay_Form_Pass -> LaterPay_Form_TimePass
- [ ] apply same naming conventions to form classes

**Comment by yastapenko-ScnSoft** [comment]
@drdla Done in https://github.com/laterpay/laterpay-wordpress-plugin/commit/59e990dff4d524a6168f15f762a0b481bf767312

**Comment by yastapenko-ScnSoft** [comment]
@drdla file renamed
