### ISSUE TITLE
Extend options for unlimited access for custom user roles

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#595]
It should be possible to define, to **which categories** a specific user role has unlimited access.

For that, we need to adjust the form for **"Unlimited Access to Paid Content"** on the advanced settings page:
- [x] Adjust the **description** for this section
> You can give logged-in users unlimited access to specific categories depending on their user role. This feature can be useful e.g. for giving free access to existing subscribers. We recommend the plugin ‘User Role Editor‘ for adding custom roles to WordPress.

- [x] All custom user roles should be **listed**, the currently existing **checkboxes can be removed**.
- [x] Next to each user role, there should be a **select** that lists the options **"all"**, **"none"**, and **all existing categories**.
- [x] The admin should be able to **select one or multiple categories** from that list.
- [x] The respective user role should then have **unlimited access** to all items in the **selected categories** and the **respective subcategories**. 

If the user selects
- [x] **"all"** and **"none"**, the selection should be corrected to **"none"**.
- [x] **"all"** and **one / multiple category/ies**, **"all"** should be **deselected**.
- [x] **"none"** and **one / multiple category/ies**, **"none"** should be **deselected**.

![unlimited access extended](https://cloud.githubusercontent.com/assets/6638286/6171281/41e78600-b2da-11e4-87a7-723374efd274.png)

**Migration and Default**
- [x] For each user role that **has currently unlimited access** (checkbox is checked), **"all"** should be selected after the update. For each user role that **hasn't unlimited access**, **"none"** should be selected.
- [x] The respective user role should then have **unlimited access** to all items in the **selected categories** and the **respective subcategories**. 
- [x] The **default** for **new** custom user roles should be **"none"**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Basically implemented. No ajax used, all done with wp settings api usage. Need to add proper styling and improove view. Also need to add translations.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft I will add translations after it's merged into master.

- [ ] Add proper styling ( @drdla )
- [ ] Test ( @twoldrich )
- [ ] Add translations ( @twoldrich )

**Comment by AliaksandrVahura-ScienceSoft** [comment]
About migration: we have a bug on old version with unlimited access saving. in result it saves only

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Please clarify if styling is complete and if yes we can merge PR into master so @twoldrich can add translations.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Done. Please check  and merge if all ok.
