### ISSUE TITLE
Purchase button is rendered in admin preview

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#600]
A customer reported that the LaterPay **purchase button** is rendered below the post in **admin preview**, if the preview mode **teaser only** is selected. As the admin preview should represent the view **after** a purchase, the purchase button should not be displayed here.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Should be fixed now. Please check.

**Comment by twoldrich** [comment]
As #601 is fixed, I suppose that this ticket can also be closed. We will see, if it works for our customers as well.
