### ISSUE TITLE
Admin preview doesn't respect "default / custom positioning" of time passes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#601]
This issue only affects the **admin preview**:

Even if **"default positioning"** for time passes is selected in the appearance tab, the shortcode [laterpay_time_passes] / the action "laterpay_time_passes" renders the time pass widget in **admin preview**.

Steps to reproduce:
- In the appearance tab, set the positioning of time passes to "default".
- Create a time pass
- Create a free post and use the shortcode [laterpay_time_passes] in it.
- Preview the post in **visitor mode** > The time pass is displayed **correctly below** the post (default position)
- Switch to **admin mode** > The time pass is displayed **within the post content**.

#600 might be related to this issue.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please check.

**Comment by twoldrich** [comment]
Works fine for me.
