### ISSUE TITLE
Add advanced setting to change VAT rate

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#602]
The admin should be able to **change the VAT rate** on the **advanced settings** page.

![vat rate](https://cloud.githubusercontent.com/assets/6638286/6226469/c44af370-b695-11e4-84d5-5ec6499477a5.png)

*This ticket is currently unassigned because at the moment, only "DE19", so 19% VAT is supported according to our documentation."

**Comment by drdla** [comment]
Kind of obsolete because of VATMOSS. Also see #639 ...
