### ISSUE TITLE
Price on time pass flipside is the same for all time passes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#606]
If there are multiple time passes, the price on the flipside (not in the purchase button on the front) is the same for all time passes:

- Everytime a **new time pass** is created, the **price of this new time pass** is displayed on the flipside of **all** time passes.
- Everytime the price of an **existing time pass** is **changed**, this **new price** is displayed on the flipside of **all** time passes.

**Comment by twoldrich** [comment]
Two additional infos:
- This only appears in the backend / pricing tab
- After reloading the page, all prices are displayed correctly.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fixed.

**Comment by twoldrich** [comment]
Works fine, thank you!
