### ISSUE TITLE
User report (0.9.9.10): Sales are not displayed in statistics tab

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#609]
*This issue is not yet assigned as we are waiting for further information on the exact problem.*

A user reports, that with the **current release** (0.9.9.10), **sales** data in his **dashboard** and **post statistics** are not displayed correctly, i.e. only views but no sales are displayed, although there are (in our database) purchases for the respective post. 

I could **neither reproduce** the issue with the **current release** 0.9.9.10 nor with the **current master**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
It is possible if users not redirected back to the website (popup closed or error that prevent redirect). This way purchase details not saved in purchases table.

**Comment by drdla** [comment]
Bug could not be confirmed. Closing as invalid or maybe fixed by magic.
