### ISSUE TITLE
Allow extensive customization of plugin via hooks

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#612]
We should have lots and lots of hooks to allow users to modify the plugin according to their needs instead of extending the plugin with lots of options.

### Purchase button
- [x] Allow modifying HTML of purchase button

#### Teaser Mode
- [x] Allow choosing the teaser mode (Teaser only / Teaser + Overlay) for each post

#### Teaser Only
- [x] Allow modifying purchase link HTML
- [x] Allow modifying purchase link text

#### Teaser + Overlay
- [x] Allow modifying overlay box HTML (.lp_overlayText)

### Time Passes
- [x] frontend time passes widget -> allow modifying introductory text
- [x] frontend time passes widget -> allow modifying call to action text

### Roles and Capabilities
- [x] LaterPay_Core_Capability::populate_roles_0951 -> allow modifying every $roles array
- [x] LaterPay_Core_Capability::populate_roles_0951 -> allow modifying every set of capabilities that is applied to a role

### Feeds
- [x] LaterPay_Controller_Post::modify_post_content -> return full content or only teaser content for paid posts
- [x] LaterPay_Controller_Post::modify_post_content -> define LaterPay hint text for paid feed items

**Comment by mturalenka** [comment]
remain to do:
- [ ] update ajax calls
- [ ] test all events

**Comment by mturalenka** [comment]
not ready yet, and should be properly tested, lets move this to next release
