### ISSUE TITLE
Remove hidden input in laterpay-backend-account.js

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#613]
A hidden input is used to save the value of a checkbox in the same form, see https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/asset_sources/js/laterpay-backend-account.js#L126
This is really weird and needs to be fixed.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Done. Please check on master and close if all ok.

**Comment by drdla** [comment]
Yay!
