### ISSUE TITLE
Fix broken day names in dashboard diagrams

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#614]
MySQL DAYNAME function returns "Monday" instead of "Mon".
It also does not allow to localize the day names.
The day names should be formatted by PHP.

**Comment by drdla** [comment]
Sooo... in quite a messy change which I directly pushed to master to make things even messier, I changed all models that retrieve day_name to not use the MySQL DAYNAME function.

Problem:
- [ ] day_name needs to be formatted by PHP in all places where it is rendered
- [ ] LaterPay_Helper_Dashboard generates day_names for missing values in get_days_as_array and fill_empty_days as gmdate( 'D', $item->day_name ), which can't be formatted later on with the function mentioned above

**Comment by drdla** [comment]
Should we delete all existing dashboard cache files in order to fix the wrong day names in them?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Yeah, cahce should be updated... I don't like cache on admin area ))

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Please check.
