### ISSUE TITLE
Abort Ajax requests on dashboard if user has already switched again

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#619]
E.g. when clicking through intervals on the dashboard you can witness that the Ajax requests for the dashboard data are always received and the result rendered, even if you have requested the next interval in the meantime.
I would be better to abort running requests, when a new request is sent.

See http://jsfiddle.net/s4pbn/3/ for an example how to do this.

**Comment by Chrico** [comment]
@drdla should be done. Please merge and close #650 if everything is ok. :-)
