### ISSUE TITLE
Data for dashboard graph are not generated correctly

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#624]
Tested with current master. The time pass dashboard does not show any graphs although there should be sales data (I actually made some purchases).
@drdla mentioned that there is no Javascript error (i.e. only 0-values are delivered for the graph).

![screenshot 2015-02-24 20 09 58](https://cloud.githubusercontent.com/assets/6638286/6357052/eb162188-bc61-11e4-80db-51675f7bbbae.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
This is the caching problem for sure. Should we ignore caching on the time passes statistics page?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Is this solution ok for now? probably i should prevent also cache files creation for the timepasses statistics. At least now time passes will be actual always.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Please check now.

**Comment by twoldrich** [comment]
Tested with current master:

- [ ] The summary row doesn't display any graphs.
- [ ] Redeemed voucher codes are counted as "active" but not displayed in the graph.
(See Time Pass 2 and 3 on the screenshot: I bought three gift card vouchers for time pass 2 and 3 and redeemed some of them).
- [x] For regular time pass purchases, the correct information is displayed.

![screenshot 2015-02-25 10 04 02](https://cloud.githubusercontent.com/assets/6638286/6367720/4ec2355e-bcd6-11e4-812f-a478f6191225.png)

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft and me couldn't reproduce the two latest issues anymore, so this seems to work fine now.
