### ISSUE TITLE
Flash messages show inverted results

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#625]
Changing the toggles for position of purchase button and displaying of time passes on the appearance tab renders flash messages that confirm the exact opposite of what should be active.
E.g. when changing to "custom position" it confirms that the buttons are rendered in their default position.

**Comment by twoldrich** [comment]
This was a translation error (should only have appeared for German language settings), which I fixed yesterday evening with https://github.com/laterpay/laterpay-wordpress-plugin/commit/446a46d8d5306a799f85e11d9f9f50f279bc5aa6
