### ISSUE TITLE
Redeeming a voucher should not be counted as sale

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#626]
Redeeming a voucher for a time pass is counted as a regular purchase of this time pass (because it actually is a 0-EUR purchase). That means that purchasing the gift card is counted as one sale and redeeming the voucher is another sale.

@AliaksandrVahura-ScienceSoft You already came up with an idea how to improve this - could you please comment on that?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Probably we need additional field redeemed cause actually client got money only once - when gift code was sold. Gift codes can be redeemed several times, based on settings. Redeem will only activate time pass for user (will increase active stat).

**Comment by drdla** [comment]
I would count a time pass gift card as redeemed, as soon as it was redeemed 1 time (so ignore the fact that it can be and maybe was redeemed multiple times).

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Makes sense. But we really should not calculate as sold purchases with zero cost or no?

**Comment by drdla** [comment]
Correct: We should not count that as a purchase at zero cost.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
For all redeems?

**Comment by drdla** [comment]
Redeeming a gift code is not a purchase. Never.

My comment https://github.com/laterpay/laterpay-wordpress-plugin/issues/626#issuecomment-75963331 referred to the 'unredeemed' and 'active' KPI on the timepass dashboard.
A timepass that was purchased as a gift card becomes 'active', when the gift code was redeemed the first time. Additional times that gift code was redeemed should not in any way be counted.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
That's not logical. For example: user buyed gift code which can be used 3 times by settings and give this code to 3 his friends. Each friend redeemed a code. Code was purchased 1 time, activated 3 times. In result sold 1, active 3, unredeemed 0.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I mean we should calculate each activation of time pass.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done, please check.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft  It seems that for the "total" row, redeemed voucher codes are still counted as sales:

![screenshot 2015-02-25 17 28 41](https://cloud.githubusercontent.com/assets/6638286/6374881/fbb85648-bd13-11e4-885b-174c56a36bc9.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fixed, please check.

**Comment by twoldrich** [comment]
Works fine with current master.
