### ISSUE TITLE
User report (0.9.11): For posts with excerpt, always the full content is displayed 

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#629]
One of our customers reports, that for posts, which use the WordPress "excerpt" (i.e. this field is not empty), always the full text is displayed, even if the user should see the teaser.

I tested with the current release and cannot reproduce the issue.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I confirm that we show full content for excerpts. Do we need to remove this?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Probably it cause of this fix: https://github.com/laterpay/laterpay-wordpress-plugin/issues/576.

**Comment by drdla** [comment]
I think the intended behaviour is pretty straightforward:
If it is a paid post, we show the teaser content as preview, not the excerpt.
(we have functionality that makes sure that we always have teaser content, so the result can not be empty)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed. Please check.

**Comment by twoldrich** [comment]
Works for me, I tested the following with the current master:
- I created a post A with teaser, full content **and excerpt**.
- I created a post B with teaser, full content and **no excerpt**.
=> LaterPay works for both of them correctly (I see the teaser before the purchase and the fulltext afterwards)
