### ISSUE TITLE
User Report: Error message on saving "Settings>LaterPay"

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#630]
A customer reported, that he receives the following error message when saving (even without changes) the advanced settings (Settings>LaterPay):

Warning: Invalid argument supplied for foreach() 
in /.../wp-content/plugins/laterpay/application/Controller/Setting.php on 
line 634
Warning: Cannot modify header information - headers already sent by 
(output started at 
/.../wp-content/plugins/laterpay/application/Controller/Setting.php:634) 
in /.../wp-includes/pluggable.php on 
line 1178

(Note: I replaced customer specific URLs by "...")

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Wrong label for commit. It belongs to #629.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed. Please check.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Error appeared during data validation after settings save, if no custom roles present in system then it supplies null value for foreach - in result we got fatal error.

**Comment by twoldrich** [comment]
Works fine for me with the current master.
I tested saving the advanced settings with and without changes on a system without custom user roles.
