### ISSUE TITLE
[Insight] Code should not be duplicated - in laterpay/application/Controller/Post.php, line 624

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#634]
**[in laterpay/application/Controller/Post.php, line 624](https://github.com/laterpay/laterpay-wordpress-plugin/blob/7cae221ffba9cae420e06135a704cb9ff1d42da5/laterpay/application/Controller/Post.php#L624)**

> The next 31 lines appear both in `laterpay/application/Controller/Post.php:624` and `laterpay/application/Helper/Post.php:156`.

```php
     *
     * @param int $post_id
     *
     * @return string url || empty string if something went wrong
     */
    public function get_laterpay_purchase_link( $post_id ) {
        $post = get_post( $post_id );
        if ( $post === null ) {
            return '';
        }

```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c0535748-172c-4419-8403-e3be9715aa53/analyses/1)_

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done.
