### ISSUE TITLE
[Insight] Code should not be duplicated - in laterpay/views/…/post/gift/gift_card.php, line 9

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#635]
**[in laterpay/views/frontend/partials/post/gift/gift_card.php, line 9](https://github.com/laterpay/laterpay-wordpress-plugin/blob/7cae221ffba9cae420e06135a704cb9ff1d42da5/laterpay/views/frontend/partials/post/gift/gift_card.php#L9)**

> The next 39 lines appear both in `laterpay/views/frontend/partials/post/gift/gift_card.php:9` and `laterpay/views/frontend/partials/post/gift/redeem_gift.php:9`.

```php
    <?php foreach ( $laterpay['passes_list'] as $pass ): ?><?php
            $pass = (array) $pass;

            $title = sprintf(
                '%s<small>%s</small>',
                LaterPay_Helper_View::format_number( $pass['price'] ),
                $laterpay['standard_currency']
            );

            $period = LaterPay_Helper_TimePass::get_period_options( $pass['period'] );
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c0535748-172c-4419-8403-e3be9715aa53/analyses/1)_

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done. Please review.
