### ISSUE TITLE
Review and fix use of exit() functions

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#638]
Sensiolabs Insight complains about our use of exit() in a lot of places, see https://insight.sensiolabs.com/projects/c0535748-172c-4419-8403-e3be9715aa53/analyses/13?status=violations#225109365.

Those occurrences should be reviews and fixed, similar to https://github.com/frmwrk123/de.plugins-zum-selberbauen.ultimate/commit/471c310afd0a5c958e63d9e0b379812beb396cc4

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done. Please check.
