### ISSUE TITLE
Don't try to identify and track users on free posts / pages

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#641]
There is no need to

* [x] log access
* [x] check / set a lptoken

if the user is not on a paid post.

This just consumes resources and leads to unexpected problems (e.g. entire site not accessible when not accepting cookies).

**Comment by Chrico** [comment]
__log access__
But currently we're checking, if the Post is purchaseable: https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Controller/Statistic.php#L63 ? This should work.

**Comment by mturalenka** [comment]
@Chrico e.g.
`$post` - free post, so we shouldn't track it
`LaterPay_Helper_Pricing::is_purchasable( $post ) == false`
`! LaterPay_Helper_Pricing::is_purchasable( $post ) == true`

we go into if condition, that returns 'false' and as result of function `$this->check_requirements()`
```
public function add_unique_visitors_tracking() {
if ( ! $this->check_requirements() ) {
    return;
}
```
`! $this->check_requirements() == true`
so we will leave tracking function - we will not track free post/pages

**Comment by Chrico** [comment]
_check/set lptoken_
added check for `is_single()` and non-purchaseable posts in `create_token()`-method.

Also i changed the `WP_Post` param from `LaterPay_Helper_Pricing::is_purchasable` to `int $post_id`, because we only need the id.

**Comment by drdla** [comment]
@Chrico 
We shouldn't check and create tokens on the home page either I think. Usually you can not purchase from the home page.
For the rare cases that allow this (-> gutjahr.biz), we could wrap the conditional with a hook, so they can modify the check, if they need to.
Opinion, @Chrico?

**Comment by Chrico** [comment]
we had some similar questions in another issue...i think we implemented this, because on the archive-pages we need the token, because it is possible that there is a purchaseable post with "laterpay_teaser"-Text instead of "the_content".

**Comment by drdla** [comment]
So would it make sense to exclude only the homepage then?
Again wrapped in a hook that allows to change this.

**Comment by drdla** [comment]
With "only the homepage" I mean "purchasable single posts + the homepage"

**Comment by Chrico** [comment]
Hm i would prefer wait with the creation of the token until the first purchaseable post was found. So we would only trigger this "create_token" if really required. The hook sounds also good, but could lead into several other problems. :-(

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I already wrote in #545. We can render timepasses and gift passes on the non-single pages and free posts and it can be purchased...

**Comment by drdla** [comment]
Excellent point...
Can we detect this?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I assume:
1. We can check if gift/timepass shortcodes/actions was used and has data and call check_token if yes only. This only actual for non-single pages and free posts.
2. Call check_token on all pages.

**Comment by Chrico** [comment]
But currently the "check_token" is only called once per page. If we check on every gift/timepass and post for the token, this would cause huge performance problems.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
No, i propose just detect this fact, and call once as usually.

**Comment by Chrico** [comment]
in past we had something similiar with posts and the token check. Also the "create_token" needs a lot of memory because of Browscap. :-(

**Comment by drdla** [comment]
Ok. We should then best offer an advanced setting that allows to disable the token check on the homepage, if the admin is really, really sure that there are no purchasable posts, time passes, or gift cards on the homepage. This will be created as separate issue.
