### ISSUE TITLE
Allow users with role "editor" to view dashboards

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#642]
A user with role 'editor' should be able to view statistics.

Specifically, he should be able to view
- the post statistics pane,
- the normal dashboard, and
- the time passes dashboard

I also suggest to rename 'laterpay_read_post_statistics' to 'laterpay_read_statistics'.

**Comment by Chrico** [comment]
The Editor already can see the statistic pane (in frontend) because of the cap [laterpay_read_post_statistics](https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Core/Capability.php#L34).
