### ISSUE TITLE
Harmonize terminology used in code

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#646]
Consistent terminology should be used throughout the entire codebase.
Currently we have a mixture of terms for key components.

The offical terms are
- "time pass", not "pass"
- "gift card", not "gift pass" or "gift"
- "voucher code"

@twoldrich input please

**Comment by twoldrich** [comment]
I collected a bunch of terms from the plugin, which could be quite likely confused or used inconsistently. For better context, I added a description. The "Not" column contains examples for terms that should not be used – it doesn't necessarily mean that they actually appear in the code.

Term | Description / Context | Not (Examples)
---- | --------------------- | --------------
post | Piece of content | article
dashboard | The tab "Dashboard" in the plugin backend, that displays general sales statistics | statistics dashboard
time passes dashboard | A dedicated subpage of the "Dashboard" tab, that displays statistics related to time passes | time pass dashboard
statistics | All sales and usage data collected by the plugin | data
post statistics | Statistics data for an individual post | statistics pane
statistics pane | Container for post statistics | statistics panel
conversion | KPI: Items Sold / Views | conversion rate
time pass | Item that gives time-limited access to content | timepass, pass
global default price | Price, that is used for every post without category default price or individual price | global price, global standard price
category default price | Price, that is used for every post in a specific category without individual price | category standard price
individual price | Price, that is used only for a specific post | price
change | Action of changing a setting | edit
save | Action of saving a setting | confirm
delete | Action of deleting a setting | remove
purchase | Purchased item | sale
buy | Action of purchasing | purchase
ppu | Revenue model pay per use | pay per use
sis | Revenue model single sale | single sale
user role | WordPress default or custom user role of the current user with according capabilities | role, user group
gift card | Form, that allows purchasing a voucher code | gift, voucher, gift pass
redeem | Action of using a voucher code to buy a time pass for a reduced price (or for free) | use
preview mode | Setting, that defines how posts are presented before purchase | teaser preview
teaser only | Teaser mode, that displays only the teaser and a purchase link below | only teaser, mode 1
teaser and overlay | Teaser mode, that displays the teaser and an excerpt of the full content under an overlay | overlay, mode 2
admin preview | Preview of a post as a user would see it after purchase | admin mode, admin view
visitor preview | Preview of a post as a user would see it before purchase | visitor mode, user preview 
voucher code | Code created by the merchant or purchased by the user, that allows purchasing a time pass for free or for a reduced price | voucher
content rating | Feature, that allows rating purchased posts on a 1-5 stars scale | rating
shortcode box | Box, that is rendered for the shortcode [laterpay_premium_download] | shortcode
laterpay purchase button | The LaterPay purchase button | purchase button, buy button
laterpay invoice indicator | The LaterPay invoice indicator | laterpay invoice
laterpay account links | Links, that enable logging in to or out from LaterPay | laterpay links, account links 
laterpay credentials | Set of merchant ID and API key | credentials
(in)visible test mode | Test mode, that is (in)visible for a regular (logged-out) visitor | public test mode
plugin mode | Setting, that defines, if the plugin is in test or live mode | mode
laterpay merchant id | 22 characters string, that identifies the merchant for LaterPay | merchant credentials, id
laterpay api key | 32 characters string, that authorizes transactions of the respective merchant | key
live mode | Plugin mode, that enables real transactions | livemode
test mode | Plugin mode, that enables test transactions against the LaterPay sandbox | testmode
default | Initial value of an object, e.g. the title of a new time pass | standard
full content | Content, that is unlocked after purchase | full text
teaser content | Content, that is displayed before purchase | teaser
toggle | Interface element that lets the user switch between two options | switch
caching compatibility mode | Mode that allows  | caching mode
time passes widget | Container for all time passes, which are relevant for the current context | time passes
render | Displaying an object | show
