### ISSUE TITLE
Price / revenue model column and pricing widget is missing on post overview

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#647]
Tested with current master:
Currently, the column for price and revenue model is not displayed on the post overview page ("Posts").

**Comment by twoldrich** [comment]
Additionally, the pricing widget on the "add / edit post" page is missing at the moment.

**Comment by twoldrich** [comment]
That's the state of the "Time passes only" mode (no pricing widget, no price / revenue column), so probably this issue is related to that feature?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
The error reason is strict comparison that was added in issue #631.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fixed. Please check.
