### ISSUE TITLE
Remove filters from laterpay_get_plugin_config

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#649]
The filters contained in laterpay_get_plugin_config are obsolete now, because we have either moved those settings to the advanced settings page or changed the interaction with them entirely.
Either way it is safe to say that there shouldn't be any filters for manipulating configurations in laterpay_get_plugin_config.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Filters removed.
