### ISSUE TITLE
Extract Browscap library and include it as submodule

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#653]
Our Browscap library is heavily modified to work properly and require low RAM and CPU resources.
Because it
a) is a modified external library and
b) would benefit all other LaterPay integrations into PHP systems
we should extract it to its own repository and include it as a submodule.

**Comment by mturalenka** [comment]
@

**Comment by drdla** [comment]
Should we rather use Composer or PEAR for including additional LaterPay libraries?

**Comment by mturalenka** [comment]
created  corresponding ticket https://github.com/laterpay/laterpay-wordpress-plugin/issues/751
