### ISSUE TITLE
Improve release-related functions of gulpfile

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#654]
- build all assets
- export files to one folder
    - git export repo
    - git export PHP client submodule
    - git export Browscap submodule

**Comment by drdla** [comment]
Maybe an alternative? https://github.com/dd32/Github-to-WordPress-Plugins-Sync

**Comment by drdla** [comment]
Shell script for that purpose: http://code.tutsplus.com/articles/quick-tip-deploying-a-plugin-from-git-to-wordpressorg--wp-29944

**Comment by drdla** [comment]
A Grunt task for releasing plugins: http://torquemag.io/automating-wordpress-plugin-updates-releases-grunt/

**Comment by mturalenka** [comment]
usage:
`npm install`
`gulp --version 0.9.13 release:production`

will execute next tasks:
        'build',
        'bump-version',
        'changelog',
        'composer',
        'commit-changes',
        'push-changes',
        'create-new-tag',
        'github-release'

**Comment by mturalenka** [comment]
remain to do:
[] update wordpress svn
[] fix assets in svn ( http://websistent.com/fix-your-wp-org-plugin-screenshots/ )
