### ISSUE TITLE
[Insight] Source code should not contain TODO comments - in laterpay/…/Form/GlobalPrice.php, line 108

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#655]
**[in laterpay/application/Form/GlobalPrice.php, line 108](https://github.com/laterpay/laterpay-wordpress-plugin/blob/5045ccf783d257bf1441acf69d5020e39c474dd6/laterpay/application/Form/GlobalPrice.php#L108)**

> TODO comments are left in the code when a feature (or a bug) isn't completely developed (or fixed). You should complete the implementation and remove the comment.

```php
        $this->set_field(
            'laterpay_global_price',
            array(
                'validators' => array(
                    'is_float',
                    // TODO: this is just a dirty hack to allow saving Single Sale prices
                    'cmp' => array(
                        array(
                            'lte' => 149.99,
                            'gte' => 0.05,
                        ),
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/c0535748-172c-4419-8403-e3be9715aa53/analyses/46)_

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Just removed this todo. It was moved from pricing controller together with conditions.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Please review. Probably you want to fix this in other way.
