### ISSUE TITLE
Add "Update Browscap Cache" button to advanced settings page

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#663]
It should be possible to update the Browscap cache file on the advanced settings page (/wp-admin/options-general.php?page=laterpay).
We will add some hint text that tells the user what Browscap is used for.
There should also be some information about the requirements (writable cache dir + some transport mechanism?) and a warning that the user only should click the button, if he is sure that the requirements are fulfilled.

**Comment by mturalenka** [comment]
open question is still: check for requirements

**Comment by mturalenka** [comment]
@drdla so should we add some kind of requirements check here?

**Comment by mturalenka** [comment]
@drdla if texts/descriptions were added, can we close ticket?
