### ISSUE TITLE
[laterpay_gift_card]: Error, if no time pass id is provided

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#664]
*Tested with the current release 0.9.11*

According to #534, the shortcode [laterpay_gift_card] should render gift cards for **all** existing time passes, if **no id="..."** parameter is provided.

Currently, **[laterpay_gift_card]** returns the following **notice** and an according error message, if **no time pass id** is provided, although two time passes exist.
> Notice: Undefined variable: time_passes_list in /var/www/wp-content/plugins/laterpay/application/Controller/Shortcode.php on line 441

![screenshot 2015-03-04 00 58 26](https://cloud.githubusercontent.com/assets/6638286/6475412/23c5550a-c20a-11e4-896f-70f7abf08080.png)

If I use [laterpay_gift_card **id="1"**] or [laterpay_gift_card **id="2"**], the respective gift card is rendered correctly.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please check.

**Comment by twoldrich** [comment]
Gift card shortcode works fine for me now, both **with and without** the **ID** parameter.
