### ISSUE TITLE
Add avanced setting to disable check_token on homepage

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#668]
There should be an advanced setting to disable **check_token** on the homepage.

![disable-token-check](https://cloud.githubusercontent.com/assets/6638286/6504802/5fd5677e-c33b-11e4-8d81-a0e91a3db2a9.png)

*To avoid confusion, I didn't use the word "homepage" as it might be misleading and taken for "this website" – wording can be changed any time.*

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla @mturalenka As i wrote before I think we should disable check_token on all non-single pages, not only on the homepage. And no need for this option. As @mturalenka said, token used only for curl requests to the Lateray and we don't need token for purchase url generation. In result we need token only for paid posts. @mturalenka Please confirm this or me if it's wrong.

**Comment by mturalenka** [comment]
why do we need lptoken?
1) make request to getAccess LP API
2) add_metered_access, get_metered_access(not sure what is it, just came from python library)

so from this part, we need to acquire token only before checking access

What do we have?
1) each request to LP API, handles next responses: 
    invalid_token - we remove current one from cookies
    new_token   - we set new one in cookies
2) we add identify iframe on pages

what can we improve?
1) we can specify redirect url for the indetification link(iframe)
https://github.com/laterpay/laterpay-wordpress-plugin/blob/master/laterpay/application/Controller/Post.php#L1046
according to https://laterpay.net/developers/docs/backend-api#Using/gettokenandaredirect
2) we can acquire new token if we get invalid_token response
3) we can request new token if its empty before calling API

after those steps we can avoid calling get_token for each pages, just only when its required

**Comment by mturalenka** [comment]
so i assume my proposal was accepted and i can proceed. :smile:

**Comment by drdla** [comment]
Yes :-)

**Comment by twoldrich** [comment]
@mturalenka I guess that was done with https://github.com/laterpay/laterpay-wordpress-plugin/issues/799? If yes, please close :)
