### ISSUE TITLE
Add "id" parameter to shortcode [laterpay_time_passes]

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#671]
There should be a parameter **"id"** for the shortcode **[laterpay_time_passes]**, that allows it to display
- **all existing** time passes (id="all").
- **one specific** time pass (e.g. id="2").

If the parameter is **not used**, the shortcode should behave as it does currently and display only the **relevant** time passes.

This would enable the merchant to have a dedicated "time passes page", which really contains **all** existing time passes or promote **one** specific time pass.

- [ ] **Add parameter "id"** for [laterpay_time_passes]
- [ ] **Add error messages**, if wrong time pass ID is provided (as for gift cards)
- [ ] **Document parameter** in appearance tab

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done, please check.

**Comment by twoldrich** [comment]
Using [laterpay_time_passes id="3"], still all relevant time passes are rendered.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Functionality restored, please test once again.

**Comment by twoldrich** [comment]
Unfortunately, I still see all the relevant time passes, even if I use e.g. [laterpay_time_passes id="2"].

**Comment by twoldrich** [comment]
Works fine, thank you, merged.
