### ISSUE TITLE
Not possible to redeem voucher code with [laterpay_redeem_voucher]

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#672]
It is **not possible to redeem** a voucher code in the form rendered by **[laterpay_redeem_voucher]** – I only get the message "XXXXXX is not a valid voucher code."
It **works fine** to redeem a **voucher code** via the "redeem voucher" form rendered by **[laterpay_time_passes]**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Yes, laterpay_redeem_voucher used for gift codes redeem only. I will add voucher codes support.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Should we calculate usages for voucher codes, same as for gift codes?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I've added ability to redeem voucher codes with usage calculation. Waiting for your renponse if we need it.

**Comment by twoldrich** [comment]
Only **gift vouchers** have a limitation. **Voucher codes** can be redeemed **without limit** (until they are deleted).

**Comment by twoldrich** [comment]
Works fine for me.
