### ISSUE TITLE
Customer report: "Undefined" values in dashboard

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#680]
A customer reported, that in his dashboard (release 0.9.11.2), only "undefined" posts are listed instead of actual post titles.

![screenshot 2015-03-10 15 14 30](https://cloud.githubusercontent.com/assets/6638286/6576537/304ce972-c738-11e4-985f-5fe99fe891bc.png)

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft confirmed the issue on his system.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done.

**Comment by twoldrich** [comment]
For completeness sake: Works fine with current master.
