### ISSUE TITLE
Undefined index in views/backend/partials/time_pass.php 

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#691]
PHP Notice:  Undefined index: url in /wp-content/plugins/laterpay/views/backend/partials/time_pass.php on line 35

Version 0.9.11.2

**Comment by larsschenk** [comment]
And
PHP Notice:  Undefined index: is_in_visible_test_mode in /wp-content/plugins/laterpay/views/backend/partials/time_pass.php on line 35

**Comment by twoldrich** [comment]
@larsschenk Thank you for reporting this issue – we will have a look at that!
