### ISSUE TITLE
SERVER_NAME is 'localhost' on cloud hosting platforms. Use site_url() instead.

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#693]
get_current_url() (and some other functions) make use of $_SERVER['SERVER_NAME']. This causes trouble on cloud hosting platforms like Heroku.

Please use wp function site_url() instead to avoid redir=http%3A%2F%2Flocalhost (in the API call URL).

**Comment by mturalenka** [comment]
this is related to https://github.com/laterpay/laterpay-client-php/blob/develop/LaterPay/Client.php#L692
using wp functions is not allowed because its a common library. we need to find some workaround to get exact url
