### ISSUE TITLE
Extend list of user agents in browscap cache file

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#699]
We have several reports of user agents that are not covered by the browscap database.

Example: In "Google Snippet Tool", all page titles are replaced by "LaterPay" and descriptions are deleted. Possibly because of the new 302 status code.

We should have a way of adding user agents that we know about to our cache file.

**Comment by mturalenka** [comment]
the idea of the browscap file is a set of regexps that point particular browser with properties(is_crawler, support cookies)
so here we need to 
1. allow user enter regexp query
2. add checkboxes to check available property
3. submit data, and store it within wp options

so here is the main problem is to create necessary regexp query: by user(somehow) or transform user-agent into regexp query by the plugin. i dont think that we can actually use "==" for comparing

**Comment by mturalenka** [comment]
@drdla what do you think?

**Comment by drdla** [comment]
We should check, if using the full version of browscap doesn't fix our problems already. E.g. the rivva crawler was missing from the list we had used so far. If that is included (which I would almost expect) then we can close this issue altogether.

**Comment by mturalenka** [comment]
as i can see in full_php_browscap.ini file there is no any entry of 'Rivva' but perhaps it can be covered by some another regexp, so let me know after check

**Comment by twoldrich** [comment]
Are there any news on that ticket? We have an open support request concerning the rivva crawler and I would like to give the customer an update.

**Comment by twoldrich** [comment]
A user reported issues with the RSS feed for the iOS RSS Reader app "Newsify".

**Comment by mturalenka** [comment]
need to test with latest browscap version

**Comment by twoldrich** [comment]
@mturalenka Do you have a status update on that ticket? A content aggregator wrote us (rivva), that there still seems to be an issue.

**Comment by mturalenka** [comment]
@twoldrich unfortunately there is no such crawler in latest browscap library

**Comment by twoldrich** [comment]
@mturalenka thanks for checking – could we add it manually?

**Comment by mturalenka** [comment]
@twoldrich how can we figure this crawler User-Agent, quick research didnt help?

**Comment by mturalenka** [comment]
looks like it is `Mozilla/5.0 (compatible; Rivva; http://www.rivva.de) `

**Comment by mturalenka** [comment]
so we have two solutions:
1) setup browscap service https://github.com/browscap/browscap, and generate each update by our self, 
+ it would be possible to update browscap lib in correct way, with only set of required fields only, as result(small size of the ini file ) reduced requirements for the cache update process
+ plugin will not be changed, except browscap update URL
+ we will not have download rates, like browscap.org already has
- need separate service to generate and distribute browscap.ini file
2) write workaround in php library to use external rules

**Comment by mturalenka** [comment]
@twoldrich  will you check after new release or could upload updated cache file ?
generally is it possible to debug rivva crawler somehow ?
