### ISSUE TITLE
Price input in pricing widget not clickable

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#700]
If both **indicators for PPU and SIS** are displayed, it's (almost) **not possible** to **enter the price input** by clicking into the input. You can only enter the price input by clicking in a very small area at the bottom of the price input – probably, there's some kind of **overlapping** issue.

![image](https://cloud.githubusercontent.com/assets/6638286/6898931/6b2c91d0-d6fd-11e4-90a4-d998c259f080.png)

Steps to reproduce:
- Go the Add/Edit Post page
- Enter an individual price of **5.00 EUR or higher** (So indicators for PPU and SIS will be displayed)
- Try to enter the price input by clicking into the input.

**Comment by drdla** [comment]
@twoldrich @avahura http://pesticide.io/ is a handy tool for debugging such problems
