### ISSUE TITLE
Price for time pass voucher codes is not validated correctly

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#701]
The price in the price input for time pass voucher codes is not validated.
It is possible to set e.g. a  price of 0.01 EUR or 2.000 EUR for a time pass voucher code (which makes the purchase fail of course).

![image](https://cloud.githubusercontent.com/assets/6638286/6936160/4fd18906-d84f-11e4-87ca-85f5df382db5.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please check.

**Comment by twoldrich** [comment]
Works fine, thanks!
