### ISSUE TITLE
Purchase dialog is not rendered correctly for time passes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#705]
Clicking the purchase button in a time pass, doesn't show the LaterPay purchase dialog in the iframe, but renders the current website within the iframe. (The dialog is correctly rendered for the "regular" purchase button).

![image](https://cloud.githubusercontent.com/assets/6638286/6946894/a344bd66-d8a3-11e4-8041-9cf389f7e3c6.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Done. Please check.

**Comment by twoldrich** [comment]
Works fine, thanks!
