### ISSUE TITLE
Not possible to select category default price

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#706]
Nothing happens, when I click the "Category Default" button in the pricing widget.

Steps to reproduce:
- Create category default price for a category
- Create new post
- Assign post to category
- Click the "Category Default" button
-> Nothing happens.

@AliaksandrVahura-ScienceSoft Please add details if necessary

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Fixed. Please check.

**Comment by twoldrich** [comment]
Works for me with current master, thanks.
