### ISSUE TITLE
Time passes are not rendered below posts

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#709]
With the current release (0.9.11.3), time passes are not displayed below paid posts by default.
Displaying time passes via Shortcode works fine.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I can't reproduce this bug.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich @drdla I've investigated problem and seems that this is customer specific problem. Modify post content called 9 times on the page. Time passes widget can be rendered only once per page and ignore all other calls. In result time passes never displayed after post content, cause it present only for 1-st post modify content call. Actually this is critical performance issue for customer (multiply post render).

**Comment by drdla** [comment]
Wrong implementation by customer, nothing to do here from our side.
