### ISSUE TITLE
Allow switching into debug mode from plugin

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#713]
It should be possible to switch on the debug mode without firing up a FTP client and modifying the wp-config.php.

This setting should be placed on our advanced settings page.

Ideally, it would only set a different value than that set in wp-config.php, if required.

This means: We should only overwrite the value in wp-config.php, if it differs.
- wp-config.php: define('WP_DEBUG', true); -> do nothing / remove override, if the user wants to have debugging mode ON
- wp-config.php: define('WP_DEBUG', true); -> set WP_DEBUG to FALSE, if the user wants to have debugging mode OFF
- wp-config.php: define('WP_DEBUG', false); -> set WP_DEBUG to TRUE, if the user wants to have debugging mode ON
- wp-config.php: define('WP_DEBUG', false); -> do nothing / remove override, if the user wants to have debugging mode OFF

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft just to clarify: can we do this or should I rather close the issue as wontdo?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla We've discussed this already. We can only turn on/off laterpay debug but not whole WP Debug. If that's enough we can implement this.

**Comment by drdla** [comment]
This feature is about switching the debugger on and off. So that would be enough.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
https://github.com/laterpay/laterpay-wordpress-plugin/commit/a441ef03f56e51341087cb0d3b632b6b4e2adc19

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Now user can turn on/off laterpay debugger separately from wordpress debug mode.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla It it correct implementation? Need to double check section name description and etc.
