### ISSUE TITLE
Add WordPress action that returns if a user has or hasn't access to the current post

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#715]
To enable the merchant to react to the fact that a user has or hasn't access to the current post (e.g. by removing ads for a purchased post), we should provide an action like "**has_access**" that returns "true" or "false".

It should return **true** if the user has access to this post because
- he has **purchased this particual post**
- he has access to this post via a **time pass**
- he has a **user role** with **full access to this post**

For all other cases, it should return **false**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Implemented in branch 731.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Please check and close.

**Comment by twoldrich** [comment]
A little hard for me to test that – @mturalenka could you have a look please?

**Comment by twoldrich** [comment]
@mturalenka Could you have a look at this, please? If it's ok for you, please close the issue.

**Comment by mturalenka** [comment]
could be used in next two ways:
WP style:
```
$access = apply_filters( 'laterpay_check_user_access', $access, $post_id );
```
or based on internal LP events
```
$event = new LaterPay_Core_Event( array( $has_access, $post_id ) );
laterpay_event_dispatcher()->dispatch( 'laterpay_check_user_access', $event );
$has_access = (bool)$event->get_result();
```
