### ISSUE TITLE
Add "comment" field for voucher codes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#716]
To make it easier for the merchant to keep track of his voucher codes, we should add the option to **comment voucher codes**.

When **editing** a time pass, it should be possible to add / edit a comment for each voucher code:
![image](https://cloud.githubusercontent.com/assets/6638286/7114957/44cb4266-e1e3-11e4-9b13-83472ac2d883.png)

This comment should be displayed above the respective voucher after saving the time pass.
![image](https://cloud.githubusercontent.com/assets/6638286/7114929/e8340e02-e1e2-11e4-9a67-03ec25177ee9.png)

For existing time passes, this field can remain **empty**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Feature implemented, i need your help with styling.

**Comment by twoldrich** [comment]
Doesn't have to be in the next release, as @AliaksandrVahura-ScienceSoft said it required extensive testing.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Styling and testing are left.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Need proper styling.
