### ISSUE TITLE
Add alert for time pass purchase button in hidden test mode

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#718]
When trying to purchase a time passes in hidden test mode, there is no alert saying "In live mode, your visitors would see the LaterPay purchase dialog" as for the regular purchase button, but the purchase dialog is displayed instead.

In hidden test mode, the same alert as for the purchase button should be displayed for time passes, too. (As mentioned here for example: https://github.com/laterpay/laterpay-wordpress-plugin/issues/437)

**Comment by OlegHainulin-ScienceSoft** [comment]
done in commit 68837e7a3c4f1570186412b7f809e6b8a1fda9ce
file application\Controller\Post.php : 1206

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Just checked. Not implemented.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
In progress.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Please check and close if all ok.

**Comment by drdla** [comment]
Working.
