### ISSUE TITLE
Localization issue: Prices are not displayed correctly

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#721]
Tested with branch /10_fix_styling_of_editing_category_prices:

When the WordPress language is **German**, prices are not displayed correctly:

**Example:**
- Go to the pricing tab
- Edit the global default price to **0,2** => It is correctly changed to **0,20**.
- Save the global default price => It is changed to **2,00**.

After changing the WordPress language to **English**, everything works fine.

**Comment by drdla** [comment]
Please add this as a comment to the pull request

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla It seems there are problems with value normalization. Should i fix this issue?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Should work fine now, please check.
