### ISSUE TITLE
Don't collect statistics data for posts that are not published yet

### ISSUE THREAD

**Issue by drdla** [laterpay/laterpay-wordpress-plugin#723]
This is closely related to #714 and #714 might even fix this issue already (because it is quite likely that only people with that cap can access a post before it is published), but I would like to have an explicit condition in the tracking functionality that checks if the post is published already and returns otherwise.

**Comment by drdla** [comment]
We should also NOT RENDER THE POST STATISTICS PANE, until a post is published.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done.
