### ISSUE TITLE
Image protection issue with PDF plugin "wp-mpdf"

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#724]
A customer reported that if he tries to print a **purchased post** that contains **images** as PDF with the plugin **"wp-mpdf"**, only the **encrypted links** are displayed in this PDF.

**Comment by twoldrich** [comment]
According to @AliaksandrVahura-ScienceSoft this plugin performs a check for the filetype of each image, which our encrypted link didn't pass. @AliaksandrVahura-ScienceSoft fixed the PDF plugin on the customer's side, so I think this can be closed.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Actually there were 2 small problems:
