### ISSUE TITLE
Automatically show time passes also for free posts in "time pass only" mode

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#725]
If the user switches to "time pass only" mode, we should automatically switch the advanced setting "show time passes also for free posts" to "checked".

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Should we uncheck this option automatically if user disable "time pass only" mode?

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Only if it was unchecked before activating the "time pass only" mode, I would say.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich And how we should monitor this fact? )))

**Comment by drdla** [comment]
Just don't act ;-)

When a merchant switches to "time pass only" mode, we set "show time passes also for free posts" to true.
When a merchant switches back to "time passes and individual purchases" mode, we don't do anything.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Ok.
