### ISSUE TITLE
Pricing widget is not rendered

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#729]
Tested with branch 728_declutter_user_interface:

The pricing widget on the add/edit post page is not rendered.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Pricing widget not rendered for me only in test invisible mode, same on master. Is it a problem?

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Yes, it should always be rendered (no matter if invisible/visible test or live mode), except for the "time-pass-only" mode.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Then i will fix this on master.

**Comment by drdla** [comment]
Just to be sure: we are talking about post_pricing_form.php

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Yes. Actually teaser also not showed in test invisible mode.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Already fixed on master. Please check.

**Comment by twoldrich** [comment]
Works fine on master, thanks.
