### ISSUE TITLE
Better handling of network outage?

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#732]
On  Apr 14, 2015 there was a network outage affecting the sandbox environment: 
http://status.laterpay.net/incidents/z42zd41wwt0x

For that period of time almost the whole site with enabled laterpay plugin was not reachable. Disabling the laterpay plugin fixed the problem.

Q: 
Was this expected behaviour for network outage?
Is a similar failure able to cause the same result on the production environment?
Why is almost the whole site affected? Homepage and even pages that are free were not reachable.

Suggestion:
A single point of failure on the laterpay backend/API should not bring down the whole site consuming the laterpay API.

Free pages should not even suffer from problems at laterpay at all. (Why is there a reason to consume the laterpay API when visiting a free page?)

Even payable content should handle offline layterpay better than just causing 500 from timeout errors.

Maybe this is already possible to achieve with latest version? If so, please point me to the right direction. Thx in advance.

**Comment by drdla** [comment]
see #717

**Comment by drdla** [comment]
I'm closing this as duplicate, because this issue will be addressed in #717
