### ISSUE TITLE
Add revenue model logged-in PPU

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#741]
The revenue model **"PPU"** allows purchasing content for prices between **[0.05 ; 5.00] EUR** (and 0.00 EUR) **without logging in** to LaterPay. We want to give the merchant the choice, if he wants to require the user to login to his LaterPay account before a purchase or not. That's why, we will add the **revenue model "Logged-in PPU"**. Just as "PPU", "Logged-in PPU" should be possible for purchases from **[0.05 ; 5.00] EUR** (and 0.00 EUR), but the user has to **login** to his LaterPay account **before** the purchase.
Technically that’s an additional parameter for the /add API request.

## Available Revenue Models

So in the future, the following revenue models should be available, depending on the price:

Price Range | Revenue Model
----------- | -------------
[0.05 ; 1.48] EUR or 0.00 EUR | PPU, Logged-in PPU
[1.49 ; 5.00] EUR | PPU, Logged-in PPU, SIS
[5.01 ; 149.99] EUR | SIS

## Technical Implementation
For the technical implementation of "Logged-In PPU", please see the LaterPay developer docs on docs.laterpay.net.

## Necessary Changes

For the implementation of "Logged-in PPU", it is necessary to:

- [x] add the revenue model "Logged-in PPU" to the pricing widget
![logged-in-ppu-pricing-widget](https://cloud.githubusercontent.com/assets/6638286/7272282/e5ba2ed2-e8e9-11e4-9233-bc777b7af377.jpg)
- [x] add the revenue model "Logged-in PPU" to category default price and global default price
- [x] add the revenue model "Logged-in PPU" to the time pass form
![image](https://cloud.githubusercontent.com/assets/6638286/7272306/0cc30b7a-e8ea-11e4-8960-2f344780170c.png)
- [ ] add the explanation for revenue model "Logged-in PPU" to the pricing tab
- [ ] add the explanation for revenue model "Logged-in PPU" to the contextual help

## Existing Prices
For existing prices with the revenue model "PPU", nothing should change (i.e. they should not automatically use the revenue model "Logged-in PPU").

## PPU Default
By default, "PPU" (i.e. the currently already existing "regular PPU") should be selected for prices between [0.05 ; 1.48], [1.49 ; 5.00] and 0.00 EUR.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla Need styling.

**Comment by drdla** [comment]
Not deployed yet as an API feature. Moving to next milestone.

**Comment by twoldrich** [comment]
@mturalenka  Still not deployed on the API side – has to be moved.

**Comment by doismellburning** [comment]
This feature should be live now - please let us know if there's any issue!

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Logged-in-PPU should be implemented now on the API side, could you please check, if it's working for the plugin?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Sure, but i need merge this issue branch with master and fix conflicts.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Can you please provide font with lock sign.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Seems it works fine. The only is left - styling.
