### ISSUE TITLE
Adjust calculation of "New Customers" metric

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#747]
According to @AliaksandrVahura-ScienceSoft, the calculation of the dashboard's **new customers** metric is implemented wrong. It should be calculated as follows:

> "Number of users, who purchased something in the reporting period and who had never (ever) before purchased anything." divided by "Number of users, who purchased in the reporting period"

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@drdla @mturalenka About new customers functionality:
1. We detect users by randomly generated used id (stored in cookie).
2. This cookie expiry time 1 month, also it can be deleted by customer.
3. After new cookie created customer became "new" for us (but actually he probably purchased some items already).
We need to do something with it, to keep user id. Any ideas?

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft (Just FYI) In the contextual help, we explicitely say

> The metric New Customers indicates the share of your customers who bought with LaterPay for the first time in the reporting period. **Please note that this is only an approximate value.**

as we were aware of that this can never be measure 100% accurately.
