### ISSUE TITLE
Implement Exceptions handling functionality

### ISSUE THREAD

**Issue by mturalenka** [laterpay/laterpay-wordpress-plugin#749]
instead of tons of variables, like logger within classes, we need to
- [x] Create Exceptions classes
- [x] Wrap code using try..catch 
- [x] Handle laterpay custom exception(call logger, error log etc.)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Depends from https://github.com/laterpay/laterpay-wordpress-plugin/issues/612

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mturalenka Please review current scope of changes.

**Comment by twoldrich** [comment]
@mturalenka @AliaksandrVahura-ScienceSoft Is that done for you? If yes, you can please close the issue?
