### ISSUE TITLE
Add composer

### ISSUE THREAD

**Issue by mturalenka** [laterpay/laterpay-wordpress-plugin#751]
We should use composer functionality instead of git submodules

**Comment by mturalenka** [comment]
@drdla 
according to https://getcomposer.org/doc/00-intro.md#system-requirements Composer requires PHP 5.3.2+ to run. so we cannot use it completely : include autoload.php. because it uses namespaces(php5.3). our minimum php requirement is php 5.2.4. 
currently we need to use in composer 2 libraries - php client and browscap. to by pass restriction we can use our autoloader to include classes from these libs.

**Comment by drdla** [comment]
@AliaksandrVahura-ScienceSoft has already used Composer in the migrator extension and did the required distinction of cases there. Should be easy to copy over.

**Comment by mturalenka** [comment]
@drdla please take a look :)
https://github.com/laterpay/laterpay-wordpress-subscriber-migrator/blob/develop/vendor/composer/ClassLoader.php this code will not work in php 5.2.4.

**Comment by mturalenka** [comment]
so we will use it as: `composer install --no-autoloader --no-dev`
and include in plugin using `LaterPay_AutoLoader::register_directory` function
## Note!
we shouldnt commit vendor directory in github, the only one thing should be here: composer.lock, to reference exact versions

**Comment by mturalenka** [comment]
usage:
dev:
```
to setup:
composer update --no-autoloader
composer run-script wpcs
to use:
composer run-script phpcs
```
prod:
```
composer update --no-autoloader --no-dev
```
