### ISSUE TITLE
Adjust behavior for deleting time passes

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#757]
Currently, when a merchant **deletes** a time pass, a user who bought this time pass will **lose his access**, as this time pass **doesn't exist** anymore.

In the future, we should **not actually delete** time passes after the user removed them, but only **don't show** them anymore to the user and to the merchant.

So
- [x] don't actually delete time passes anymore
- [x] don't show removed time passes to users
- [x] don't show removed time passes in the pricing tab
- [x] adjust the confirm message to "Deleting a time pass cannot be undone."

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Actually we can restore "deleted" timepasses later cause it not deleted actually, so "Deleting a time pass cannot be undone" is incorrect.

**Comment by drdla** [comment]
Totally true. The correct confirm message is "Are you sure?".

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Done. @twoldrich Need to test various time pass and gift pass aspects.
