### ISSUE TITLE
Issue with time pass prices

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#765]
There seems to be an issue with price setting for time passes and voucher codes (current master).

Steps to reproduce:

- Set blog language to English
- Define a time pass for 0.15 EUR
- Define two voucher codes for 0.19 and 0.17 EUR
- Save the time pass

=> So far, everything works fine, both purchasing the time pass and redeeming the voucher codes.

- Set blog language to German
- Add a voucher code to the existing time pass

=> The time pass price is set to 0.00 EUR
=> The two voucher prices are set to 19.00 and 17.00 EUR
=> Redeeming one of the voucher codes sets the time pass price to 1.00 EUR.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich issue with time pass price fixed already in branch velocity, i will check vouchers

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Please check and merge if all ok.

**Comment by twoldrich** [comment]
Works for me, thanks.
