### ISSUE TITLE
Add New Basic Tests

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#769]
## First Basic Tests

The following very few and very basic tests ensure, that users can still purchase individual PPU items and PPU time passes and access them after an update. It should be easy to extend those basic tests (e.g. to SIS purchases or logged-in PPU, different preview modes, different price types) later on, so I tried to make those tests as "modular" as possible. A detailed description for every test step and the used constants (c_...) are outlined in separate sections. Of course, the naming of constants (c_...), parameters (p_...) and modules is only for illustrative purposes.
#### 1. User Can Purchase PPU Item With Current Release

_This test checks, if users can successfully purchase and access a PPU item._

| Step | Parameter | Description |
| --- | --- | --- |
| Login | c_url_test_system, c_user, c_password | Log in to the test system |
| Install | c_current_plugin_version | Install the current plugin version |
| Create_Post | c_post_title, c_fulltext, c_teaser, c_revenue_model_ppu, c_price_ppu, c_price_type_individual, none | Create a test PPU post |
| Logout |  | Log out from the test system |
| Check_Post | c_post_title, p_is_fulltext_visible=false, p_is_teaser_visible=true, p_is_purchase_button_visible=true, p_is_overlay_visible=false, p_is_purchase_link_visible=true, p_are_time_passes_visible=false | Check, if teaser content, purchase button and purchase link are visible and if the fulltext is hidden. Overlay should not be visible (this tests with preview mode "Teaser only") and time passes should not be displayed (as there are none in this setting). |
| Purchase_Post_PPU | c_post_title | Purchase the test post |
| Check_Post | c_post_title, p_is_fulltext_visible=true, p_is_teaser_visible=false, p_is_purchase_button_visible=false, p_is_overlay_visible=false, p_is_purchase_link_visible=false, p_are_time_passes_visible=false | Check, if teaser content, purchase button and purchase link are hidden and if the fulltext is visible. Overlay should not be visible (after the purchase and generally not in this setting) and time passes should not be displayed (as there are none in this setting). |
| Deactivate |  | Deactivate the LaterPay WordPress plugin |
| Delete |  | Delete the LaterPay WordPress Plugin |

**Assertion**: This test passes, if all the conditions of the **last "Check_Post"** step are fulfilled.
#### 2. User Can Purchase PPU Time Pass With Current Release

_This test checks, if users can successfully purchase and access a PPU time pass._

| Step | Parameter | Description |
| --- | --- | --- |
| Login | c_url_test_system, c_user, c_password | Log in to the test system |
| Install | c_current_plugin_version | Install the current plugin version |
| Create_Post | c_post_title, c_fulltext, c_teaser, c_revenue_model_ppu, c_price_ppu, c_price_type_individual, none | Create a test PPU post |
| Create_Time_Pass | c_time_pass_title, c_time_pass_description, c_validity_period, c_validity_unit, c_validity_access, c_revenue_model_ppu, c_price_ppu | Create a test PPU time pass |
| Logout |  | Log out from the test system |
| Check_Post | c_post_title, p_is_fulltext_visible=false, p_is_teaser_visible=true, p_is_purchase_button_visible=true, p_is_overlay_visible=false, p_is_purchase_link_visible=true, p_are_time_passes_visible=true | Check, if teaser content, purchase button and purchase link are visible and if the fulltext is hidden. Overlay should not be visible (this tests with preview mode "Teaser only") and time passes should be displayed. |
| Purchase_Time_Pass_PPU | c_time_pass_title | Purchase the test time pass |
| Check_Post | c_post_title, p_is_fulltext_visible=true, p_is_teaser_visible=false, p_is_purchase_button_visible=false, p_is_overlay_visible=false, p_is_purchase_link_visible=false, p_are_time_passes_visible=false | Check, if teaser content, purchase button and purchase link are hidden and if the fulltext is visible. Overlay should not be visible (after the purchase and generally not in this setting) and time passes should not be displayed (as this time pass has already been purchased). |
| Deactivate |  | Deactivate the LaterPay WordPress plugin |
| Delete |  | Delete the LaterPay WordPress Plugin |

**Assertion**: This test passes, if all the conditions of the **last "Check_Post"** step are fulfilled.
#### 3. User Can Access Individual PPU Purchase (Purchased Before Update)

_This test checks, if users can access a PPU purchase with the current plugin version, which they did with the previous plugin version._

| Step | Parameter | Description |
| --- | --- | --- |
| Login | c_url_test_system, c_user, c_password | Log in to the test system |
| Install | c_previous_plugin_version | Install the previous plugin version |
| Create_Post | c_post_title, c_fulltext, c_teaser, c_revenue_model_ppu, c_price_ppu, c_price_type_individual, none | Create a test PPU post |
| Logout |  | Log out from the test system |
| Purchase_Post_PPU | c_post_title | Purchase the test post |
| Login | c_url_test_system, c_user, c_password | Log in to the test system |
| Install | c_current_plugin_version | Install the current plugin version |
| Logout |  | Log out from the test system |
| Check_Post | c_post_title, p_is_fulltext_visible=true, p_is_teaser_visible=false, p_is_purchase_button_visible=false, p_is_overlay_visible=false, p_is_purchase_link_visible=false, p_are_time_passes_visible=false | Check, if teaser content, purchase button and purchase link are visible and if the fulltext is hidden. Overlay should not be visible (this tests with preview mode "Teaser only") and time passes should not be displayed (as there are none in this setting). |
| Deactivate |  | Deactivate the LaterPay WordPress plugin |
| Delete |  | Delete the LaterPay WordPress Plugin |

**Assertion**: This test passes, if all the conditions of the **last "Check_Post"** step are fulfilled.
#### 4. User Can Access PPU Time Pass Purchase  (Purchased Before Update)

_This test checks, if users can access a PPU time pass with the current plugin version, which they bought with the previous plugin version._

| Step | Parameter | Description |
| --- | --- | --- |
| Login | c_url_test_system, c_user, c_password | Log in to the test system |
| Install | c_previous_plugin_version | Install the previous plugin version |
| Create_Post | c_post_title, c_fulltext, c_teaser, c_revenue_model_ppu, c_price_ppu, c_price_type_individual, none | Create a test PPU post |
| Create_Time_Pass | p_time_pass_title, p_time_pass_description, p_validity_period, p_validity_unit, p_validity_access, p_revenue_model_ppu, p_price_ppu | Create a test PPU time pass |
| Logout |  | Log out from the test system |
| Purchase_Time_Pass_PPU | c_time_pass_title | Purchase the test time pass |
| Login | c_url_test_system, c_user, c_password | Log in to the test system |
| Install | c_current_plugin_version | Install the current plugin version |
| Logout |  | Log out from the test system |
| Check_Post | c_post_title, p_is_fulltext_visible=true, p_is_teaser_visible=false, p_is_purchase_button_visible=false, p_is_overlay_visible=false, p_is_purchase_link_visible=false, p_are_time_passes_visible=false | Check, if teaser content, purchase button and purchase link are hidden and if the fulltext is visible. Overlay should not be visible (after the purchase and generally not in this setting) and time passes should not be displayed (as this time pass has already been purchased). |
| Deactivate |  | Deactivate the LaterPay WordPress plugin |
| Delete |  | Delete the LaterPay WordPress Plugin |

**Assertion**: This test passes, if all the conditions of the **last "Check_Post"** step are fulfilled.
## Test Modules

This section contains all the modules, which are used in the tests above. Each module lists the exact action, that has to be taken and the involved element.
Example: Login(p_url_test_system, p_user, p_password} is the step "Login" that is used for all the tests above. As three parameters, it needs the URL of the test system, the user name for an admin user and the corresponding password. (An explanation of the parameters can be found in the "Constants" section below.)
#### Login(p_url_test_system, p_user, p_password)

_Log in to the WordPress test installation_

| Action | Involved Element or URL |
| --- | --- |
| Go to {p_url_test_system}/wp-admin | id="user_login" |
| Enter user name {p_user} and password {p_password} | id="user_pass" |
| Click "Login" button | id="wp-submit" |
#### Install(p_plugin_version)

_Install and activate a specific version of the LaterPay WordPress plugin_

| Action | Involved Element or URL |
| --- | --- |
| Click the "Plugins" navigation item | ...wp-admin/plugins.php |
| Click the "Add New" button | .../wp-admin/plugin-install.php |
| Click the "Upload Plugin" button | .../wp-admin/plugin-install.php?tab=upload |
| Click the "Select File" button | id="pluginzip" |
| Select the zip file with plugin version {p_plugin_version} |  |
| Click the "Install" button | id="install-plugin-submit" |
| Click the "Activate" link | .../wp-admin/plugins.php?action=activate... |
#### Deactivate

_Deactivates the LaterPay WordPress plugin_

| Action | Involved Element or URL |
| --- | --- |
| Click the "Plugins" navigation item | ...wp-admin/plugins.php |
| Click the "Deactivate" link for the LaterPay plugin | class="deactivate" |
#### Delete

_Deletes the LaterPay WordPress plugin_

| Action | Involved Element or URL |
| --- | --- |
| Click the "Plugins" navigation item | ...wp-admin/plugins.php |
| Click the "Delete" link for the LaterPay plugin | class="Delete" |
| Confirm the question, if you want to delete the plugin |  |
#### Create_Post(p_post_title, p_fulltext, p_teaser,p_revenue_model, p_price, p_price_type, p_category)

_Creates a test posts with the given parameters_

| Action | Involved Element or URL |
| --- | --- |
| Click the "Posts" navigation item | .../wp-admin/edit.php |
| Click the "Add New" button | .../wp-admin/post-new.php |
| Enter a title {p_post_title} in the title input | name="post_title" |
| Enter a fulltext {p_fulltext} in the post content input | name="content" |
| Enter a teaser {p_teaser} in the teaser input | name="laterpay_post_teaser" |
| Assign the post to one/multiple categories, if {p_category} is not "none" | id="categorychecklist" |
| Select the price type {p_price_type} from the price type button group | e.g. id="lp_js_useIndividualPrice" for individual prices |
| Enter a price {p_price} in the price input | name="post-price" |
| Select the revenue model {p_revenue_model} from the revenue model button group | id="lp_js_postPriceRevenueModel" |
| Click the "Publish" button | name="publish" |
#### Create_Time_Pass(p_time_pass_title, p_time_pass_description, p_validity_period, p_validity_unit, p_validity_access, p_revenue_model, p_price)

_Creates a time pass with the given parameters_

| Action | Involved Element or URL |
| --- | --- |
| Click the "LaterPay" navigation item | .../wp-admin/admin.php?page=laterpay-plugin |
| Click the "Pricing" navigation item | .../wp-admin/admin.php?page=laterpay-pricing-tab |
| Click the "Create" button to add a time pass | id="lp_js_addTimePass" |
| Enter a title {p_time_pass_title} in the title input | name="title" |
| Enter a description {p_description} in the description input | name="description" |
| Select the accessible content {p_validity_access} from the select | name="duration" |
| Select the validiy period {p_validity_period} from the select | name="duration" |
| Select the unit for the validiy period {p_validity_unit} from the select | name="period" |
| Enter a price {p_price} in the price input | name="price" |
| Select the revenue model {p_revenue_model} with the revenue model toggle | name="revenue_model" |
| Click the "Save" button | class="lp_js_saveTimePass" |
#### Logout

_Logs the test user out from the test system_

| Action | Involved Element or URL |
| --- | --- |
| Click the "Logout" link | id="wp-admin-bar-logout" |
#### Check_Post(p_post_title, p_is_fulltext_visible, p_is_teaser_visible, p_is_purchase_button_visible, p_is_overlay_visible, p_is_purchase_link_visible, p_are_time_passes_visible)

_Checks, if certain elements of a post are visible for the user or not. This check is often used as an assertion for the tests in this ticket._

| Action | Involved Element or URL |
| --- | --- |
| Go to post {p_post_title} |  |
| Check, if the fulltext is visible / not visible (depending on {p_is_fulltext_visible}) | class="entry-content" |
| Check, if the teaser is visible / not visible (depending on {p_is_teaser_visible}) | class="lp_teaser-content" |
| Check, if the teaser_overlay is visible / not visible (depending on {p_is_overlay_visible}) | class="lp_benefits" |
| Check, if the purchase_button is visible / not visible (depending on {p_is_purchase_button_visible}) | class="lp_purchase-button"" |
#### Purchase_Post_PPU(p_post_title)

_Purchase the given PPU post_

| Action | Involved Element or URL |
| --- | --- |
| Go to the article page for post {p_post_title} |  |
| Click the LaterPay purchase button | class="lp_purchase-button" |
| Accept the LaterPay Terms and Conditions | name="agree" |
| Confirm the purchase in the LaterPay purchase dialog | id="nextbuttons" |
#### Purchase_Time_Pass_PPU(p_time_pass_title)

_Purchase the given PPU time pass_

| Action | Involved Element or URL |
| --- | --- |
| Go to the article page for post {p_time_pass_title} |  |
| Click the LaterPay purchase button in the respective time pass | class="lp_purchase-button" |
| Accept the LaterPay Terms and Conditions | name="agree" |
| Confirm the purchase in the LaterPay purchase dialog | id="nextbuttons" |
## Test Variants

The basic tests have to performed under various conditions:

| Variant | Description |
| --- | --- |
| Without Caching Plugin | No caching plugin is installed on the test environment |
| With Caching Plugin | A caching plugin (WP Super Cache) is installed and active on the test environment |
## Constants

The following constants are used as placeholders in this ticket:

| Constant | Value | Description |
| --- | --- | --- |
| c_user | "admin" | User name for admin test account |
| c_passwort | "admin" | Passwort for admin test account |
| c_post_title | "Test Post" | Title for test posts |
| c_teaser | 200 words of Lorem Ipsum (http://www.loremipsum.de/) | Teaser text for test posts |
| c_fulltext | 1000 words of Lorem Ipsum | Fulltext for test posts |
| c_price_ppu | 29 | Price for PPU test posts in Cents |
| c_price_sis | 249 | Price for SIS test posts in Cents |
| c_revenue_model_ppu | "PPU" | Revenue model PPU |
| c_revenue_model_sis | "SIS" | Revenue model SIS |
| c_time_pass_title | "Test Time Pass" | Title for test time pass |
| c_time_pass_description | "This is a test time pass" | Description for test time pass |
| c_time_pass_access | All content | Access definition for test time pass |
| c_time_pass_validity_period | 1 | Time valid for test time pass |
| c_time_pass_validity_unit | "Day" | Unit for the validity period |
| c_url_test_system | xxx.xxx.xx.xx/xx | URL of the respective WordPress test installation |
| c_current_plugin_version | 0.9.11.4 | Current version of the LaterPay WordPress plugin, has to be changed with every release |
| c_previous_plugin_version | 0.9.11.5 | Previous version of the LaterPay WordPress plugin, has to be changed with every release |
| c_price_type_individual | "Individual" | Price type "Individual price" |
| c_price_type_individual_dynamic | "Individual Dynamic" | Price type "Individual dynamic price |
| c_price_type_category | "Category Default" | Price type "Category default price" |
| c_price_type_global | "Global Default" | Price type "Global default price" |

**Comment by twoldrich** [comment]
@mturalenka Could you please assign this ticket?

**Comment by mturalenka** [comment]
@twoldrich do you suppose to create/update old one UI selenium tests?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mturalenka FYI, tests are done. We need to proceed to the futher stages.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Sorry for the delay – what would be the "further stages"?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mturalenka @twoldrich We need to configure testing env and determine where and when we should run tests, which browsers we should check, where we should store data and etc.

**Comment by mturalenka** [comment]
@twoldrich could you please assist with getting required env?

**Comment by twoldrich** [comment]
@mturalenka I'll ping @doismellburning about that.

**Comment by twoldrich** [comment]
Sorry, I forgot about that – I'll ask Kristian right now.

**Comment by doismellburning** [comment]
Dude if it takes me five scrolls to get past the description, I don't think you get to call it "basic" ;)

@mturalenka What do you mean "getting required env"? This should be configured for Travis

**Comment by twoldrich** [comment]
@doismellburning The description is just so long because it describes the individual steps for each one of the "basic tests" ;)

**Comment by mturalenka** [comment]
@doismellburning to run selenium test we need:
1) linux server to trigger automated testing, travis looks ok for that
2) browserstack or saucelabs or dedicated server with selenium(with x-server or X virtual framebuffer)
