### ISSUE TITLE
PHP Warning after update from 0.9.11.3 to 0.9.11.4

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#771]
I had this PHP Warning every hour:
 PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'LaterPay_Controller_Admin_Dashboard' does not have a method 'refresh_dashboard_data' in /wp-includes/plugin.php on line 571

I've deleted the event hook to get rid of the warning:
"laterpay_refresh_dashboard_data"

Had it on development, staging and production environment.

**Comment by mturalenka** [comment]
the issue due to typo in method name,
https://github.com/laterpay/laterpay-wordpress-plugin/blob/v0.9.11.4/laterpay/application/Controller/Admin/Dashboard.php#L192

**Comment by mturalenka** [comment]
fixed in 7d946ba
