### ISSUE TITLE
Shortcodes from plugins are not processed. Possibly reopen #119.

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#774]
In caching compatible mode I have the shortcode from "Contact Form 7" not processed while the [caption] shortcode is processed correct.

I see:
````
[contact-form-7 id=”843488″ title=”something”]
````
in the page or post instead of the form. So I wonder if shortcodes from plugins are broken or if something is wrong with the Contact Form 7 plugin/shortcodes. (The form is showing up correct on a free page/post.) I have not yet tested other shortcodes from other plugins. (Update: Another shortcodes from a second plugins is not working, too. So I assume shortcodes that were added by plugins are broken in latest laterpay plugin v0.9.11.4.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@larsschenk Is it (shortcode contact-form-7) processed correctly if laterpay plugin is disabled?

**Comment by larsschenk** [comment]
Yes, the same page with the same shortcode is processed correctly when the laterpay plugin is disabled.
It is also processed correctly with the laterpay plugin enabled and the page/article price is set == 0.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@larsschenk Found a problem with contact form plugin. Issue with shortcode appeared only in caching compatibility mode, when we load content via ajax. As you know WP make ajax through admin area, so is_admin() is true. In contact form you can see such strings in base file:
```
if ( is_admin() )
	require_once WPCF7_PLUGIN_DIR . '/admin/admin.php';
else
	require_once WPCF7_PLUGIN_DIR . '/includes/controller.php';
```
They register shortcodes in conroller, so if is_admin is true shortcodes not registered. That's why after content load via ajax contact form shortcodes not processed. One of the ways to fix this: you need to manually add check if ajax used (defined( 'DOING_AJAX' ) && DOING_AJAX) and include controller.php of the contact form plugin.

**Comment by larsschenk** [comment]
Thanks for the hints and pointing me into the right direction. At another plugin with the same problem I can confirm that the trouble was caused by "not registered shortcodes" because of "is_admin". I'll try if I can help contact form 7 to make it compatible with laterpay.

**Comment by larsschenk** [comment]
@AliaksandrVahura-ScienceSoft I can confirm that your fix will work for the contact form 7 plugin. I made a suggestion to contact form 7 and hope the author will "merge the pull request": https://wordpress.org/support/topic/a-simple-fix-to-make-it-work-with-the-laterpay-plugin

**Comment by twoldrich** [comment]
@larsschenk Thanks a lot for your effort!

**Comment by larsschenk** [comment]
For documentation purpose only:

With latest contact form 7 version 4.2 the shortcode is working (= the form will be displayed). 

But I still can't use contact form 7 (on PPU pages when caching is enabled) because of the way it is working: Action handler is the URL that contains the form (self). It results in:

/wp-admin/admin-ajax.php?action=laterpay_post_load_purchased_content&post_id=4691&is_front=true&nonce=0a12345678#wpcf7-f1234-o1

but it should be the simple URL of the page l.e.:
/my-ppu-page-that-contains-a-form/

I suppose that the ajax solution - to work around the cache - brings some new problems that authors need to be aware of.
