### ISSUE TITLE
Error "Multiple primary key defined" on re-enabling the plugin.

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#776]
When I temporarily disabled the plugin I got this error on re-enabling in the log. The error can be re-produced by simply disable and enable again:

WordPress-Datenbank-Fehler Multiple primary key defined für Abfrage ALTER TABLE wp_laterpay_post_views CHANGE COLUMN id id                INT(11)              NOT NULL AUTO_INCREMENT PRIMARY KEY von activate_plugin, do_action('activate_laterpay/laterpay.php'), call_user_func_array, laterpay_activate, LaterPay_Core_Bootstrap->activate, LaterPay_Controller_Install->install, dbDelta

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@larsschenk Thanks, found problem with dbDelta. Will be fixed.
