### ISSUE TITLE
Customer Report: Action for LaterPay account links ignores custom CSS file

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#778]
A user reported, that the action for LaterPay account links ignores the custom CSS file they hand over in the shortcode.

@AliaksandrVahura-ScienceSoft Could you please check, if that's actually a plugin (shortcode) issue (if not, it's most likely a LaterPay API issue)?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I assume this functionality not well tested. I will check it.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich @drdla @mturalenka It seems the problem is that we use a secure connection for dialog api and insecure url for css path. Browser block such usages. The way to solve this made dialog api requests via http (?) or provide secure css link url.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@doismellburning Is it possible to solve problem from the LaterPay side and give ability for customer to use http protocol?

**Comment by twoldrich** [comment]
@mturalenka Can be moved to the next milestone

**Comment by doismellburning** [comment]
Sorry I've just seen this. We're not going to strip SSL just to allow custom CSS I'm afraid...

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich So i assume this feature should work only if customer support https and we should check this fact before rendering account links. Should i add this check so in result account links will not render  on non-https pages?

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Sure, that sounds good!

**Comment by doismellburning** [comment]
> Should i add this check so in result account links will not render on non-https pages?

Seems reasonable!

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mturalenka Please review, merge and close if all ok.
