### ISSUE TITLE
State of "Time Passes Only"-toggle is not saved

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#779]
With the current release, it's not possible for me to switch to "time passes only" mode: I can switch the toggle, but when I reload the pricing tab, the toggle has gone back to it's default position.

![image](https://cloud.githubusercontent.com/assets/6638286/7854737/80d0f4d4-051c-11e5-9bd1-e4ac54885bc7.png)

**Comment by mturalenka** [comment]
have you checked current master? that was fixed by @AliaksandrVahura-ScienceSoft  a few days ago

**Comment by twoldrich** [comment]
@mturalenka no, thanks for the hint – will check!

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Fixed in https://github.com/laterpay/laterpay-wordpress-plugin/commit/686542d27708ab04ec337b800cf06af256f01859.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
The reason of the error was disabled checkbox, in result serialized form was without checkbox value.

**Comment by twoldrich** [comment]
Ok, thanks @AliaksandrVahura-ScienceSoft
