### ISSUE TITLE
Customer Report: Images are not displayed in print preview / not printed in Internet Explorer

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#780]
A merchant with the current plugin release mentioned that one of his users complained, that he cannot print images for a purchased post or even see the images in the print preview.
I tested with Internet Explorer 10 and 11 (Browserstack) and can confirm that.

I will add an example URL in our internal development channel.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I've investigated the problem: 
1. Unlike other browsers, IE send requests for images (load_file in our case).
2. We process request, that contain no cookies info.
3. No token present so we try to acquire it.
4. After redirect we got back to the load_file but already with token and new hash.
5. We verify hash and it not matched.
So seems we have a different mechanism of hash creation on Python and PHP laterpay clients or params for hash creation are different. Need to investigate problem futher.
