### ISSUE TITLE
PHP Notice:  Undefined index: pass_id

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#781]
PHP Notice:  Undefined index: pass_id in /wp-content/plugins/laterpay/application/Model/Payment/History.php on line 106

While in sandbox mode (live mode not tested).

**Comment by mturalenka** [comment]
@AliaksandrVahura-ScienceSoft the same method `set_payment_history` is used for both calls `buy_post` and `buy_time_pass`. this means that some parameters cannot be present (e.g. `pass_id`) please add corresponded checks to `set_payment_history` method
