### ISSUE TITLE
Check KPI "Committed Revenue" in statistics dashboard

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#790]
A customer reported, that his dashboard shows higher committed revenues than displayed in the LaterPay merchant backend on merchant.laterpay.net. The customer used voucher codes for time passes, so it could be the case, that we count revenues for time passes, which were made free be using a voucher code.
@AliaksandrVahura-ScienceSoft  Could you please check for the dashboard KPI "Committed Revenue", if there could be a case, where we count too high/low revenues?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mturalenka @twoldrich I've investigated this problem and it can be the case with access loose (removed cookie). When user restore access to the content we write additional data into the purchase history, which is not correct.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@doismellburning We need to detect if user restored access to the content and got "you already bought this" message - right now your redirect user back with the same params we provided for purchase url. Could you please add additional parameter (or other solutions) for case if it was not purchase, but access restore?

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Thanks for investigating the issue! Just for the records: As far as I understood, the issue could occur in the following case:

- User purchases a time pass for e.g. 4.99 € with a voucher code (for this example: 0 €)
=> We write "1 time pass sale" / "0€ revenue"
- He looses his access and clicks the purchase button for this time pass again.
=> LaterPay restores the access and the user receives a "You've already bought this" message.
=> We write another "1 time pass sale" / " but now with "4.99€ revenue" in the database
=> Instead of ignoring this "purchase", we count it twice and with the regular price.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Thanks for detailed explanation ) Exactly.

**Comment by mturalenka** [comment]
can be skipped from release due to #797

**Comment by twoldrich** [comment]
This can be closed as we removed the statistics dashboard.
