### ISSUE TITLE
Warning: "Cannot modify header information - headers already sent"

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#791]
A customer reported, that with the current release one of his users saw the following warning:

> *Warning*: Cannot modify header information - headers already sent by (output started at
/xxxxx/wp-content/plugins/seo-ultimate/modules/titles/titles.php:138) in */xxxxx/wp-content/plugins/laterpay/vendor/laterpay/laterpay-client-php/LaterPay/Client.php*
on line *647 

I can't see this warning on the merchant's website, but with the current release, I see the following warning in the WordPress (not LaterPay!) Dashbaord:

> Warning: Cannot modify header information - headers already sent by (output started at /var/www/wp-admin/includes/misc.php:881) in /var/www/wp-content/plugins/laterpay/vendor/laterpay/laterpay-client-php/LaterPay/Client.php on line 647

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich I've fixed this already in https://github.com/laterpay/laterpay-wordpress-plugin/commit/9073b995ca37d6160cc8de5b6540731bbeae392a

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Please check on current master and close if all ok.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft I don't see the warning with the current master, thank you!
