### ISSUE TITLE
Add advanced setting to not contact LaterPay on the homepage

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#799]
There should be an advanced setting (checkbox) to disable contacting LaterPay on the homepage, if the merchant really wants that (as mentioned in https://github.com/laterpay/laterpay-wordpress-plugin/issues/641). This feature is relevant for the merchants, you really want to contact LaterPay only on paid posts.

**Comment by mturalenka** [comment]
This option will only disable requests to create token API, check access will still be called

**Comment by twoldrich** [comment]
@mturalenka For the background: This option is mainly for the case, that a user has disabled thirdparty cookies. In that case, he will see a message, that he please should enable them for LaterPay. So I'm not sure, if the access call also needs thirdparty cookies?

**Comment by mturalenka** [comment]
third party cookies(LaterPay's i think in this case) are only setup in token creation
