### ISSUE TITLE
Merchant Report: Fatal error after plugin activation

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#804]
A merchant reported, that with the current release, he gets a fatal error after activating the plugin:
<img width="1398" alt="fatal error" src="https://cloud.githubusercontent.com/assets/6638286/8518569/933e772c-23cb-11e5-96bf-6d9223821e4c.png">

**Comment by mturalenka** [comment]
this error means that customer has xcache php module but its not configured correctly

**Comment by twoldrich** [comment]
@mturalenka Thanks, so it's not a LaterPay plugin issue. Do you have any idea, what the problem/misconfiguration could be?

**Comment by mturalenka** [comment]
the issue is described directly on screenshot: `xcache.admin.user and/or xcache.admin.pass is not configured`. so such options should be configured.

**Comment by twoldrich** [comment]
@mturalenka Thank you, I replied the customer, that it's a configuration issue of the caching plugin.
