### ISSUE TITLE
User report: Unexpected error in cache.php

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#810]
A merchant reported, that after installing the current plugin release, he get's an "unexpected" error and a white screen (blank screen) with the debugger message

> /plugins/laterpay/…/cache/cache.php ein „unexpected ‚;‘ in line 4

**Comment by mturalenka** [comment]
@twoldrich could you please share cache.php file?

**Comment by twoldrich** [comment]
@mturalenka I asked the customer for the cache.php file and will post it in our internal development channel as soon as I receive a reply.

**Comment by twoldrich** [comment]
@mturalenka The customer replied that he has already deleted the plugin and thus the respective file, too.

**Comment by mturalenka** [comment]
There's nothing illegal in the file. At line 4. Could customer update cache file? During this process could happen some issues or process was interrupted

**Comment by twoldrich** [comment]
The customer will provide us further infos and access to his test system, but didn't report this particual issue anymore - that's why I close that for the moment.
