### ISSUE TITLE
Google translate is blocked because of the plugin

### ISSUE THREAD

**Issue by haraball** [laterpay/laterpay-wordpress-plugin#82]
Both pages with paid content from laterpay, but also blog posts which are open/free to view, are blocked. This is a similar issue for other services (content aggregators etc), said @drdla.

![screen shot 2014-07-05 at 14 27 52](https://cloud.githubusercontent.com/assets/25930/3495412/56282e82-05d6-11e4-8285-4559c3ce09f4.png)

**Comment by drdla** [comment]
Very closely related to #545 and #334

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Should be fixed now. Need to check.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft I just tested with current master:
- I see the "LaterPay requires cookies" dialog when I try to translate a **paid post**.
- The translation works (i.e. no "LaterPay requires cookies" dialog is displayed) for **free posts**.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Seems browscap update didn't fix this issue.

**Comment by VadzimBelski-ScienceSoft** [comment]
The cookies from from website A that is translated by google website B can not be shared. This is a principal of web security. So if website A shared cookie to user website B can not get access to them, so Laterpay token set on website A can not be transferred to website B in such a case you can not grant access to paid content. Of course we can play around with this and use some Ajax technique with cross-domain requests - however even in a such situation content will not be translated i assume.

**Comment by drdla** [comment]
Wontfix
