### ISSUE TITLE
Shortened URL to a purchased post is invalid

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#826]
Using the URL shortener http://buff.ly creates invalid links.
@mturalenka I guess this is a browscap thing – could you please have a look?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich @mturalenka I can't confirm this issue. Works fine for me.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich @mturalenka I've investigated this issue and found no problems here. All shortened urls work fine. I've checked issue on 2 customers's sites and on our demo site.

http://buffer.com shortener add extra parameters to the end of shortened url, so looking on url provided by customer it seems that someone shortened https://api.laterpay.net/gettoken url by himself.
