### ISSUE TITLE
Remove "dashboard" entry from navigation

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#837]
With the last plugin release, we moved the statistics to the LaterPay merchant backend and added a notice to show the merchant, where he can find statistics in the future. With the next release, we should remove the "Dashboard" items from the navigation in order not to show a currently "useless" dashboard tab for the moment.

![image](https://cloud.githubusercontent.com/assets/6638286/9604270/ce7d1ace-50b6-11e5-9041-9141ad51f03f.png)

@mturalenka Could you please take care / assign the ticket accordingly?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Should we only apply visual changes or remove dashboard code completely from plugin as well?
