### ISSUE TITLE
Make "Pricing" tab the default tab

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#838]
Currently, the "dashboard" tab is the default tab when opening the plugin backend (i.e. when clicking on the "LaterPay" navigation item). As #837 removes the dashboard entry from the navigation, the new default page should be the "Pricing" tab.

@mturalenka Could you please take care / assign the ticket accordingly?

**Comment by mturalenka** [comment]
this is a part of #837

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mrutalenka Fixed with #837.
