### ISSUE TITLE
Remove statistics notice in post statistics

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#839]
Currently, we display a notice in the post statistics pane, that the sales statistics have moved to the LaterPay merchant backend. To be consistent with #837, we should remove this notice also from the post statistics pane, i.e. it should only display the toggle for switching between admin and visitor view:

![image](https://cloud.githubusercontent.com/assets/6638286/9604593/e7fc28b2-50b8-11e5-9e62-bc2189ec37df.png)

@mturalenka Could you please take care or assign the ticket accordingly? I guess, @sherkhan could help with the frontend part of that im necessary?

**Comment by mturalenka** [comment]
sounds like a part of #837, will be done indirectly by @AliaksandrVahura-ScienceSoft

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@mturalenka Fixed with #837.
