### ISSUE TITLE
Customer report: With active plugin, 302 is returned instead of 404

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#846]
A merchant reported that with an active LaterPay plugin, entering an unknown URL (like www.randomsite.com/**randomstring238792384ul** doesn't return the usual 404 but instead a 302.

@AliaksandrVahura-ScienceSoft Could you please have a look, I added the respective client-specific details in our internal development channel.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Can't reproduce this on local env and on others sites with laterpay. It seems problem not in plugin but with server settings.

**Comment by twoldrich** [comment]
The customer just replied that this issue doesn't occur, when he deactives the plugin.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Can i have access to their system? Better staging.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Some third-party services can return 302 status cause of browscap limitations. I see no problems here with direct usage.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Does this problem still actual?

**Comment by doismellburning** [comment]
We've seen this in other client implementations.

A common "mistake" is to check for the token _before_ doing URL path matching, then, whether or not the path is "valid" or not, redirecting to `/gettoken`

This violates the principle of least surprise, because suddenly `GET /this/is/totally/bogus` returns a 302 (to `/gettoken`) not a 404.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
You are right. In wordpress we use check if selected post is single and non purchasable. But it seems this check return false in this case (invalid path). Same as it was with RSS page.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Then fix probably will be is_404 check.
