### ISSUE TITLE
Add advanced setting to disable feed handling

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#847]
Currently, the plugin is handling how paid content is displayed in feeds. As multiple customer's requested to handle that on their own / don't want the plugin to edit the feed's content, we should add an advanced setting for enabling/disabling this feed handling. I.e., if this option is disabled (unchecked), the feeds sould be displayed as if the LaterPay plugin wouldn't be active.

The default for this advanced setting should be **enabled** (checked).

@AliaksandrVahura-ScienceSoft Could you please take care of that?

![image](https://cloud.githubusercontent.com/assets/6638286/10815412/1bd4eaf2-7e2c-11e5-9274-5584c891b764.png)

**Comment by AliaksandrVahura-ScienceSoft** [comment]
This issue will be fixed with #850. Do we still need to create this option?

**Comment by twoldrich** [comment]
@doismellburning @AliaksandrVahura-ScienceSoft It would be nice if you two could exchange opinions about wether this (#850) also can solve the problem of "some bots" which are not listed in the browscap library cannot access the blog" or not.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
We don't need tokens on feed at all. Fixed.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Nice, thank you – seems to be the easiest solution indeed!

**Comment by doismellburning** [comment]
#850 does not relate to this at all, but (as I think @AliaksandrVahura-ScienceSoft is saying), I'd just blindly ship the excerpt, and not hit LP at all for RSS
