### ISSUE TITLE
User report: Action for invoice indicator doesn't work

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#848]
One of our merchants reported, that the invoice indicator Action

<?php do_action( 'laterpay_invoice_indicator' ); ?>

doesn't return the expected invoice indicator, but just outputs a line break.

@AliaksandrVahura-ScienceSoft Could you please have a look? I'll add customer specific details in our internal development channel.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft I just checked on a different user's website and the action itself seems to work. Could you please check if the action I stated above contains an error? If not, I would like to connect you directly to the customer to figure out what the problem might be – ok for you?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@twoldrich Action you stated above is ok. Need to view implementation on customer's system.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Great, thanks for looking into that, I'll contact the merchant with this info. I guess this ticket can be closed for the moment as "Not a bug", then.
