### ISSUE TITLE
Drop iframed dialogs in favour of redirection, for broader user support

### ISSUE THREAD

**Issue by doismellburning** [laterpay/laterpay-wordpress-plugin#850]
We're in the process of publishing an advisory change to the Platform docs, recommending _against_ an iframe overlay for our dialogs, and instead a good old-fashioned HTML link.

This will mean users don't need to allow third-party cookies in order to use us, PLUS it reduces the risk of future potential PCI-DSS regulatory changes impacting our merchants.

We're still sorting out the actual messaging of the documentation change, but a summary of the draft is:

> Present / link / redirect users to generated Dialog URLs. Do not attempt to present them inside an iframe

One of the consequences of this is that it effectively obsoletes the JavaScript API.
This should make life much simpler from a user (of the Platform; e.g. a plugin author) perspective.

I hope this finds you well!

**Comment by doismellburning** [comment]
@twoldrich FYI

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft FYI ^ I'll keep you updated concerning the status of this change.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Ok.

**Comment by doismellburning** [comment]
Right, we've just rolled out those docs changes - check out http://docs.laterpay.net/platform/dialogs/main_endpoints/ etc.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Do you have all the information you need for that issue?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Not sure about this, i saw the documentation but need to try implement this. Do you want to implement this in current version?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
As i understood base idea of this functionality that now user will be redirected to the laterpay side directly (not in iframe).

**Comment by AliaksandrVahura-ScienceSoft** [comment]
@doismellburning It seems we need tokens anyway to detect if user has access to the content. So it seems this solution only about drop YUI and fully redirect to the laterpay side during purchases? In that case this will not solve problems with crawlers like i thought...

**Comment by doismellburning** [comment]
@AlexandrTsumarov-ScienceSoft Exactly
