### ISSUE TITLE
Better handling of network outage?

### ISSUE THREAD

**Issue by larsschenk** [laterpay/laterpay-wordpress-plugin#853]
https://lpstatic.net/combo?yui/3.17.2/build/yui/yui-min.js&client/1.0.0/config.js
had 503 and cause bad page load times.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
It works now. That's known problem and happen from time to time.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Also please check #850.
