### ISSUE TITLE
Videos are not displayed in teaser

### ISSUE THREAD

**Issue by twoldrich** [laterpay/laterpay-wordpress-plugin#855]
A merchant reported that a video which he embedded in the teaser of a paid post, is not displayed. @AliaksandrVahura-ScienceSoft Could that be a sanitizing issue? If so, we should enable videos in the teaser.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
Build-in shortcode [embed] works fine. Need more details.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
We need to add autoembed links support in teaser.

**Comment by AliaksandrVahura-ScienceSoft** [comment]
It works in cache mode too.
