### ISSUE TITLE
Undefined offset errors after autoupdate.

### ISSUE THREAD

**Issue by AliaksandrVahura-ScienceSoft** [laterpay/laterpay-wordpress-plugin#863]
In some cases after Laterpay plugin autoupdate if plugins page wasn't visited user could see undefined offser error. That's cause voucher codes structure was changed, but update script not runned from install.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Are there any updates on this ticket so far?

**Comment by AliaksandrVahura-ScienceSoft** [comment]
I've fixed this issue already with another commit. Need only test it.

**Comment by twoldrich** [comment]
@AliaksandrVahura-ScienceSoft Ok, thanks for the update!
