### ISSUE TITLE
Purchase flow returns user to page without showing paid content

### ISSUE THREAD

**Issue by ericflarsen** [laterpay/laterpay-wordpress-plugin#913]
**Steps to duplicate:**
Go to https://laterpay-test.go-vip.co/2018/07/05/test/
Click the buy button
Complete purchase flow
Browser returns user to content page, but doesn’t show blocked content
Refresh page and blocked content appears

**Desired behavior:** 
When user is returned to the content page, the purchased content appears. 

**Probable cause:**
The purchase dialog returns the user to the content page with parameters in the query string. WordPress Varnish configuration strips the parameters and returns the cached page.

**Comment by PatelUtkarsh** [comment]
I've followed up with VIP on this. 

More details: VIP-GO supposed to by pass cache when cookie is present but it is serving page from cache. 

![Image of Request](https://www.dropbox.com/s/q9osuc1iopfbo4q/screenshot_2018-07-12_11-32-10.png?raw=1)

**Comment by simonwheatley** [comment]
Hi Eric and Patel 👋

> The purchase dialog returns the user to the content page with parameters in the query string. WordPress Varnish configuration strips the parameters and returns the cached page.

This is as we suspected during our call, Eric 🙂 For clarity, it's the VIP Go Varnish config, not WordPress Varnish Config. 

On to the technical details and possible fix…

We do not do any query string stripping or query string normalisation on the URL for caching purposes:

> The page cache considers the whole URL, including GET parameters; e.g. ?a=1&b=1 is different from ?b=1&a=1 and both are cached separately. When purging a URL, all variants of the GET parameters are purged at the same time. This means that a post with slug hello-world will have all variants ( eg.: /hello-world?a=1&b=1 as well as /hello-world?b=1&a=1 ) purged along with the main post.
> – [Controlling VIP Go Page Cache, overview](https://vip.wordpress.com/documentation/vip-go/controlling-vip-go-page-cache/#overview)

> VIP-GO supposed to by pass cache when cookie is present but it is serving page from cache.

VIP Go only bypasses cache when certain cookies are set, you can see the [list of those cookies in our documentation](https://vip.wordpress.com/documentation/vip-go/controlling-vip-go-page-cache/#cookies). 

I suggest that this case is handled by setting the `vip-go-cb` cookie on the site with a value of `1` for users who purchase from LaterPay; you can read more in "[Setting individual users of requests to bypass cache](https://vip.wordpress.com/documentation/vip-go/controlling-vip-go-page-cache/#setting-individual-users-or-requests-to-bypass-cache)". This will mean that LaterPay purchasers will `PASS` the cache completely, and content for them will always be served from the origin (as long as they have that cookie). How does this sound? 

I'm not sure what the lifespan on this cookie should be, or how re-authenticating is handled for returning users without the cookie, or users who have rights to see the content but are visiting on a different device or browser… so I'm not sure how to advise there.

**Comment by PatelUtkarsh** [comment]
@simonwheatley Thank you, 

@ericflarsen I've pushed these changes on the testing vip-go site. It's working fine now: https://laterpay-test.go-vip.co/2018/07/05/test/

Please check and merge following PRs. 
- https://github.com/laterpay/laterpay-wordpress-plugin/pull/914
- https://github.com/laterpay/laterpay-client-php/pull/20

**Comment by simonwheatley** [comment]
…hmmm, I went back through to detail the steps to reproduce and I cannot reproduce now, perhaps some caching on my browser.
