### ISSUE TITLE
Remove unnecessary request to /validatesignature before every /access request

### ISSUE THREAD

**Issue by designandcopy** [laterpay/laterpay-wordpress-plugin#915]
WPP does a LaterPay API "health check" before every request to the /access Platform API endpoint. This check consists of doing a request to /validatesignature Platform API endpoint. It happens here https://github.com/laterpay/laterpay-wordpress-plugin/blob/ba9d46281040ce23ded37fc835e99cf60f089ed1/laterpay/application/Helper/Request.php#L147-L175

---

The result from the `/access` request itself (since that request needs to happen always anyway) could be used to determine if the LaterPay API is down instead of requesting `/validatesignature` before doing the `/access`.

In an ideal scenario, one user's request to a WPP enabled page would result in one `/access` request to LaterPay API. And the results from that `/access` request would be used to:
1. Determine if the fallback mode should be used because the response from `/access` is non HTTP 200 or a connection error for example.
2. Determine which articles (depending on what page the user requested) the user has access to. Since one request to `/access` can be used to ask for multiple `article_id`s.

But if the structure of the WPP itself makes (2.) complicated, then keeping on doing multiple requests to `/access` might be a better solution?

**Comment by designandcopy** [comment]
Ah, thanks for the correction & yes, thank you for looking for an optimisation here.
I just recently noticed that our logs are full of those redundant requests.

**Comment by PatelUtkarsh** [comment]
>Determine which articles (depending on what page the user requested) the user has access to. Since one request to /access can be used to ask for multiple article_ids.

@designandcopy Currently, each WP_Query is being evaluated so in case a page has two WP_Query it will send two access api request. And it's hard determine all requests for all use-cases. 

One solutiuon is if we have a endpoint which sends all purcahsed article from user without sending aricle ids. Currently, Access endpoint requires `article_id` params.

**Comment by PatelUtkarsh** [comment]
@designandcopy Feel free to open the issue to discuss above.
