### ISSUE TITLE
Missing German Translation

### ISSUE THREAD

**Issue by ericflarsen** [laterpay/laterpay-wordpress-plugin#923]
![wp-plugin_freeride today](https://user-images.githubusercontent.com/32423746/43477701-19ac5944-94b9-11e8-9481-0faa94aa78e9.png)

"Buy now for 3.99 EUR" should read “Jetzt kaufen für 3,99 EUR” 
“After 1 Jahr” which should be “Nach 1 Jahr”.

**Comment by sudhir-yadav** [comment]
Passes with translated content.
![transl2](https://user-images.githubusercontent.com/3166668/43517938-0670d770-95a8-11e8-97d2-e812414069a4.png)
![transl1](https://user-images.githubusercontent.com/3166668/43517941-06aaa536-95a8-11e8-9433-318f0d43c971.png)
