### ISSUE TITLE
Conflict with WordPress Social Login 2.3.3 by Miled

### ISSUE THREAD

**Issue by ericflarsen** [laterpay/laterpay-wordpress-plugin#932]
When this plugin is installed, it prevents the setting of the laterpay_token cookie and stops the user from gaining access to the content they just purchased.

Please look into what is causing the conflict and if there is a way we can work with it installed. Meaning, can we make our plugin more robust and not fail due to other plugins?

If we can't function well with the social plugin, is there a way we can identify that it is installed and place a notification in the admin console saying "WordPress Social Login conflicts with LaterPay and prevents it from working. Please disable the plugin." ?

**Comment by PatelUtkarsh** [comment]
After checking the code on wpengine it can be confirmed that, WSL uses `session*` functions in it, which was the reason for cookies being deleted.

https://wpengine.com/support/cookies-and-php-sessions/ 

We can add a notice on laterpay setting page in case of WPengine that if you're facing issue on WPengine after bypassing our requested cookies please check if any of the plugin is using the session and link above article there.

Any thoughts on showing this a better way? Maybe notice or setting page bottom or help menu.

In case of a notice should it be dismissible?

**Comment by thrijith** [comment]
Hey @ericflarsen,

We can have a `F.A.Q` section at the bottom of `Account` tab.

Let me know if we should implement it like this.

![account laterpay plugin settings](https://user-images.githubusercontent.com/13589980/44334153-66189b00-a48e-11e8-81c1-f0eedfbb53fd.png)

**Comment by PatelUtkarsh** [comment]
@thrijith Please send PR for this with the screenshot of an account tab UI.
