### ISSUE TITLE
Auto-Format Validation in the Values Field Triggered too Quickly

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#941]
Currently the auto-format validation in the values field is being triggered too quickly after an amount has been entered. If I am a slow typer or indecisive about my value the numbers change whilst I am still entering my amount and it feels like a bug.
(to recreate, try typing 0.50 but type slowly and see what happens)

**Comment by thrijith** [comment]
@ksmoore125 I've increased auto-format validation time to from `800` milliseconds to `1.5` seconds, is that fine or should we increase it more?

**Comment by ksmoore125** [comment]
That should be plenty; thanks!

**Comment by ksmoore125** [comment]
Business Acceptance Complete on http://laterpaywptest.wpengine.com/
