### ISSUE TITLE
Add Intro to LaterPay

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#943]
### User Story
As a self-service WordPress user, I likely have never heard of LaterPay and therefore do not understand our value proposition. I would like to have this explained to me inside WordPress so that I do not have to go to the LaterPay site to figure out how to take advantage of all of our products.

### Acceptance Criteria
On the Account tab, add a new section as follows:
**Section Heading:** Who is LaterPay?
**Section Subheading:** Meet the online payment system that cares about the user experience as much as you do
**Section Content:** 
With LaterPay, your users can purchase digital content and services, or make contributions and donations, with a single click—a frictionless experience that turns traffic into transactions.

Requiring upfront registration and payment results in customer abandon rates of up to 98%. LaterPay's patented Pay Later revenue model instead defers the registration process until a customer’s purchases reach a $5 threshold. Only then, once your content’s value is firmly established, is the customer asked to register and pay. This results in shopping cart conversion rates of over 80%. LaterPay’s frictionless customer onboarding helps you turn traffic into transactions.

**Comment by thrijith** [comment]
Hey @ksmoore125,

Do you have any mockup design in mind?

![account-tab-with-info](https://user-images.githubusercontent.com/13589980/44983353-7d7b7c00-af96-11e8-9a2a-4e6040fe0559.png)

**Comment by ksmoore125** [comment]
That looks great; I would just move it up so that it is the first section at the top of the page.

**Comment by ksmoore125** [comment]
Sorry, could it actually go below the in TEST versus LIVE mode section?

**Comment by ksmoore125** [comment]
Business Acceptance Complete on http://laterpaywptest.wpengine.com/
