### ISSUE TITLE
Version Number Updates

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#944]
### User Story
As a LaterPay Marketer, I would like the version to sound a bit more exciting so I can encourage users to upgrade. I would also like to be able to track which users are on which version number.

### Acceptance Criteria
- With the next release update the LaterPay Plugin version to 2.##
- Add WordPress the version number to the access requests so that we can see which merchants are using which version

**Comment by thrijith** [comment]
Hey @ksmoore125,

>Add WordPress the version number to the access requests so that we can see which merchants are using which version

By *access requests* Do you mean the request's that plugin sends to **LaterPay API**?

**Comment by ksmoore125** [comment]
I received additional clarification from our dev team:

> The value of the `User-Agent` request header in the requests WP Plugin sends to our `/access` API. This will allow us to see which WP Plugin versions are doing server to server communication with our Platform.
> Currently it seems to be `LaterPay Client - PHP - v0.2` regardless of the actual WP Plugin version.

**Comment by ksmoore125** [comment]
During their review, our engineering team requested that we update the User-Agent request from
LaterPay Client - PHP - v123
to 
LaterPay WP Plugin - v123
just to add a bit more clarity. Thanks!

**Comment by PatelUtkarsh** [comment]
@ksmoore125 We have made this such if the request is coming from WP plugin then it will be `LaterPay WP Plugin - v0.12.2` and in other cases of php application it will be `LaterPay Client - PHP - v0.3` 

Since that library can be used with other PHP frameworks.

**Comment by PatelUtkarsh** [comment]
@ksmoore125 can you ask the team to review and merge https://github.com/laterpay/laterpay-client-php/pull/21?
