### ISSUE TITLE
Pay Now vs Pay Later

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#945]
### User Story
As a self-service WordPress user, I likely have never heard of LaterPay and therefore do not understand our value proposition. I would like additional guidance / clarity around the Global Default Price so that I do not have think about what I am doing and whether I should choose Pay Now or Pay Later or why one or the other of them are disabled.

### Acceptance Criteria

- In the LaterPay > Pricing > Edit Global Default Price panel, display the following text to the right of the Pay Later / Pay Now toggle:
**TIP:** "Pay Later" is LaterPay's patented revenue model which allows your customers to purchase content with a single click, dramatically reducing their barriers to entry. Once the they have purchased $5 or 5€ worth of content, they will be asked to settle their invoice. [Click here to learn more.](https://support.laterpay.net/hc/en-us/articles/201251457-What-is-LaterPay-)
- When Pay Now is disabled display the following tool tip on hover above Pay Now:
Pay Now requires users pay for purchased content immediately; available for posts with pricing above $1.99 or 1.49€
- When Pay Later is disabled display the following tool tip on hover above Pay Later:
Pay Later allows users to gain access now by committing to pay once their invoice reaches $5 or 5€; it is available for posts with pricing between 0.05 and 5.00
- Update the tool tips on the Blog Post > Pay Later and Pay Now button tooltips to match the corresponding text above

**Comment by thrijith** [comment]
Hey @ksmoore125,

Can you please share a mockup for this if possible?

**Comment by thrijith** [comment]
Hey @ksmoore125,

Please check this screenshot and let me know if the updated position/design looks ok.

![45145212-c2ddba80-b1dd-11e8-9027-9636213d9645](https://user-images.githubusercontent.com/13589980/45291123-eb7ff000-b50e-11e8-90f3-7f01e62df081.jpeg)

**Comment by ksmoore125** [comment]
Yes, that looks great, thanks!

**Comment by ksmoore125** [comment]
1) The Pay Later / Pay Now toggle should have a fixed width so that the text does not extend past it's designated area (see Pay Later in screenshot)
![image](https://user-images.githubusercontent.com/41650164/45305886-e441ed80-b4e0-11e8-9aa2-d818f6631300.png)
2) Pay Now tooltip minor update: instead of a comma "immediately," it should be a semi-colon "immediately;"
3) Pay Later tooltip minor update: instead of a comma "5€," it should be a semi-colon "5€;"
