### ISSUE TITLE
Category Pricing UX

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#948]
### User Story
As a self-service WordPress user, I may just be setting up my site for the first time and not have a thorough understanding of WordPress. So that I do not have to think about what I am doing or wonder if the LaterPay plugin is broken, we should add clarity around category pricing.

### Acceptance Criteria

- On the Blog post page, if there are no Category prices, add a tooltip on hover above "Category Default Price" with the following text:
It looks like you have not set up a Category Default Price; click here or go to the LaterPay > Pricing page to set up Category Default Prices.
- On the LaterPay > Pricing page add the following text as a new paragraph at the bottom of the Set prices by category panel
Not familiar with WordPress categories? [Click here to learn more.](https://en.support.wordpress.com/posts/categories/)

**Comment by thrijith** [comment]
Hey @ksmoore125,

We can't add a link on the disabled button for Category Default Price on post edit screen if category price is not set up, We can add a tooltip saying "It looks like you have not set up a Category Default Price. Go to the LaterPay > Pricing page to set up Category Default Prices."

And on Pricing Page under Set prices by category panel
I think we should have a link pointing to https://codex.wordpress.org/Posts_Categories_Screen

Let me know your thoughts on this.

**Comment by ksmoore125** [comment]
That sounds great, thanks!

**Comment by ksmoore125** [comment]
It looks like we have another case. Is it possible to do the following:

- If there are no Category Default Prices established on the Pricing tab, use the tooltip above (what you have done looks great)
- **NEW CASE:** If there are Category Default Prices but the article is "Uncategorized" display the following tooltip instead:
Please select a category from the "Categories" panel below to enable Category Default Pricing.
- **NEW CASE:** If Category Default Price is enabled, do not display a tooltip
