### ISSUE TITLE
HIGH PRIORITY CUSTOMER REQUEST: Add Vouchers to Subscriptions

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#949]
### User Story
Per Tom, we have current customers who would like to be able to use vouchers on subscriptions to offer subscriptions at a reduced price to a select group of users. (ones that already have a print subscription, in this case)

### Acceptance Criteria
- Enable vouchers for subscriptions
- Beneath the voucher code box please also add the following message in lighter grey text:
Please note that at this time, subscription are maintained for the user's lifetime. Once discounted, you will not be able to raise the price.

**Comment by thrijith** [comment]
Hey @ksmoore125, 

I have some queries regarding this.

1. Do we need to enable vouchers on subscription as we have on timepass?

2. Not sure what you meant by this `ones that already have a print subscription, in this case`

3. Once discounted, you will not be able to **raise the price**.

Raise the price of Subscription/Voucher?

Even in timepass vouchers, you can't raise the price of a voucher. What you can do is delete a voucher or add another voucher with a different price.

**Comment by ksmoore125** [comment]
1. Yes 
2. Our customer is a newspaper and so they have a print subscription service and want to offer a discount to those users but giving them a voucher code.
3. Correct. My understanding of subscriptions is that since they auto-renew, as long as that user has that subscription the price cannot be modified. So if we have a subscription for $10/month but a user has a voucher that makes it $5/month, they will be paying $5/month indefinitely. Whereas with the timepass, they do not auto-renew so you can delete the voucher and the user would have to pay full price again once their timepass is up. ... Let me know if I am understanding everything correctly.
