### ISSUE TITLE
Enhance Data Being Sent to Google Analytics

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#961]
### User Story
As a LaterPay WordPress merchant, I would like to be able to view all of my data integrated together in one place so that I am confident in how my LaterPay implementation is performing.

### Acceptance Criteria
WordPress needs to capture the same information that LaterPay is collecting from other integration options.
- WordPress plugin detects if GA is already implemented by the merchant
- If WordPress plugin detects existing GA, we add a tracker
- If we don't detect existing GA, we inject GA script tag to LaterPay-enabled pages (ie: pages that have a price associated to them)
- We emit events to GA for all configured trackers on the page, so that both the publisher and LaterPay get events
- Merchant can opt-out out of the LaterPay events being sent to GA
- See mockup below for suggested design & copy

### Technical Details
**Information on Data and Recipients:**
- UA-50448165-9 (LaterPay USA in Live Mode)
- UA-50448165-10 (LaterPay USA in Sandbox mode)
- UA-50448165-3 (LaterPay EU in Live Mode)
- UA-50448165-4 (LaterPay EU in Sandbox mode)
- UA-XXXXXX (whatever the publisher has configured; see mockup for input location)

**Event Actions**
- Paid Content Replacement Show (triggered when closed paywall is viewed)
- Paid Content Purchase (triggered when user clicks buy button and is redirected to our hosted purchase dialog pages)
- Paid Content Purchase Complete (triggered when customer returns after successful purchase and content is unlocked when access state is true)
- Paid Content Identify (triggered when user clicks "I have already purchased this" link)

**Event Category**
"LaterPay WordPress Plugin"

**Event Label** 
these events should have in comma-separated form:
- "the_title()" (the WordPress title of the post)
- "bloginfo()" (the name of the site)
- "get_permalink()" (the permalink of the post)

### Related Documentation
How this is accomplished in other LaterPay integration methods:
* https://docs.google.com/spreadsheets/d/1sCpMX4Mnru97xkeHncvNVKK4mO5vhNJWXuyN4u3qpWY/edit#gid=0
* http://docs.laterpay.net/connector/analytics/integration/
* http://docs.laterpay.net/connector/analytics/event_actions/

### UX
![image](https://user-images.githubusercontent.com/41650164/45774443-90d34c00-bc12-11e8-97d9-d22f80483265.png)

If a user un-checks the second "LaterPay Google Analytics" box, please display the following in a modal:

> LaterPay collects this information to improve our products and services and also so that you can determine the effectiveness of your pricing strategy using our Merchant Analytics dashboard.
> 
> Are you sure you would like to disable this feature?

With a button to "Yes, Disable Tracking" and a Cancel link (similar to Save & Cancel on the Pricing tab)

**Comment by thrijith** [comment]
>WordPress plugin detects if GA is already implemented by the merchant
>If WordPress plugin detects existing GA, we add a tracker

We can check if GA is enabled by a particular plugin, but not for all plugins also this could be enabled via a theme too, so it's not possible to check against all as there isn't a generic way to do that. We can give an option to add a **UA-ID** and on pages where we are going to send data, we could check if enabled then add a tracker else inject GA script.

>Display a modal ... (similar to Save & Cancel on the Pricing tab)

I am not sure if we have a **modal** anywhere right now, we have a form. Please correct me if wrong.

**Comment by ksmoore125** [comment]
> We can check if GA is enabled by a particular plugin, but not for all plugins also this could be enabled via a theme too, so it's not possible to check against all as there isn't a generic way to do that. We can give an option to add a UA-ID and on pages where we are going to send data, we could check if enabled then add a tracker else inject GA script.

Yes, lets:
- Check if GA is enabled by "Google Analytics for WordPress by MonsterInsights"
- Give an option to add a UA-ID (as shown in the mockup for the update to the settings page)
- On pages where we are going to send data, we could check if enabled then add a tracker else inject GA script

Does that sound reasonable?

> I am not sure if we have a modal anywhere right now, we have a form. Please correct me if wrong.
I am sorry for the confusion, "similar to Save & Cancel on the Pricing tab" was referring only to the button & cancel styling
![image](https://user-images.githubusercontent.com/41650164/45888707-54bff880-bd84-11e8-95b2-f38a5584160c.png)
Except instead of "Save" the button would say "Yes, Disable Tracking"

If you have an alternate solution I am open to suggestions. I would just like it to be somewhat difficult for them to uncheck the tracking :)

**Comment by thrijith** [comment]
@ksmoore125  I have some queries about these two events.

**Paid Content Purchase Complete** and **Paid Content Identify** 

The first event redirects back to the post page, We will trigger an event there.

The second event is triggered on click of `I already bought this` link, which after successful check redirects back to post page, should we trigger the **Paid Content Purchase Complete** event again? We don't have a straight way to identify after which event the user was redirected.

**Comment by ksmoore125** [comment]
Sorry for the delay. A lot of our team is out on leave at the moment so I am asking around. I hope to have an answer to you soon.

**Comment by thrijith** [comment]
Hi @ksmoore125,

Do we have any updates on this?
For now, I'll be continuing with remaining points in this task.

**Comment by ksmoore125** [comment]
I believe that I have found the missing information [here](https://rtcamp.slack.com/files/UCATVSB63/FDB46L95Z/Google_Analytics_Tracking__issue_-_961_).

Please let me know if you need additional information.

**Comment by thrijith** [comment]
Hi @ksmoore125,

The link doesn't seem to be working, Can you please check and let me know?

**Comment by ksmoore125** [comment]
I have shared the document with you in Slack; please let me know if you still have issues accessing it and I can re-post it

**Comment by thrijith** [comment]
Thanks. Got the file, also the link is working now :smiley:

**Comment by thrijith** [comment]
@ksmoore125 

Thanks for the response, but the doc might not work in WP case.

Code for sending all events is done next is the `auto detection` part. 

When a user updates to the `v2.2.0` the `LaterPay Google Analytics:` will be enabled by default.

If a user has enabled and configured `Google Analytics for WordPress by MonsterInsights` correctly we will use it and fill up the text box for `Your Personal Google Analytics:`. When the user visits the `LaterPay Advanced Settings` page we will display `auto detected` next to the Personal UA-ID.

Just to confirm the auto-detected text to be displayed only once after update? ( I am assuming this is the case and starting to work on it. )

**Comment by ksmoore125** [comment]
@thrijith 

When you say that "the doc might not work in WP case" does that mean that there are still issues around distinguishing `Paid Content Identify` from `Paid Content Purchase Complete`?

> _(auto detected)_
This text should be displayed next to `Your Personal Google Analytics:` if the box is filled in. Is that what you were asking?

**Comment by thrijith** [comment]
>When you say that "the doc might not work in WP case" does that mean that there are still issues around distinguishing Paid Content Identity from Paid Content Purchase Complete?

@ksmoore125, No issues. It is working as expected.

>(auto detected) This text should be displayed next to Your Personal Google Analytics: if the box is filled in. Is that what you were asking?

Nope. The text will be displayed next to the `Your Personal Google Analytics textbox`.

Note: **The user can change auto detected UA-ID  and use a different one.**

****
- Do you want the auto-detected text to be displayed only once? ( This has been implemented, please let me know if needs change. )
- What should be done if the user enters a different UA-ID?
- What should be done if the user re-enters the UA-ID that was auto-detected after changing it to something else?

**Comment by ksmoore125** [comment]
> The text will be displayed next to the Your Personal Google Analytics textbox. This auto-detection will only work when the user updates our plugin and has activated and configured Google Analytics for WordPress by MonsterInsights correctly. Please let me know if this needs change.
> 
> Note: The user can change auto detected UA-ID and use a different one.

This sounds good, no changes needed.

> Do you want the auto-detected text to be displayed only once? ( This has been implemented, please let me know if needs change. )
Yes, please only display it once

> What should be done if the user enters a different UA-ID?
> What should be done if the user re-enters the UA-ID that was auto-detected after changing it to something else?

In either of these cases, we should save the UA-ID that they enter (when they hit the save button) and send the GA data to that UA-ID.

For this first round, since we don't know if anyone will use this feature any way, (it is mostly for our internal tracking) we don't need need to worry about any sort of validation. They can determine it is not working by checking their Google Analytics page if needed.
