### ISSUE TITLE
"Unlimited Access to Paid Content" feature displays "Post Preview Mode" widget

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#969]
**How to reproduce:**
"Unlimited Access to Paid Content" feature displays "Post Preview Mode" widget.

1. Install "User Role Editor" plugin or another WP Custom User Role management plugin.
2. Create a custom role with at least post reading rights
3. go to /wp-admin/options-general.php?page=laterpay and set the access permissions to "all" for your new role under "Unlimited Access to Paid Content"
4. This will give this user role free access to all paid content
5. Create a test user with your custom role
6. Log into WordPress with custom user
7. Access any type of paid post
8. The "Post Preview Mode" widget that is only meant for admin users will appear on the top right

**Expected behaviour:**
We only show the "Post Preview Mode" widget to admins.

**Comment by ksmoore125** [comment]
I no longer see the "Post Preview Mode" widget when I am logged in as myself, an Admin.

Per the expected behavior, this should still be displayed to admins.

**Comment by PatelUtkarsh** [comment]
As discussed in thread: https://rtcamp.slack.com/archives/GA2P84GBZ/p1537254405000100 (Private link)

Problem is with passing cookie from HTTP URL to HTTPS `admin-ajax.php` (Same problem explained: https://stackoverflow.com/questions/10230341/http-cookies-and-ajax-requests-over-https)

As @ksmoore125 mention if we can use other endpoint which isn't `wp-admin`: I think we can try rest endpoint. @thrijith

**Comment by thrijith** [comment]
@ksmoore125 
The issue has bee fixed using [this](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials).

Adding `xhrFields` object to the request fixed issue with cross-domain requests.

Please check on WPEngine Staging environment and let me know if this working for you.
