### ISSUE TITLE
Adjust title for purchases for which a voucher code has been used

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#970]
**Description**
Our merchants currently can't tell in their LaterPay statistics, if a time pass has been purchased regularly or with a voucher code. A simple solution proposed by Tom Nemec was, that we could add the used voucher code to the title of the respective purchase.

**Example:**

- A user has a voucher code "ABC123" for a time pass with the title "Month Pass".
- The user redeems this voucher.
- The purchase dialog opens and shows "Month Pass (Voucher Code ABC123)" as the purchase title.

This ticket is done, when the voucher code is added to the title of a time pass, which is purchased with a voucher code.

**Comment by ksmoore125** [comment]
Is there a way for me to validate this or can it only be reviewed via the code?

**Comment by thrijith** [comment]
You can check this by doing a test purchase on the WPEngine staging site.

Here is a screenshot for the same.

![pass-title-with-voucher](https://user-images.githubusercontent.com/13589980/45863047-0dd8ff80-bd92-11e8-9165-1824e7fe3be0.png)
