### ISSUE TITLE
Merchant Reported Issue: Pricing Not Backward Compatible between v0.12.2 and v.2.0.0

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#977]
One of our merchants reported the following issue which I was able to reproduce by following the steps below:

### 1. Ensure that you are on LaterPay v0.12.2
2. Set up your Pricing tab as follows:
     Global Default Price: 0.00
     No Category Prices
     No Time Passes
     Subscription: 19.99 for 1 year
![image](https://user-images.githubusercontent.com/41650164/45900556-bf356080-bda5-11e8-9fd9-8dfd0a5c1dec.png)
3. View a post set to default pricing (note that the subscription does not show up; the article is free)
![image](https://user-images.githubusercontent.com/41650164/45900533-b3499e80-bda5-11e8-9536-a3b0ce40c9c9.png)
4. Set an Individual Price (for example 0.29) for the post
![image](https://user-images.githubusercontent.com/41650164/45900499-99a85700-bda5-11e8-8a94-dd53e6912788.png)
5. View the post (note that the single purchase price and the subscription show up)
![image](https://user-images.githubusercontent.com/41650164/45900512-a167fb80-bda5-11e8-9d61-5b027a32ccde.png)

6. Reset the post to the Default price (to make the post free again)

### 7. Now upgrade to v2.0.0 (or follow steps 1-5 on a different site that is on v2.0.0)

**Observed Result**
When the article was free in v0.12.2 (as in steps 3 & 6 above) the subscription is visible and the user cannot read the article.
![image](https://user-images.githubusercontent.com/41650164/45900708-1e937080-bda6-11e8-9d54-078dee9ffbc0.png)

**Next Steps**
At this time please simply evaluate what change was made to cause this behavior. DO NOT MAKE ANY CHANGES. I am still working to decide on our best course of action given other items on our roadmap.

**Comment by thrijith** [comment]
@ksmoore
We have updated post display conditions to match https://github.com/laterpay/laterpay-wordpress-plugin/issues/909#issuecomment-412577977

Let me know if you have any doubts.

**Comment by ksmoore125** [comment]
We now have 3 merchants (FreeRide, Pulp, & Bridges Solution) who have contacted us about this issue so I would like us to get this resolved ASAP.

### Acceptance Criteria
Make the following update to the Pricing tab's Global Default Price section (see mockups below)
- Add radio buttons for "Make article free unless price is set on post page", "Posts cannot be purchased individually" and "Set individual article default price"
- "Make article free unless price is set on post page"
  - **Tooltip:** Should also have an info icon at the end and should display the following message on hover "All articles will be free by default; Time Passes & Subscriptions will only be displayed if an Individual Article Price greater than 0.00 is manually set on the Post page."
  - **Pricing Behavior:** This should restore the behavior from v 0.12.2 as mentioned above. If this selection is chosen, then the Time Passes and Subscriptions do not appear unless the individual article price is over 0.00
  - **Global Default Price Behavior:** The price and revenue model options should be hidden (see second mockup below)
- "Posts cannot be purchased individually" 
  - **Tooltip:** Should also have an info icon at the end and should display the following message on hover "Only Time Passes & Subscriptions will be displayed in the purchase dialog."
  - **Pricing Behavior:** This should replicate the existing behavior of the "Posts can / cannot be purchased individually" toggle when it is set to 'Posts cannot be purchased individually' so that posts can only be purchased using Time Passes and Subscriptions.
  - **Additional Details:** "Posts can / cannot be purchased individually" toggle that currently exists at the top of the Pricing tab should be removed since it is now being replaced by the "Posts cannot be purchased individually" option
  - **Global Default Price Behavior:** The price and revenue model options should be hidden (see second mockup below)
- Set individual article default price"
  - **Pricing Behavior:** Should not change from the v2.0.0 behavior: this should be the individual article default price and if it is set to 0.00 then the post cannot be purchased individually but the relevant Time Passes and Subscriptions should still be displayed
  - **Global Default Price Behavior:** See the first mockup below

### Default Selection
This is only relevant for users upgrading from v.0.0.12 or earlier. Once they have made their radio button selection we will have this information stored.
1. If existing "Posts can / cannot be purchased individually" toggle is currently set to Posts cannot be purchased individually, then this radio button should be selected by default
2. Else if current Global Default Price is set to 0.00 then "Posts cannot be purchased individually" should be selected
3. Else, "Set individual article default price" should be selected

### Mockup 1 - "Set individual article default price" is selected
![image](https://user-images.githubusercontent.com/41650164/46295259-39f83b80-c55d-11e8-952b-8c290ed00bd7.png)

### Mockup 2 - "Make article free unless price is set on post page" or "Posts cannot be purchased individually" is selected
_The option that is selected should have the corresponding radio button show as selected._
![image](https://user-images.githubusercontent.com/41650164/46295344-6dd36100-c55d-11e8-8688-744cfba64a47.png)

**Comment by thrijith** [comment]
@ksmoore125 I have some queries regarding Default Selection 

Note: toggle can only be set to `Posts cannot be purchased individually` if there is at least a time pass/subscription created.

>If existing "Posts can / cannot be purchased individually" toggle is currently set to Posts cannot be purchased individually, then this radio button should be selected by default

Are you suggesting to select `Make article free unless the price is set on post page` if the toggle is set to `Posts cannot be purchased individually`?

If so do we have to check this condition ( i.e at least a time pass or subscription is created ) whenever the user wants to enable this? 

>Else if current Global Default Price is set to 0.00 then "Posts cannot be purchased individually" should be selected

Will same condition ( i.e at least a time pass or subscription is created ) apply to this option too?

If so then we can't check if time pass or subscription exists while making the default selection.

We'd have to check if the toggle is set to `Posts cannot be purchased individually` and default price is `0.00` then we can select this, will that be ok?

**Comment by ksmoore125** [comment]
@thrijith 
> If existing "Posts can / cannot be purchased individually" toggle is currently set to Posts cannot be purchased individually, then this radio button should be selected by default

Then `Posts cannot be purchased individually` option should be selected by default.
Validation: if re-using the existing validation is simple then we can do that. Otherwise, my first instinct is that we do not _need_ the validation. If they select this option and there are no time passes or subscriptions then the articles would just be free...

> Else if current Global Default Price is set to 0.00 then "Posts cannot be purchased individually" should be selected

CORRECTION: `Make article free unless the price is set on post page` option should be selected by default (therefore we do not need to check for time passes and subscriptions)

Please let me know if you have any other doubts!
