### ISSUE TITLE
SPIKE: AMP Compatible Plugin

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#978]
What would it take to make our existing WordPress Plugin AMP-compatible?

Please provide a high-level effort estimate and also if this would conflict with an of our existing features.

We have an existing AMP Plugin here:
https://www.ampproject.org/docs/reference/components/amp-access-laterpay

**Comment by pradeep910** [comment]
@ksmoore125 AMP-compatible code should not conflict with existing plugin if it's done right. Considering it's going to be used with [AMP-WP plugin](https://github.com/Automattic/amp-wp/), I see that following efforts are involved:
1. Add conditions  `is_amp_endpoint()` for AMP compatible markups.
2. Remove custom JS libraries and use AMP components instead.
3. Add `Pay now` / `Pay Later` external links directly to the buttons / a tags as custom javascript won't work in AMP.
4. Handle front end markup for AMP compatibility based on plugin settings given in “Appearance” such as content preview options, purchase button, subscription etc.

Apart from this, I would still have to find out how many things are being done behind the scene and see if it can be supported in AMP.

### Issue with the current Laterpay AMP version
I checked existing examples of laterpay for AMP - https://ampexample.laterpay.net/ and https://ampbyexample.com/components/amp-access-laterpay/. I think this will have an issue.
AMP version of laterpay here uses the <amp-access> component. The teaser is show and paid content is hidden, but it exposes paid content on front end markup. https://www.ampproject.org/docs/reference/components/amp-access-laterpay
While the above can work fine for mobile devices, as there is no direct way to get access to the paid content on mobile. But normally, people can also access AMP version of the page on desktop as they have link to amp version of the page, in which case they can use developer tools to unhide the <amp-access>.

As you know AMP’s new 1.0 version is coming with Native, Paired and Classic modes. These modes are already available starting with 0.7 version with some coding changes. This is currently in beta version with new features and fixes.

If someone uses this amp plugin with ‘Native’ AMP mode, then users can have paid content hidden but exposed in the document/markup.

I would like to know if you are concerned with paid content being exposed like that.


### MVP for Laterpay AMP support
Existing Laterpay Plugin provides 3 content preview options, standard / custom positions for purchase buttons and Display setting for Subscriptions & Time Passes.
We can support plugin options. However, I would like to know if you have any roadmap for this. How many options would like to support in the initial version?

**Comment by ksmoore125** [comment]
Won't Do
