### ISSUE TITLE
Custom table compatibility code

### ISSUE THREAD

**Issue by PatelUtkarsh** [laterpay/laterpay-wordpress-plugin#984]
On version [0.10.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v0.10.0) we added WP table schema support so laterpay doesn't need custom tables. We kept backwards compatibility and are maintaining it since then. 

New installations uses WP schema by default.

We should now force a user to migrate if they haven't done already using admin notice(added in 0.10.0) and keep only WP schema support in code. 

We can decide on which version we want to do that if we want to remove custom table support  @ksmoore125 

Disadvantage of keeping custom table support is overhead of maintaing two database schema for same query.

This will allow us to have same build as VIP [build](https://vip-svn.wordpress.com/plugins/laterpay/).

Currently, we are removing [compatibility](https://github.com/laterpay/laterpay-wordpress-plugin/tree/master/laterpay/application/Compatibility) folder from VIP build.

**Comment by ksmoore125** [comment]
@PatelUtkarsh - Can you please provide a few more details?

For example:
- Who would this affect? Would it affect all users who have been using WP since before version 10?
- Is there any way that we can do this for them without them knowing since it is a backend change?
- What would "forcing the user to migrate" look like?

**Comment by PatelUtkarsh** [comment]
@ksmoore125 
- It will affect all users who have installed the plugin before `0.10.0` and haven't run the migration yet.
- We can do that but depend on server config and a number of time pass and subscription they have in the system - some server has small request timeout and we don't want it to timeout during migration. 
- Some Ideas:
  - We can change current notice and say on next version we are removing custom table support so do migrate before that.
  - We can display overlay on update of plugin to run migration.
  - Identify number of subscriptions and timepasses and migrate it if it's less or show popup to migrate if not already.

@thrijith Can you share screenshot of current migration admin notice?

**Comment by ksmoore125** [comment]
Thank you for the additional details. I am hoping that v2.3.0 will be a project to send us data on how merchants are using our plugin including things like how many time passes and subscriptions they have set up. If you do not feel that this is urgent, I will schedule this after that project so that we can go into it fully informed.

**Comment by PatelUtkarsh** [comment]
Sure that works for me.

We will need to track data if a client has performed migration or not. Also, one problem will have is we will only get data of client who has v2.3.0 installed and not previous clients.

**Comment by thrijith** [comment]
**Migration Notice**
![migration_notice](https://user-images.githubusercontent.com/13589980/46691609-ee135980-cc22-11e8-90ff-a94e8bb7bbd0.png)

After successfull migration.
![migration_complete](https://user-images.githubusercontent.com/13589980/46691744-3a5e9980-cc23-11e8-8a96-d12af9c29ca0.png)

**Comment by thrijith** [comment]
In this version, we can update the notice to Inform users about the removal of the custom table and provide with two options.

1)  Migrate Now. ( Which will migrate the data and delete custom tables. )
2) Already Migrated. ( Which will be for the users that have already done the migration, so we will just remove the custom tables )

And on next version, we will check if the user has completely migrated or not.

1) We can disable activation if not migrated. User will have to rollback migrated and then only they will be able to update.

2) Now that we will be only using wp schema and if user has not migrated already no data will be shown.

Even if go with option 2, user can just rollback and use older versions.

There are around **30%** users that are on **0.9*** versions. So we should hold this for a while and wait for user to update to newer versions.

Stats Ref : [WP.org](https://wordpress.org/plugins/laterpay/advanced/)

Let me know if the notice for migration should be updated with two options as mentioned above.

CC: @PatelUtkarsh @ksmoore125

**Comment by ksmoore125** [comment]
Overall it looks good I just want to confirm that with:

> 2. Already Migrated. ( Which will be for the users that have already done the migration, so we will just remove the custom tables )

We will verify on the back end that they have migrated before we remove the custom tables. I do not want us to delete merchant data in the case that they may not fully understand what they are clicking.

**Comment by thrijith** [comment]
@ksmoore125 

We will only remove custom tables if the data is already migrated and if the current version is above or equal to `v0.10.0`

Let me know if that's ok.

**Comment by ksmoore125** [comment]
That is perfect, thanks!

**Comment by thrijith** [comment]
Fixed and released in [2.3.0](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/v2.3.0)
