### ISSUE TITLE
Global Default Price Changes: Pricing Tab Changes

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#992]
Since we made the changes per https://github.com/laterpay/laterpay-wordpress-plugin/issues/977 we also need to update the minimized display of the **Global Default Price** panel

### Case 1: Global Default Price = Make article free unless price is set on post page
Display the following in the minimized Global Default Price panel
> Every post is FREE unless they match a Category Default Price or have an Individual Article Price set on the Post page.

![image](https://user-images.githubusercontent.com/41650164/46753441-7591b480-cc85-11e8-93fe-c70fa6f08bac.png)

**Additional Changes**
1. Expanded Global Default Price panel text
  `FREE unless price is set on post page or by category`
2. Expanded Global Default Price panel tooltip text
  `All articles will be free by default; Time Passes & Subscriptions will only be displayed if the article matches a Category Default Price or has an Individual Article Price set on the Post page.`

### Case 2: Global Default Price = Posts cannot be purchased individually
Display the following in the minimized Global Default Price panel
> Posts cannot be purchased individually; 
> only Time Passes & Subscriptions will be displayed.

![image](https://user-images.githubusercontent.com/41650164/46752280-63624700-cc82-11e8-9c78-ca5aff510f7c.png)

### Case 3: Global Default Price = Set individual article default price
No change from current behavior

![image](https://user-images.githubusercontent.com/41650164/46753468-8d693880-cc85-11e8-8174-6a34e2569e43.png)

**Comment by thrijith** [comment]
Hi @ksmoore125,

I'll update the text for the minimized the section. I am not sure about the expanded section and tooltip placement though. Could you please provide mockup for the said section?

**Comment by ksmoore125** [comment]
Sorry for the confusion please 
Replace: `Make article free unless price is set on post page`
With: `FREE unless price is set on post page or by category`

And the existing tooltip of: `All articles will be free by default; Time Passes & Subscriptions will only be displayed if an Individual Article Price greater than 0.00 is manually set on the Post page.`
With: `All articles will be free by default; Time Passes & Subscriptions will only be displayed if the article matches a Category Default Price or has an Individual Article Price set on the Post page.`
