### ISSUE TITLE
Dynamic Pricing Bug - Pay Now allows for Prices under 5.00

### ISSUE THREAD

**Issue by ksmoore125** [laterpay/laterpay-wordpress-plugin#998]
https://laterpay.atlassian.net/browse/PRODUCT-223

> Steps to reproduce:
> Set an individual pay now price (must be over 5.00)
> Add dynamic pricing
> Set one of the price stages to "0.49" (below 5.00)
> => It should automatically switch to 5.00 automatically
> Instead you have to Update the post, then it's updated to 5.01 (which should be 5.00).

**Comment by ksmoore125** [comment]
@thrijith - This did not appear to be working properly when I tested on staging. After further evaluation, could we instead do something like this:

![image](https://user-images.githubusercontent.com/41650164/60351276-0bdc4680-998b-11e9-9735-a92f157452d2.png)

Where the price charged to end users automatically switches from Pay Now to Pay Later at 1.99

**Comment by ksmoore125** [comment]
To clarify ☝️ the ideal flow (if possible) would be to:

**Acceptance Criteria** 
- Add the PayLater line to the graph at the threshold ($1.99 or 1.49€)
- Force the price to automatically switch from Pay Now to Pay Later once it gets to the threshold ($1.99 or 1.49€)

In the example above, it would remain at $5.00 `Pay Now` then decreases as charted 
once it reaches $1.99 or below, it automatically switches to `Pay Later`

**Comment by thrijith** [comment]
> Add the PayLater line to the graph at the threshold ($1.99 or 1.49€)

Added this.

> Force the price to automatically switch from Pay Now to Pay Later once it gets to the threshold ($1.99 or 1.49€)

This doesn't seem to working as mentioned above as of now. I've set price above `5` still the purchase option was `Buy Now, Pay Later`.

**Comment by ksmoore125** [comment]
**Steps to Reproduce**
- Add Dynamic Price
- Start at a `Pay Later` price with the price set to increase to a `Pay Now` price

**Observed Result**
The article is priced at 0.00

**Desired Result**
It should be priced at the `Pay Now` price OR it should be priced at the max `Pay Later` price

**Example**
http://lpwptestprod.wpengine.com/2019/07/09/hello-world/

**Comment by thrijith** [comment]
I am able to see the price set to `4.63` right now, however it's not pay now. 

Right now the `Pay Now` only comes into effect if the price is above single sale limit which is `5.00` should I update the behaviour to set `Pay Now` automatically if price is above `Pay Later` price?

Currently posts priced between `1.99` - `5.00` can be sold either as `Pay Later` or `Pay Now`.

**Comment by thrijith** [comment]
Released in [v2.6.1](https://github.com/laterpay/laterpay-wordpress-plugin/releases/tag/2.6.1)
